### ISSUE TITLE
Couldn't deploy in Azure Container Instance-argument cannot be satisfied: type *anypb.

### ISSUE THREAD

**Issue by zainuvk** [hashicorp/waypoint#1006]
I am trying to deploy the  Nodejs app which comes with example in Azure container Instance for waypoint.This the doc which is used as ref https://learn.hashicorp.com/tutorials/waypoint/azure-container-instance?in=waypoint/deploy-azure
The deployment is failing with error:

argument cannot be satisfied: type *anypb.Any (subtype:
  "hashicorp.waypoint.sdk.Args.DataDir.Component")

version of Waypoint  is v0.2.0

Here are the logs:

Creating new buildpack-based image using builder: heroku/buildpacks:18
✓ Creating pack client
✓ Building image
 │ [exporter] Reusing 1/1 app layer(s)
 │ [exporter] Reusing layer 'launcher'
 │ [exporter] Reusing layer 'config'
 │ [exporter] Adding label 'io.buildpacks.lifecycle.metadata'
 │ [exporter] Adding label 'io.buildpacks.build.metadata'
 │ [exporter] Adding label 'io.buildpacks.project.metadata'
 │ [exporter] *** Images (9560a16ad786):
 │ [exporter]       index.docker.io/library/example-nodejs:latest
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:nodejs'
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:toolbox'
✓ Injecting entrypoint binary to image

Generated new Docker image: example-nodejs:latest
✓ Tagging Docker image: example-nodejs:latest => acrregtest.azurecr.io/example-nodejs:latest
✓ Pushing Docker image...
 │ 3d9f72266d0a: Layer already exists
 │ bce2a6759588: Layer already exists
 │ 63bd0a61a1eb: Layer already exists
 │ 30b9277e5b4f: Layer already exists
 │ b77f97933693: Layer already exists
 │ fe6d8881187d: Layer already exists
 │ 23135df75b44: Layer already exists
 │ b43408d5f11b: Layer already exists
 │ latest: digest: sha256:e79a270186a94c71274c9cea38dc3f55ee66bd0abf1a11554ce7264e9
 │ a56f9f7 size: 2829
✓ Docker image pushed: acrregtest.azurecr.io/example-nodejs:latest

» Deploying...
! 1 error occurred:
        * argument cannot be satisfied: type *anypb.Any (subtype:
  "hashicorp.waypoint.sdk.Args.DataDir.Component")

**Comment by mitchellh** [comment]
Hello this should be fixed in the release branch we just haven’t cut a new patch yet. Soon, maybe next week!

**Comment by mschirbel** [comment]
Any updates on this one?
I'm getting the same error on AWS EKS.

**Comment by briancain** [comment]
Hey there @mschirbel! - please open a new issue and fill out the requested information. We will be able to assist you there. Thanks 😄
