### ISSUE TITLE
dockerfile.v0: failed to create LLB definition: no active sessions

### ISSUE THREAD

**Issue by ldiqual** [hashicorp/waypoint#1056]
**Describe the bug**

`waypoint build` fails with:

```
$ waypoint build
✓ Initializing Docker client...
⠦ Building image...
! unable to stream build logs to the terminal: failed to solve with frontend
  dockerfile.v0: failed to create LLB definition: no active sessions
```

**Steps to Reproduce**

Run `waypoint build` with the configuration file below

**Expected behavior**

Waypoint should build the app

**Additional context**

Waypoint 0.2.1.

waypoint.hcl:

```
project = "myproject"

app "myproject-myapp" {

  labels = {
    "service" = "myapp"
    "env" = "dev"
  }

  build {
    use "docker" {
      buildkit = true
    }

    registry {
      use "docker" {
        image = "gcr.io/myproject/myapp"
        tag = "test-0"
      }
    }
  }

  deploy {
    use "google-cloud-run" {
      project  = "myproject"
      location = "us-central1"
      port = 8080
      unauthenticated = true

      capacity {
        memory = 2048
        cpu_count = 1
        max_requests_per_container = 80
        request_timeout = 900
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```

Dockerfile:

```
FROM minimalcompact/thumbor
ENV THUMBOR_PORT=8080
```

**Comment by briancain** [comment]
Hey there @ldiqual - Could you please share the result of running `waypoint build -vvv` in a [gist](https://gist.github.com/)?

Also what version of Docker do you have installed? If not on latest, can you upgrade and try again? Thannks!

**Comment by ldiqual** [comment]
@briancain Here are the logs: https://gist.github.com/ldiqual/d50ff2593ffa16f3c94fa92f8bdc0e6a

```
$ docker --version
Docker version 20.10.2, build 2291f61
```

Docker for mac:

![image](https://user-images.githubusercontent.com/941453/106960679-48d4f700-66f1-11eb-81d7-d9ae1b2447aa.png)

**Comment by briancain** [comment]
@ldiqual - If you disable buildkit, does it work then?

```hcl
build {
    use "docker" {
      buildkit = false
    }
...
```

Also a quick check, it seems like Docker expects its `Dockerfile` to start with a `D`, so making sure that's the case would be another good thing to check on! I ask only because the error has it as lower case `d`.

**Comment by ldiqual** [comment]
@briancain Yes, disabling buildkit works. Note, however, that if I run `docker build` with buildkit on I experience no issue.

Not too sure where `dockerfile.v0` comes from, my dockerfile is named `Dockerfile` (with a capital `D`) and is located alongside `waypoint.hcl`:

```
[ldiqual@ldiqual-mbp-myproject myapp]$ ls -a
total 2040
drwxr-xr-x  11 ldiqual  staff     352 Feb  3 17:47 .
drwxr-xr-x  17 ldiqual  staff     544 Sep 28 14:44 ..
drwxr-xr-x   4 ldiqual  staff     128 Dec 19 13:38 .waypoint
-rw-r--r--   1 ldiqual  staff      49 Jan 27 13:43 Dockerfile
-rw-r--r--   1 ldiqual  staff     653 Aug 12 16:15 README.md
-rw-------   1 ldiqual  staff   65536 Feb  4 13:57 data.db
-rw-r--r--   1 ldiqual  staff     864 Jan 27 13:43 package.json
-rw-------   1 ldiqual  staff       0 Feb  3 17:47 waypoint-restore.db.lock
-rw-r--r--   1 ldiqual  staff     645 Feb  3 17:47 waypoint.hcl
```

**Comment by briancain** [comment]
@ldiqual - Thanks! It looks like upgrading to Docker Desktop `3.0.3` might fix this error on macOS. If you upgrade to that version, do you end up with the same issue? I think latest is `3.1.0` so maybe try that :crossed_fingers:

**Comment by ldiqual** [comment]
I'm already on 3.1.0:

![image](https://user-images.githubusercontent.com/941453/107075200-a5422000-679e-11eb-9200-82e1d1415099.png)

**Comment by ldiqual** [comment]
@briancain happy to jump on a quick zoom call if it helps. Feel free to hit me up at lois@siteline.com

**Comment by krantzinator** [comment]
We are unable to replicate this issue. You can upgrade Docker Desktop to 3.3 and Waypoint to 0.3 and try again! I'm going to close this issue for now since it does not appear to be a Waypoint issue. Let us know if you continue to have problems after doing the upgrades.
I'd recommend poking around Docker's help forums, as according to [this post](https://stackoverflow.com/questions/64221861/failed-to-resolve-with-frontend-dockerfile-v0) it seems to be a local docker configuration issue.

**Comment by izaaklauer** [comment]
I can replicate this with the [reactjs waypoint-example](https://github.com/hashicorp/waypoint-examples/tree/main/docker/reactjs) by enabling buildkit on the docker build.
