### ISSUE TITLE
Allowing adding label and network for docker deployment

### ISSUE THREAD

**Issue by prabirshrestha** [hashicorp/waypoint#1064]
This feature request is similar to the one for nomad tags mentioned here. https://github.com/hashicorp/waypoint/issues/567#issuecomment-710987735

I have traefik setup in docker swarm and would like to use it for dns and lets encrypt.

Here is a `docker-compose.yml`.

```Dockerfile
version: '3'
services:
  helloworld:
    image: traefik/whoami
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`whoami.domain.com`)"
        - "traefik.http.routers.helloworld.entrypoints=websecure"
        - "traefik.http.routers.helloworld.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true
```

I would like to be able to specific these labels and network in `waypoint.hcl` when using docker.

**Comment by briancain** [comment]
Thanks @prabirshrestha - I've opened a pull request at #1065 that addresses this. It should be in the next release.

**Comment by prabirshrestha** [comment]
Awesome. That was fast. 

Looking forward to it. I'm working on building a mini PaaS that uses waypoint internally which is currently a blocker. https://github.com/prabirshrestha/zcloud

**Comment by briancain** [comment]
Cool @prabirshrestha ! Sounds great :smile:
