### ISSUE TITLE
aws/ecs existing load balancer cannot be used

### ISSUE THREAD

**Issue by pharindoko** [hashicorp/waypoint#1070]
**Describe the bug**
cannot use existing  application load balancer in AWS.

When I try to deploy with "waypoint deploy" and this configuration 

```hcl
project = "backend"

app "backend" {

  build {
    use "docker" {}

    registry {
      use "aws-ecr" {
        region     = "eu-central-1"
        repository = "backend-dev"
        tag        = "latest"
      }
    }
  }

  deploy {
    use "aws-ecs" {
      region  = "eu-central-1"
      memory  = 512
      subnets = ["subnet-xxxx", "subnet-xxxxx"]
      alb {
        listener_arn = "arn:aws:elasticloadbalancing:eu-central-xxxxxx"
        zone_id      = "ZoneID"
        domain_name  = "api.test.com"
        certificate  = "cert_arn"
      }
      service_port = 3000
    }
  }

}
```

I get 

```
 waypoint deploy                            

» Deploying...
! When using an existing listener, Route53 setup is not available

```

due to this error in the code:

properties are required properties by default but in this if condition it fails because it doesn`t accept those properties:

https://github.com/hashicorp/waypoint/blob/a400665719d58d936c36cabd4a5beac8b0c91892/builtin/aws/ecs/platform.go#L213

**Comment by pharindoko** [comment]
ok works when I just keep the properties empty...


```hcl
project = "backend"

app "backend" {

...

  deploy {
    use "aws-ecs" {
      ...
      alb {
        listener_arn = "arn:aws:elasticloadbalancing:eu-central-xxxxxx"
        zone_id      = ""
        domain_name  = ""
        certificate  = ""
      }
```

**Comment by pharindoko** [comment]
#732

**Comment by krantzinator** [comment]
What is the desired outcome here? That you would be able to have the waypoint.hcl as follows:
```
alb {
  listener_arn = "arn:aws:elasticloadbalancing:eu-central-xxxxxx"
}
```
?
This appears to be working as expected, per the error message, so I'm not sure what we need to fix.

**Comment by krantzinator** [comment]
That makes sense! Two things:
1) regarding the `transport closing` message, this should be fixed in the next release (PR https://github.com/hashicorp/waypoint/pull/1085)
2) regarding the overall issue here with input validations, we'll take a look

**Comment by pharindoko** [comment]
Thanks a lot - will try out the next release.
