### ISSUE TITLE
ALB Releaser doesn't implement destroy functions

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#1081]
Currently, when using the `aws-alb` plugin for releasing, it's not possible to use `waypoint destroy` because the ALB plugin does not implement `DestroyRelease` nor `DestroyWorkspace`.

**Steps to Reproduce**
1. Use `aws-alb` as a releaser (ECS or Lambda as deploy most likely)
2. Do a deploy, then do a `waypoint destroy`
3. AWS errors will indicate that the TargetGroups to be destroy are still wired up to the ALB.

**Expected behavior**
The ALB should delete it's usage of TargetGroups when it's destroyed. Then the deployments that provided those TargetGroups can be deleted.

**Waypoint Platform Versions**
0.2.1 and main.

* Waypoint CLI Version: 0.2.1 and main
* Waypoint Plugin: `aws/alb`

**Comment by krantzinator** [comment]
This relates to https://github.com/hashicorp/waypoint/issues/1011. I'll close that issue in favor of this one.
