### ISSUE TITLE
`path` command or subcommand for Waypoint artifacts

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1107]
**Is your feature request related to a problem? Please describe.**
If you're flipping between OSes in managing Waypoint, you may not know the default paths for configs, etc.

**Describe the solution you'd like**
Either a command (e.g. `waypoint path context`) or artifact-specific subcommand (e.g. `waypoint context path`)

**Describe alternatives you've considered**
using `find` or my favorite search engine to ask the default config path for a specific OS flavor

**Comment by evanphx** [comment]
Maybe `waypoint context inspect`?
