### ISSUE TITLE
Exec deployment issue

### ISSUE THREAD

**Issue by orenmazor** [hashicorp/waypoint#1111]
**Describe the bug**
I'm not sure if this is just me yet, but several of my apps no longer seem to deploy. I've been digging through the TRACE logs but so far nothing jumps out at me as obvious.

I edited my hcl down to a really simple example. I expect in this case for it to just run the command, but instead I've been getting this error:

```

» Deploying...
! 1 error occurred:
  	* argument cannot be satisfied: type *anypb.Any
  
```

**Steps to Reproduce**
sample waypoint.hcl:

```

app "qrunner" {
    build {
        use "docker-pull" {
            image = "alpine"
            tag = "latest"
        }

        registry {
            use "aws-ecr" {
                repository = "orentest"
                tag = "latest"
            }
        }
    }

    deploy {
        use "exec" {
            command = ["uname"]
        }
    }
}

```

**Waypoint Platform Versions**
```
➜ waypoint --version        
Waypoint v0.2.0-555-g3c49efa7 (3c49efa7)
```

**Comment by krantzinator** [comment]
It looks like you're building Waypoint directly off of `main`, which has some in-progress feature work and we don't recommend using it if you require stability. We just released 0.2.2 yesterday if you want to give that a go and see if it solves your problems!

**Comment by orenmazor** [comment]
@krantzinator I like to live dangerously!

but yeah, this is off today's build. I'll rollback to 0.2.2 and report back

**Comment by krantzinator** [comment]
Thanks!

**Comment by orenmazor** [comment]
reverted to `waypoint v0.2.2 (20144449)` and this issue went away. I have a different problem but that one's my fault.
