### ISSUE TITLE
Empty logging block needed or else deploy fails on AWS with aws-ecs plugin

### ISSUE THREAD

**Issue by kfh** [hashicorp/waypoint#1115]
WP server: 0.2.2
WP client: 0.2.2

This is the client failing when deploying. Reverted back to client version 0.2.1 and verified that it's working as expected. 
The only error i got was the very little helpful: `! transport is closing`. Had to dive into the code and look for into the flow of the code. There has been some added functionality around logging and the new logging options mentioned here: https://www.waypointproject.io/plugins/aws-ecs#logging require that you set an empty block `logging {}` or else the deployment fails. I would expect that those properties had sane defaults / not being set if you dont actually specify that logging block. That would align perfectly with the `log_group` block which isn't mandatory but falls back to a _default group_ if non is specified. 

All of the _logging properties_ are also missing information about the _type_ expected and if it's _optional_ or not which diffs from the rest of the documentation.

**Comment by krantzinator** [comment]
Yes this is a bug. PR is open here https://github.com/hashicorp/waypoint/pull/1120

**Comment by krantzinator** [comment]
The fix was released with 0.2.3, let us know if you run into anything else! https://github.com/hashicorp/waypoint/releases/tag/v0.2.3
