### ISSUE TITLE
How to push local container directly to a remote server's Docker daemon?

### ISSUE THREAD

**Issue by elimisteve** [hashicorp/waypoint#1155]
**Is your feature request related to a problem? Please describe.**

I would like to be able to build a Docker container on my laptop and push it directly to my servers so that I don't need to trust any registry, including a private registry I run, any of which could be hacked.

**Describe the solution you'd like**

I'd like to use Waypoint to copy a local container to a remote server, then have that server's Docker daemon run it using config I specify in an HCL file.

**Describe alternatives you've considered**

The aforementioned feature is not necessary _if_ there is some simple way that I can cryptographically sign my containers and tell my server's Docker daemon to only run containers signed by my key. (CoreOS's rkt did exactly this and it was amazing! Container images could be stored anywhere, like behind Nginx + HTTP Basic Auth, no fancy registries required...)

**Explain any additional use-cases**

This feature would help us all get back to a `git push heroku master`-like world!

**Additional context**

N/A

**Comment by elimisteve** [comment]
I suppose that the aforementioned feature could use https://github.com/hashicorp/waypoint/pull/631 (for telling a remote Docker daemon what to deploy) after copying the local image to the server.

**Comment by briancain** [comment]
@elimisteve hey there! I imagine this should be possible using `docker-pull` with a registry stanza defined for accessing your private registry: https://www.waypointproject.io/docs/lifecycle/build#docker-pull-build

Give that a spin and let us know if that works! Thanks.

**Comment by elimisteve** [comment]
> ...with a registry stanza defined for accessing your private registry

@briancain But my goal is to not use registries at all.

Potential solution: use Podman instead of Docker. Podman lets me pull a container image from a local directory, so Waypoint could scp my container to my server, run `podman pull`

    $ podman pull dir:/tmp/myimage

then run the container that was just pulled.

**Comment by briancain** [comment]
@elimisteve - thanks for the extra info! I could see this being solved potentially by enhancing the `docker-pull` plugin to use `docker import` or through the future-feature dockerless img build. I'll keep this marked as an enhancement for now.

**Comment by evanphx** [comment]
Hi @elimisteve,

Could you talk more about how the rest of the deployment process would work? We're unsure how this remote machine would be addressable to be deployed to by the rest of waypoint also. Are you looking to have waypoint talk directly to many different docker daemon's on your own servers? This particular configuration is not well served by waypoint right now.

If you can give us more information, maybe we can figure out the right balance to strike. Thanks!

**Comment by briancain** [comment]
Hey there! It's been a while since we've heard from you, and since the resolution for this issue is unclear, we're going to go ahead and close this issue. Please feel free to drop a comment and let us know about ☝🏻 and we can re-open the issue if it makes sense to. Thank you!
