### ISSUE TITLE
Add support for Amazon ECS to deploy the Waypoint server 

### ISSUE THREAD

**Issue by mreferre** [hashicorp/waypoint#1222]
**Is your feature request related to a problem? Please describe.**
I would like the Waypoint install routines to be able to install the server on Amazon ECS in addition to the currently supported Nomad, Kubernetes and Docker endpoints. 

**Describe the solution you'd like**
I would like to be able to run `waypoint install --platform=ecs -accept-tos`. Ideally the installation would create the ECS cluster and deploy the Waypoint container to Fargate backed by an EFS filesystem. But open to discuss alternatives.  

**Describe alternatives you've considered**
As an alternative I am considering using the currently available options or [manually install on EC2](https://github.com/hashicorp/waypoint/issues/1217) or the currently supported endpoints. 

**Explain any additional use-cases**
One of the main value propositions of Waypoint is that it allows users to pick an endpoint of their choice to deploy/release their code. It is likely that these users would like to use the same endpoint to setup the Waypoint server itself. For example, an organization that has strategically opted to use Amazon ECS may not want to have to setup/learn Kubernetes or Nomad to deploy the Waypoint server.  

**Additional context**
None

**Comment by briancain** [comment]
Closed via https://github.com/hashicorp/waypoint/pull/1564. This will come out in the next release! 😄 Thanks for the report
