### ISSUE TITLE
Enhance Waypoint to be more conscious of the resources it creates through its lifecycle

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1234]
**Is your feature request related to a problem? Please describe.**

Waypoint needs a way to be more aware of the resources it creates during deployments. Through the lifecycle of a deployment for a given platform, Waypoint ends up created a lot of different resources such as statefulsets, pods, job allocations, containers, and more. Once Waypoint is aware of these resources, it will be easier for it to take future action on these resources after deploy.

**Describe the solution you'd like**

This issue should enhance the Waypoint plugin SDK to be able to keep track of the resources it creates during the lifecycle of Waypoint

**Comment by mitchellh** [comment]
I'm gonna mark this as done. We have merged the SDK changes and brought the updated SDK into this repo too with the recent Docker PR. We have to convert more plugins but I think this is done enough for this to be closed.
