### ISSUE TITLE
Waypoint Up from browser UI

### ISSUE THREAD

**Issue by gregone** [hashicorp/waypoint#1238]
**Is your feature request related to a problem? Please describe.**
In our quest to bring Waypoint CLI functionality to the browser UI, we should be adding the ability to trigger the `up` command from the the CLI

**Describe the solution you'd like**
The application view should have a button to allow the user to run `waypoint up` from their browser

**Comment by jgwhite** [comment]
This work was partially blocked by #1684 but is now unblocked thanks to #1685
