### ISSUE TITLE
Mutable Deployment Support in the browser UI

### ISSUE THREAD

**Issue by gregone** [hashicorp/waypoint#1239]
**Is your feature request related to a problem? Please describe.**
Alongside the core Mutable Deployment Support feature (https://github.com/hashicorp/waypoint/issues/1235), we need to support that functionality in the UI

**Describe the solution you'd like**
- surface the mutability of deployments in the UI
- adapt the UI to decouple per-deploy horizon URLs from releases
- surface "generation" objects for operations

**Comment by briancain** [comment]
Implemented via https://github.com/hashicorp/waypoint/pull/1549. Closing this issue now!
