### ISSUE TITLE
Add ability to write config files in the entrypoint

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#1241]
Applications commonly need more than just env vars to configure themselves. It would be great if waypoint had a way to write config files, not just set env vars.

**Describe the solution you'd like**
Config files described in waypoint.hcl that are populated before the application runs.

**Describe alternatives you've considered**
Using random scripts before hand to write config files from env vars.

**Comment by RealHarshThakur** [comment]
@evanphx Would love to contribute to this. I guess the implementation might vary based on plugin, for instance in case of Kubernetes, would this be a configmap mounted as volume ? 

Anyway, I'd like to pick it up for Kubernetes and Cloud Run for starters if possible

**Comment by evanphx** [comment]
Hi @RealHarshThakur,

The implementation will not vary based on plugin, it's going to be enabled via the entrypoint, like the environment variables. The work for this has begun internally so there isn't a place for you to pick this up at present.
