### ISSUE TITLE
pack: exclude/include files

### ISSUE THREAD

**Issue by nateberkopec** [hashicorp/waypoint#1258]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to include or exclude directories/files from apps packed with the `pack` plugin. I think normally you would do this via `project.toml`, but reading the `pack` plugin makes me think that such a file would just be ignored.

My use case is excluding log directories, which often grow to quite substantial size when developing locally, inflating my resulting images by quite a bit.

**Describe the solution you'd like**

```
use "pack" {
  builder     = "heroku/buildpacks:18"
  exclude = ["logs/", "various globs go here"]
}
```

**Describe alternatives you've considered**

Simply loading a project.toml doesn't feel right - I think Waypoint should provide it's own abstraction on top of the Pack client.

**Comment by evanphx** [comment]
Looks pretty easy to add, sounds good!

**Comment by nateberkopec** [comment]
I'm opening issues that _you_ implement now? Oh how the turn tables 😆

**Comment by RealHarshThakur** [comment]
@evanphx Can I please take this up?

**Comment by nateberkopec** [comment]
I'm not explicitly for or against, but using a _separate_ file doesn't feel very "Hashicorpy" to me. I'm used to configuring all the behavior about my project in 1 or more `hcl` files.

That said if you _want_ a separate file, doing something like:

```
use "pack" {
  builder     = "heroku/buildpacks:18"
  exclude =  file(".packignore")
```

should also be possible.

Just a random user's opinion.

**Comment by RealHarshThakur** [comment]
@nateberkopec I was thinking user shouldn't have to provide it in the config at all and just mention the files/directories it in the `.packignore` file

Just another random user's opinion :)
