### ISSUE TITLE
ui: Support default field for git branch if none supplied

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1264]
**Is your feature request related to a problem? Please describe.**

When adding new git settings to a Waypoint project in the UI, it requests a ref to be supplied and can't be blank or use a default.

![Screenshot from 2021-04-06 11-40-29](https://user-images.githubusercontent.com/810277/113792032-ccaf5d80-96f9-11eb-92f4-87368368f235.png)

**Describe the solution you'd like**

 We should support a default value of `HEAD` if left empty so that it isn't required.

**Comment by mitchellh** [comment]
Just tested HEAD (to verify it works) and it does, I think that's a good default cause it'll work no matter what the default branch is.
