### ISSUE TITLE
ui: git settings don't clear on new project

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/waypoint#1268]
I don't know if this is a bug, it actually worked really nicely for me cause I _did_ want to create a project pointing to the same place. But when you create a project, then create another project, the Git setting values are retained.

Bug? Not a Bug?

![image](https://user-images.githubusercontent.com/1299/113792640-3d0aae80-96fb-11eb-8f8b-ad2ddbf9aefa.png)

**Comment by gregone** [comment]
definitely a bug. I had caught something similar coming from another route, but this one will be fixed by https://github.com/hashicorp/waypoint/pull/1275
