### ISSUE TITLE
ui: app settings link goes to blank page

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/waypoint#1270]
There is a settings link in the tab bar for an app, but clicking it goes to a blank page.

Bigger picture: it isn't immediately clear that you have to go back to the project to modify the settings, I wonder if we should make this go there or make this more clear?

![image](https://user-images.githubusercontent.com/1299/113793446-26655700-96fd-11eb-96a1-ac9f2ad41337.png)

**Comment by gregone** [comment]
🤦 This was the app settings link (in a tab), which we decided not to do. Thought I had removed it, but that maybe got lost in the umpteen rebases I did. Will remove entirely
