### ISSUE TITLE
plugin/nomad: namespace config option is ignored and not used for deploy

### ISSUE THREAD

**Issue by spuder** [hashicorp/waypoint#1295]
Add documentation on how to deploy to a specific nomad namespace using waypoint

This feature request has 2 parts: 

1. Document how to do a `waypiont install` to a specific namespace
2. Document how to do a `waypoint deploy` to a specific namespace

### Waypoint Install

I believe the majority of users will want to overwrite the namespace, and so the example on [this page](https://learn.hashicorp.com/tutorials/waypoint/get-started-nomad?in=waypoint/get-started-nomad) should be updated to include `-nomad-namespace=default` as part of the install command. 

```
waypoint install -platform=nomad -nomad-dc=dc1 -nomad-namespace=default -accept-tos
```

![Screen Shot 2021-04-08 at 11 47 30 AM](https://user-images.githubusercontent.com/242382/114073301-609b3980-9860-11eb-8862-765800a02f7a.png)

----

### Waypoint deploy

I have not been able to figure out how to deploy an application to a specific namespace. The following does _not_ work
```
# not working
    deploy {
        use "nomad" {
            datacenter = "sb"
            namespace = "foobar"
        }
    }
```

In researching how to do this I discovered`internal/serverinstall/nomad.go` but I don't see how that maps to a config file. 

```

type nomadConfig struct {
	serverImage        string            `hcl:"server_image,optional"`
	namespace          string            `hcl:"namespace,optional"`
	serviceAnnotations map[string]string `hcl:"service_annotations,optional"`

	region         string   `hcl:"namespace,optional"`
	datacenters    []string `hcl:"datacenters,optional"`
	policyOverride bool     `hcl:"policy_override,optional"`

	serverPurge bool `hcl:"serverPurge,optional"`
}
```

Please consider updating the waypoint examples (issue https://github.com/hashicorp/waypoint-examples/issues/61)  and the learning tutorial to show users how to change the nomad namespace (if that functionality exists)

**Comment by briancain** [comment]
I've made a pull request to include some information around additional options for the install command. However our Learn site is not public, so I can't link it here! It should be updated within the next few days.
