### ISSUE TITLE
Remote runner job for Nomad clusters OOMs when doing basic tasks

### ISSUE THREAD

**Issue by nateberkopec** [hashicorp/waypoint#1302]
Pretty simple: I tried using the new runner created by `waypoint install` as a remote runner, pulling a git repo. The runner got OOM-killed before it even finished pulling the repo down.

Not sure what the solution is - configurable resource limits? Maybe just generate some nomad jobspecs that I can modify with resource stanzas appropriate for my setup?

**Comment by briancain** [comment]
Hey there @nateberkopec ! Can you provide us with the waypoint runner logs when it crashes? Were you pulling a git repo through a project created in the UI or the CLI? Thanks!

**Comment by mitchellh** [comment]
@briancain I think the issue is that our default runner resource requests are too low. I don't see us explicitly setting any so we're probably inheriting some low defaults from somewhere. We should increase them.

**Comment by mitchellh** [comment]
Working on unrelated Nomad things, I grabbed a screenshot. These are some defaults from somewhere and are definitely too low.

![image](https://user-images.githubusercontent.com/1299/114202032-a95bfc80-990b-11eb-8a4d-f3712ee377a7.png)

**Comment by nateberkopec** [comment]
Yup. And then I just see some messages regarding OOM killing in the Nomad job log once I actually try to `waypoint up -remote`.
