### ISSUE TITLE
Git Configuration Checkbox for New Project is Broken in Safari

### ISSUE THREAD

**Issue by almonk** [hashicorp/waypoint#1305]
**Describe the bug**
When setting up a new project, a custom checkbox is shown. The custom checkbox is buggy and the 'real' checkbox it is managing is visible.

![CleanShot 2021-04-09 at 11 58 20](https://user-images.githubusercontent.com/51724/114170508-eedbf200-992a-11eb-9fa3-5608374fec1e.png)

**Steps to Reproduce**
Start a new project on Waypoint 0.3 using Safari 14.0.3

**Expected behavior**
As in Chrome, the underlying checkbox should not be visible:

![CleanShot 2021-04-09 at 11 58 15](https://user-images.githubusercontent.com/51724/114170474-e4215d00-992a-11eb-84cf-155072b55af4.png)

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.3
* Waypoint Server Platform and Version: docker

**Comment by gregone** [comment]
@almonk Thanks for reporting this one! The fix merged here https://github.com/hashicorp/structure/pull/68  will solve that one. I just need to do a new release of the addon, and import that new version
