### ISSUE TITLE
Workspace Selection

### ISSUE THREAD

**Issue by josephlim75** [hashicorp/waypoint#1339]
**Is your feature request related to a problem? Please describe.**
As `waypoint` CLI allow to use `-workspace`, it would be a good feature to allow user to view workspaces from Waypoint web ui.  Similar to how Vault namespace web ui display

**Describe the solution you'd like**
A drop down list at the header that allow user to select which workspace they would like to view.  Pairing with RBAC, it will help to segregate Team A can view Workspace A, TEam B can view Workspace B

**Comment by almonk** [comment]
@josephlim75 thanks for raising this issue. Below are the proposed designs for the Waypoint UI.

![Application -_ Deployments](https://user-images.githubusercontent.com/51724/119483858-53bda100-bd4d-11eb-9c27-2b6929d3d839.png)

![Application -_ Deployments-1](https://user-images.githubusercontent.com/51724/119483863-54eece00-bd4d-11eb-82f8-bb4c0660326f.png)

**Comment by jgwhite** [comment]
Closed by #2674
