### ISSUE TITLE
Showing Project As Folder in Waypoint UI

### ISSUE THREAD

**Issue by josephlim75** [hashicorp/waypoint#1343]
**Is your feature request related to a problem? Please describe.**
Is there any possibility that when creating a project in waypoint by using '/' forward slash, the project will treat it as folder, similar to what Vault display the secret path.  This is how it is being shown in the current version.

![image](https://user-images.githubusercontent.com/21043283/114902900-41625600-9de4-11eb-9588-927102589b4c.png)

**Describe the solution you'd like**
Example : `waypoint.hcl`
project = "dev-cluster/alpine"

Can it be shown like the following screenshot ?.  There are advantages of doing this so that we could group applications in folders.  Is also good to have a search textbox to filter and drill down to the application we would like to see

![image](https://user-images.githubusercontent.com/21043283/114902568-f2b4bc00-9de3-11eb-8095-2d44d452017b.png)
![image](https://user-images.githubusercontent.com/21043283/114902680-0eb85d80-9de4-11eb-9077-ac4bc0aba514.png)
![image](https://user-images.githubusercontent.com/21043283/114902727-1b3cb600-9de4-11eb-9391-4bcb6ee48d13.png)

**Comment by krantzinator** [comment]
I'm trying to understand the request. Are you asking if you can have multiple sub-projects nested underneath a given parent project? So you want to create `dev-cluster/alpine` and `dev-cluster/slim`, and then see both `alpine` and `slim` show up as separate projects if you click on `dev-cluster` on the Projects page?

**Comment by josephlim75** [comment]
Your understand is correct.  That is what my intention is.  Is that something feasible to be implemented ?

**Comment by krantzinator** [comment]
We don't plan to support this specific method of nesting projects, but we do provide support for [workspaces](https://www.waypointproject.io/docs/workspaces). Can you take a look and see if workspace management would help you out here? (Workspace management is currently done through the CLI only, but UI support is coming.)

**Comment by josephlim75** [comment]
`workspaces` does works for us.  We have already tried that earlier.  As you have mentioned, the UI support will be important for us.  If UI support is coming in near future, this will definitely fulfill our requirement.  You can close this issue as `workspaces` will solve the problem

**Comment by krantzinator** [comment]
Great! Thank you!
