### ISSUE TITLE
Ruby buildpack does not see ENV vars, causing bundle install to fail with e.g. sidekiq-pro

### ISSUE THREAD

**Issue by paulca** [hashicorp/waypoint#1353]
**Describe the bug**
We use sidekiq-pro for background jobs, which requires either `bundle config set enterprise.contribsys.com username:password` or the `BUNDLE_ENTERPRISE__CONTRIBSYS__COM` to be set.

Despite setting the env var, it doesn't appear to be available during the build process, so bundle install fails:

<img width="604" alt="CleanShot 2021-04-19 at 16 04 44@2x" src="https://user-images.githubusercontent.com/1229/115258563-fe2c1e00-a128-11eb-8b16-ea63221978c8.png">

**Steps to Reproduce**

I have a clean, non-custom `waypoint.hcl` file. The app uses [Sidekiq Enterprise](https://sidekiq.org/products/enterprise.html), so if you have access to something like that, or any gem that requires authentication.

**Expected behavior**
bundle install should succeed and all gems should be installed.

**Waypoint Platform Versions**
* Waypoint CLI Version: Waypoint v0.3.0
* Waypoint Server Platform and Version: Docker Desktop 3.2.2
* Waypoint Plugin: Just Docker

**Comment by evanphx** [comment]
Hi! So thinking more about this, there isn't a consistent way to forward env vars into our builders, so instead we'll have to deal with one-off.

For pack, I suggest using the `static_environment` map to pass the var in. Basically you'd have something like this:

```hcl
app "myapp" {
  build {
    use "pack" {
       static_environment = {
          "BUNDLE_ENTERPRISE__CONTRIBSYS__COM" = "username:password"
       }
    }
  }
...
```

Or once 0.3.2 is released and you want to use a Dockerfile directly, you'll need have the Dockerfile set a build arg as the environment (see https://vsupalov.com/docker-build-pass-environment-variables/) and then pass in a build arg in the config:

```hcl
app "myapp" {
  build {
    use "docker" {
       build_args = {
          "contribsys_access" = "username:password"
       }
    }
  }
...
```

**Comment by evanphx** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
