### ISSUE TITLE
unknown method IsExecer for service hashicorp.waypoint.sdk.Platform

### ISSUE THREAD

**Issue by rwsegura** [hashicorp/waypoint#1377]
**Describe the bug**
I have been using Waypoint with [this 3rd party plugin](https://github.com/turnerlabs/waypoint-plugin-fargate) since release. However with 0.3.0 on the deploy stage we now see this error:

```
unknown method IsExecer for service hashicorp.waypoint.sdk.Platform
```

This does not happen in Waypoint 0.2.x or lower. I am not sure if this is an actual issue with Waypoint or something has been deprecated and the plugin must adapt. I could not find anything to suggest something was removed or changed the plugin would need to adapt with.

**Steps to Reproduce**
1. Create a Waypoint file using the plugin above
2. Run waypoint up

**Expected behavior**
Deployment to not error

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.3.0
* Waypoint Server Platform and Version: kubernetes

**Additional context**
I should note the deploy step never hits our waypoint server.

Example waypoint.hcl
```
project = "auth-service"

app "auth-service" {
  build {
    use "docker" {
      disable_entrypoint = true
      dockerfile = "./Dockerfile"
    }
    registry {
      use "aws-ecr" {
        region = "us-west-2"
        repository = "auth-service"
        tag = "latest"
      }
    }
  }
  deploy {
    use "fargate" {
      region = "us-west-2"
      cluster = "auth-service"
      service = "auth-service"
    }
  }
}
```

**Comment by evanphx** [comment]
@rwsegura The bug here is that you forgot to update your waypoint server to 0.3.0 as well as the client. The client is asking the server about some new APIs and they aren't there because the server is still running 0.2.x.

**Comment by mitchellh** [comment]
@evanphx we should probably handle the error code not implemented for these situations and behave as if IsExecer is just false. That’s what we have tried to do with other introductions (such as the server side up operation in 0.3)

**Comment by evanphx** [comment]
yaeh, I was a little surprised we didn't hear. I believe it's done elsewhere.

**Comment by rwsegura** [comment]
Hello,

Thank you for the quick reply!

We update our Waypoint Server to version 0.3.1. The error still persists. Is there some output I could provide to help with triage?

Output of Waypoint Version:
```
[rednave@Developer auth-service]$ waypoint version
CLI: v0.3.1 (b550e5ce)
Server: v0.3.1
```

**Comment by evanphx** [comment]
@rwsegura that's pretty odd. It looks like the plugin is using a quite old version of the plugin-sdk and needs to be updated. That being said, we should be handling this more gracefully. Would you mind running `waypoint -v up` and gist'ing the output?

**Comment by rwsegura** [comment]
@evanphx here is the gist: https://gist.github.com/rwsegura/427db71e326a4be4de4e669d101d0f4a

**Comment by peytoncasper** [comment]
I just wanted to add that updating to this version of the plugin sdk resolved this issue for me. I pulled it from the existing build in waypoint plugins go.mod.

github.com/hashicorp/waypoint-plugin-sdk v0.0.0-20210510195008-b42c688ebedf

**Comment by evanphx** [comment]
@peytoncasper Thank you for confirming!
