### ISSUE TITLE
Deploying Waypoint to EKS Fargate results in a timeout

### ISSUE THREAD

**Issue by digitalsanctum** [hashicorp/waypoint#1399]
**Is your feature request related to a problem? Please describe.**

I attempted to install WP on an AWS EKS cluster on Fargate and the result was a timeout with no indication of why. 

Here's the interaction that occurred:
```
wp install --platform=kubernetes -accept-tos
 + Creating Kubernetes resources...
 + Kubernetes StatefulSet reporting ready
 ! Waiting for Kubernetes service to become ready..
! Error installing server into kubernetes: timed out waiting for the condition
```

**Describe the solution you'd like**
It would be nice to have some validation that the EKS cluster is not Fargate only and have a fast feedback error message indicating that WP requires node group.

**Describe alternatives you've considered**
n/a

**Explain any additional use-cases**
n/a

**Additional context**
n/a

**Comment by evanphx** [comment]
@digitalsanctum This kind of timeout is because the service failed to start. Was the issue because your cluster had no node groups?

**Comment by digitalsanctum** [comment]
> @digitalsanctum This kind of timeout is because the service failed to start. Was the issue because your cluster had no node groups?

@evanphx Yeah, I was trying to install to a Fargate only cluster.

**Comment by evanphx** [comment]
@digitalsanctum I haven't used an EKS Fargate cluster yet. Did you not hook a node group up to it by accident?

**Comment by digitalsanctum** [comment]
Nah, I was trying Fargate only

**Comment by evanphx** [comment]
@digitalsanctum can you please get the `kubectl get pods` and `kubectl describe pod <id>` for the pod that didn't launch? It's not clear why it failed to launch since EKS should have started the pod on fargate.

**Comment by evanphx** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
