### ISSUE TITLE
feature-request: Add `waypoint project destroy`

### ISSUE THREAD

**Issue by denysvitali** [hashicorp/waypoint#1418]
**Is your feature request related to a problem? Please describe.**
Currently, there seems to be no way to delete a project or a remote app (= easily without creating an hcl file locally).

**Describe the solution you'd like**
It would be great to be able to delete projects from the UI / CLI and maybe being able to do so _per workspace_.

**Describe alternatives you've considered**
Destroying the Waypoint DB and restarting from scratch - although it doesn't seem like a good alternative for production 😄 

**Explain any additional use-cases**
- Being able to delete certain apps from certain workspaces
- Being able to delete certain projects from certain workspaces
- Being able to delete all projects from a certain workspace

**Additional context**
None

**Comment by evanphx** [comment]
This goes along with `waypoint destroy` which removes all the Builds, Deploys, and Releases for an application but not the application (or project) itself. We need to provide the ability to delete the project/application itself as well.

**Comment by kamilgregorczyk** [comment]
almost a year later, a simple delete is still not there 😢

**Comment by fewknow** [comment]
This is preventing people from wanting to use this product in production.

**Comment by JPBeltman** [comment]
Bumping the issue. Just signed up for HCP and was checking out some resources in  when waypoint got activated, seems there is still no way on a brand new account (no resources added)
