### ISSUE TITLE
Release Operation always returns proto message even if platform has no releaser configured

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1478]
**Describe the bug**

I'm not 100% sure if the decision to return a Release proto was intentional, but I believe this might be a cause of confusion and potentially a bug at the moment for the UI and release CLI command. There might be some logic we aren't fully checking which causes some confusion behavior. I'll try my best to explain what I think is going on and why the behavior might be occuring!

The [operation_release job](https://github.com/hashicorp/waypoint/blob/main/internal/runner/operation_release.go#L139-L143) always returns a Release proto message, even [if the requested platform doesn't implement a release](https://github.com/hashicorp/waypoint/blob/main/internal/core/app_release.go#L60-L64). This makes sense since the operation is returning the top level Release proto message, but it looks like the UI still shows that a "release" happens with a SHA. It's also possible there are other parts of the code that make this assumption that a release occurs, like with the `waypoint release` CLI for example:

```
# release an old release (docker platform, with no releaser implemented)

$ waypoint release 01F5XKRRCRRCZ2RWA8W820X3D8
» Releasing...
» Pruning old deployments...
  Deployment: 01F5XKRRCRRCZ2RWA8W820X3D8
Deployment 01F5XMMCEDGE8S3ZMGC9R42P60 marked as released.
No release manager was configured and the configured platform doesn't
natively support releases. This means that releasing doesn't generate any
public URL. Waypoint marked the deployment aboved as "released" for server
history and to prevent commands such as "waypoint destroy" from deleting
the deployment by default.
```

Then try to release a different release after a few `waypoint deploy`s:

```
# 'foo' could also be another recent release after the initial successful release

$ waypoint release foo
The deployment "01F5XN9V4318GS5ZFSWXYWAB6X" is already the released deployment. Nothing to be
done.
```

Additionally, as a Waypoint dev, determining if a release actually happened on the result returned by the release operation requres this check:

```golang
if releaseResult != nil && releaseResult.Release != nil && releaseResult.Release.Release != nil {}
``` 

Which makes me wonder if there are other places that assume if `releaseResult` is not nil, a release occured.

The ultimate question here is:

Should the release operation be returning a Release proto message if no releaser was configured? Should it include a higher level option in the proto message that marks the release as skipped or unimplemented?

**Steps to Reproduce**

Look at release result on a platform with no releaser, like docker.

**Expected behavior**

Unclear, I can see returning a Release proto message as being intentional, even if no releaser was configured. Maybe we need to be more explicit when checking for releases beyond if the release result was nil or empty.

**Waypoint Platform Versions**

n/a, I assume this has been this way for a while but it's at least on `main` and the latest release 0.3.2.

**Additional context**

**Comment by mitchellh** [comment]
I think always returning a release proto makes sense. Instead I'd maybe change or add a field to the release result structure that determines if the release was done or not. Perhaps...

**Comment by evanphx** [comment]
@mitchellh Is there a reason always returning a release proto even if there was no actual release makes sense? It appears many things assume (albeit incorrectly) that if there is a release value, there was a release.
