### ISSUE TITLE
List releases from the CLI

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1479]
It would be nice to be able to list releases from the CLI. It would enable me to learn which deployment is currently released without visiting the UI.

Ideally, I think it would include the following:
- The release ID, for cross-referencing to a deployment
- The release platform (alb, k8s, etc).
- The date/time the release occured
- The release hash (i.e. `01F5XRRQ2CDSK8DJQ0GM1PFMTR`)? The UI gives this, but i'm not sure what value it has, and `deployment list` doesn't give you the hash either
- The global release horizon url? I don't know if it belongs here, but I don't think can be obtained anywhere else from the CLI currently.

It's not clear to me what the noun should be. We have `waypoint deploy` and `waypoint deployment list`. If we choose `waypoint release list`, we're overloading the release command unlike deploy. If we choose `waypoint releases list`, then we have inconsistent pluralization with deployment.

**Comment by evanphx** [comment]
This is related to #1478 because if we list releases, we should be listing them accurately.

**Comment by briancain** [comment]
We have an `Unimplemented` field now. So I think when ever this work starts, we can just omit any unimplemented releases since they didn't actually occur.

**Comment by briancain** [comment]
In terms of what we show, I think it should be similar to a `waypoint deployments list`. Something like:

- Id (the release sequence id)
- Deployment id (the sequence id)
- Platform
- Application
- Workspace
- Preload details (if any)
- Started
- Completed
- Health
- Url (omit if no release URL)
