### ISSUE TITLE
UI and CLI should agree on which representation of ID or Seq Number is displayed

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#1513]
Presently, the CLI shows mostly sequence numbers by default but the UI shows ID. They should agree on what they show by default.

**Comment by mitchellh** [comment]
My opinion is we should standardize on the seq number everywhere. The downside of the seq number is it requires the `(project, app)` to have meaning. The ID is globally unique, the seq number is only unique within the full tuple of `(project, app, seq)`. However, I think from a UX perspective, you're using operating in that context anyways, so it makes sense.

Internally, our APIs should probably continue accepting both cause its easy enough.

**Comment by evanphx** [comment]
Could/should we establish a format to capture that tuple in the UI? For instance a common format of `#{app_name}:#{seq_no}` or something?

**Comment by mitchellh** [comment]
> Could/should we establish a format to capture that tuple in the UI? For instance a common format of `#{app_name}:#{seq_no}` or something?

Yeah, the CLI currently accepts the `project/app` format for THAT, we could do like `project/app#seq` or something similar to GitHub's reference style...

**Comment by evanphx** [comment]
👍🏻

**Comment by izaaklauer** [comment]
We also use ULIDs as names for aws resources we create (i.e. my target group is called `example-nginx-4C4THAKBKPN61X25HA`). Sequence number would be much friendlier there anyway, and we should remember to change that too so platform owners can still tie resources back to deployments.

**Comment by jgwhite** [comment]
Just to ensure we’re all on the same page about the scope of these changes:

![image](https://user-images.githubusercontent.com/34030/122240719-474ae500-cec2-11eb-9630-630eb122a110.png)

**Comment by izaaklauer** [comment]
I like the idea of having some advanced way to get the internal ID out of the UI, both for us and for advanced users trying to reference debug logs.

Other than that, I agree with the scope of the UI changes.

**Comment by evanphx** [comment]
Yes, you're correct @jgwhite. We have the sequence number there, it's the #4 or v4 in other views. View wise, we can just not show the ulid if the sequence number is right there too, giving more visual area for other things.

**Comment by jgwhite** [comment]
@evanphx perfect. That fits in well with @almonk’s latest designs.
