### ISSUE TITLE
Support for environments that use different platforms

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1517]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to have a workflow that deploys to docker for development and ECS in production.

With input variables, I could switch between dev and prod ECS clusters, but I cannot use different platform plugins for different environments.

**Describe the solution you'd like**

This could be solved by allowing duplicate dev and prod waypoint.hcl files, but I think ideally I would be able to describe my environments in a single file.

**Describe alternatives you've considered**

- Input vars
- Duplicate config files (maybe isolated in different branches or repos)

**Comment by nathancoleman** [comment]
I ran into this issue recently and resorted to creating separate applications for development and production. This wasn't ideal though and seems to go against the spirit of applications described [here](https://www.waypointproject.io/docs/waypoint-hcl/app) and [here](https://www.waypointproject.io/docs/projects#multiple-applications).
