### ISSUE TITLE
Checkbox appears twice in new project screen

### ISSUE THREAD

**Issue by almonk** [hashicorp/waypoint#1518]
**Describe the bug**
In latest Safari, the checkbox to enable a GitHub repo is shown twice
![CleanShot 2021-05-20 at 10 16 30](https://user-images.githubusercontent.com/51724/118953201-841fcc80-b954-11eb-92f5-5cbc475d5e74.png)

**Steps to Reproduce**
Create a new project in macOS Safari 

**Expected behavior**
Only the styled checkbox should be shown

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

CLI: v0.3.1 (b550e5ce)
Server: v0.3.1

**Comment by jgwhite** [comment]
The checkboxes appear to render correctly [in the structure docs](https://structure.hashicorp.vercel.app/?path=/story/components-checkboxfield-facade--index) so we must have a CSS conflict in the project. Good spot!

**Comment by almonk** [comment]
@jgwhite I filed a similar bug a month or so ago (https://github.com/hashicorp/waypoint/issues/1305) which was resolved, so this appears to be a regression to that

**Comment by jgwhite** [comment]
Looks like upgrading to pds-ember 0.6.0 does the trick. Some improvements to the “facade” styles.

**Comment by gregone** [comment]
weird, I wonder why this happened again?
