### ISSUE TITLE
Display Docker Image Version

### ISSUE THREAD

**Issue by denysvitali** [hashicorp/waypoint#1520]
**Is your feature request related to a problem? Please describe.**

Currently, Waypoint considers a "version" to be an instance of a deployment.
Whilst this is great for many use cases, it is not fascinating as it is basically removing information such as:
- which commit is this build based on?
- which Docker tag is being used?
- what was the last change?

Examples of the current UI:

<img width="879" alt="Screenshot 2021-05-20 at 12 42 35" src="https://user-images.githubusercontent.com/4939519/118965374-ebe01280-b968-11eb-82fb-4cfb16bc0a65.png">

<img width="1587" alt="Screenshot 2021-05-20 at 12 44 34" src="https://user-images.githubusercontent.com/4939519/118965641-2ea1ea80-b969-11eb-9cd1-cdb4d8e5b2f4.png">

Examples of the current CLI:

```
$ waypoint deployment list -workspace-all
    | ID |   PLATFORM   |  DETAILS   |   STARTED    |  COMPLETED
----+----+--------------+------------+--------------+---------------
  ✔ | 14 | cloudfoundry | artifact:6 | 18 hours ago | 18 hours ago
  ✖ | 13 | cloudfoundry | artifact:5 | 18 hours ago | 18 hours ago
```

The Waypoint UI (and the CLI) are not showing any relevant information to the user about what has been deployed. A vague ID / version is provided instead.

**Describe the solution you'd like**

We should be able to see exactly which artifact has been deployed / released in a certain workspace and maybe add relevant information such as "which commit did generate this change".

Without this improvement, it is really hard to tell with a quick glance, which Docker Image (repository + tag) was used or which commit caused the build to be triggered.

**Describe alternatives you've considered**

N/A

**Explain any additional use-cases**

- Seeing the version (as in software version, not Waypoint version) of the deployment that is currently deployed / released
- Getting with a quick glance the reason why a certain deployment / release was performed (`git log --format="%h: %s" | head -n1`)
- Reverting to a specific version by performing a GitOps revert commit directly from waypoint (write access to the GitOps repo)

**Additional context**

Our use case is mainly focused on Docker images and their tags. We would like to know, at any time, which version are we running in dev, staging or prod.

**Comment by jgwhite** [comment]
Thanks for the detailed write-up. We’re currently planning to add git information in the UI for the 0.5.0 release (#1508) but to the best of my knowledge we haven’t written up plans for surfacing docker image information yet (someone please correct me if I’m wrong). You’ve provided some great details and use-cases to motivate that work, and we’ll be sure to incorporate it into our planning.

**Comment by mitchellh** [comment]
You're right @jgwhite we haven't discussed this yet.

I'll add some more color to this for future discussion: each registered artifact is query-able and has a `google.protobuf.Any` details field on it. We could detect specific well known types (such as Docker images) and use that to extract meaningful information out of it such as the image name and tag, and potentially the UI or CLI could render this. So this is possible!

**Comment by evanphx** [comment]
If plugins had the ability to set labels on the artifacts, we could have a vocab of labels that are treated specially. For instance `waypoint/source` could be displayed by the UI.

**Comment by mitchellh** [comment]
> If plugins had the ability to set labels on the artifacts, we could have a vocab of labels that are treated specially. For instance `waypoint/source` could be displayed by the UI.

Good point. They already do, its just not well documented probably: https://github.com/hashicorp/waypoint-plugin-sdk/blob/53694fdd7d98e5e4df3be191d7ed547f914312bd/component/component.go#L213 If you implement this interface in your artifact return value it sets labels.
