### ISSUE TITLE
internal/server/singleprocess: Flaky tests

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1521]
**Describe the bug**
Flaky tests in `internal/server/singleprocess`

**Steps to Reproduce**
Flakes from:
- ~`TestServiceRunnerJobStream_cancel`: [one](https://app.circleci.com/pipelines/github/hashicorp/waypoint/4393/workflows/3c705bad-3280-4e46-91ab-9c22c1636ee5/jobs/31799) and [two](https://app.circleci.com/pipelines/github/hashicorp/waypoint/5710/workflows/1a5d72db-0c69-4873-b52b-9ba984ef6d03/jobs/43406)~ Fixed by #1538 
- `TestServiceGetLogStream_depPlugin`: [one](https://app.circleci.com/pipelines/github/hashicorp/waypoint/4771/workflows/8ca9236e-eb93-4b79-8896-52431556b9f6/jobs/35491) and [two](https://app.circleci.com/pipelines/github/hashicorp/waypoint/5786/workflows/a602c260-80fd-4db5-b944-218852e3bd98/jobs/44248)
- [`TestServiceEntrypointExecStream_invalidSessionId`](https://app.circleci.com/pipelines/github/hashicorp/waypoint/2907/workflows/174cbbb0-caba-489c-8f20-c5e7658e59f0/jobs/20495)

**Expected behavior**
Less flakes.

**Waypoint Platform Versions**
All.

**Comment by mitchellh** [comment]
So the `fault` errors are actually potentially bugs in BoltDB. They seem to pop up in _any_ test and the stack traces are deep in Bolt. I would separate those from this issue cause thats a bigger discussion of if we want to switch to the etcd fork since they maybe have fixed this...

The others are probably real flakes that are our fault. 😄

**Comment by krantzinator** [comment]
Updated to remove the `fault` error tests, and will put that info in our planning doc instead.

**Comment by evanphx** [comment]
Given the merger of #1538, we're going to presume that these are fixed.
