### ISSUE TITLE
plugins/{ecs/ec2}: Report on deployment and release status

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1556]
**Is your feature request related to a problem? Please describe.**

The ECS and EC2 plugins should report on the status of a deployment and release: https://github.com/hashicorp/waypoint/issues/1224

**Describe the solution you'd like**

Include a StatusFunc for both plugins and build a health report

**Comment by izaaklauer** [comment]
Closing this for now. ECS now builds status reports, and EC2 should be it's own issue.
