### ISSUE TITLE
ui: Reconcile icon colors

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1581]
**Is your feature request related to a problem? Please describe.**
The icons in the UI were updated for status reports. We should use these updated icons across all indicators.

**Describe the solution you'd like**
For example, here is the UI with Deployments with status checks showing the status check icons, and the Builds and Releases still using the original icons.
![image](https://user-images.githubusercontent.com/8461333/120663997-8efc5600-c458-11eb-9d31-e4151ccddddc.png)

**Additional context**
The icons were updated after an accessibility review to make the color contrast meet standards. This is why the new icons are preferable to the original set.

**Comment by jgwhite** [comment]
The plans in WP-071 will address this.

**Comment by jgwhite** [comment]
Closed by #1668
