### ISSUE TITLE
ui: dark mode tabs on-hover state

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1582]
**Describe the bug**
On-hover of tabs on dark mode whites out the whole tab.

**Steps to Reproduce**
Spin up the UI in dark mode.
![Screenshot from 2021-06-03 10-47-00](https://user-images.githubusercontent.com/8461333/120664983-61fc7300-c459-11eb-8fc8-9e9cb64cf11c.png)

**Expected behavior**
The tabs should be legible on-hover.

**Waypoint Platform Versions**
This has been around for several versions, possibly the whole time.

**Comment by jgwhite** [comment]
Closed by #1597
