### ISSUE TITLE
docs: Plugin Pack `ignore` field fails to properly auto-format with docs autogen

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1589]
**Describe the bug**

Our auto-gen tool ends up smashing all of the `ignore` help text about ignoring files into a single paragraph instead of respecting the formatting defined.

**Steps to Reproduce**

`waypoint docs -website-mdx`

Then run the website, navigate to the pack plugin, and read the ignore field.

**Expected behavior**

It should format the mdx file like how its defined in the component.

**Comment by krantzinator** [comment]
Fixed by https://github.com/hashicorp/waypoint/pull/1803
