### ISSUE TITLE
Unable to list deployments with v0.4.0

### ISSUE THREAD

**Issue by HeavyHorst** [hashicorp/waypoint#1595]
**Describe the bug**

`waypoint deployment list` fails with the following error:
! unknown method GetLatestStatusReport for service hashicorp.waypoint.Waypoint

This only happens with Version 0.4.0

**Steps to Reproduce**

Install version v0.4.0 and run waypoint deployment list

**Expected behavior**
```
$ waypoint version
CLI: v0.3.2 (b0f44cd6)
Server: v0.3.2

$ waypoint deployment list
     | ID |  PLATFORM  |  DETAILS   |   STARTED   |  COMPLETED   
-----+----+------------+------------+-------------+--------------
  🚀 |  7 | kubernetes | artifact:7 | 3 weeks ago | 3 weeks ago 
```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4.0
* Waypoint Server Platform and Version: kubernetes (I ran waypoint server upgrade)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Comment by krantzinator** [comment]
I was able to get this error message with mis-matched CLI and server versions (CLI 0.4.0, server 0.3.2), but if both CLI and server are 0.4.0 I do not get the error. (running a server on docker)
Can you confirm that both your CLI and server were running 0.4.0 at the time of the error?

**Comment by HeavyHorst** [comment]
Ah, that seems to be the problem:

```
$ waypoint version
CLI: v0.4.0 (3b3dd831)
Server: v0.3.2
```

```
waypoint server upgrade -platform=kubernetes -auto-approve
✓ Context "install-1620673572" validated and connected successfully.
✓ Snapshot of server written to: 'waypoint-server-snapshot-1622811846'

» Upgrading...
  Waypoint server will now upgrade from version "v0.3.2"
✓ Gathering information about the Kubernetes cluster...
✓ Image set to update!
✓ Upgrade complete!

Kubernetes is now set to upgrade waypoint server image with its
'RollingUpdate' strategy. This means the pod might not be updated immediately.

» Verifying upgrade...
✓ Server connection verified!

» Upgrading runner if required...
✓ Previous runner uninstalled
✓ Runner deployment deleted
✓ Installing runner...
✓ Creating Deployment for Runner
✓ Kubernetes Deployment for Waypoint runner reporting ready

Server upgrade for platform "kubernetes" context "install-1620673572" complete!
Waypoint has finished upgrading the server to version "v0.3.2"

Advertise Address: xxxx:9701
   Web UI Address: https://xxxxx:9702
```

i thought this command would install the latest version.

I was able to install the latest version with:
`waypoint server upgrade -platform=kubernetes  -k8s-server-image=hashicorp/waypoint:0.4.0 -auto-approve`
what fixed the problem.


Thanks for the help!

**Comment by krantzinator** [comment]
Oh, odd! It should have pulled `waypoint:latest`, yes. We'll look into that too.
Thanks for letting us know, this was still an edge case we needed to handle, and now we do 🙌🏻

**Comment by krantzinator** [comment]
Oh, this may be due to the k8s cluster checking to see that it has `waypoint:latest` and it did so it didn't pull a new version -- but its latest was `waypoint:0.3.2`.
