### ISSUE TITLE
Enhancement/API: Add endpoint that retrieves a Deployment or Release with an associated status report

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1622]
**Is your feature request related to a problem? Please describe.**

When asking for a deployment or release, you likely also what to know what the reported health status was. For both the planned CLI command [waypoint status](https://github.com/hashicorp/waypoint/issues/1501) and future UI enhancements or current UI improvements (/cc @jgwhite for any additional context), having this endpoint seems like an easy addition to the api with high value added.

**Describe the solution you'd like**

Instead of requiring the caller to make a couple of requests for a deployment/release plus a status report, we should provide an endpoint that includes both of these things to save an extra API call. For an example getting a deployment with a report, we'd add an endpoint like `GetDeploymentsWithStatusReport` which would return all of the deployment info, artifact info, and the latest associated status report.

**Comment by jgwhite** [comment]
As you say, this seems like it has a high return-on-investment.

One thought: do we go with a very-explicit `ListDeploymentsWithStatusReports` or something more general like `ListDeploymentsExpanded` to encompass bundling in `status_reports`, `artifact`, `build`, `deploy_url`, and any other associated entities we may wish to include in future?

A very rough sketch:

```proto
service WaypointUI {
  rpc ListDeploymentsExpanded(ListDeploymentsExpandedRequest) returns (ListDeploymentsExpandedResponse);
}

message ListDeploymentsExpandedRequest {
  Ref.Application application = 1;
  Ref.Workspace workspace = 2;
  repeated StatusFilter status = 3;
  Operation.PhysicalState physical_state = 4;
  OperationOrder order = 5;
  bool include_latest_status_report = 6;
  bool include_artifact = 7;
  bool include_build = 8;
  bool include_deploy_url = 9;
  // ... more in future?
}

message ListDeploymentsExpandedResponse {
  repeated DeploymentExpanded deployments = 1;
}

message DeploymentExpanded {
  Deployment deployment = 1;
  StatusReport status_report = 2;
  PushedArtifact artifact = 3;
  Build build = 4;
  string deploy_url = 5;
}
```

The term “expanded” is a bit wooly, but the best I could think of.

**Comment by briancain** [comment]
Totally, I think something like `ListDeploymentsExpanded` is probably a more future thinking way to go about implementing this. I'm sure there will be other _things_ we'll associate with deployments and releases in the future so those API calls could stay the same but get more data in the future. Sounds good to me! 👍🏻

**Comment by briancain** [comment]
We can totally bike shed on the name too once the implementation starts. Maybe `List(Deployments|Releases)FullDetails`? 🤔

**Comment by jgwhite** [comment]
`List(Deployments|Releases)WithKitchenSink` 😅

**Comment by jgwhite** [comment]
@briancain shall we take this out of the 0.4.x milestone? It’s definitely a good goal, but probably not a requirement for 0.4.x

**Comment by briancain** [comment]
I was planning on using it for the [waypoint status](https://github.com/hashicorp/waypoint/issues/1501) command, so I'll move it into the 0.5.0 bucket since I think it's more or less required to make that easy to implement. But totally not a 0.4.x requirement, good call!

**Comment by jgwhite** [comment]
I’ve pushed this to `0.5.x` because there’s no feature in `0.5.0` that depends upon it, and we’re still hashing out the details so it’s unlikely to be implemented in time for `0.5.0`.

We have an internal RFC for this now. Further conversation is happening there until we start implementing.

**Comment by jgwhite** [comment]
@briancain & @izaaklauer 
Shall we say that #1994 closes this?

**Comment by briancain** [comment]
@jgwhite Yep. I'll go ahead and close this. We should open a new issue for tracking the pagination feature once we're sure what it's going to be like.
