### ISSUE TITLE
Error when installing server on docker

### ISSUE THREAD

**Issue by jcollado** [hashicorp/waypoint#1642]
**Describe the bug**
`waypoint install --platform=docker -accept-tos` fails to complete

**Steps to Reproduce**
Run `waypoint install --platform=docker -accept-tos` and get the following error:
```
$ waypoint install --platform=docker -accept-tos
✓ Pulling image: hashicorp/waypoint:latest
 │ latest: Pulling from hashicorp/waypoint
 │ Digest: sha256:a81537a8bc68c2ed69604ce1c377e861d5b06f8256cfaf809ccfb30ba99e8ecd
 │ Status: Image is up to date for hashicorp/waypoint:latest
✓ Installing Waypoint server to docker
✓ Server container started!
❌ Retrieving initial auth token...
! Error attempting to authenticate to bootstrapped server:
  
  Waypoint has detected that the server has already been deployed and bootstrapped.
  However, the current context used to restart the server is not configured
  to authenticate to the current server. If there is a valid context, switch
  to it using "waypoint context use".
```

The server is running according to docker:
```
$ docker container ls
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS              PORTS                              NAMES
19de16178fc4   hashicorp/waypoint:latest   "/usr/bin/waypoint s…"   About a minute ago   Up About a minute   0.0.0.0:9701-9702->9701-9702/tcp   waypoint-server
```

However, if I remember correctly, when trying the same command in `0.3`, it worked and runner container was also running next to the server container.

**Expected behavior**
`waypoint install` command runs without any error

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4 (I tried with 0.3 in the past and it worked)
* Waypoint Server Platform and Version: `docker` 20.10.2 (both client and server)
* Waypoint Plugin: N/A

**Additional context**
Running on Ubuntu 20.04 LTS

**Comment by jgwhite** [comment]
The output indicates that the server booted from an existing database, likely from an existing docker volume, for which you no longer have a token (stored in a CLI context).

If you’d like to start again from a clean slate, try the following:

1. Uninstall the server from docker:
   ```
   waypoint server uninstall -platform=docker -auto-approve
   ```
2. Remove the `waypoint-server` volume (the previous step may have achieved this):
   ```
   docker volume rm waypoint-server
   ```
3. Try installing the server again

Hope that helps. Let me know if I’ve missed any details.

**Comment by jcollado** [comment]
Removing the docker volume worked as expected. Thanks!
