### ISSUE TITLE
Bug: `waypoint runner agent -remote` panics

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1704]
**Describe the bug**
Running `waypoint runner agent` with the `-remote` flag causes a panic for me under all circumstances.

Trace:
```
$ waypoint runner agent -remote

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x319bb61]

goroutine 1 [running]:
github.com/hashicorp/waypoint/internal/cli.(*baseCommand).Init(0xc000c00000, 0xc000d3fcb0, 0x4, 0x4, 0xc000caa3f0, 0xc000d3fb28)
	/home/circleci/project/waypoint/internal/cli/base.go:253 +0x821
github.com/hashicorp/waypoint/internal/cli.(*RunnerAgentCommand).Run(0xc000792c40, 0xc00040dab0, 0x1, 0x1, 0x0)
	/home/circleci/project/waypoint/internal/cli/runner_agent.go:40 +0x218
github.com/mitchellh/cli.(*CLI).Run(0xc000ca4000, 0xc000d3fee8, 0x3e2bf18, 0xc0003e84d0)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
github.com/hashicorp/waypoint/internal/cli.Main(0xc00040da80, 0x4, 0x4, 0x0)
	/home/circleci/project/waypoint/internal/cli/main.go:119 +0x57a
main.main()
	/home/circleci/project/waypoint/cmd/waypoint/main.go:14 +0xa5
```

**Expected behavior**

I am honestly not sure what this flag is supposed to be doing. I ran across it accidentally while trying to set up a standalone runner.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4.0
* Waypoint Server Platform and Version: 0.4.0
* Waypoint Plugin: any

**Additional context**

It's crashing [here](https://github.com/hashicorp/waypoint/blob/321eb68d56e918968b0145392158826a9b77e5e8/internal/cli/base.go#L253), specifically when inspecting `c.cfg.Runner`.  The crazy thing is that c.cfg is, in fact, not nil _until_ you ask for `c.cfg.Runner`

It seems like a funky interaction with the embedded [*hclConfig](https://github.com/hashicorp/waypoint/blob/321eb68d56e918968b0145392158826a9b77e5e8/internal/config/config.go#L16), which is nil in this case?

https://github.com/hashicorp/waypoint/blob/321eb68d56e918968b0145392158826a9b77e5e8/internal/config/config.go#L15-L31

I also tried running it in a project directory with an hcl config that had a runner stanza, which I was kind of hoping would work based on the [error message](https://github.com/hashicorp/waypoint/blob/321eb68d56e918968b0145392158826a9b77e5e8/internal/cli/base.go#L255-L259) I think this panic is masking.

**Comment by mitchellh** [comment]
I don’t think the `waypoint runner` should take the `-remote` flag. Definitely a bug here but noting that that flag is non-sensical so we shouldn’t IMPLEMENT it, we should just fix the crash haha.
