### ISSUE TITLE
CLI: Add a `-prune` flag to `waypoint context verify`

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1707]
**Is your feature request related to a problem? Please describe.**

As Waypoint server contexts are destroyed out of band from the `waypoint server uninstall` command, there ends up being a lot of stale contexts left on disk. You can either delete them one by one (assuming you know which ones are valid), or you can delete them all at once with `waypoint context delete -all`. If you have any valid contexts left then neither option is very efficient.

**Describe the solution you'd like**

Update the `waypoint context verify` subcommand to include a `-prune` flag to remove any stale or invalid contexts that cannot be connected to or verified.

This might be slightly tricky if a context is still "valid" but the CLI can't connect to it. It might be accidentally pruned.

**Comment by grahamhub** [comment]
Hey, I'd be happy to take a stab at implementing this!

As far as accidental pruning goes, I've got two thoughts on how to approach ensuring valid contexts don't get pruned.

The first is just a simple confirmation after gathering all the contexts which couldn't be verified - and if a user sees a context they want to keep perhaps ask them to make sure it's running and reachable before re-running the command.

The second is another attribute contained within `~/.config/pilot/context/<ctx>.hcl` - something like a `last_verified` date that will prune contexts with a `last_verified` date X amount of time ago (perhaps a configurable amount of time as well, or just a reasonable default).

Let me know what you think!

**Comment by briancain** [comment]
Hey @grahamhub ! Sorry to take so long to get back to you. After some thinking, I don't think this feature actually makes sense to implement. It feels a lot like a Waypoint developer need, rather than a Waypoint user need. And the work required to get this right so that we don't accidentally prune legit contexts doesn't feel like it's worth it. Generally I don't imagine users will have so many contexts to prune that they'd want a flag, compared to the dev cycle (I'll often I have 30-50 old contexts lying around). Although perhaps in the future users might say otherwise, but for now I think it's not a big enough deal to do.

I appreciate you asking though! I'm going to go ahead and close this.
