### ISSUE TITLE
Ability to disable `waypoint exec` to mitigate security risk.

### ISSUE THREAD

**Issue by dzrtc** [hashicorp/waypoint#1720]
**Is your feature request related to a problem? Please describe.**
The existence of `waypoint exec` creates a security vulnerability in my environment, but the other capabilities of the entrypoint are nice.

**Describe the solution you'd like**
I'd like to be able to disable support for `waypoint exec` without disabling the Waypoint entrypoint entirely.

**Describe alternatives you've considered**
Disabling the Waypoint entrypoint is the only alternative, but it seems like overkill considering that `waypoint logs` is pretty useful.  On the other hand, there are plenty of service mesh sidecar proxy solutions that might, overall, be a better fit for monitoring instances.

**Explain any additional use-cases**
-

**Additional context**
-

**Comment by mitchellh** [comment]
Agreed, this is something we’ve wanted to do.
