### ISSUE TITLE
"bad signature: invalid authentication token" with new tokens

### ISSUE THREAD

**Issue by 1mamute** [hashicorp/waypoint#1721]
**Describe the bug**
Hello, i'm trying to setup a waypoint server to test the application with our team.  
- I created an EC2 instance with ports 9701 and 9702 open in the security group.  
- I SSHed in the instance and installed docker, waypoint. 
- Runned `waypoint install -platform=docker -accept-tos`, looked the logs with `docker logs -f waypoint-server` and the server's up. I reached the webUI in the browser using the public IP from the instance and got the authentication screen, seemed like everything is running smoothly.
- I created an application load balancer in front of the EC2 instance configured this way:
9701 - Listening on HTTPS - Targeting HTTPS port 9701 with gRPC protocol (this one don't become healthy no matter what I change in the health_check)
9702 - Listening on HTTPS - Targeting HTTPS port 9702 with HTTP1 protocol
- I generated a new token with `waypoint token new`. 
- I reached the WebUI through the LB, pasted the token and nothing happened. I thought I missclicked, then I tried again, many times. Didn't work.
- Tried directly on the IP of the instance, port 9702, didn't worked
- Cognito Tab didn't worked
- Authenticating with a invite token also didn't work

Here's the screenshots and logs below:

```
2021-06-27T21:59:01.078Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/ListProjects request
2021-06-27T21:59:01.078Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/ListProjects response: error="bad signature: invalid authentication token" duration=95.499µs
2021-06-27T21:59:01.078Z [INFO]  waypoint.server.http: HTTP request: POST /hashicorp.waypoint.Waypoint/ListProjects: date=2021-06-27T21:59:01.078079487Z http.host=example.org:9702 http.method=POST http.request_path=/hashicorp.waypoint.Waypoint/ListProjects http.remote_addr=my_ip http.response_size=0 http.scheme=https http.status_code=200 http.useragent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" http.version=HTTP/1.1
```

![image](https://user-images.githubusercontent.com/22196761/123560710-519a9800-d77a-11eb-85a2-c257abeb06e0.png)

**Steps to Reproduce**
Create an EC2 with ports 9701 and 9702 open and try to authenticate to it, I guess?

**Expected behavior**
I expected to be able to authenticate with CLI token and create new projects inside the WebUI.

**Waypoint Platform Versions**
* Waypoint CLI Version: v0.4.0
* Waypoint Server Platform and Version: docker (installed with `waypoint install -platform=docker -accept-tos`)

**Additional context**  
- Docker version: 20.10.7
- Browser: Google Chrome 91.0.4472.114 (64 bits)
- I generated a new token for a friend on mine and he also couldn't authenticate (he was using chrome too)
- I can telnet succesfully into 9701 and 9702 in both the IP Addres of the EC2 and the DNS name
- The following grpcurls are not reaching the gRPC endpoint:
`grpcurl -plaintext 55.55.55.55:9701 55.55.55.55.Waypoint/GetVersionInfo`
`grpcurl -plaintext example.org:9701 example.org.Waypoint/GetVersionInfo`

**Comment by izaaklauer** [comment]
Hey 1mamute,

That "bad signature: invalid authentication token" error that you're seeing generally occurs when you present waypoint with an invite token generated by a different waypoint server. Did you run `waypoint token new` on the ec2 instance that you installed the server on?

After you run `waypoint token new` on your ec2 server, and you use that token to authenticate in the UI, you'll be able to use the "Invite" button in the upper-right corner of the UI to generate a new token that you can use to create a working waypoint context locally.

**Comment by 1mamute** [comment]
Hey @izaaklauer,

Yes, I ssh'ed in the EC2 instance and run `waypoint token new`. I copied to token directly from the terminal to the UI, several times.

I'm 100% sure I was copying the token from inside the EC2 instance. `waypoint token invite` also didn't worked. 

Is there any other information I can give so we can find if i'm doing something wrong or the token is not being correctly checked?

**Comment by gregone** [comment]
@1mamute did you generate multiple contexts? And are you using the correct one from the CLI? You can run `waypoint context list` to see what you have and what default context you are using. It could be that your token was created for a different context than the one you're using, and is therefore not valid.

We tried your setup (without the LB) and it works as expected.

**Comment by 1mamute** [comment]
Tried again today, this time with waypoint 0.4.1. Everything went well. Don't know what I was doing wrong.

![image](https://user-images.githubusercontent.com/22196761/124512357-84621300-ddae-11eb-8a70-fef85d5866d8.png)

![image](https://user-images.githubusercontent.com/22196761/124512365-8926c700-ddae-11eb-8bf7-5f849438b3cd.png)

Closing the issue for the time being, If i jump into the problem I will reopen again. Thanks for the help everyone.

**Comment by izaaklauer** [comment]
@1mamute Glad it's working now, and please let us know if you experience this kind of issue again! We'll keep our eyes out for others experiencing this kind of problem too.
