### ISSUE TITLE
Poor man's waypoint.run implementation

### ISSUE THREAD

**Issue by apollo13** [hashicorp/waypoint#1762]
I simply cannot and do not want to use `waypoint.run`. I do understand that adding more code to the entrypoint to support other types of ingress probably makes no sense either. But I could imagine the following:

 * Allow starting waypoint with a disabled URL service and a "base-domain name" ala `--domain waypoint.office.lan`
 * Expose this domain as well as a hostname to the service created. To clarify, if you would have generated a URL like `app--v1.waypoint.run` pass `subdomain: app--v1, domain: waypoint.office.lan` as variables to the plugins
 * Depending on the plugin (for instance using `nomad-jobspec`) one could then configure a consul service with tags so an existing fabio/traefik would properly route to the service (or even consul ingress for that matter)

This way people not using the URL service can start building routing on their own. Or am I missing something and this can already be achieved somehow?

**Comment by krantzinator** [comment]
This issue is being tracked and discussed in #1160. We still need better documentation on how to do this. If you have any more context or requests for documentation, feel free to leave in #1160!
