### ISSUE TITLE
Polling should consider sub-directory of project for changes

### ISSUE THREAD

**Issue by denysvitali** [hashicorp/waypoint#1796]
**Is your feature request related to a problem? Please describe.**
The way Waypoint works currently is well described by the following paragraph of the documentation:
> A project in Waypoint is a 1:1 mapping to a VCS repository (if one exists). A project can be comprised of one or more applications. Each application in a project represents a single thing that can be deployed. A project is the first thing you ever create after installing Waypoint.

Waypoint seems to be more focused on tackling the CI + CD part, but most of the time the CI part might be super complex and thus be handled by another tool such as Jenkins. This is why (I guess?) Waypoint lets you have a "Build" step that is not really a build per se (e.g: `docker-pull`).

We're currently using Waypoint as a multi-cloud / multi-target continuous delivery software, and as such we're trying to use Waypoint as we would use [Flux.CD](https://fluxcd.io/), but for generic `waypoint.hcl` files.

In Flux.CD you usually have a single repository (single source of truth) containing all your Kubernetes manifests, and an agent on your Kubernetes cluster(s) takes care of polling your repository (exactly as Waypoint does) and `kubectl apply`ing the manfiests.

Unfortunately, for the way Waypoint is built, the separation between code and the continuous delivery part is not that easy to achieve for the following problems:

- Per-workspace project settings cannot be applied (this means that you cannot use branch `develop` for the `develop` workspace, branch `staging` for the `staging` workspace and so on...) (#1665)
- A git commit on the set-up repository triggers a `waypoint up`, despite maybe the files in the _Git Source Path (optional)_ did not change

In our current set-up, we have a `waypoint` repository configured as follows:
- 3 branches (`develop`, `staging`, `prod`)
- `project/waypoint.hcl` structure

The folder looks like following:
```
.
├── README.md
└── key
    ├── prj-1
    │   ├── VERSION
    │   └── waypoint.hcl
    └── prj-2
        ├── VERSION
        └── waypoint.hcl
```

The `waypoint.hcl` file looks like as follows:

```hcl
project = "prj-1"
labels = { "product" = "project-1" }

app "app-1" {
    build {
        use "docker-pull" {
            image = "prj-1"
            tag   = trimspace(file("${path.app}/VERSION"))
            disable_entrypoint = true
        }
    }

    deploy {
        use "cloudfoundry" {
            organisation = "org"
            space = "prj-1-${workspace.name}"
            domain = "xyz.swisscom.ch"
            envFromFile = file("${path.app}/.env")
            quota {
                memory = "512Mi"
                disk = "2Gi"
            }
        }
    }

    release {
        use "cloudfoundry" {
            domain = "xyz.swisscom.ch"
            hostname = "prj-1-${workspace.name}"
        }
    }
}
```

Jenkins opens a PR to our single source of truth repo with the change (bump of the `VERSION` file), so that then Waypoint can deploy the new stuff:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/4939519/124799121-7ea63200-df54-11eb-8199-a8c40dcdfe3b.png">

Unfortunately, with this approach, having as a Data Source for `prj-1` and `prj-2` the same git repository causes `prj-2` to be deployed as well if you change something in `prj-1`: this is due to the fact that file changes are not taken into consideration but the poll algorithm is merely checking for a newer commit and then running `waypoint up` with the _Git Source Path_ (which is different from `prj-1` and `prj-2`) 

**Describe the solution you'd like**

It would be awesome if the polling took into consideration paths as well (e.g: no files changed in `prj-1` directory, let's skip this commit). Bonus points if this polling is centralized so that we don't have to poll 10 times the same repository to check for changes when a single repository is specified for every project.

**Describe alternatives you've considered**

`1:1` project - repo mapping, although we're trying to move away from this approach because we would like to have a GitOps repository where all the CD related changes happen

**Explain any additional use-cases**

N/A

**Additional context**

N/A

**Comment by mitchellh** [comment]
There's multiple things here and they're all good:

## Polling should take into account sub-directories that a project specifies

This makes sense. I think one risk is you'd miss some changes if the project actually references files above its directory (which Waypoint doesn't restrict). I imagine that the default behavior ignoring this is correct, and we'd want some sort of override at some point to trigger on ANY repo change.

## Polling the same repo should happen 1 time rather than N for each project 

This makes sense as well and goes against how the polling works today (but can be fixed).

**Comment by denysvitali** [comment]
> This makes sense. I think one risk is you'd miss some changes if the project actually references files above its directory (which Waypoint doesn't restrict).

I actually wondered about the same, but we can have as a contract (between the user and Waypoint) that files changed outside of the "base path" will not trigger a deployment - which is totally fine if it's made crystal clear to the user IMHO.

Anyways, kind of unrelated question: is there a plan to have a flag to run `waypoint deploy` instead of `waypoint up`? I'm thinking on how feature branch previews could be implemented with this approach :D

**Comment by mitchellh** [comment]
> I actually wondered about the same, but we can have as a contract (between the user and Waypoint) that files changed outside of the "base path" will not trigger a deployment - which is totally fine if it's made crystal clear to the user IMHO.

Yes, that sometimes work. We did this with Terraform and it angered people cause there are usually legitimate monorepo usecases where you want to reach out. We'll figure it out when we get there.

**Comment by mitchellh** [comment]
Note for Waypoint team members: I didn't put this into a milestone or remove the "new" label cause I dunno when we'll get to all this. 😄

**Comment by mitchellh** [comment]
I got a fix for one thing here: https://github.com/hashicorp/waypoint/pull/1821

**Comment by evanphx** [comment]
Should we consider #1821 an acceptable answer for this issue.

Btw @denysvitali, thanks so much for the brief tour of your workflow. We'd love to know more about the front end of that also, and how waypoint could grow (maybe to replace the Jenkins bits?).
