### ISSUE TITLE
Out of order headings

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#1854]
**Is your feature request related to a problem? Please describe.**

We currently have occurrences of both out-of-order headings and headings that skip levels.

https://user-images.githubusercontent.com/34030/125523753-5e13726b-592e-4322-a8d2-d3d9e20d66f4.mp4

**Any other background?**

We’ve deferred addressing this issue by [excluding certain elements from automated a11y testing](https://github.com/hashicorp/waypoint/blob/v0.4.1/ui/tests/helpers/a11y.ts#L16), and by merit of the fact that we don’t yet have exhaustive test coverage (some pages such as empty states and error pages don’t get audited as part of the suite).

**Describe the solution you’d like**

We should correct the out-of-order headings and remove the exclusion if possible (though there may be other a11y violations that stand in the way of this).

**Comment by gregone** [comment]
Here's the approach I'd recommend: 

- reset the heading styles of `h1, h2, h3, h4, h5, h6` so that they all look the same
- add html classes or a classless component to provide equivalent styling 
- restructure all pages using the new component or html classes

**Comment by jgwhite** [comment]
Think this might be moot following the 0.7 redesign.
