### ISSUE TITLE
Waypoint UI should display the commit SHA associated with a job

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1858]
**Is your feature request related to a problem? Please describe.**

When Waypoint goes through the build lifecycle, when using a project setup by git, it would be useful to know what version in your git repo the current build was built off of. We keep track of this information for git polling via a git ref in a job which includes a commit sha and timestamp. That job gets associated with an operation which can be referenced back to get the direct commit SHA.

Having a project SHA show up in the UI would give users more information as to what version their app was currently deployed or built off of. Having this information should make it easier to figure out why a build or release failed and track down which commit caused the issue.

**Describe the solution you'd like**

Update the UI to look for the git sha. It can be obtained by first getting the operation to use as a reference to get which job was associated with that operation. The SHA should be inside that job to display in the UI.

**Comment by jgwhite** [comment]
Is this related to #1508?

**Comment by briancain** [comment]
@jgwhite Yes! I didn't realize there was an issue already for tracking this.

**Comment by gregone** [comment]
Closed with #2025
