### ISSUE TITLE
`waypoint version` includes `context deadline exceeded` error if a server is not installed

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1865]
**Describe the bug**
```
$ waypoint version
CLI: v0.4.1 (4d5c838e)
Error connecting to server to read server version: context deadline exceeded
```

**Steps to Reproduce**
Run `waypoint version` or `waypoint -v`

**Expected behavior**
For it to include no server version info if there is not an active server; possibly a note like "No Waypoint server found"

**Waypoint Platform Versions**
0.4.1

**Comment by mitchellh** [comment]
If you have no context, it shows nothing (no error, nothing). If you have a context, it assumes you mean to reach a server cause it can't tell the difference between "no server" and "down server" so I think showing the error makes sense.

**Comment by krantzinator** [comment]
Aha ignore me
