### ISSUE TITLE
Tagging of waypoint platform resources based on labels.

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1909]
**Is your feature request related to a problem? Please describe.**
Most platforms support the concept of labels. Kubernetes has annotations, aws has tags, etc. Waypoint currently allows you to add labels to plugin operations (https://www.waypointproject.io/docs/extending-waypoint/plugin-interfaces/default-parameters#component-labelset), but those labels aren't visible on resources that platforms create.

**Describe the solution you'd like**
Labels applied to waypoint operations should be translated by plugins into platform-native lables/annotations/tags, for platforms that support this metadata.

**Describe alternatives you've considered**
Plugins could each support their own tagging feature exposed through their waypoint.hcl stanza.

**Explain any additional use-cases**
This would allow platform operators to see more context when viewing resources in the platform native view. It could also allow other automation to recognize and act upon resources for sophisticated users.

**Concerns**
We would need to clarify the purpose of labels in our documentation. We would also need to decide which set of labels get applied to resources (i.e. app labels, project labels, workspace labels, etc)

**Comment by mitchellh** [comment]
My preference would be to not do this automatically, and just have users redefine a `tags {` or `annotations {` block and reuse the labels that are set. One of the proposals set forth by the multi-env RFC is exposing a `labels` variable that can be used in the waypoint.hcl to reference the current set of labels (for that operation). So users could easily do:

```hcl
// if they want all labels
annotations = labels 

// if they want to prefix them
annotations = { for k, v in labels: "waypoint/${k}" => v }

// if they want to filter them
annotations = { for k, v in labels: k => v if regex("^foo", k) }
```

I think this works a lot better than a "magic" or "automatic" approach cause its fully customizable and explicit.

**Comment by mitchellh** [comment]
PR here: https://github.com/hashicorp/waypoint/pull/2065

**Comment by mitchellh** [comment]
Merged
