### ISSUE TITLE
GCR Deployment just fails without any info why

### ISSUE THREAD

**Issue by bnrosa** [hashicorp/waypoint#1942]
I'm trying to deploy my project to GCR using the [tutorial](https://learn.hashicorp.com/tutorials/waypoint/google-cloud-run?in=waypoint/deploy-google-cloud#overview) but it simply fails on the deployment step without comprehensible errors, is there a way I can debug it further? The logs aren't of any help either. Also, I'm have enabled my GC account, the API as well, made it billable, so it shouldn't be related to that.
```
project = "konf-auth-dev"

app "konf-auth-dev" {

  labels = {
    "service" = "konf-auth-dev",
    "env"     = "dev"
  }

  build {
    use "pack" {
    }

    registry {
      use "docker" {
        image = "gcr.io/konf-auth-dev/dev"
        tag   = "latest"
      }
    }
  }

  deploy {
    use "google-cloud-run" {
      project  = "konf-auth-dev"
      location = "us-east1"

      port = 5000

      capacity {
        memory                     = 128
        cpu_count                  = 1
        max_requests_per_container = 10
        request_timeout            = 300
      }

      auto_scaling {
        max = 2
      }


      vpc_access {
        connector = "custom-vpc-connector"
        egress = "all"
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```
![image](https://user-images.githubusercontent.com/14277020/127369408-7f63b123-e45f-4a86-84fa-3c1c82cd3b85.png)

**Comment by krantzinator** [comment]
@bnrosa Are you able to share what the solution was? If it's something that would help our tutorial our we can add it!

**Comment by krantzinator** [comment]
Or our error messaging :)

**Comment by bnrosa** [comment]
Well, first there's some inconsistency between the tutorial and docs, if you look into the [docs](https://www.waypointproject.io/plugins/google-cloud-run) it says that the **vpc_access** parameter is required, but it doesn't appears in the tutorial setup.
I'm still trying to fix it, but I can identify what the issue is, so the problem is simply the status of the GCR service, it is not ready. The issue is caused by the connector not being found.
![image](https://user-images.githubusercontent.com/14277020/127387031-f891593c-fedd-4e12-9122-dbe74e626269.png)

Hope it's helpful info 😄

**Comment by bnrosa** [comment]
Also, this error gaves the same message: 
![image](https://user-images.githubusercontent.com/14277020/127387834-53aa15cc-2b0a-4163-a98b-a7545954a5a1.png)
Maybe the message should indicate that you must check your GCR console or something..

**Comment by krantzinator** [comment]
Thanks! I just got the same error message as you did the first time. So I'm joining this troubleshooting party 🥳

**Comment by bnrosa** [comment]
solved it by creating the connector at https://console.cloud.google.com/networking/connectors

**Comment by krantzinator** [comment]
Hm it looks like the `vpc_access` param is actually optional, so hopefully that is not the problem here. We just don't set it if it's not specified in the config: https://github.com/hashicorp/waypoint/blob/81cbf8c38b82e5518bb8cf52044085fd30225425/builtin/google/cloudrun/platform.go#L370

**Comment by krantzinator** [comment]
Great! Seems like we need to update the tutorial then to match GCR specs: https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate
