### ISSUE TITLE
docs generation leaves off anything after `[options]` for website docs

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#1976]
**Describe the bug**
The docs on our website for the following commands have a command like `command [options] NAME`, where the `NAME` text shows up in the CLI help text, but not the website documentation:
- `waypoint auth-method set oidc`
- `waypoint context create`
- `waypoint context delete`
- `waypoint context use`
- `waypoint project apply`

**Steps to Reproduce**
Go to https://waypointproject.io/commands/context-delete and observe the docs say `Usage: waypoint context delete [options]`. Then run `waypoint context delete -h` and observe the help text there says `Usage: waypoint context delete [options] NAME`

**Expected behavior**
Consistency between the two.

**Additional context**
This is because we populate the Usage text for the docs manually here: https://github.com/hashicorp/waypoint/blob/32ee1e8cb5a09c4cc0fbf451ae5a08ad46f09287/internal/cli/docs.go#L108

**Comment by briancain** [comment]
This was fixed via https://github.com/hashicorp/waypoint/pull/2010!
