### ISSUE TITLE
`waypoint server uninstall` can delete the wrong context

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2046]
**Describe the bug**
Running `waypoint server uninstall` deletes the current context, even if that context does not use the platform you're uninstalling.

**Steps to Reproduce**
- Install waypoint with `waypoint install -platform=docker -accept-tos`
- Run a waypoint server manually, generating a bootstrap context
- Run `waypoint server uninstall -platform=docker -auto-approve`
- Notice your waypoint bootstrap context is gone, not your docker context!

**Expected behavior**
Only the waypoint docker context should be deleted. I don't think it's currently possible to use `waypoint install` to get more than one context for any given platform, so scanning the contexts to find the one with the matching platform name should be safe.

**Waypoint Platform Versions**

* Waypoint CLI Version: 0.5.0
* Waypoint Server Platform and Version: 0.5.0
* Waypoint Plugin: any (tested docker)

**Comment by briancain** [comment]
I see what's going on here....we're assuming the `-platform` flag is correct. One thing we could do is validate the context loaded matches the platform requested.
