### ISSUE TITLE
plugin/k8s: include sequence number in resource names

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2060]
Currently, it is difficult to look at a kubernetes pod or deployment and understand which waypoint deployment it corresponds to. We encode the internal operation ULID on the deployment, but we don't expose that it users anywhere else.

We should use the waypoint deployment sequence number instead of (or in addition to if necessary), the internal operation ULID as part of the deployment name.

**Comment by sl1pm4t** [comment]
If no one is working on this, I'm happy to work on a fix?
I'm asking to avoid a double up of effort like my last [PR](https://github.com/hashicorp/waypoint/pull/2221). 😂

**Comment by izaaklauer** [comment]
I think you can take an initial stab at this! One concern I have is that I'm not sure yet how much core rewiring will be required to make the deployment operations aware of the sequence number. If that part starts to feel complex, don't hesitate to reach out for feedback early or pass this issue back to us.

**Comment by sl1pm4t** [comment]
Thanks. I didn't realise this might involve touching the core, but I'm still happy to start poking around.

**Comment by sl1pm4t** [comment]
@izaaklauer I've submitted PRs to [this repo](https://github.com/hashicorp/waypoint/pull/2296) and the [waypoint-plugin-sdk](https://github.com/hashicorp/waypoint-plugin-sdk/pull/58), but I do not have permissions to tag you as a reviewer.
