### ISSUE TITLE
Wrong status shown in tooltip for deployment on Nomad

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#2069]
**Describe the bug**

https://user-images.githubusercontent.com/810277/129928459-0bce8c8c-6f06-4989-b964-6d1d9412fddd.mp4

Nomad shows a status Unknown in the tooltip despite knowing the health.

**Steps to Reproduce**

Do a deployment with nomad and check the UI.

**Expected behavior**

It should show the health. If I remember right, the UI might be showing the health message directly from the status report. So it's likely something that needs to be fixed in the Nomad plugin rather than a UI fix.

**Waypoint Platform Versions**

Latest 0.5.0

**Additional context**

**Comment by jgwhite** [comment]
> If I remember right, the UI might be showing the health message directly from the status report

That is correct.

That pertinent UI lines are:

https://github.com/hashicorp/waypoint/blob/0d8a7babb51b4f70010f8cdc5eb7223ad5df9983/ui/app/components/status-report-indicator.hbs#L4

and:

https://github.com/hashicorp/waypoint/blob/0d8a7babb51b4f70010f8cdc5eb7223ad5df9983/ui/app/components/status-report-indicator.hbs#L39

Flattened out:

```ts
statusReport.health.healthMessage || "Status unknown"
```

**Comment by jgwhite** [comment]
I’m probably misreading this, but it looks like we stamp over the top of `HealthMessage` on line 355 here:

https://github.com/hashicorp/waypoint/blob/a80281204903a02ce156729b6d1a94155782b94a/builtin/nomad/platform.go#L338-L355

**Comment by briancain** [comment]
@jgwhite - Nope I think you're reading that right 😄 We shouldn't set the health message to the job description, those are unrelated. Looks like that's the source of the issue. If you wanted to give it a go and fix it on the go side feel free!

**Comment by jgwhite** [comment]
> If you wanted to give it a go and fix it on the go side feel free!

I was hoping you’d say that ☺️ Gonna have a go tonight.
