### ISSUE TITLE
ui: Terminal output should match CLI for consistency

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#2071]
**Is your feature request related to a problem? Please describe.**

When viewing a deployment or release in the UI, we omit all of the output that happened. As a user mainly in the CLI, I'd like to see matching output to have some assurance the right thing happened when a deployment or release happened. This includes output like status checks for the deployments and its resources. Otherwise I'm not sure what the terminal output is used for when you view a deployment or release in the UI.

![Screenshot from 2021-08-18 08-51-23](https://user-images.githubusercontent.com/810277/129930398-d2650d0b-19c8-4df5-ade4-3fd48490a533.png)

**Describe the solution you'd like**

Show the same output for a deployment or release in the UI.

**Describe alternatives you've considered**

**Explain any additional use-cases**

As we add more features to a deployment or release, having that info directly in the terminal output will be a nice to have even if it's represented in the UI.

**Additional context**

None yet.

**Comment by gregone** [comment]
@briancain this is related to one of the issues I opened while researching the Log/Exec improvements: https://github.com/hashicorp/waypoint/issues/1736

**Comment by briancain** [comment]
Ahh, makes sense! I can close this as a duplicate of that one then.
