### ISSUE TITLE
Deployments in an unsuccessful state cannot be deleted

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2089]
**Describe the bug**
Attempting to destroy an unsuccessful deployment gives a `» 1 deployments will be destroyed.` message, but then silently refuses to destroy the deployment.

**Steps to Reproduce**
- Create a failed deployment. This can be done by attempting to perform an ECS deployment locally with incorrect credentials set.
- Attempt to destroy the deployment by sequence number (i.e. `waypoint deployment destroy 1`. Note no error or warning.
- List deployments again, note the failed deployment is still present

Example:
<img width="937" alt="Screen Shot 2021-08-23 at 9 38 56 AM" src="https://user-images.githubusercontent.com/8404559/130457530-54bf89d1-9dee-4c65-b5b4-373118414785.png">

**Expected behavior**
I would expect the erroring deployment to be destroyed. Barring that, waypoint should warn the user that the deployment cannot be destroyed because it's in an unsuccessful state

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable: 0.5.0

* Waypoint CLI Version: 0.5.0
* Waypoint Server Platform and Version: any
* Waypoint Plugin: any

**Additional context**

Looks like the relevant part is here: https://github.com/hashicorp/waypoint/blob/0d8a7babb51b4f70010f8cdc5eb7223ad5df9983/internal/cli/deployment_destroy.go#L62-L65

I'm not positive why we can't destroy unsuccessful deployments - maybe we want to make sure we don't re-use that sequence number for some reason?

**Comment by krantzinator** [comment]
This is something the work of adding the Resource Manager was meant to address. The original issue was #533, but that admittedly does not have much discussion on it.

**Comment by izaaklauer** [comment]
I think that resource manager solves the core part of this problem by automatically destroying a deployment’s resources immediately when a deployment fails. You’ll still see the “error” state deployment in the list though.

Now that resource manager is ensuring that we don’t have dangling resources for deployments, “deleting” error state deploys might be as easy as just removing the record from our db.

**Comment by briancain** [comment]
> I would expect the erroring deployment to be destroyed. Barring that, waypoint should warn the user that the deployment cannot be destroyed because it's in an unsuccessful state

By destroyed, are you expecting the entry to be removed from `deployments list`? I could see why we're holding onto the deployment, even if unsuccessful. It's useful historic information to see an errored deployment. But maybe you mean "marked as destroyed"?

**Comment by izaaklauer** [comment]
Ah good clarification - I expected `waypoint deployment destroy` to remove the entry from the list, in the same way that it removes a successful deployment from the list when you destroy it.

**Comment by krantzinator** [comment]
Closing in favor of #533
