### ISSUE TITLE
`waypoint status` displays status of destroyed deployments

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2097]
**Describe the bug**
If you destroy all deployments, `waypoint status` will continue to display the status of the most recent deployment. It will also continue scheduling status poll jobs against the most recent deployment

**Steps to Reproduce**

- Run `waypoint up` with a plugin that supports status checks (docker or k8s)
- Enable app polling (e.x.: `waypoint project apply -app-status-poll-interval=10s -data-source=git -git-url=https://github.com/hashicorp/waypoint-examples -git-path=aws/aws-ecs/nodejs -app-status-poll example-nodejs`
- Make sure you have a valid remote runner
- Run `waypoint destroy -auto-approve` to destroy all deployments
- Run `waypoint status -app=<app>`. Observe a report for the most recent deployment, and that it continues to refresh

**Expected behavior**
`waypoint status` should show that there are no releases or deployments, and should not continue scheduling status checks

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.5.1
* Waypoint Server Platform and Version: 0.5.1
* Waypoint Plugin: docker, k8s

**Issues involved**
- [x] #2129
- [x] #2130
- [x] #2131

**Comment by briancain** [comment]
I think these are two separate issues: one about `waypoint status` the CLI command and the other about the application status poll handler. But I think both can be solved by taking into account the operation status and checking if the deployment has been destroyed. For the CLI, we can probably just show the operation like we do for `deployment list`. For the poll handler, if the latest is destroyed maybe we skip the poll? 🤔 Or we poll the most recent non-destroyed deployment?

**Comment by izaaklauer** [comment]
That sounds good to me! I would vote that `waypoint status` defaults to showing the latest non-destroyed deployment or release, and the poll hander polls the latest non-destroyed deployment or release.

**Comment by xiaolin-ninja** [comment]
Piggy backing off this too, deleting deployments doesn't change anything in `waypoint release list`. Should we at least change the icon from a rocket ship to a red cross, or delete altogether?
