### ISSUE TITLE
clean up optional HCL parsing in documentation

### ISSUE THREAD

**Issue by xiaolin-ninja** [hashicorp/waypoint#2109]
**Describe the bug**
Our auto-generated documentation parsing can't parse optional blocks as optional. Our current workaround is to keep them in the "Required parameters" section, but show all the nested fields as optional. It'd be great to just put everything under the "Optional parameters" heading to avoid confusion. 

**Steps to Reproduce**
https://www.waypointproject.io/plugins/aws-ecs#required-parameters-1
https://github.com/hashicorp/waypoint/pull/2102

Please include any `waypoint.hcl` files if applicable, as well as a
[GitHub Gist](https://gist.github.com/) of any relevant logs or steps to
reproduce the bug. Running `waypoint` commands with `-v` up to `-vvv` will
include any additional debugging info in the log.

**Expected behavior**
Optional blocks are under the "Optional parameters" heading and not in "Required parameters" with all optional nested fields. 

**Waypoint Platform Versions**
CLI: v0.5.0 (c2455052)
Server: v0.5.0

**Comment by xiaolin-ninja** [comment]
Fixing this would require a large-scale re-write of our documentation generation.

**Comment by krantzinator** [comment]
Fixed in https://github.com/hashicorp/waypoint/pull/3507
