### ISSUE TITLE
Use ember-a11y-refocus

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2300]
**Is your feature request related to a problem? Please describe.**
Currently the UI does not do any intelligent focus management when transitioning between routes, leading to a broken/disorientating experience for screen reader users.

**Describe the solution you'd like**
I’d like us to use [ember-a11y-refocus](https://github.com/ember-a11y/ember-a11y-refocus) to solve this problem.

**Describe alternatives you've considered**
[a11y-announcer](https://github.com/ember-a11y/a11y-announcer), an older solution.

**Comment by jgwhite** [comment]
cc @MelSumner

**Comment by gregone** [comment]
@hashicorp/waypoint-frontend I'm adding this to the 0.7.0 milestone to go along with some larger UI changes

**Comment by jgwhite** [comment]
Good idea 👍

**Comment by jgwhite** [comment]
We gave this a try on 2021-11-24 and ran into the following challenges:

1. https://github.com/ember-a11y/ember-a11y-refocus/issues/302
2. We use [`RouterService.refresh`](https://emberjs.github.io/rfcs/0631-refresh-method-for-router-service.html) for polling, which triggers a `routeDidChange` every 15 seconds, in turn inadvertently triggering ember-a11y-refocus’ behavior

Both issues are surmountable, but will require a little work.
