### ISSUE TITLE
ui: Renaming a config variable does not remove the original

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2339]
**Describe the bug**
When I rename a config variable then I get two versions of the variable, one with the old name and one with the new:

https://user-images.githubusercontent.com/34030/134333304-3c9b5247-a196-433b-abd1-3d7bb30a37e6.mp4

**Steps to Reproduce**

1. Rename a config variable in the UI (Edit -> Change name -> Save)
2. Observe the duplicate with the original name

**Expected behavior**
Only the config variable with the new name should exist.

**Waypoint Platform Versions**

* Waypoint CLI Version: 55f28f1e83b04ccea7463f385d3ba44aa671aa34

**Comment by gregone** [comment]
I'll look into the issue later in this cycle, but with the ability to compare the `initialVariable` we should be able to create the renamed var, then unset the old one when that case happens.

**Comment by jgwhite** [comment]
@gregone alternatively we could have the variable name be read-only (this is what Heroku’s config vars UI does).
