### ISSUE TITLE
Deployment resource table border is the wrong color

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2376]
**Describe the bug**

Not sure when/how this regressed, but shouldn’t be hard to fix:

![image](https://user-images.githubusercontent.com/34030/135162661-681a7d17-ff1a-4d29-be38-fa6e0544a68d.png)

**Comment by jgwhite** [comment]
This is very curious. Seems like the border color is just _gone_ in the prod build.

| dev | prod |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/34030/135250716-f070e0bf-cf0b-4945-847a-68bd1bf3bd05.png) | ![image](https://user-images.githubusercontent.com/34030/135250524-4bb8a9c1-3fde-4de5-be9a-95e2f2690054.png) |

**Comment by jgwhite** [comment]
I wonder if [clean-css](https://github.com/clean-css/clean-css) is responsible?

**Comment by jgwhite** [comment]
Just validated the clean-css hypothesis by adding the following in `ember-cli-build.js`:

```js
minifyCSS: {
  enabled: true,
},
```

And indeed, we see the missing color declaration.

**Comment by gregone** [comment]
Can you attempt to (re)declare using `border-color` and see if the issue still happens? Could be a quick fix while we investigate?

**Comment by jgwhite** [comment]
> Can you attempt to (re)declare using `border-color` and see if the issue still happens? Could be a quick fix while we investigate?

Absolutely. I’ll go with this as a fix for now, but we will want to fix this long-term otherwise it’s bound to bite us again.

**Comment by jgwhite** [comment]
Wrote up a broader issue for the continued investigation: #2356 2382
