### ISSUE TITLE
Protect ourselves against clean-css misfires

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2382]
**What’s the bug?**
It’s possible for clean-css to misfire and produce incorrect optimized CSS, as in #2376.

**What should we do about it?**
We need to investigate a little more, but here’s what we’ve discussed so far:

1. ~Upgrade clean-css~ — this is rather involved, we’d have to take over maintenance of [broccoli-clean-css](https://github.com/shinnn/broccoli-clean-css) and perform a chain of major version upgrades
2. Disable clean-css — we’ll first have to determine if the filesize trade-off is acceptable
3. Disable a specific clean-css optimization — this will probably involve a lot of hunting around, and we still might running into bugs we’re not yet aware of

**Comment by jgwhite** [comment]
4. Recruit Percy to help us catch things by enabling `minifyCSS` in the test env

**Comment by gregone** [comment]
there was [a very possibly related bug in clean-css](https://github.com/clean-css/clean-css/commit/dc240b82cb0349f98798faa011e5b7fc3211b85f) that was fixed in 3.3.0 Broccoli-clean-css is stuck on 3.1.x 
I think the upgrade, although involved, would be a big benefit for the ember ecosystem

**Comment by jgwhite** [comment]
In the end we chose option 4 👍
