### ISSUE TITLE
UI: migrate the UI Icons from `structure-icons` to `flight`

### ISSUE THREAD

**Issue by gregone** [hashicorp/waypoint#2392]
Use https://github.com/hashicorp/flight to replace the Structure icons

i.e restart the work started in our experiment here https://github.com/hashicorp/waypoint/pull/2194 and replace the icons. 

It would be a good idea to start by adding more screenshots to the Percy test to cover most icons, then update the icons.

**Comment by sabrinako** [comment]
^ didn't properly link the PR, closing now!
