### ISSUE TITLE
Log rendering causes Safari bug(s)

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2397]
**Describe the bug**
I’m not completely sure what’s going on here, but the best way to demonstrate is to compare Chrome and Safari rendering an app page:

https://user-images.githubusercontent.com/34030/135535924-6c1b7c90-9b37-4fc2-b12d-4833f65c7c60.mp4

https://user-images.githubusercontent.com/34030/135535956-f74a4530-9f7c-457d-8968-6bf2ac65b9cf.mp4

Notice how the page becomes unresponsive, the logs never appear, buttons stop working.

**Steps to Reproduce**
Visit an app page with active logs in Safari.

**Expected behavior**
Safari should behave just like Chrome.

**Waypoint Platform Versions**
* Waypoint CLI Version: be051d7

**Browser Versions**
* Safari Version 15.0 (16612.1.29.41.4, 16612)

**Additional Context**
I imagine this is an issue with xterm.js’s canvas renderer. I had a quick look at their issues and there are certainly reports that sound similar.

**Comment by jgwhite** [comment]
Update — this bug appears to be fixed in Safari Technology Preview `Release 132 (Safari 15.4, WebKit 16613.1.1.5)`. I’d suggest waiting for a Safari update to roll out rather than doing anything ourselves with this bug. Feel free to close.

**Comment by gregone** [comment]
Yup looks related to https://github.com/xtermjs/xterm.js/issues/3357

**Comment by gregone** [comment]
@jgwhite let's keep it open until the update rolls out
