### ISSUE TITLE
Waypoint runner : Out of Memory without activity

### ISSUE THREAD

**Issue by pam199968** [hashicorp/waypoint#2406]
Hello,
We have installed a waypoint server and a waypoint runner (0.5.2) in a nomad cluster. Every day, after a couple of hours we observe that the runner is killed by Nomad with this message : Exit Code: 2, Exit Message: "OOM Killed".
We increase memory (4gb)  but the leak still occurs every day even no build has run.

[waypoint-runner.nomad.txt](https://github.com/hashicorp/waypoint/files/7273019/waypoint-runner.nomad.txt)
[alloc_logs_runner.stderr.0.txt](https://github.com/hashicorp/waypoint/files/7273030/alloc_logs_runner.stderr.0.txt)
![memory_consumption](https://user-images.githubusercontent.com/88666492/135747335-2b54c9ea-b1c7-46c4-b03c-b5a8397fce0d.jpg)

Thanks for this very nice product.

**Comment by briancain** [comment]
Hey there @pam199968 ! Sorry to hear about the memory leak. 😞 The Waypoint team will take a look soon.

According to the image you shared, it looks like the OOM kill happens almost right away when the task starts? Is that the typical case in your experience? The graph there also makes it seem less like a leak and more like the task is just using all 4 GB right away, the line is pretty flat at almost 100% 🤔 Thanks!

**Comment by pam199968** [comment]
Yes, the OOM occurs during restart when the memory is already full. When there is memory available the restart works perfectly.
Memory consumption is approximately 250MB every 10 minutes.

**Comment by evanphx** [comment]
@pam199968 if you're willing, you could also take a snapshot of your server and send it to us. That could let us look at the data that's being managed, might help us track it down. The information on doing a snapshot is here: https://www.waypointproject.io/commands/server-snapshot

**Comment by pam199968** [comment]
I forgot a piece of information: We modified the container to allow it to access the docker daemon

FROM hashicorp/waypoint
MAINTAINER ans.fr
USER root
ARG GID=987
RUN addgroup -g $GID docker && \
    addgroup waypoint docker
USER waypoint

**Comment by pam199968** [comment]
The problem only occurs when using polling strategy. With the new REST API, we now invoke waypoint from our ci server and there is no more memory leak.

**Comment by krantzinator** [comment]
It sounds like this issue has been resolved so I will close this issue. If you are still encountering this issue feel free to comment back here or open a new issue!
