### ISSUE TITLE
ui: re-run health check button alignment

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2497]
**Describe the bug**
The “re-run” button sits ever-so-slightly low on the line:

![CleanShot 2021-10-14 at 23 13 20@2x](https://user-images.githubusercontent.com/34030/137396575-0e3ccf0a-a0b0-41fb-ba05-e8ab0994ca3b.png)

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.6.0

**Browser**
Chrome Version 94.0.4606.81 (macOS)

**Comment by sabrinako** [comment]
<img width="900" alt="Screen Shot 2022-01-06 at 10 28 03 AM" src="https://user-images.githubusercontent.com/60155296/148407056-0f484b16-6596-45b5-9e34-da6d4e367221.png">
Fixed at one point during redesign work
