### ISSUE TITLE
ui: `<StatusReportMetaTable>` alignment is slightly off

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2539]
**Describe the bug**
The values in the table are set ever-so-slightly low relative to the headings:

![CleanShot 2021-10-21 at 13 57 18@2x](https://user-images.githubusercontent.com/34030/138272599-7773deaf-89a2-4a0e-89d3-405be6ebe208.png)

**Steps to Reproduce**
1. Boot the dev server (`cd ui && yarn start`)
2. [Visit a deployment page](http://localhost:4200/default/marketing-public/app/wp-matrix/deployment/seq/4)
3. Observe the issue

**Expected behavior**
Row heading and values should share a baseline.

**Waypoint Platform Versions**
0fd4ce0c9100d4a3a2c79e01e18e367a2a83437e

**Comment by sabrinako** [comment]
Solved with #2898 PR
