### ISSUE TITLE
website: when linking to a section, the linked-to portion is hidden by the banner

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2653]
**Describe the bug**

Related to https://www.waypointproject.io/, not the waypoint UI.

When sharing a link to something within a page, the most relevant part of the page is usually cut off by the nav banner:

https://user-images.githubusercontent.com/8404559/139928901-04838dea-5982-4636-84bd-c4f685a99c49.mov

**Comment by izaaklauer** [comment]
Looks like this is true across all of our docs pages (see https://www.consul.io/docs/agent/options#verify_server_hostname)

**Comment by BRKalow** [comment]
Thanks for the heads up! We've got a fix in progress and should have it rolled out soon.

cc @thiskevinwang
