### ISSUE TITLE
Docs: Document any additional info or caveats for `waypoint install -platform=ecs`

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#2658]
**Is your feature request related to a problem? Please describe.**

This pull request https://github.com/hashicorp/waypoint/pull/2635 introduces docs for the `waypoint install` command for officially supported server images. The AWS ECS section still needs to be filled out.

**Describe the solution you'd like**

If there's any extra information needed to make running that command easier for the AWS ECS platform, update the docs to detail those steps and information. It would be good to update the section with any platform specific info that the the install command creates and manages.

**Comment by izaaklauer** [comment]
Something brief is probably good enough for now. Even if it's just listing out the resources that we create, and potentially linking to the IAM policy definitions in our codebase, that would be very useful.
