### ISSUE TITLE
ui: Default workspace selection

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2662]
**Is your feature request related to a problem? Please describe.**
When I visit Waypoint’s UI, it automatically drops me into the `default` workspace. But what if I don’t use the default workspace? How should it behave?

**Describe the solution you'd like**
Given I have not specified the workspace in the URL, I want the UI to intelligently choose the workspace I’m most likely to want.

Some thoughts the team discussed in a recent sync.

- Store the most-recently viewed workspace in local storage and try to re-use this
- Try using the most recently active workspace (we bump activity timestamp on every operation)
- Failing that, show the alphabetically first
- Failing all the above, settle for default

Here’s that in flowchart form (there are other ways to draw this, but I think this works):

![image](https://user-images.githubusercontent.com/34030/140068859-42c3423f-091b-4c2b-a76e-687d7270b566.png)

Additionally, @amandakalk suggested the following:

> if your default workspace is blank and you have other workspaces, the empty message could give you a little suggestion to change workspaces

I think this will be very useful when I *do* specify a workspace but the UI can tell that I don’t actually have anything in there.

**Describe alternatives you've considered**
TODO

**Additional context**
This will follow #1339 (currently underway)

Long term, we’ve discussed having a similar model to GitHub’s branch selection, where users can elect a default for each project. This, however, is not in the immediate roadmap.

**Comment by izaaklauer** [comment]
I think the downside of using "most recently active" is it increases the odds that someone will take an action against the prod workspace, thinking they're in dev. I feel like doing something consistent, like alphabetical, might help give people "muscle memory" for jumping to the workspace they're interested in.

**Comment by jgwhite** [comment]
@izaaklauer all good points, and simpler to implement too! I don’t see any reason not to go with this simpler approach.

**Comment by jgwhite** [comment]
Updated flow chart:

![image](https://user-images.githubusercontent.com/34030/140191340-0a053658-59b6-4cf6-8e33-fef7ceea46ba.png)

**Comment by jgwhite** [comment]
Actually, given the special status of “default”, maybe this would be better:

![image](https://user-images.githubusercontent.com/34030/140191961-7dc835cd-98bb-42f9-ab18-6d5fa804a86d.png)
