### ISSUE TITLE
ui: add git commit mock data to mirage

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/waypoint#2680]
**Is your feature request related to a problem? Please describe.**
With the current testing setup, there's no way to see the Gitops related features (git commit badges, etc) with the preloaded data. You need to make a Waypoint server to see these assets in the UI

**Describe the solution you'd like**
Add git information to one of the test data projects so we can see that data in the UI.

**Comment by jgwhite** [comment]
@sabrinako I just opened a PR to address this. Apologies if you were intending to tackle this one yourself!
