### ISSUE TITLE
ui: redirect to `/auth` when no token is present

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2695]
**Describe the bug**
Given I’m unauthenticated, when I visit the Waypoint UI directly in the browser (not using `waypoint ui -authenticate`), then I see the following:

<img width="1360" alt="CleanShot 2021-11-08 at 14 19 24@2x" src="https://user-images.githubusercontent.com/34030/140749167-8b79a27b-04a0-4463-a6bc-97739b799500.png">

**Steps to Reproduce**
1. Visit the web UI in an incognito window
2. Observe the error message shown above

**Expected behavior**
I should be redirected to `/auth`:

<img width="1360" alt="CleanShot 2021-11-08 at 14 21 27@2x" src="https://user-images.githubusercontent.com/34030/140749302-9fbc233d-7063-4d9d-bc8d-ad48c978f667.png">

**Waypoint Platform Versions**
* Waypoint UI Version: a7de59a6141c02d5861d0521d7c42712e7a580af

**Comment by jgwhite** [comment]
Minutes later, I found I couldn’t reproduce this!

**Comment by gregone** [comment]
Well, turns out there was a bug but it was a little weirder than expected. https://github.com/hashicorp/waypoint/pull/2696
