### ISSUE TITLE
Waypoint config - Dynamic internal values as waypoint.hcl vars 

### ISSUE THREAD

**Issue by stevenheinze57** [hashicorp/waypoint#2722]
Would we be able to get a feature added to use dynamic internal variables as interpolated variables throughout the waypoint.hcl file? This would be incredibly useful when using something like nomad-jobspec plugin to pass values pulled from vault, as one example. I'm sure there's many more instances where this would be incredibly useful. Right now it seems dynamic variables can only be injected into an applications environment.

**Comment by evanphx** [comment]
Hi @stevenheinze57,

We agree this would be great and are working on it now!

**Comment by izaaklauer** [comment]
Hey @stevenheinze57 ,

Thanks again for the request - this is a great idea! Out of curiosity, which values are you looking to pass from vault into your nomad jobspec? I'd also be interested to hear any other specific use-cases you have in mind for this feature.

**Comment by stevenheinze57** [comment]
@izaaklauer  I have at least two use cases for this:

1. Passing vault pulled variables to the noamd jobspec template 
2. Using vault pulled variables for something like docker authentication, pre-hook and post-hook tasks, etc

**Comment by izaaklauer** [comment]
If you're willing to share, which values in particular are you pulling from vault into the nomad jobspec? I assume it's not application config or secrets, because the existing dynamic config system could get you that - is it a datacenter name, or a port number, or something else?

**Comment by stevenheinze57** [comment]
@izaaklauer  One example where this comes into play is passing in a docker password to be used for pulling an image from docker hub. My goal is to pull this password from vault and inject it into the template to be used by nomad to pull the image. I think the real issue is that internal references are only scoped to the config stanza. I haven't been able to reference internal config within the build or deploy stanzas.
