### ISSUE TITLE
Waypoint, Installation on Nomad

### ISSUE THREAD

**Issue by wahmedswl** [hashicorp/waypoint#2727]
**Describe the bug**
Unable to install Waypoint on Nomad development server. Following tutorial from https://learn.hashicorp.com/tutorials/waypoint/get-started-nomad?in=waypoint/get-started-nomad and after running 
```waypoint install -platform=nomad -accept-tos -nomad-host-volume=potato -nomad-consul-service=false``` its not being completed. Following are the details under Nomad jobs ui

```
Placement Failures
waypoint-server 1 unplaced
Constraint missing compatible host volumes filtered 1 node
```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Nomad CLI Version: Nomad v1.1.6 (b83d623fb5ff475d5e40df21e9e7a61834071078)
* Waypoint CLI Version: CLI: v0.6.2 (99350730)

Thanks

**Comment by wahmedswl** [comment]
Hi, Sorry missed volume mount stepped as in the tutorial Nomad was launched via ```nomad agent -dev -network-interface="en0"``` but to configure host volume config file was not mentioned.

Now running Nomad via ```nomad agent -dev -network-interface="eth0" -config=conf.hcl```

```
server {
  enabled = true
}

client {
  enabled = true
  host_volume "waypoint-data" {
    path = "/home/ubuntu/waypoint"
  }
}
```

Now, installation is started and waiting on 
```
⠙ Installing runner...
⠙ Nomad allocation created
```

Thanks

**Comment by krantzinator** [comment]
Hey @wahmedswl FYI these types of questions are typically best posted on our Discuss forum. We use our Discuss forum for troubleshooting conversations, and GitHub Issues for reporting bugs or feature requests.

But since we're both here, go ahead and let me know what errors you are seeing in Nomad as to why the allocation isn't starting.

**Comment by wahmedswl** [comment]
Sorry about that, Waypoint is installed. Thanks
