### ISSUE TITLE
Docs: Missing info on gitrefpretty()

### ISSUE THREAD

**Issue by kmcquade** [hashicorp/waypoint#2804]
The tutorials include `gitrefpretty()` in the tutorial - which is a super slick feature - but does not explain what it does. When I followed the tutorial I wasn't running it from a Git repo. As a result, waypoint would throw an error (can't remember what it was, but something about being confused about gitrefpretty). I think the tutorial should include a step to explain that the user should create a repository in GitHub before running the tutorial. This way, other users won't be confused when following the tutorial.

I'm not sure what other utility functions exist within waypoint that are similar to `gitrefpretty`, but it would be useful to have a doc page specific to nifty utility functions like that if other ones exist.

Thanks for a great tool! I hope this helps.

**Comment by briancain** [comment]
Hey there @kmcquade - We've got the HCL function documented here along with other available functions: https://tip.waypointproject.io/docs/waypoint-hcl/functions/all#gitrefpretty

Can you say which tutorial you were following? It would be good to give a heads up to the readers that this function is not possible in a Waypoint project without git tracking.

**Comment by kmcquade** [comment]
@briancain - actually, I can't find it now that I am trying to dig it back up. In the interest of keeping the issues clean, I'll close this issue to reduce noise. Sorry for causing any confusion.

**Comment by jhillyerd** [comment]
I see it here https://www.waypointproject.io/docs/waypoint-hcl/variables/artifact
