### ISSUE TITLE
Enable Waypoint usage without Waypoint server deployment

### ISSUE THREAD

**Issue by kmcquade** [hashicorp/waypoint#2805]
I'm running Waypoint for a personal project, but I'm generally very nervous about running my own server for the following reasons:
* The security groups would need to be open to the internet instead of restricted to GitHub actions IPs. GitHub Actions IPs (CIDR addresses [here](https://api.github.com/meta)) exceed the limit of 60 AWS security group rules per security group.
* Cost - this is a personal project so I would prefer to not add the cost of running on ECS. I think the expectation that users will run their own Waypoint server is cost-prohibitive for those who would use it for personal projects.
* Maintenance - As a rule, I **try** to use serverless or PaaS for personal projects and where possible professionally because I know how hard it is to maintain IaaS.

Is there any chance you would consider a feature that allows certain Waypoint functionality to occur by using something similar to Terraform state? I'd love to maintain the application state in an S3 backend so I don't have to manage my own server.

**Comment by briancain** [comment]
Hey there @kmcquade - yes, this is possible today! You can use Waypoint without a server, we call it [local mode](https://tip.waypointproject.io/docs/internals/execution#most-limited-cli-no-server). Please note that you will miss out on some features of Waypoint, but it is possible today.

This is generally not our main use-case but we do support it. If there's something more specific you wish to support on local mode please feel free to update your issue or open a new enhancement request. Thank you!

**Comment by kmcquade** [comment]
@briancain - I use local mode, but when I run `waypoint up` to update my Lambda functions from GitHub Actions, waypoint tells me that there is already an IAM role created with the same name and I'm not able to update it.

**Comment by briancain** [comment]
I'm not sure if that's related to local mode, but I recommend opening a new bug report issue about that so we can take a look @kmcquade ! Thank you

**Comment by kmcquade** [comment]
I'm going to close this bug - it looks like this was not a local mode thing... my Waypoint server didn't have iam:CreateRole permissions
