### ISSUE TITLE
aws-ecs deploy breaks on external ingress sg creation

### ISSUE THREAD

**Issue by nathanhruby** [hashicorp/waypoint#2854]
**Describe the bug**
Testing out Waypoint and hitting what seems to be a bug with deploying an artifact, in this case to an already existing ECS cluster.

 This service and cluster are meant to be used as a batch service, whereby we have logic that starts the service with additional params that tell the task what to act on. We don't need ingress traffic or an alb so I omitted that config and disabled the alb.  It's weird that it's trying to create an ingress sg which it doesn't need.  Even so, it fails.  If I go and create the sg manually with the given name it also fails.  AFAICT it is as if the code never gets to the point of trying the upsert of the SG.

Output of command is:
```
waypoint deploy

» Deploying wpt-foosrv...
❌ Initializing deployment...
✓ Discovered service subnets
✓ Found existing task IAM role: ecs_task_foosrv
✓ Using existing execution IAM role "ecs_execution_foosrv"
✓ Using existing log group /ecs/foosrv
✓ Registered Task definition: waypoint-wpt-foosrv
✓ Using existing ECS cluster foosrv
❌ Initiating creation of external security group named wpt-foosrv-inbound
! error reading from server: EOF
```

**Steps to Reproduce**
Steps to reproduce the behavior.
* waypoint.hcl
```
project = "co/repo"
app "foosrv" {
  path = "langdir/foosrv/docker"
  url {
    auto_hostname = false
  }
  build {
    use "docker" {
      context = "."
    }
    registry {
      use "aws-ecr" {
        region = "us-east-1"
        tag = gitrefpretty()
      }
    }
  }
  deploy {
    use "aws-ecs" {
      region = "us-east-1"
      memory = 5120
      cpu = 1024
      disable_alb = true
      assign_public_ip = false
      cluster = "foosrv"
      count = 0
      execution_role_name = "ecs_execution_foosrv"
      task_role_name = "ecs_task_foosrv"
      log_group = "/ecs/foosrv"
      subnets = [
        "subnet-a",
        "subnet-b",
        "subnet-c"
      ]
      security_group_ids = [
        "sg-1"
      ]
      static_environment = {
        AWS_ACCOUNT_ID = "x"
        AWS_REGION = "us-east-1"
      }
    }
  }
}

```
* stacktrace from running deploy with `-vvv` https://gist.github.com/nathanhruby/fdb607190698d4cd641ac044a4d0181d

**Expected behavior**
Deploy works

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

installed from homebrew this morning

* Waypoint CLI Version: 0.6.3
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`) aws-ecs
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

**Comment by nathanhruby** [comment]
I think this is because since DisableALB is set, `resourceAlbSubnetsDiscover` returns without setting subnets which `resourceExternalSecurityGroupsCreate` requires.  

Seems like a good fix would be to also check for DisableALB skip the group creation if set?

**Comment by sgabenov** [comment]
Have the very same behaviour. I do not need to create any additional SG (don't have permissions on it), so need to explicitly set up a VPC, subnets, sg. And when i try to override it with "security_group_ids", waypoint just ignores these configuration.

**Comment by catsby** [comment]
I've merged https://github.com/hashicorp/waypoint/pull/2894 which should address this, so I'm closing this for now. If you feel https://github.com/hashicorp/waypoint/pull/2894 does not fix this issue, please let us know and we can reopen this. Thanks!
