### ISSUE TITLE
Add git commit message to responses from backend

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/waypoint#2880]
**Is your feature request related to a problem? Please describe.**
In the UI, we're displaying the git commit SHA in multiple places. Ideally, we would like to also show the commit message, since this is more easily recognizable and human readable for distinguishing different commits.

**Describe the solution you'd like**
Wherever the backend sends us the commit SHA, also include the commit message.

**Comment by evanphx** [comment]
Sounds good! This is pretty easy, we just need to enhance https://github.com/hashicorp/waypoint/blob/c9f539c58a710c7381a2b53d130fff28cbc8e1cb/internal/datasource/git.go#L270-L273 to add information from from `commit.Message`, I'm pretty sure.
