### ISSUE TITLE
ui: add a resources tab/table view

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/waypoint#2881]
**Describe the solution you'd like**
As part of the UI redesign, a `Resources` tab was proposed for the application overview page. The `Resources` tab would direct the user to a comprehensive list of all the resources related to the application and display various information about each (status, what artifact it's attached to, etc).

**Additional context**
[Already in progress](https://github.com/hashicorp/waypoint/tree/ui/artifact-overview-popover), just wanted to document this work

**Comment by jgwhite** [comment]
Closed by #2777
