### ISSUE TITLE
ui: polling causes ember-a11y-refocus to refire

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/waypoint#2882]
**Describe the bug**
With the new package `ember-a11y-refocus`, screen readers now announce when the user has navigated to a new page and refocuses them to the top of the page, since this is a SPA. Unfortunately, with how our data is collected/stored with polling and not ember data, this announcement of the user navigating to a new page happens every time the frontend successfully polls the backend.

**Steps to Reproduce**
1. Start up the UI `yarn start`
2. Start up the screen reader
3. Check that `ember-a11y-refocus` runs when navigating to a new page
4. Wait on an application overview page for a little bit until a polling event occurs

**Expected behavior**
Should not fire whenever polling occurs

**Comment by jgwhite** [comment]
@MelSumner and I have been working on a feature for ember-a11y-refocus that should help us out with this. Watch this space.
