### ISSUE TITLE
Waypoint UI app empty logs tab should explain why it is empty correctly

### ISSUE THREAD

**Issue by jbayer** [hashicorp/waypoint#2911]
**Describe the bug**
In the UI, the text on the Logs tab says:

```
There are no logs to display for this app yet
Logs will be displayed when you run actions in the CLI such as build, deploy or release
```

The 2nd sentence is incorrect as the logs tab will show content when the app has system out or system error content.

<img width="1136" alt="CleanShot 2022-01-20 at 16 40 45@2x" src="https://user-images.githubusercontent.com/34030/150371446-6beda740-ff18-4615-b5c2-fdec4f042a7f.png">

**Steps to Reproduce**
Deploy an example app with `waypoint up`. I used [the NodeJS example for EKS](https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/aws-eks/nodejs).

**Expected behavior**
When no content is available, the explanatory sentence would read something like:

```
There are no logs to display for this app yet
Logs will be displayed when the app prints to system out or system error.

```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.7.0
* Waypoint Server Platform and Version: `kubernetes` and 0.7.0

**Comment by evanphx** [comment]
Yeah, that message is incorrect.

**Comment by jgwhite** [comment]
@sdav9375 note that the `<LogStream>` component you see here is used in a few different places, so you may find you need to make the message customizable.
