### ISSUE TITLE
ui: Limit number of deployments requested

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2919]
@briancain and I discussed this and we think as a temporary measure we could limit the number of deployments requested to ~50~ 10. We should still improve the performance of these methods, and pursue true pagination in the API, but the ~50~ 10 limit will hopefully make Waypoint UI usable in cases like this.

_Originally posted by @jgwhite in https://github.com/hashicorp/waypoint/issues/2304#issuecomment-1015858019_

**Comment by siccous** [comment]
Not sure if 50 is still small enough, at least for me.

Maybe I am doing something wrong but for example I have app with 59 deployments and it took more than 10 seconds to load.

![image](https://user-images.githubusercontent.com/7812885/150305948-72860eb8-48d9-4d41-a96a-07447136a320.png)

**Comment by jgwhite** [comment]
@siccous that’s great data, thank you.

@briancain what do you think? I’m tempted to reduce the limit to 10 as a starting point, but we should probably also prioritize #2304
