### ISSUE TITLE
ui: CI parallelism leads to duplicate Percy builds

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#2923]
**Describe the bug**
We have parallelism set to `2` in our CircleCI config for UI test. This leads to extra redundant Percy builds. The builds count against our company Percy limits, so we should address this sooner rather than later.

This thread from a Percy support engineer is instructive:
https://github.com/percy/percy-agent/issues/477#issuecomment-597118489

**Comment by evanphx** [comment]
![200514_logan_lerman_percy_jackson 0](https://user-images.githubusercontent.com/7/150186953-7d456392-9c4f-48ee-a701-00fc83974573.jpg)
