### ISSUE TITLE
Cannot list contexts after deleting the active one

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2951]
**Describe the bug**
If you delete your current context, you cannot then list contexts

**Steps to Reproduce**
```
$ waypoint context list # (see which is current)
$ waypoint context delete <current active context>
$ waypoint context list
! Error loading context "<your-context>": <nil>: Configuration file not found; The configuration file /Users/<your-user>/Library/Preferences/waypoint/context/<your-context> does not exist.
```

ALSO WEIRD: after deleting the context, your waypoint commands still work! i.e. `waypoint auth-method list` will still call out to the server addr of the context you just deleted! I assume this is because the deleted context lives on inside `_default.hcl`

## Expected behavior

I think if you delete the current context, we should also delete the `_default.hcl` file, and all subsequent waypoint commands that need a context should error with something like `no context selected`.

Alternatively we could disallow deleting the currently selected context.

* Waypoint CLI Version: v0.7.1
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

**Comment by krantzinator** [comment]
This almost sounds like you might have had two same-named contexts. This would explain why commands like `auth-method` were still working, and would explain the "file not found" error also, since we unset defaults based on the name of the context https://github.com/hashicorp/waypoint/blob/914b4b8fe963216a0813b3c173031e21974fe682/internal/clicontext/storage.go#L138-L145

**Comment by izaaklauer** [comment]
Confirmed - I was in some kind of weird state. I cannot reproduce this when starting with a totally clean context directory. I'll keep my eyes out for it in the future.
