### ISSUE TITLE
Re-run jobs

### ISSUE THREAD

**Issue by ugurcemozturk** [hashicorp/waypoint#3002]
**Is your feature request related to a problem? Please describe.**
There is no option to re-run jobs via UI. I believe that the folks may need to rerun the job via UI, not only limited to the waypoint CLI.

**Describe the solution you'd like**
Successful deploys can be replayed via the UI. We'd like to perform the same action for unsuccessful builds, deploys, or any atomic task.
 
**Describe alternatives you've considered**
Users do not need to install and configure waypoint locally for anything that can be done via UI.

**Comment by xiaolin-ninja** [comment]
Hi! We have an issue for this here https://github.com/hashicorp/waypoint/issues/2445 and are working on this feature. Thanks!
