### ISSUE TITLE
waypoint CLI's config get/set does not respect the `-app` scope param

### ISSUE THREAD

**Issue by 1xyz** [hashicorp/waypoint#3031]
**Describe the bug**
the waypoint CLI's config get/set does not respect the `-app` scope param

**Steps to Reproduce**
Here's an example:
```shell
$ waypoint config set -app=db POSTGRES_USER=foo

$ waypoint config get
   SCOPE  |       NAME        |  VALUE   | WORKSPACE | LABELS
----------+-------------------+----------+-----------+---------
  project | PORT              |     8080 |           |
  project | POSTGRES_PASSWORD | postgres |           |
  project | POSTGRES_USER     | foo      |           |

I would expect waypoint config to have the scope for app: db, and not project

This scoping seems to work when the config is defined in a waypoint.hcl file
```
Also, once I have defined app scoped config variables (defined in a waypoint.hcl file). `get` returns incorrect values

```
$ waypoint config get
   SCOPE  |       NAME        |  VALUE   | WORKSPACE | LABELS
----------+-------------------+----------+-----------+---------
  project | PORT              |     8080 |           |
  project | POSTGRES_PASSWORD | foo      |           |
  app: db | POSTGRES_PASSWORD | postgres |           |
  project | POSTGRES_USER     | foo      |           |
  app: db | POSTGRES_USER     | postgres |           |

$ waypoint config get -app=foo
   SCOPE  |       NAME        |  VALUE   | WORKSPACE | LABELS
----------+-------------------+----------+-----------+---------
  project | PORT              |     8080 |           |
  app: db | POSTGRES_PASSWORD | postgres |           |
  app: db | POSTGRES_USER     | postgres |           |

Expected: would have expected to get project scope values for -app=foo

```

**Waypoint Platform Versions**
```
 waypoint version
CLI: v0.7.1 (062857d16)
Server: v0.7.1```

**Comment by xiaolin-ninja** [comment]
Hi @1xyz, currently, in order to set a specific scope with the CLI, [`config set` requires an explicit `-scope` flag in addition to `-app`. ](https://www.waypointproject.io/commands/config-set#scope)

So you'd want something like: `waypoint config-set -scope='app' -app='db' POSTGRES_USER=foo`

This is a good idea for a new feature though! We'll make a ticket for the `-app` flag to automatically set the scope as well. Thank you!

**Comment by jurgenwerk** [comment]
@xiaolin-ninja I would also expect for the `-app` flag to work with `config get`, but for me, adding the `-app` flag in `waypoint config get -app=MY_APP` does nothing (it displays config from all apps). I'm on version 0.4.2.

**Comment by briancain** [comment]
@jurgenwerk - Please upgrade to a more recent version of Waypoint. The latest currently is [0.7.1](https://www.waypointproject.io/downloads). Thanks!

**Comment by jurgenwerk** [comment]
@briancain thanks! We would upgrade but https://github.com/hashicorp/waypoint/issues/1568 is currently preventing us from doing that.

**Comment by 1xyz** [comment]
> Hi @1xyz, currently, in order to set a specific scope with the CLI, [`config set` requires an explicit `-scope` flag in addition to `-app`. ](https://www.waypointproject.io/commands/config-set#scope)
> 
> So you'd want something like: `waypoint config-set -scope='app' -app='db' POSTGRES_USER=foo`
> 
> This is a good idea for a new feature though! We'll make a ticket for the `-app` flag to automatically set the scope as well. Thank you!

Thanks for the note @xiaolin-ninja
* I missed the `-scope` option, 👍  for setting it implicitly if `-app` is provided 

For the `config get` subcommand. I'm using  ver:`0.7.1` and I don't see the `-scope` param 
```
# Ex: the output of this command does not show the -scope option unlike `config set`
$ waypoint config get --help 
```
cc: @jurgenwerk @briancain

**Comment by briancain** [comment]
@1xyz - Shoot, our apologies then. I thought this was in a 0.7.x release, but it looks like it is not. Let's leave this open to track the work fixing this up.

**Comment by xiaolin-ninja** [comment]
This will be included in the next 0.8 release!

**Comment by briancain** [comment]
@lukemelia - The fix has already been merged against `main` it just is not released yet. I'll put this in the 0.8 milestone. We were leaving it open to track the question.

**Comment by briancain** [comment]
Hey all - We pushed out a recent release that should include these app scope fixes. I'm going to go ahead and close this issue! Version 0.8.1 is latest as of this comment, so I recommend giving this a try. If you encounter any more issues please feel free to open a new issue and we will take a look. Thank you again all!
