### ISSUE TITLE
[plugin/k8s/task] Limit runner job resources

### ISSUE THREAD

**Issue by nsurleraux-railnova** [hashicorp/waypoint#3047]
**Is your feature request related to a problem? Please describe.**
We are willing to build our containers using Waypoint runners instead of Github Actions but for now, we cannot limit the resource limit using Kubernetes runners.

**Describe the solution you'd like**
We should be able to specify limits in the runner profile configuration.
It seems there is already a beginning of work [there](https://github.com/hashicorp/waypoint/blob/adfed1457920d547b51fee26d30c4b5d656014b1/builtin/k8s/task.go#L204-L210).

**Describe alternatives you've considered**
Creating a new plugin for that seems a bit over-engineered.

**Explain any additional use-cases**
We are running several deployment pipelines on Github Actions and would like to migrate them on our Waypoint K8s cluster and limit the impact on the resources.

**Additional context**
N/A

**Comment by evanphx** [comment]
Hi @nsurleraux-railnova,

You're right on, we just didn't add settings to control resource usage on the TaskConfig. Those need to be added like we have them on the Deploy config. Then you'd configure those settings in the runner config.

**Comment by nsurleraux-railnova** [comment]
Hi @evanphx,

Thanks for your answer. Is it planned soon? Can I help somehow?

**Comment by evanphx** [comment]
@nsurleraux-railnova It's not currently planned but might be picked up soon. If you'd like to help, you can submit a PR to add the functionality! Those are usually handled quickly.
