### ISSUE TITLE
CLI: Implement job stream watching for `waypoint job get-stream`

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#3071]
**Is your feature request related to a problem? Please describe.**

Allow users to attach a local CLI to a running job and read the event stream through `waypoint job get-stream`

Related to the remaining work from https://github.com/hashicorp/waypoint/issues/3064. The CLI command was added but not implemented yet.

**Describe the solution you'd like**

Add a client helper package that can handle returning a job event stream that the CLI can use. It would be best to do this rather than copy/pasting the entire implementation where we already handle the stream in `internal/client/job.go`.

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by evanphx** [comment]
We should couple this with a `-d` to CLI actions that would normally output a job to "detatch" instead. This CLI method could then be used to "attach" to a previously "detached" job.

**Comment by briancain** [comment]
The stream watch implementation is open in a PR: https://github.com/hashicorp/waypoint/pull/3410

Currently on the `f-pipelines` branch because that's the branch that has the extracted job stream client. I'd say we should do the detach in a separate PR from now, because getting the jobstream for pipelines is important and we can do a follow up to implement detach.
