### ISSUE TITLE
plugin env vars don't show up in the docs

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#3135]
**Describe the bug**

We're documenting env vars in our code (i.e. VAULT_NAMESPACE): https://github.com/hashicorp/waypoint/blob/473c44791c98df8e5264a59a0ae25bc3eaaa8f13/builtin/vault/config_sourcer.go#L445

But that isn't showing up in our docs:

https://www.waypointproject.io/plugins/vault#namespace

<img width="493" alt="Screen Shot 2022-03-23 at 3 14 10 PM" src="https://user-images.githubusercontent.com/8404559/159778168-6e3b7f08-fc28-4a61-9ddd-c33a791e3191.png">

**Comment by krantzinator** [comment]
Closed by #3582
