### ISSUE TITLE
Cannot use "dynamic" function to load a secret from HashiCorp Vault even configuring source-set already

### ISSUE THREAD

**Issue by dmakeroam** [hashicorp/waypoint#3228]
**Describe the bug**
We cannot use "dynamic" function to load a secret from HashiCorp Vault in the application configuration section as below:

```hcl
config {
    env = {
      ASPNETCORE_URLS = "http://*:8090"
      PASSWORD = dynamic("vault", {
        path = "kv/database"
        key  = "/data/password"
      })
    }
  }
```

The secret is in HashiCorp Vault KV version 2 storage and in the path kv/database with namespace "admin"

```sh
$ vault kv get kv/database
```
====== Data ======
Key         Value
---         -----
password    REDACTED

And, We already configured the vault plugin as shown below: 

```sh
$ waypoint config source-get -type=vault
     KEY    |                                             VALUE                                               
------------+-------------------------------------------------------------------------------------------------
  addr      | REDACTED
  token     | REDACTED                                                                
  namespace | REDACTED                                       
```

Once we deployed the application with command

```sh
$ waypoint up  -var=registryUsername="REDACTED" -var=registryPassword="REDACTED"
```

We could not find a secret in our application env

Exec to the application

```sh
$ waypoint exec /bin/sh
```

Get the PASSWORD secret

```sh
$ echo $PASSWORD
```

We got nothing.

**Steps to Reproduce**

1. Run the command "waypoint up" with the following HCL file to deploy the application

```sh
$ waypoint up  -var=registryUsername="REDACTED" -var=registryPassword="REDACTED"
```

HCL File:
https://gist.github.com/dmakeroam/00337dcc649f37fa909b3ad3a40aa70c

2. Exec to the application after it deployed successfully

```sh
$ waypoint exec /bin/sh
```

3. Get the PASSWORD secret

```sh
$ echo $PASSWORD
```

We got nothing.

**Expected behavior**
** We should got the secret from HashiCorp Vault

**Waypoint Platform Versions**
*** HashiCorp Waypoint v0.8.1, API: v1, Entrypoint: v1

* Waypoint CLI Version:
** CLI: v0.8.1 (622f37bd1)

* Waypoint Server Platform and Version: 
** Azure Kubernetes Service v1.21.9, Ubuntu 18.04.6 LTS, Azure CNI

* Waypoint Plugin:
** Kubernetes

**Comment by dmakeroam** [comment]
Any idea of this ? @mitchellh @briancain

**Comment by catsby** [comment]
Hello @dmakeroam  - does `waypoint logs` give you any additional information? I would expect some log entries like `entrypoint.config.watcher`

**Comment by catsby** [comment]
@dmakeroam I would also double check your `key` and `path` values. Using Vault KV2 and the paths you mention, I would expect the `path` to be `kv/data/database`, and not `kv/database`. Please let us know if that addresses the issue. 

- https://www.waypointproject.io/plugins/vault#vault-configsourcer

**Comment by dmakeroam** [comment]
> Hello @dmakeroam - does `waypoint logs` give you any additional information? I would expect some log entries like `entrypoint.config.watcher`

It does not give me anything.

**Comment by dmakeroam** [comment]
> @dmakeroam I would also double check your `key` and `path` values. Using Vault KV2 and the paths you mention, I would expect the `path` to be `kv/data/database`, and not `kv/database`. Please let us know if that addresses the issue.
> 
> Example:
> 
> ```terraform
> config {
>     env = {
>       ASPNETCORE_URLS = "http://*:8090"
>       PASSWORD = dynamic("vault", {
>         path = "kv/data/database"
>         key  = "/data/password"
>       })
>     }
>   }
> ```
> 
> * https://www.waypointproject.io/plugins/vault#vault-configsourcer

I will try it

**Comment by dmakeroam** [comment]
Once I tried it, it was working as your mention @catsby. So we can close this issue.

**Comment by catsby** [comment]
Thank you for opening the issue and following up @dmakeroam !
