### ISSUE TITLE
Feature request: improve error/warning for `ui -authenticate` when no default context

### ISSUE THREAD

**Issue by thiskevinwang** [hashicorp/waypoint#3243]
**Is your feature request related to a problem? Please describe.**

When running `waypoint ui -authenticate` with no _default/active_ context:
1. The error doesn't isn't clear on how to resolve itself.
2. The config/context is looked up with an empty (`""`) name.

**Describe the solution you'd like**

The error message should include some steps on how to remediate the situation.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**

Terminal output
```console
λ waypoint -v              
CLI: v0.8.1 (622f37bd1)

λ  waypoint context list
No contexts. Create one with `waypoint context create`.

λ  waypoint ui -authenticate
Waypoint must be configured in server mode to access the UI

» Creating invite token
This invite token will be exchanged for an authentication
token that your browser stores.
! <nil>: Configuration file not found; The configuration file
  /Users/kevin/Library/Preferences/waypoint/context/.hcl does not exist.
```

Blank name lookup:
https://github.com/hashicorp/waypoint/blob/26396c895f40276db532a368dae351f40b01d55e/internal/cli/ui.go#L55-L60

The error being thrown appears to be from:
https://github.com/hashicorp/hcl/blob/2ef09d129d968e8c6e7df29f9af103025eafd61a/hclsimple/hclsimple.go#L89-L97

**Comment by evanphx** [comment]
Hi @thiskevinwang,

Good call! We have a few places where we could be doing a much better job around messaging that there is no default context set.
