### ISSUE TITLE
Document runner targeting

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#3277]
Runner targeting was introduced in 0.8, and is a very useful feature for enabling complex workflows! I think it needs more documentation.

1: update our `waypoint.hcl` app stanza docs here: https://www.waypointproject.io/docs/waypoint-hcl/app  To include the new `runner` stanza.

2: Add something to the runner docs (here: https://www.waypointproject.io/docs/runner) explaining runner targeting. Maybe it should be it's own page inside the runner docs. It should explain:
- What runner targeting does (allows waypoint apps to choose which apps their operations happen on)
- Explain why it's useful (multi-cluster workflows)
- Probably give an end-to-end simple example of runner targeting (i.e. launch a runner with a label, create a named profile with that label, target that profile name from the waypoint.hcl)
- (probably) At least hint at the underlying power. You can have profiles that match multiple runners (and round-robin) for scale or redundancy, you can make the profile target dynamic in the waypoint.hcl based on the workspace name (to enable dev/prod to go to separate clusters), etc.

We should also update the "[Additional Runners](https://www.waypointproject.io/docs/runner/run-manual)" docs to mention that you probably want to start the new runners with labels, and mention the k8s standalone-runner helm mode.

**Comment by izaaklauer** [comment]
Labeling as a "bug", because as far as I can find we're not documenting runner targeting in the waypoint.hcl at all right now.

**Comment by xiaolin-ninja** [comment]
Let's add documentation about runner adoption to this job item as well. & we could actually leverage the Runner Install documentation to show the entire runner flow with adoption, profile setting, targeting, etc.
