### ISSUE TITLE
cloning recursive git repos w remove runner

### ISSUE THREAD

**Issue by jessfraz** [hashicorp/waypoint#3350]
**Is your feature request related to a problem? Please describe.**

If building a project relies on submodules there should be an option for the remote runner config to clone the repo recursively, or maybe just a way to pass arbitrary git flags to the command that is run.

**Comment by mitchellh** [comment]
I got you. PR open #3351.

**Comment by mitchellh** [comment]
We have a point release 0.8.2 scheduled soon (this week? next?) so if we get it merged and backported in time (we should), it'll be in that release.

**Comment by jessfraz** [comment]
amazing thank you!
