### ISSUE TITLE
Nomad 1.3.0: Node excluded because "${attr.consul.version} semver >= 1.7.0"

### ISSUE THREAD

**Issue by joshuacox** [hashicorp/waypoint#3376]
Following the official [tutorial](https://learn.hashicorp.com/tutorials/waypoint/get-started-nomad?in=waypoint/get-started-nomad#install-the-waypoint-server), when deploying the example nodejs application,  Waypoint errors out with:

```
* Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
```

  Full logs below.  And my consul version is above 1.7.0 (at 1.12.0). 

**Steps to Reproduce**
Follow the [tutorial](https://learn.hashicorp.com/tutorials/waypoint/get-started-nomad?in=waypoint/get-started-nomad#install-the-waypoint-server)

```
nomad agent -dev -network-interface=enp8s0 -config=nomad.config
```

with this nomad.config to account for the host volume:
```
client {
  host_volume "waypoint-server" {
    path = "/data/waypoint-server"
    read_only = false
  }
}
```

with a waypoint install command (adjusted for host volume):
```
waypoint install -platform=nomad -accept-tos -nomad-host-volume=waypoint-server -nomad-consul-service=false  
```

waypoint, indeed, creates it's db:
```
root@vagrant: ~# ls -Rlh /data                         
/data:
total 4.0K
drwxr-xr-x 2 systemd-network vagrant 4.0K May 22 22:35 waypoint-server

/data/waypoint-server:
total 44K
-rw------- 1 systemd-network vagrant 64K May 22 22:42 data.db
-rw------- 1 systemd-network vagrant   0 May 22 22:35 waypoint-restore.db.lock
```

the official example nodejs waypoint was used --> https://github.com/hashicorp/waypoint-examples/blob/main/nomad/nodejs/waypoint.hcl 

**Expected behavior**
The nodejs application to start.

**Waypoint Platform Versions**

* Waypoint CLI Version:
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

```
root@vagrant:~# waypoint version
CLI: v0.8.2 (5b8885480)
Server: v0.8.2
root@vagrant:~# consul version
Consul v1.12.0
Revision 09a8cdb4
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

root@vagrant:~# nomad version
Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)
root@vagrant:~# vault version
Vault v1.10.3 (af866591ee60485f05d6e32dd63dde93df686dfb)
root@vagrant:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-80-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.775GiB
 Name: vagrant
 ID: 7CYX:MNFM:YUVU:RI3M:XT3C:YZSH:R3ZP:VSOQ:M55N:QAW2:JSFU:74TB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
```

**Additional context**

logs from a generic ubuntu focal:
```
root@vagrant:~/waypoint-examples/nomad/nodejs# ls
index.js  package.json  public  README.md  views  waypoint.hcl
root@vagrant:~/waypoint-examples/nomad/nodejs# waypoint init
✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "example-nodejs" and all apps are registered with the server.

Project initialized!

You may now call 'waypoint up' to deploy your project or
commands such as 'waypoint build' to perform steps individually.
root@vagrant:~/waypoint-examples/nomad/nodejs# waypoint up
  Performing operation locally

» Building example-nodejs...
✓ Running build v1
Warning! Buildpacks are known to have issues on architectures other than amd64. The architecure being reported by the Docker server is "x86_64". We will still attempt to build the image,
but may run into issues.
Creating new buildpack-based image using builder: heroku/buildpacks:20
✓ Creating pack client
✓ Building image
 │ [exporter] Adding layer 'process-types'
 │ [exporter] Adding label 'io.buildpacks.lifecycle.metadata'
 │ [exporter] Adding label 'io.buildpacks.build.metadata'
 │ [exporter] Adding label 'io.buildpacks.project.metadata'
 │ [exporter] Setting default process type 'web'
 │ [exporter] Saving example-nodejs...
 │ [exporter] *** Images (42f4521666c2):
 │ [exporter]       example-nodejs
 │ [exporter] Adding cache layer 'heroku/nodejs-engine:dist'
 │ [exporter] Adding cache layer 'heroku/nodejs-npm:toolbox'
✓ Injecting entrypoint binary to image

Generated new Docker image: example-nodejs:latest
✓ Running push build v1
✓ Tagging Docker image: example-nodejs:latest => nodejs-example:1
✓ Docker image pushed: nodejs-example:1

» Deploying example-nodejs...
✓ Running deploy v1
✓ Job registration successful
✓ Evaluation status changed: "pending" -> "complete"
⚠️ Evaluation "59459995-c2e7-30cc-dbcf-3a3c04c51400" finished with status "complete" but failed to place all allocations
⚠️ Task Group "example-nodejs-01g3gwqgmrh02msgt0jhvg2v5t" (failed to place 1 allocation):
  * Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
⚠️ Evaluation "860af1f2-6dd1-d4a1-ea55-ba161bda2c6b" waiting for additional capacity to place remainder
example-nodejs-01g3gwqgmrh02msgt0jhvg2v5t
! Failed to schedule all allocations
```

[full focal -vvv waypoint deploy log](https://gist.github.com/joshuacox/33d0ee83025cdf8a7a6faf2e7ebb132d)
[archlinux full debug](https://gist.github.com/joshuacox/0fbc21f55c149ca2eb128260b6f674f8)

[discuss.hashicorp topic](https://discuss.hashicorp.com/t/node-excluded-because-attr-consul-version-semver-1-7-0/39818)

EDIT:
I upgraded nomad to 1.3.1 and reran on a fresh focal install, pretty much the same results, I have a gist of the `waypoint deploy -vvv` step and the accompanying nomad stdout [here](https://gist.github.com/joshuacox/65431d3da42f24ff5cb2dfcb89b32087).

[Vagrantfile](https://gist.github.com/joshuacox/267062259e38de8a45545faca8b50467)

EDIT: workaround with consul [Vagrantfile](https://gist.github.com/joshuacox/7f9e45f6741a1ca18e059116650734f4)

```
vagrant up && vagrant ssh
```

then

```
sudo -i
./start.sh
```

**Comment by centur** [comment]
I have somewhat similar issue. From what I found so far - this issue might be related to  #12958  (missing provider="nomad" for service stanza). 
My case is slightly different though - our cluster is still running nomad 1.2.6 and consul :(

**Comment by joshuacox** [comment]
@centur can you give a direct link to that issue?  waypoint doesn't have that many issues yet so [#12958](https://github.com/hashicorp/waypoint/issues/12958) 404s out here.  What was your fix?  the waypoint example does have [this](https://github.com/hashicorp/waypoint-examples/blob/main/nomad/nodejs/waypoint.hcl#L17) use line in regards to nomad, but it's not a `provider`.

As an aside note I built an example [Vagrantfile](https://gist.github.com/joshuacox/267062259e38de8a45545faca8b50467) exhibiting the issue in a regular fashion.

**Comment by centur** [comment]
Sorry, I had many of them open and thought it's the issue in the same repo. This is the one meant to be in the comment:
https://github.com/hashicorp/nomad/issues/12958
Will update that commment too

**Comment by slondr** [comment]
I'm getting the exact same issue following the tutorial

**Comment by taytayp** [comment]
Turning -dev mode on my consul agent did not work for me :/ 
This is on a one agent one server set up with Terraform for [this](https://learn.hashicorp.com/tutorials/nomad/consul-service-mesh?in=nomad/integrate-consul) Nomad tutorial.

**Comment by joshuacox** [comment]
Hashicorp really needs to weigh in here as the official tutorial is, indeed, broken.   It is explicitly stated:

**Comment by evanphx** [comment]
Hi all!

The waypoint team have been looking at this and it's definitely a bug. It exists because we wanted the tutorial to be able to run when the user didn't also have nomad configured with consul. Now that nomad 1.3.0 is out and has its own service discovery, we're going to look at updating the tutorial to take advantage of that.

That being said, you're all still hitting a bug and we're going to see if it's because of something that changed in 1.3.0 or not.

For now, we suggest running `consul agent -dev` along side nomad when running the tutorial to avoid this issue. Optionally, you should be able to use an older version of nomad with the tutorial.

**Comment by nergdron** [comment]
so I just started seeing this today on a semi-prod cluster with an existing traefik job, it's now started making the same complaint and not running:

```

traefik 1 unplaced

    Constraint ${attr.consul.version} semver >= 1.7.0 filtered 1 node
```

is this the same root cause, or is this somethinng else broken in nomad? is there a fix for existing clusters so that it doesn't generate this error? having traefik down breaks pretty much everything else running on the cluster.

**Comment by rongcuid** [comment]
The quickstart here https://learn.hashicorp.com/tutorials/nomad/get-started-run?in=nomad/get-started also cause the problem.

**Comment by joshuacox** [comment]
I have an updated [Vagrantfile](https://gist.github.com/joshuacox/7f9e45f6741a1ca18e059116650734f4) that does reflect the workaround (i.e. adding in `consul agent -dev`).  But I'll leave this open until the tutorials are fixed for the poor n00bs out there just trying to learn.

**Comment by Y--** [comment]
Just ran into the same issue and solved it by starting Consul bound to my node's IP.

Something along the lines of:
```sh
consul agent -dev -bind <node ip address> -config-dir=/some/config/dir -log-level INFO
```

When it is discovered by Nomad, you can check that your node is using it by checking the `Attributes` section of your node config. 

Something along the lines of:
```sh
curl -s http://localhost:4646/v1/node/<node uuid> | jq ".Attributes" | grep consul
```

Hope it helps.

**Comment by ChinW** [comment]
so consul is a MUST dependency of nomad?

**Comment by agardnerIT** [comment]
It appears consul is a requirement although this isn't mentioned in the [getting started](https://learn.hashicorp.com/collections/nomad/get-started).

The following worked for me:
```
consul agent -dev -bind 0.0.0.0 -log-level INFO
sudo nomad agent -dev -bind 0.0.0.0 -log-level INFO
nomad job init
nomad job run example.nomad
```

**Comment by tuborg4** [comment]
from what i found, for consul with enabled ACLs, explicit read and write policy need to be configured for nomad servers:

service_prefix "" {
  policy = "write"
}

service_prefix "" {
  policy = "read"
}

agent_prefix "" {
  policy = "write"
}

agent_prefix "" {
  policy = "read"
}

node_prefix "" {
  policy = "write"
}

node_prefix "" {
  policy = "read"
}

acl = "write"
acl = "read"

**Comment by rikhuijzer** [comment]
I managed to avoid Consul in Nomad 1.3.2 by setting `provider = "nomad"` in `service`.

From `example.nomad` generated via `nomad job init`:
```hcl
job "example" {
  datacenters = ["dc1"]
  type = "service"

  group "cache" {
    count = 1

    [...]

    service {
      name     = "redis-cache"
      tags     = ["global", "cache"]
      port     = "db"
      provider = "nomad"
     
      [...]
    }

    [...]

}
``` 

Unfortunately, trying to enable service checks with this doesn't work (yet, I suppose) with error: `Service with provider nomad cannot include Check blocks`.

**Comment by marcgweg** [comment]
Any news on this? I have a 3 nodes Raspberry PI cluster with Consul/Nomad. And the waypoint deploy gives the same error nowadays.
Consul.    v1.14.2 Revision 0ba7a401
Nomad.    v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)
Waypoint CLI: v0.10.1 (830e74dd0)
                 Server: v0.10.v


» Deploying calibre...

» Performing operation locally
✓ Running deploy v4
✓ Deleting job: calibre
✓ Job registration successful
✓ Evaluation status changed: "pending" -> "complete"
⚠️ Evaluation "21d5e8ee-edaa-790e-1baa-1294574c5dfa" finished with status "complete" but failed to place all allocations
⚠️ Task Group "calibre" (failed to place 1 allocation):
  * Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter  * Resources exhausted on 1 nodes  * Dimension
"memory" exhausted on 1 nodes
⚠️ Evaluation "12f72bc0-4575-0cd6-c73e-bf0fe245f01b" waiting for additional capacity to place remainder
! Failed to schedule all allocations

**Comment by briancain** [comment]
Please open a new issue and we'll take a look, thank you!

**Comment by marcgweg** [comment]
Ah saw this issue was closed. Will do, sorry.
