### ISSUE TITLE
Documentation search does not include HCL functions

### ISSUE THREAD

**Issue by jhillyerd** [hashicorp/waypoint#3393]
**Describe the bug**
Documentation search does not include HCL functions on https://www.waypointproject.io/docs/waypoint-hcl/functions/all

**Steps to Reproduce**
1. Visit https://www.waypointproject.io/docs
2. Type `/gitrefpretty` or `/abspath`, etc
3. Observe not search results

**Expected behavior**
Referred to to https://www.waypointproject.io/docs/waypoint-hcl/functions/all#gitrefpretty etc

**Waypoint Platform Versions**
Docs 0.8.x or tip.

**Additional context**
Would have helped #2804 for example

**Comment by thiskevinwang** [comment]
Thanks for raising this @jhillyerd! This looks to be a current limitation/bug in our search content indexing logic.

We should be able to get a fix out for this by end of week — cc: @hashicorp/web-platform

**Comment by BRKalow** [comment]
This should be resolved now, thanks for raising this!
