### ISSUE TITLE
waypoint logs does not respect -workspace switch

### ISSUE THREAD

**Issue by rhabbachi** [hashicorp/waypoint#3395]
**Describe the bug**
Using the **Logs** tab on a project on a workspace A (or any workspace for that matter) will show logs from a different workspace B. On the Web UI, This also affect the **default** workspace even there are no deployments done in it.

CLI wise, `waypoint logs -app appname -workspace A` and `waypoint logs -app appname -workspace B` show identical output. The first command is showing logs from workspace B instead.

**Steps to Reproduce**
1. Deploy a waypoint app with the helm plugin (not sure it's tied to the helm plugin thought).
2. Check logs.

- Selecting workspaces with no deployment (default) or destroyed deployment (preview-3) still shows log output.
https://user-images.githubusercontent.com/1914306/171048750-858e8b19-baae-48d0-9c3a-76914e47cc60.mp4

- Demo logs from workspace __preview-3__ are show instead of logs from the __develop__ workspace.
https://user-images.githubusercontent.com/1914306/171049278-b08aec87-e495-4f0d-a75b-5d6377238975.mp4

**Expected behavior**
_Logs_ tab and `waypoint logs` command respect -workspace switch

**Waypoint Platform Versions**
```
> waypoint --version
CLI: v0.8.2 (5b8885480)
Server: v0.8.2
```
* Platform: Kubernetes/EKS
* Waypoint Plugin: local runner, docker for build, helm for deployment

**Additional context**
N/A.

**Comment by rhabbachi** [comment]
Probably similar to https://github.com/hashicorp/waypoint/issues/3224

**Comment by briancain** [comment]
Thanks @rhabbachi for reporting this issue ! That sounds right, we have some work to make sure our CLI commands respect the `-workspace` flag.

**Comment by rhabbachi** [comment]
Hi @briancain! Still slated to be addressed as part of a 0.9 point release?

We are trying to get the developers to use waypoint more but not having the correct logs makes it difficult. Obviously no pressure, just a heads up for the ops team to implement some workarounds.

**Comment by briancain** [comment]
Hey there @rhabbachi - I've made a fix for this via #4009. It should go out in the next minor release! Apologies for the delay on this one.

**Comment by briancain** [comment]
@rhabbachi - A workaround for now is specifying the deployment sequence. This will by chance respect the workspace because deployment sequence ids span across workspaces.

**Comment by rhabbachi** [comment]
Thank you!
