### ISSUE TITLE
`runner profile delete` should use `name` and not `id`

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#3481]
Once #3379 is fixed and runner profiles are guaranteed to have unique names, we should update `runner profile delete` (to be released as of this issue creation) to require the `name` and not the `id`, as getting the id is cumbersome.

**Describe the bug**
```
❯ waypoint runner profile delete -name=docker
! flag provided but not defined: -name

 ❯ waypoint runner profile list
Runner profiles
   NAME  | PLUGIN TYPE |            OCI URL            | TARGET RUNNER | DEFAULT
---------+-------------+-------------------------------+---------------+----------
  docker | docker      | hashicorp/waypoint-odr:latest | *             | yes
  docker | docker      | hashicorp/waypoint-odr:latest | *             | yes
```

* Waypoint CLI Version: upcoming release

**Comment by tharun208** [comment]
@krantzinator I am new to waypoint and I like to contribute to this

**Comment by briancain** [comment]
We should update the dbstate package to accept name on delete. We can have it index on a profile name and do the lookup that way, and return an error if there are two or more profiles by the same name and ask the user to specify `id` instead.
