### ISSUE TITLE
Waypoint runner uninstallation should remove unused runner profiles

### ISSUE THREAD

**Issue by demophoon** [hashicorp/waypoint#3495]
**Is your feature request related to a problem? Please describe.**
When uninstalling a runner, the runner profile which is associated with that runner is left behind. This can leave your `waypoint runner profile list` filled with a bunch of no longer used runner profiles with no way to clean them up.

**Describe the solution you'd like**
Either a way to show what runner profiles are inactive and can be safely deleted or have that process handled for you automatically during runner uninstallation.

**Describe alternatives you've considered**
Deleting runner profiles is brand new so not much outside of letting the unused profiles languish.

**Explain any additional use-cases**
This can crop up over time with regular waypoint server upgrades as each waypoint server upgrade creates its own runner profile for the upgraded runner. Note this particular case is addressed in #3490 but it would still be a nice to have to have uninstallation remove profiles so long as they are no longer in use as we set them up in the first place.

**Additional context**
Thanks to #3474 and the work in #3335 it looks like the features are in place to enable this work to be done, this issue is for finding the edge cases for runners like if a profile is being used by multiple runners, how can we detect that in order to ensure that a runner profile pruning doesn't wreck a users environment.

**Comment by demophoon** [comment]
This ends up being a little bit more complicated than it originally sounds because we currently do not have any way of determining what runner profiles are actively in use by other runners.

We are actively thinking about how runners work and may revisit this issue in the future. For now runner profiles will need to be removed manually with `waypoint runner profile delete`.

**Comment by krantzinator** [comment]
Per Slack convo, we could also consider including a `delete-profile` flag with the `uninstall` command, so that user can indicate "yes the matched profile only belongs to this one runner, delete that also as part of the uninstall."

**Comment by krantzinator** [comment]
As an FYI, the specific error path I hit on this case is as follows, when I delete the only runner a profile is assigned to, I am unable to remove the profile:
```
❯ waypoint runner uninstall -id=01GCCR39V8YHA08YS9FFFGCJY0 -platform=kubernetes
✓ Runner "01GCCR39V8YHA08YS9FFFGCJY0" uninstalled successfully
✓ Runner "01GCCR39V8YHA08YS9FFFGCJY0" forgotten on server
✓ Runner "01GCCR39V8YHA08YS9FFFGCJY0" uninstalled
✓ Persistent volume claims cleaned up

❯ waypoint runner profile list
Runner profiles
                  NAME                  | PLUGIN TYPE |                OCI URL                 |       TARGET RUNNER        | DEFAULT
----------------------------------------+-------------+----------------------------------------+----------------------------+----------
  01GCCR0DJQ41KCSG9YRBQERER9            | kubernetes  | docker.io/hashicorp/waypoint-odr:0.9.1 | *                          | yes
  kubernetes-bootstrap-profile          | kubernetes  | hashicorp/waypoint-odr:latest          | *                          | yes
  kubernetes-01GCCR39V8YHA08YS9FFFGCJY0 | kubernetes  | hashicorp/waypoint-odr:latest          | 01GCCR39V8YHA08YS9FFFGCJY0 |


❯ waypoint runner profile delete kubernetes-01GCCR39V8YHA08YS9FFFGCJY0
! object missing primary index
```

**Comment by krantzinator** [comment]
We are not going to do this right now
