### ISSUE TITLE
ECS upgrades fail on runner install

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#3527]
**Describe the bug**
Per debugging by the Waypoint team, we have hit the below issue on attempting to upgrade from the 0.8.1 install:
```
:x: Installing runner...
:x: Creating IAM role:
! Error installing the runner: InvalidParameter: 1 validation error(s) found.
  - minimum field size of 1, CreateRoleInput.RoleName.
```

**Steps to Reproduce**
See Slack for additional context.

**Expected behavior**
ECS server installs could upgrade using `waypoint upgrade`

**Comment by catsby** [comment]
This should be resolved in #3564
