### ISSUE TITLE
General feedback and all bugs found during deployment of 8 microservices on AWS EKS and usage during past couple of months

### ISSUE THREAD

**Issue by rastakajakwanna** [hashicorp/waypoint#3551]
**Is your feature request related to a problem? Please describe.**
Yes, please see "Additional context".

**Describe the solution you'd like**
Evaluate the feedback and implement fixes in the future releases.

**Describe alternatives you've considered**
none

**Explain any additional use-cases**
See additional context

**Additional context**
Here is my experience with the HCP Waypoint on two projects with 8 micro services deployed on AWS EKS cluster during a past couple of months.
Waypoint v0.7 and v0.8 (v0.9 not tested yet).

1. `waypoint fmt` always shows changes in files while the exit code is `0` (#3816). Also unlike in the other HCP products argument `check` is missing - we usually use it in pipelines during code validation phase after push in order to keep the code formatting in line. (edit by @krantzinator: #3817)
```
[15:01:51](main) ~/git/XY $ waypoint fmt
waypoint.hcl

[15:02:35](main) ~/git/XY $ waypoint fmt
waypoint.hcl

[15:02:38](main) ~/git/XY $ waypoint version
CLI: v0.8.2 (5b8885480)
Server: v0.8.2
```
2. (edit by @krantzinator: fixed in 0.9+) Helm install fails to bootstrap waypoint if PV exists (Waypoint is already bootstrapped), manual clean is required
3. (edit by @krantzinator: fixed in 0.9+) Waypoint install does not deploy K8S cluster SA which limits the application deployment to the default namespace only (or the same ns as waypoint), manual deployment of the cluster SA resources is necessary when using custom ns for applications. Also try to find this information in your documentation or repositories. Cluster SA resources yaml is located in the one of your demo repositories only and not in the repositories where one would expect it. If I remember well, Helm is also missing cluster SA, but I am not 100% sure now.
UPDATE: I am sure now. I have another project and fresh deployment to EKS using the latest Helm and I had to help myself out and deploy the clusterRoleBinding so that Waypoint can manage other resources. This is not the best security practice but I need something working first.
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: waypoint-runner-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: waypoint-runner-odr
  namespace: waypoint
```
5. waypoint restore from backup restores also tokens which means that default runner stops working immediately and needs to be reconfigured (deleted and added with the new invite token), also local config file needs a backup, otherwise it is rewritten with the new waypoint installation and then you do not have the previous token when you restore from backup and which results in losing access to the waypoint server completely. I somehow found reconfiguring all repositories and executing ~15 commands faster than trying to recover all failing parts after restoration from backup. (edit by @krantzinator: #3818)
6. application created in project by mistake cannot be deleted, same for project, runner profile and many other resources, delete api is mostly missing (edit by @krantzinator: will be fixed in 0.10, see PR in comments)
7. runner Kubernetes tasks are not deleted automatically, `kubectl -n waypoint get pods` shows thousands of finished tasks (edit by @krantzinator: fixed in 0.9+)
8. variables - dynamically sourced variables must be only string! I was trying to configure a map for database credentials under one variable. Now I have to use separate variables for user name and password. (edit by @krantzinator: #3819)
9. Docker pull plugin cannot pull from ECR due to missing/unsupported credentials type (edit by @krantzinator: #3821)
10. conditionals missing for certain configuration parts and must be workarounded using empty variables - for example K8S ingress deployment in PR/MR. Yes, there is an advanced configuration option with environments, but simple boolean would be sometimes better for newbies :) Using the variable option now `host = "my-app${var.endpoint_url_suffix}.my.domain"` where the url suffix is empty variable on stable releases.
11. TF Cloud source plugin is unpredictable and I failed to used it due to some weird error about variable which has to be unset first (edit by @krantzinator: tracked in https://github.com/hashicorp/waypoint/issues/3675)
12. K8S environment variable from secret should be represented in the applied deployment resource as a reference to the secret and not as the exact value from the secret. I could not find a way how to refer to the secret in env. vars directly instead of using dynamic variable and then referring the var. value using native Waypoint syntax, see below. (edit by @krantzinator: #3823)
```
variable "postgres_admin_name" {
  default = dynamic("kubernetes", {
    name      = "rds-schema-credentials"
    namespace = "app-ns"
    key       = "admin_user"
    secret    = true
  })
  type        = string
  sensitive   = true
  description = "postgres admin username"
}
deploy {
    use "kubernetes" {
      static_environment = {
        DB_USERNAME    = var.postgres_admin_name # results in the explicit value, not a reference to dynamic source. Is there a way to set a reference to a k8s resource?
}
```
13. git repository configuration which would allow dynamic branch configuration and git secrets sourcing from environment variables or secrets managers would improve the experience with Waypoint significantly. Now I have to keep the cli commands somewhere safe in case I would need to recover Waypoint from failure. (edit by @krantzinator: see https://registry.terraform.io/providers/hashicorp-dev-advocates/waypoint/0.3.0 to manage this)
14. How do I list Waypoint workspace resources from foreign contexts? Like a root user overview? There is a pipeline user which uses different workspaces during PR/MR deployments as suggested in the Waypoint docs. I wanted to check that context but I was unable to find an easy way to switch to that context and list all workspaces and its resources used by that foreign context.
15. urls generated using auto_hostname  are not being deleted when workspace is destroyed or when new deployment succeeds and there is a new url generated for it, there has to be another extra pipeline step in order to delete them (edit by @krantzinator: #3824)
```
WHOSTS=`waypoint hostname list -plain -workspace=$CI_COMMIT_REF_SLUG | tail -n +3 | awk '{print $1}'`
for hostname in ${WHOSTS}; do waypoint hostname delete ${hostname}; done
```
16. heroku auto-magic does not really produce production-like containers. Is there any way how to improve it besides using custom Dockerfile?

Overall, I really like Waypoint! It is an excellent choice and a silver bullet solution for certain projects and it is incredible what it can do with only few configuration lines. But the issues listed above made me struggling sometimes more than I would be willing to accept if I would know about them earlier. Especially the missing delete api's are really frustrating and I had to wipe out and reconfigure Waypoint many times before I was mostly satisfied with the result. Anyway, keep the good work and I hope that you will get some of the worst bugs resolved soon 😄

**Comment by briancain** [comment]
Hey there @rastakajakwanna ! Thanks so much for taking the time to gather all of this feedback and report it to us. We really appreciate you taking the time to try out Waypoint and write up your thoughts while using it.

If you can, please open these in separate issues/bug reports/enhancement requests. It will be very difficult to respond to any of this feedback in a single GitHub issue. I understand if you do not have time to do this, and if so, we're happy to take the feedback and split it out into their own issues. I see you already have done this with a few follow-up issues. But taking the content here and making them their own issues will help us keep track of everything and give proper responses to everything as well.

Thanks again!

**Comment by briancain** [comment]
@rastakajakwanna no worries, I understand. Thanks again for providing us with your feedback! We'll split them up as separate issues and eventually close this one once the rest is represented on GitHub.

**Comment by krantzinator** [comment]
For "2. Helm install fails to bootstrap waypoint if PV exists (Waypoint is already bootstrapped), manual clean is required" -- this is fixed in Waypoint 0.9. A `waypoint server uninstall` cleans up PVCs.

**Comment by krantzinator** [comment]
Fix for 6 will be released with our next major release. Keep an eye out for the 0.10 release. https://github.com/hashicorp/waypoint/pull/3626

**Comment by krantzinator** [comment]
7 should not be an issue. Try upgrading your version of Waypoint to 0.9 and if that is still an issue, please open a separate issue with more information.

**Comment by krantzinator** [comment]
Please open a separate issue for item 10. There is not enough information there for us to fully understand the depth of the problem.

**Comment by krantzinator** [comment]
For 14, please open a discussion post on [Discuss](https://discuss.hashicorp.com/c/waypoint/51)

**Comment by krantzinator** [comment]
I am not sure what you mean by 16. That sounds like a good discussion point for the Discuss forum mentioned previously.

**Comment by krantzinator** [comment]
For your last item in your comments, we need more information to accurately understand what your setup is. Please open a new issue with your waypoint.hcl file and a description of what you have tried so far.

>I found today another gap which I would probably need to workaround using kubernetes plugin apply (https://developer.hashicorp.com/waypoint/plugins/kubernetes#kubernetes-apply-platform ):
>I cannot find a way how to mount secret data as volume. I am trying to deploy NATS-io client app where the use of the nkey authentication requires the nkey to be put inside a file.

**Comment by krantzinator** [comment]
@rastakajakwanna I have opened issues for many of these, and left further comments regarding upgraded versions of Waypoint which would fix the issue, requests to post some of these on our Discuss board if this is still an issue for you, and also requests for you to open a couple of new issues with more information as I need to ask clarifying questions. Since asking questions about several different items in the same GitHub issue will quickly become confusing, I will close this issue.

Please continue to open new issues as you encounter hurdles. Thank you for your usage of Waypoint and providing this valuable feedback.
