### ISSUE TITLE
Release: Include 64-bit ARM Waypoint binary builds for Linux

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#3572]
**Is your feature request related to a problem? Please describe.**

Currently, for Waypoint binary builds on Linux, we do not yet support 64-bit versions of `waypoint` for `arm` architectures. We should include it.

On the [downloads page for linux](https://www.waypointproject.io/downloads), we do have an `arm` binary but it's 32-bit.

<img width="283" alt="Screen Shot 2022-07-12 at 1 57 25 PM" src="https://user-images.githubusercontent.com/810277/178594977-efa2f0f9-9ca6-4d8a-b568-9a19ef7e785b.png">

```
brian@ubuntu:scratch λ unzip waypoint_0.9.0_linux_arm.zip
Archive:  waypoint_0.9.0_linux_arm.zip
  inflating: waypoint
brian@ubuntu:scratch λ od -An -t x1 -j 4 -N 1 waypoint
 01
```

Where `01` refers to the byte that signifies this binary is a 32-bit build. (ref: https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header)

**Describe the solution you'd like**

In the next release, include a 64-bit version of Waypoint for `arm`.

**Describe alternatives you've considered**

Build the `waypoint` binary yourself off of a `release` branch or tag.

**Comment by star3am** [comment]
Thank you for opening this issue @briancain I'd be interested in this as well, thank you!

**Comment by briancain** [comment]
This happened with the 0.10.0 release!

waypointproject.io/downloads

**Comment by star3am** [comment]
@briancain man that is great news! Thank you Hashicorp for being such a cool company!
