### ISSUE TITLE
Improved health check interface for ECS plugin

### ISSUE THREAD

**Issue by DanielChalk** [hashicorp/waypoint#3600]
**Is your feature request related to a problem? Please describe.**

We have no control over the health checks of target groups within the ECS plugin

**Describe the solution you'd like**

We should be able to:

- Enable/disable health checks
- Set a path we want to use for a health check
- Set the response code the health check expects back from the path

**Describe alternatives you've considered**

- Not using the ECS plugin, and using something like a Kubernetes option
- Not using Waypoint

**Explain any additional use-cases**

I don't think this is an issue of use-case, is an issue of operational maturity. Health checks should not be this basic, hitting only a route URL of a deployment.

**Additional context**
None

**Comment by senortroll** [comment]
We've run into this as well, for now we work around it by hitting the AWS API with a script run by a post-deploy hook.  The script alters the health check to be the path and response that we want.  Not ideal, but gets the job done.

That being said, a native way to do this would be better in almost every way.

**Comment by m00lecule** [comment]
(+1)
