### ISSUE TITLE
Runner uninstall hangs w/o region specified

### ISSUE THREAD

**Issue by cicoyle** [hashicorp/waypoint#3681]
**Describe the bug**
Waypoint runner uninstall hangs infinitely and I cant cancel it if no region is specified.

```
$ waypoint runner uninstall -platform=ecs -id=054890e209a79dc64 
⠴ Uninstalling runner...
❌ Could not get list of ECS services
! Error uninstalling runner: MissingRegion: could not find region configuration^C^C^C^C^C


^C^C^C^C

```

Also, ran into the same err when region was specified. Looks like this is always a problem when the cluster does not exist.
```
$waypoint runner uninstall -platform=ecs -id=054890e209a79dc64 -ecs-region=us-west-2
⠇ Uninstalling runner...
❌ Could not get list of ECS services
! Error uninstalling runner: ClusterNotFoundException: 
```

**Expected behavior**
I would expect an err message saying to specify a region, rather than just hang.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
CLI: v0.9.1 (9562f453c)

**Comment by briancain** [comment]
For reference, this typically happens when output gets caught within a `StepGroup` that never properly calls done, abort or cancel on error.
