### ISSUE TITLE
`scratch_path` is not using tmpfs by default

### ISSUE THREAD

**Issue by denysvitali** [hashicorp/waypoint#3687]
**Describe the bug**

In [the documentation](https://developer.hashicorp.com/waypoint/plugins/kubernetes#kubernetes-platform) we describe the `scratch_path` option as (emphasis mine):
> A path for the service to store temporary data.
> 
> A path to a directory that will be created for the service to store temporary data **using tmpfs**.

The implementation doesn't really use tmpfs because, as stated in [`emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir):
> Depending on your environment, `emptyDir` volumes are stored on whatever medium that backs the node such as disk or SSD, or network storage. However, if you set the `emptyDir.medium` field to "Memory", Kubernetes mounts a tmpfs (RAM-backed filesystem) for you instead. While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write count against your container's memory limit.

Therefore, we should either correct the documentation to mention that our `scratch_path` is not using `tmpfs` by default.
Additionally, it would be interesting to add something like `scratch_tmpfs_path` so that we can cover this specific use case (mounting directories to tmpfs, and thus setting `emptyDir.medium: "Memory"`).

**Steps to Reproduce**

```hcl
app "xyz" {
  deploy {
        use "kubernetes" {
            scratch_path = [
               "/opt/example/not-tmpfs/
            ]  
        }
  }
}
```

```
$ k describe deployment xyz-v1
(...)
Volumes:
  scratch-0:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
(...)
```

**Expected behavior**
N/A

**Waypoint Platform Versions**
0.8.0

**Additional context**

Relevant snippet:
https://github.com/hashicorp/waypoint/blob/f9b5e91a9ab0e9798f7c88428e6d1c36ef589155/builtin/k8s/platform.go#L652-L664

**Comment by izaaklauer** [comment]
Good catch! We'll update our docs here to clarify our current usage of emptydir.

**Comment by krantzinator** [comment]
Fixed https://github.com/hashicorp/waypoint/pull/4129
