### ISSUE TITLE
Waypoint destroy command doesn't work for AWS ECS plugin

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/waypoint#369]
**Describe the bug**
The `waypoint destroy` command doesn't destroy the AWS ECS infrastructure creating when using the [aws-ecs](https://waypointproject.io/plugins/aws-ecs) plugin.

```bash
waypoint destroy
» Destroying releases...
» Destroying deployments...
! Error destroying: rpc error: code = Unknown desc = ValidationError: A target group ARN must be specified
  	status code: 400, request id: 644db8e1-1d17-42d7-9fb0-6363195f8e72
```

**Steps to Reproduce**
Run through the [ECS](https://github.com/hashicorp/waypoint-examples/tree/main/aws-ecs/nodejs) example in the hashicorp/waypoint-examples repo. Run `waypoint up` and then run `waypoint destroy` to clean the infrastructure.

The `waypoint.hcl` configuration file is as follows:

```hcl
project = "example-nodejs"

app "example-nodejs" {
  labels = {
    "service" = "example-nodejs",
    "env" = "dev"
  }

  build {
    use "pack" {}
    registry {
      use "aws-ecr" {
        region = "us-east-1"
        repository = "waypoint-example"
        tag = "latest"
      }
    }
  }

  deploy {
    use "aws-ecs" {
      region = "us-east-1"
      memory = "512"
    }
  }
}
```

**Expected behavior**
`waypoint destroy` command cleans the infrastructure created by Waypoint.

**Comment by eddiezane** [comment]
I ran into this and while attempting to script a clean up I noticed that the ECS service names and LB targets don't match up to the Waypoint deployments or releases. I actually can't find any references to the actual ECS services names anywhere inside Waypoint.

Is this intentional?
