### ISSUE TITLE
pipeline list lists pipelines for a different project

### ISSUE THREAD

**Issue by xiaolin-ninja** [hashicorp/waypoint#3791]
**Describe the bug**
```
❯ waypoint-dev status
Current project statuses in server context "127.0.0.1:9731"

PROJECT     	WORKSPACE	DEPLOYMENT STATUSES	RELEASE STATUSES 
example-java	default  	1 READY            	N/A             	
k8s-tetris  	default  	N/A                	N/A             	
```

```
❯ waypoint-dev pipeline list -project=k8s-tetris

» Waypoint Pipelines for k8s-tetris
              ID             | NAME |    OWNER     | CURRENT STEPS | LAST RUN STARTED | LAST RUN COMPLETED |  STATE  | TOTAL RUNS  
-----------------------------+------+--------------+---------------+------------------+--------------------+---------+-------------
  01GBBBC63TR5DYQXQVGJPS8JGZ | test | example-java |             2 | 3 hours ago      | 3 hours ago        | success |          2  
```

**Steps to Reproduce**
1. Make two projects.
2. `waypoint pipeline list -project=A`
3. Observe.

**Expected behavior**
`-project` flag should filter and only list pipelines for the specified project.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

**Comment by briancain** [comment]
Fixed via #3792 !
