### ISSUE TITLE
urls generated using auto_hostname are not being deleted when workspace is destroyed

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#3824]
From #3551 @rastakajakwanna:
>urls generated using auto_hostname are not being deleted when workspace is destroyed or when new deployment succeeds and there is a new url generated for it, there has to be another extra pipeline step in order to delete them
```
WHOSTS=`waypoint hostname list -plain -workspace=$CI_COMMIT_REF_SLUG | tail -n +3 | awk '{print $1}'`
for hostname in ${WHOSTS}; do waypoint hostname delete ${hostname}; done
```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.8.2
* Waypoint Server Platform and Version: 0.8.2 (like `docker`, `nomad`, `kubernetes`)

**Comment by briancain** [comment]
With the #3626 work, we will clean up horizon URLs associated with the project!

**Comment by rastakajakwanna** [comment]
Partially also relates to #3760
