### ISSUE TITLE
variable must be always set even for waypoint stages where not needed

### ISSUE THREAD

**Issue by rastakajakwanna** [hashicorp/waypoint#3834]
From #3551 , @krantzinator 
> Please open a separate issue for item 10. There is not enough information there for us to fully understand the depth of the problem.

> 10. conditionals missing for certain configuration parts and must be workarounded using empty variables - for example K8S ingress deployment in PR/MR. Yes, there is an advanced configuration option with environments, but simple boolean would be sometimes better for newbies :) Using the variable option now host = "my-app${var.endpoint_url_suffix}.my.domain" where the url suffix is empty variable on stable releases.

Let me first describe a different scenario.

When there is a dynamic variable declared  in the configuration, the value must be always resolvable using the specified plugin or somehow set (cli arg or vars file), that applies for:
* `waypoint build -local`
* `waypoint release` (we don't need legit values for deployment resource while deploying ingress or service resources, but values cannot be empty)
* `waypoint destroy` (nobody cares about the values, but values must be set anyway)

Why not `waypoint deploy` ? Because that is when the variables are actually resolved by the dynamic sourcer plugin and used by the deployment/releaser plugin. In other words, that is the only time when the variable value is actually needed and the value must be legit because it is somehow represented in the k8s deployment resource.
```
variable "nats_root_ca" {
  default = dynamic("kubernetes", {
    name      = "nats-io"
    namespace = "staging"
    key       = "ca.crt"
    secret    = true
  })
  type        = string
  sensitive   = true
  description = "nats.io ca crt"
}
```
Pipeline steps:
```
waypoint build -local -var-file=waypoint.local.wpvars
waypoint deploy # no need for dummy values as we need to get legit values
waypoint release -var-file=waypoint.local.wpvars
```
Content of the waypoint.local.wpvars
```
nats_root_ca         = "dummy"
```

However I meant something else in my first post and I had to think really hard to recall what I meant by that sentence. Sorry for that 😄 

I wanted to have the ingress deployed conditionally based on some variable. If it is a merge request, deploy ingress, otherwise not. I guess the conditional would be closer to a Terraform interpretation using count
```
release {
  count = var.ingress_host != "" ? 1 : 0
  host = var.ingress_host
}
```
I know there is a way how to achieve that, but when you try that, you hit #3759 😃

**Comment by briancain** [comment]
Hey there @rastakajakwanna - The kubernetes dynamic config sourcer should be resolving regardless of the kind of job operation. Do you have the runner job logs for those operations where the k8s dynamic config sourcer fails? That might give you some more information as to why it didn't work. Thank you!

**Comment by rastakajakwanna** [comment]
It is clear to me why it is happening in the build stage. That's due to a `-local` argument, it is actually described in the documentation.

Deploy stage is the stage where I need the values to be resolved, no problems there.

Release stage errors are unexpected because the job is executed on remote runner as expected. I will try to gather the logs and come back to you.

It will require more experimentation but I've seen sometimes errors also during `init` and `destroy`, but that's happening randomly.

**Comment by rastakajakwanna** [comment]
Cannot reproduce anymore, therefore closing.
