### ISSUE TITLE
Remote runner job listing

### ISSUE THREAD

**Issue by rastakajakwanna** [hashicorp/waypoint#3859]
**Is your feature request related to a problem? Please describe.**
I am unable to figure out what job on the associated remote runner is blocking the current operation due to inexistent `runner job` api.

The output basically looks like this:
```
» Deploying test-app...
» Operation is queued waiting for job "01GCRQHWE6QQXSPCV79Z4ZYENV". Waiting for runner assignment...
  If you interrupt this command, the job will still run in the background.
```
But the user is unable to see what is blocking the deployment which is waiting for runner assignment for several minutes already.

**Describe the solution you'd like**
Support for listing, inspecting and deleting jobs on remote runner exists.
Output should contain information about who executed the job, in what workspace, which app, build/deploy/release/destroy, status: paused/waiting, in progress, done, and all information and privileges necessary to debug and resolve hanging jobs.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by briancain** [comment]
Hey there @rastakajakwanna - Have you tried using the `waypoint job` CLI? All of this information would be there. We have flags to only show jobs assigned to the runner as well, and you can filter on job state which would show you what jobs are running and on which runner.

**Comment by rastakajakwanna** [comment]
Hey @briancain , apologies, I somehow completely overlooked this command exists 😃 

So, I tried now and I might have another bug report, unless I am overlooking something again...
```
waypoint status
Current status for project ...
# output works
waypoint job list
! grpc: received message larger than max (16727054 vs. 4194304)
# always shows this error
```
No jobs are pending now, could it be it? Or should I rather wait for another stuck job and come back later?

**Comment by briancain** [comment]
Hey @rastakajakwanna - Ah yes, that's an unfortunate bug. We don't yet support pagination, which is why you're hitting that issue. The data returned over grpc has a size limit and we hit it with enough jobs. We're tracking that issue here: https://github.com/hashicorp/waypoint/issues/3439
