### ISSUE TITLE
`! failed to create client: context deadline exceeded` as a generic error 

### ISSUE THREAD

**Issue by mjwhodur** [hashicorp/waypoint#4015]
**Describe the bug**
It came to my attention, that `context deadline exceeded` error is a generic message shown whenever unhandled errors arise. For example, I have a scenario where I have a self-signed certificate and forgot to issue `-server-tls-skip-verify` flag.

**Steps to Reproduce**
1. Set up a Waypoint instance
2. Do not set up any valid HTTPS certificate
3. Go to the UI and setup a connection:, i.e.: 
``` waypoint context create \
    -server-addr=192.168.0.140:9701 \
    -server-auth-token=<< omitted >> \
    -server-require-auth=true \
    -set-default 192.168.0.140-ui
```
4. 
``` 
michal.weglowskihodur@mhodur1m-war1 ~ % waypoint project list
! failed to create client: context deadline exceeded
michal.weglowskihodur@mhodur1m-war1 ~ %
```
5. When you correct the connection settings like that:
``` waypoint context create \
    -server-addr=192.168.0.140:9701 \
    -server-auth-token=<< omitted >> \
    -server-require-auth=true \
    -server-tls-skip-verify \
    -set-default 192.168.0.140-ui
```
and you issue any other command you would receive correct reply:
```
michal.weglowskihodur@mhodur1m-war1 ~ % waypoint context create \
    -server-addr=192.168.0.140:9701 \
    -server-auth-token=<<>> \
    -server-require-auth=true -server-tls-skip-verify \
    -set-default 192.168.0.140-ui
Context "192.168.0.140-ui" created.
michal.weglowskihodur@mhodur1m-war1 ~ % waypoint project list    
mojprojekt
nomad-nodejs
sonarpolityczny
michal.weglowskihodur@mhodur1m-war1 ~ % 
```

This error may be cumbersome for beginners and more verbose error like in Vault or other Hashicorp CLIs would be easier to understand.

**Please include any `waypoint.hcl` files if applicable, as well as a
[GitHub Gist](https://gist.github.com/) of any relevant logs or steps to
reproduce the bug. Running `waypoint` commands with `-v` up to `-vvv` will
include any additional debugging info in the log.**

**Expected behavior**
The errors should be more informative. Would help to diagnose what went wrong.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.10.2
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`): nomad and kubernetes
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`) n/a

**Additional context**
GoLang's context do not carry any relevant message - `context deadline exceeded` is too broad error.

**Comment by evanphx** [comment]
The quick fix here is, when we timeout trying to dial the grpc server, check to see if there is a recent grpc connection error created (or heck, just see if we managed to connect at all). If we had an underlying error OR we never connected, report a special error that the connection wasn't able to be made rather than the deadline error.

**Comment by evanphx** [comment]
https://github.com/hashicorp/waypoint/blob/c50b92c705b4dad0b65968322bfb0962f487a681/pkg/serverclient/client.go#L196 can be changed to rather than returning the error from DialContext directly, it should see if the returned error is a context.Timeout, and if so, report a specific error about inability to connect to the server.

**Comment by izaaklauer** [comment]
We can probably also add that to the CEB client creation:

https://github.com/hashicorp/waypoint/blob/main/internal/ceb/server.go#L114 https://github.com/hashicorp/waypoint/blob/main/internal/ceb/server.go#L192
