### ISSUE TITLE
CLI/UX: Deprecate Table view in favor of Simple Table

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#4036]
**Is your feature request related to a problem? Please describe.**

With certain `list` commands, the table renderer ends up overflowing and making it difficult to read the information inside the table. The border of the table we show ends up overflowing too. Longer list commands like `waypoint job list` end up always overflowing without a large space to render all of the columns.

**Describe the solution you'd like**

Standardize the CLI to use the `Simple` style table renderer that `waypoint status` introduced.

We could either make the Simple view the default renderer so any future table renderers we add to the CLI use the same format, or stick with explicitly requesting `terminal.WithStyle("Simple")` for now on a case-by-case basis.

**Describe alternatives you've considered**

Fix table rendering to fit within small terminal buffer sizes

**Comment by evanphx** [comment]
Let's see if we can do some column wrapping or something!

**Comment by briancain** [comment]
Yep - the fix was even easier. We can enable the autowrap property for tablewriter and it solves it completely!
