### ISSUE TITLE
Pod unable to access Docker image

### ISSUE THREAD

**Issue by starlightromero** [hashicorp/waypoint#4049]
**Describe the bug**

Unable to successfully run `waypoint up` on a waypoint example. 

**Steps to Reproduce**

Clone code from [https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/go](https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/go)
 
Run `waypoint init`

Run `waypoint up`

Receive error message:
```
» Deploying go-k8s...
✓ Running deploy v5
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Creating deployment...
✓ Expected "http" port "3000" for app "go-k8s-v5"
❌ error
✓ Kubernetes client connected to https://kubernetes.docker.internal:6443 with namespace default
✓ Deployment deleted
Detected pods having an issue starting - Pod unable to access Docker image: rpc error: code = Unknown desc = Error response from daemon: Get "https://waypoint.local/v2/": Failed to
lookup host: waypoint.local
The following is events for pods observed while attempting to start the Deployment

» Events for go-k8s-v5-9c8769c86-52645
  Warning: Failed to pull image "waypoint.local/go-k8s:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://waypoint.local/v2/": Failed to lookup
host: waypoint.local (Failed)
  Warning: Error: ErrImagePull (Failed)
  Warning: Error: ImagePullBackOff (Failed)
! Deployment was not able to start pods after 5m10s
2022-10-12T19:56:37.191-0700 [TRACE] waypoint: stopping signal listeners and cancelling the context
```

**Expected behavior**

Waypoint application is up and running

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.10.2 (2c9926ef8)

**Comment by briancain** [comment]
Hey there @starlightromero - I will direct you to this error message from the output you shared:

> Warning: Failed to pull image "waypoint.local/go-k8s:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://waypoint.local/v2/": Failed to lookup
host: waypoint.local 

This means your kubernetes cluster cannot access your container registry from the host `waypoint.local`. You need to give network access to whereever your container registry is so that Kubernetes can pull the image, assuming you have a container registry routable at `waypoint.local`?

**Comment by starlightromero** [comment]
I have a local image:

```
docker images                                                                                                                                                                                                                
REPOSITORY                                                TAG                                                                          IMAGE ID       CREATED         SIZE
waypoint.local/go-k8s                                     latest                                                                       7b59eb490a02   21 hours ago    112MB
```

Is it possible for the deploy stage to use a local image or does the image need to come from a container registry?

**Comment by briancain** [comment]
@starlightromero - the error you got is actually coming from Kubernetes, not Waypoint! Are you using docker desktop maybe? I know it has a local docker-shim that gives access to the docker image registry. Otherwise, `waypoint.local` won't be resolvable by a kubernetes cluster because there's no route to that host.

**Comment by starlightromero** [comment]
Yep! That was the problem! I ended up switching up anyways to use a remote container registry. Thanks
