### ISSUE TITLE
Kaniko: docker-pull fails to authenticate to container registry to pull container artifact

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#4055]
**Describe the bug**

Attempting to use the `docker-pull` plugin with on-demand runners, which uses Kaniko to pull containers, ends up failing to authenticate to the container registry despite being configured with a username and password via Waypoint:

```hcl
app "tetris" {
  build {
    use "docker" {
    }
    workspace "production" {
      use "docker-pull" {
        image = var.image
        tag   = var.tag
        encoded_auth = base64encode(
          jsonencode({
            username = var.registry_username,
            password = var.registry_password
          })
        )
      }
    }
    registry {
      use "docker" {
        image    = var.image
        tag      = var.tag
        username = var.registry_username
        password = var.registry_password
        local    = var.registry_local
      }
    }
  }
...
...
```

Note that `var.registry_username` and `var.registry_password` are the same input variables used to _push_ the container to that same registry, so I know at least internally those vars are set.

```
✓ Running build v3
✓ Injecting entrypoint...
⠹ Executing Kaniko...
 │ INFO[0000] Retrieving image manifest <registry>/tetris:latest
 │ INFO[0000] Retrieving image <registry>/tetris:latest from registry <registry>
 │ error building image: GET https://<registry>/token?scope=repository%3Atetris%3Ap
 │ ull&service=<registry>: : Authentication is required
! 1 error occurred:
        * rpc error: code = Unknown desc = exit status 1

```

**Steps to Reproduce**

Attempt to run a docker-pull plugin for a build step using on-demand runners via Kaniko.

**Expected behavior**

Kaniko should have the proper credentials setup to pull a container from the specified registry.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.10.2
* Waypoint Server Platform and Version: n/a
* Waypoint Plugin: `docker-pull` with `kaniko`

**Additional context**

There are some closely related issues but they don't 100% line up with this one:

- https://github.com/hashicorp/waypoint/issues/4001
- https://github.com/hashicorp/waypoint/issues/3557

**Comment by catsby** [comment]
Hopefully fixed in https://github.com/hashicorp/waypoint/pull/4121 🤞
