### ISSUE TITLE
Test Flakes: TestImpl/pipeline_run/TestPipelineRun/Put_and_Get

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#4106]
**Describe the bug**

This test seems to fail often enough we should investigate and fix why it's flaking.

```
Failed
=== RUN   TestImpl/pipeline_run/TestPipelineRun/Put_and_Get
    test_pipeline_run.go:64: 
        	Error Trace:	test_pipeline_run.go:64
        	Error:      	Received unexpected error:
        	            	rpc error: code = NotFound desc = pipeline run v"1" could not be found for pipeline Id: "test"
        	Test:       	TestImpl/pipeline_run/TestPipelineRun/Put_and_Get
            --- FAIL: TestImpl/pipeline_run/TestPipelineRun/Put_and_Get (0.00s)
```

**Steps to Reproduce**

See it occasionally flake on circle-ci `go-tests`

**Expected behavior**

It should always pass.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

**Comment by xiaolin-ninja** [comment]
Oof I thought fixing the job list ordering fixed this test? :(

**Comment by briancain** [comment]
Ok woot, they passed after those backports! I'll close this then.
