### ISSUE TITLE
Are variables not supported in Waypoint Pipelines?

### ISSUE THREAD

**Issue by voycey** [hashicorp/waypoint#4122]
We have about 5 microservices that I am trying to bring variables across from our Terraform deployment into, I am trying to create a pipeline that fetches the necessary information from Vault and insert it into the container. However there doesn't seem to be any way to interpolate variables into the exec command? There is no documentation showing this behaviour either.

```hcl
variable "stage" {}
variable "app_name" {}
variable "gcp_project_id" {}
variable "git_sha" {}
variable "gcp_service_account" {}
variable "vault_addr" {}
variable "vault_token" {}
variable "vault_namespace" {}

project = "tymlez-platform"

pipeline "full-up" {

  step "tymlez-config" {
    use "exec" {
      command = "curl"
      args    = ["--header \"X-Vault-Token :",var.vault_token,"\"",var.vault_addr,"/v1/kvv2/",var.app_name,"/",var.stage,"/all-app-variables", "jq -r .data.data > /tmp/variables.json"]
    }
  }
...
```

**Expected behavior**
Variables should be able to be included anywhere in a HCL file

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

CLI: v0.10.2 (2c9926ef8)
Server: v0.10.2

**Comment by briancain** [comment]
Hey there @voycey ! Yes, this is a current known limitation of the pipelines feature in tech preview! It's the next feature task on my list of things to implement, so this will be supported soon!

**Comment by voycey** [comment]
Hi @briancain - thanks just wanted to make sure it wasn't me missing something!
