### ISSUE TITLE
How to set credentials for dynamic external data for Vault?

### ISSUE THREAD

**Issue by voycey** [hashicorp/waypoint#4123]
The documentation here is confusing and incomplete:

https://developer.hashicorp.com/waypoint/plugins/vault#source-parameters

> The parameters below are used with waypoint config source-set to configure the behavior this plugin. **These are not used in dynamic calls**. The parameters used for dynamic are in the previous section.

There is no information about the parameters used for dynamic - I have tried environment variables but to no avail.

Can some documentation be added that explains how to authenticate against Vault for external data?

**Comment by briancain** [comment]
Hey there @voycey - you might of missed it, but the docs that you shared in that quote mention where the dynamic parameters are:

> These are not used in dynamic calls. The parameters used for dynamic are in the previous section.

https://developer.hashicorp.com/waypoint/plugins/vault#required-parameters

**Comment by voycey** [comment]
Thanks @briancain! Totally did miss it!
