### ISSUE TITLE
Waypoint deploy to Kubernetes always fails with timeout on GKE Autopilot - can we increase the timeout for deploy?

### ISSUE THREAD

**Issue by voycey** [hashicorp/waypoint#4125]
GKE Autopilot often takes a while to "increase the node size" on an autopilot cluster, even a simple pod is taking longer than the default 5 minutes timeout. It fails with:

> Deployment was not able to start pods after 5m10S

I cant see anything in the documentation on how to increase this timeout to account for this longer wait time?

**Comment by evanphx** [comment]
Hi @voycey,

You can control how long Waypoint waits for the start by changing the probe configuration: https://developer.hashicorp.com/waypoint/plugins/kubernetes#probe-category.

Those values are fed to an equation that governs how long Waypoint will wait, available here for you to see: https://github.com/hashicorp/waypoint/blob/main/builtin/k8s/platform.go#L837-L854
