### ISSUE TITLE
Environment file fails when written using file() via config stanza?

### ISSUE THREAD

**Issue by voycey** [hashicorp/waypoint#4135]
When trying to write a file containing environment variables (standard .env format) via the config stanza I am getting the following error:

```
**2022-10-31T01:07:16.648Z [ERROR] entrypoint.config.watcher.watchloop: error evaluating expression: 
var=.env error=".env:1,15-19: Variables not allowed; Variables may not be used here."**
```

Is waypoint trying to parse this file for some reason? It shouldn't care what the contents of that file are surely?

Code I am using is:

```hcl
app "tymlez-middleware" {
  config {
    file = {
      ".env" = file("${path.cwd}/.env")
    }
  }
...
```

Also tried in case serializing it helps (no luck):

```hcl
app "tymlez-middleware" {
  config {
    file = {
      ".env" = filebase64("${path.cwd}/.env_b64")
    }
  }
...
```

**Comment by evanphx** [comment]
This is the same issue as #4148.
