### ISSUE TITLE
Add support for optional input variables

### ISSUE THREAD

**Issue by ddaws** [hashicorp/waypoint#4149]
### Is your feature request related to a problem?

I would like to be able to pass optional variables. In Terraform this can be accomplished by setting `default = null` in the variable definition and allows the author to conditionally enable features, source values from different places falling back if the input variable is null, and a host of use cases.

For reference, see the discussion here: https://github.com/hashicorp/waypoint/pull/4067

### Describe the solution you'd like

In Terraform optional values are supported by specifying defaults, and optional omittable values are specified by setting `default = null`. This works because in Terraform variables support the property `nullable` where `nullable` is true by default. This means that any variable can be set to null by default, and setting the default value for a variable to null effectively makes the value optional.

https://developer.hashicorp.com/terraform/language/values/variables#default-values

For example, for some variable my_api_key

```hcl
variable "my_api_key" {
  type = string
}
```

Valid values for this var are a string or null because nullable is true by default, but the value must be specified. If you also set the default value to null then the variable is nullable and defaults to null, so it is effectively optional. For example

```hcl
variable "my_api_key" {
  type    = string
  default = null
}
```

**Nullability is weird though**, and allowing values to be null by default may mean introducing null checks into existing Waypoint code. Some approaches to address this could include introducing `nullable` to Waypoint variable definitions but setting `nullable = false` by default. This would allow optional variables to specified as 

```hcl
variable "my_api_key" {
  type      = string
  nullable  = true
  default   = null
}
```

To simplify this a `required` property could also be introduced, where `required = true` is equivalent to `nullable = true` and `default = null`. For example, our previous variable definition would simplify to 

```hcl
variable "my_api_key" {
  type     = string
  required = true
}
```

### Describe alternatives you've considered 

I think the current alternative is to pass a flag value, like an empty string in the case of `type = string`. This adds noise because it means that values will need to be checked for flag values to indicate omission, but the flag values are going to be different depending on how the variable is used. An empty string may still be a valid value for an optional variable.

### Explain any additional use-cases

- Optionally enable debug mode
- Optionally pass API keys to a third party Telemetry service
- ...

### Additional context

See the discussion here: https://github.com/hashicorp/waypoint/pull/4067

**Comment by evanphx** [comment]
Hi @ddaws,

I followed along in the other PR and I can reassure you that if you pass a value to an input variable that contained a dynamic default, the dynamic value will NOT be fetched.

As for the ability to have optional/nullable input variable, we don't plan to add that functionality because it causes many more issues for users accidentally referencing values that aren't set.

If a user needs to use conditionally check a variable (ala with coalesce), a ternary can be used instead.

**Comment by ddaws** [comment]
@evanphx you can check via a ternary but this means needing to set flag values for variables that the developer wants to be optional. For example, if I want to optionally pass a value I need to do something like 

```hcl
variable "my_api_key" {
  type    = string
  default = "-1" # My flag value
}
```

Then later check for the flag value like `var.my_api_key == "-1" ? ...`. That's fine, but flag values are arbitrary and change depending on the type of data being passed. 

Nullability introduces it's own weirdness but why not support nullability with `nullable = false` as the default, so variables not nullable by default (as opposed to being nullable by default like they are in Terraform)? This would let people opt into the functionality without introducing the potential for errors in existing code.

**Comment by evanphx** [comment]
@ddaws If a variable set to null is used, what do you feel the logic should be? Should it transparently become an empty string? Fail the operation when encountered?

**Comment by ddaws** [comment]
If a variable is null it should fail the operation similar to the way it's handled in Terraform. Ideally this can be known in advance (before starting a deployment) by parsing the waypoint.hcl, reading in variables, and then evaluating the AST for any usage of null values in operations that don't support null values.

Nullability / optionality should be something that can be opted into, but if a user opts into using a nullable value then 
> With great power comes great responsibility
