### ISSUE TITLE
docs: add Runner section to Fundamentals splash page

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#4155]
If you visit https://developer.hashicorp.com/waypoint/docs, you see that we have `Quick Start`, `App Lifecycle`, `Projects`, and `waypoint.hcl` summaries for new Waypoint users. This should also include a `Runners` summary as that is an intrinsic part of running Waypoint.

**Comment by xiaolin-ninja** [comment]
PR: https://github.com/hashicorp/dev-portal/pull/1424
