### ISSUE TITLE
waypoint pipeline list panics CLI

### ISSUE THREAD

**Issue by pandom** [hashicorp/waypoint#4195]
**Describe the bug**
Stacktrace when issuing waypoint pipeline list on empty pipelines.

**Steps to Reproduce**
Selecting a HCP or Self-Hosted server context run `waypoint pipeline list`

```
➜  nodejs git:(main) ✗ waypoint pipeline list

» Waypoint Pipelines for nomad-nodejs
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hashicorp/waypoint/internal/cli.(*PipelineListCommand).Run(0x140009594e0, {0x14000c428f0?, 0x16?, 0xffffffffffffffff?})
	/private/tmp/waypoint-20221103-1557-tl8hfu/waypoint-0.10.3/internal/cli/pipeline_list.go:118 +0xc94
github.com/mitchellh/cli.(*CLI).Run(0x1400025e000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x4a8
github.com/hashicorp/waypoint/internal/cli.Main({0x14000114090?, 0x10216f46c?, 0x104e2ab60?})
	/private/tmp/waypoint-20221103-1557-tl8hfu/waypoint-0.10.3/internal/cli/main.go:127 +0x510
main.main()
	/private/tmp/waypoint-20221103-1557-tl8hfu/waypoint-0.10.3/cmd/waypoint/main.go:14 +0xa8
```

**Expected behavior**
Return an empty list of pipelines

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.10.3
* Waypoint Server Platform and Version: nomad
* Waypoint Plugin: pack

**Additional context**
As discussed on Slack.

**Comment by briancain** [comment]
Hey @pandom - thanks for reporting this issue!

I think there's a couple of fixes for this: We should fix the panic in the CLI to make sure a PipelineRun has a list of jobs before accessing it in the job slice.

Then we should also make sure that the HCP Waypoint server doesn't return any pipelines or pipeline runs if there aren't actually any in the database. It might be returning an empty message without any fields set, which is how I think we reached this part of the CLI.

**Comment by cicoyle** [comment]
This also happens on `waypoint pipeline inspect -name=<name>`

**Comment by briancain** [comment]
https://github.com/hashicorp/waypoint/blob/0dd26e99498f9fb2cdefacc0e07e7585e996b1d7/internal/cli/pipeline_list.go#L116-L119

https://github.com/hashicorp/waypoint/blob/0dd26e99498f9fb2cdefacc0e07e7585e996b1d7/internal/cli/pipeline_inspect.go#L198-L200

We can fix this on the CLI by ensuring we don't attempt to access the jobs slice if it's nil.

Then on the HCP side (and should confirm on the self-managed side here) that we're properly populating the jobs slice for pipeline runs!
