### ISSUE TITLE
Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter

### ISSUE THREAD

**Issue by marcgweg** [hashicorp/waypoint#4335]
**Describe the bug**
Referring to issue #3376. I have a 3 nodes Raspberry PI cluster with Consul/Nomad. And the waypoint deploy gives the same error nowadays.

» Deploying calibre...

» Performing operation locally
✓ Running deploy v4
✓ Deleting job: calibre
✓ Job registration successful
✓ Evaluation status changed: "pending" -> "complete"
⚠️ Evaluation "21d5e8ee-edaa-790e-1baa-1294574c5dfa" finished with status "complete" but failed to place all allocations
⚠️ Task Group "calibre" (failed to place 1 allocation):
* Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter * Resources exhausted on 1 nodes * Dimension "memory" exhausted on 1 nodes
⚠️ Evaluation "12f72bc0-4575-0cd6-c73e-bf0fe245f01b" waiting for additional capacity to place remainder
! Failed to schedule all allocations

**Steps to Reproduce**
Steps to reproduce the behavior.

Please include any `waypoint.hcl` files if applicable, as well as a
[GitHub Gist](https://gist.github.com/) of any relevant logs or steps to
reproduce the bug. Running `waypoint` commands with `-v` up to `-vvv` will
include any additional debugging info in the log.

Image built: waypoint.local/calibre:latest (arm64)
✓ Running push build v3
✓ Tagging Docker image: waypoint.local/calibre:latest => calibre:1.0.4
✓ Docker image pushed: calibre:1.0.4

» Deploying calibre...
✓ Running deploy v5
✓ Deleting job: calibre
✓ Job registration successful
✓ Evaluation status changed: "pending" -> "complete"
⚠️ Evaluation "01256bf5-27f7-65be-4de2-7c9f2b2bda4d" finished with status "complete" but failed to place all allocations
⚠️ Task Group "calibre" (failed to place 1 allocation):
  * Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter  * Resources exhausted on 1 nodes  * Dimension "memory" exhausted on 1
nodes
⚠️ Evaluation "ea7e9639-e025-13bd-fb44-041faa6fcb44" waiting for additional capacity to place remainder
! Failed to schedule all allocations
2022-12-15T13:13:52.002+0100 [TRACE] waypoint: stopping signal listeners and cancelling the context

**Expected behavior**
A deployed application as was before (version !?)

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.10.1 (830e74dd0)
* Waypoint Server Platform and Version: nomad v0.10.4
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**
Consul: v1.14.2 Revision 0ba7a401
Nomad: v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

**Comment by marcgweg** [comment]
Ok, changed the following:
      resources {
        cpu    = 200
        memory = 80
      }

to:
      resources {
        cpu    = 100
        memory = 40
      }

and now it works. Strangely, the previous settings worked just fine in all earlier releases...  I guess it's the memory in this one.

Just checked, set cpu back to 200 no problem.

**Comment by evanphx** [comment]
Hi @marcgweg,

Thanks for the output. Looking at it, we're pretty sure the problem is stated by the output:

```
  Constraint "${attr.consul.version} semver >= 1.7.0": 1 nodes excluded by filter
* Resources exhausted on 1 nodes
* Dimension "memory" exhausted on 1 nodes
```

So basically nomad is saying your Raspberry Pi doesn't have the ram that your job is requesting. You basically figured that out when you changed things, but we wanted to close the loop!

Happy deploying!
