### ISSUE TITLE
Server install to Nomad+Consul fails with context canceled error

### ISSUE THREAD

**Issue by jhillyerd** [hashicorp/waypoint#4358]
**Describe the bug**

Install to Nomad fails first time with:

```
❌ Connecting to: waypoint-ui.service.skynet.consul:9702
❌ Failed to connect to Waypoint server after max retry attempts of 12
! Error connecting to server: error connecting to server: context canceled
A clear and concise description of what the bug is.
```

Inspecting nomad; the waypoint-server job is installed, starts fine, but is never bootstrapped.

Running the same `waypoint install` command (below) a second time causes the install to complete successfully, and I am able to generate a token from the CLI and login.

```
⚠️ Detected existing Waypoint server
✓ Configured server connection
✓ Successfully connected to Waypoint server in Nomad!
✓ Server installed and configured!
Waypoint server successfully installed and configured!
```

Is the installer caching a failed consul DNS lookup or similar?

**Steps to Reproduce**

```
waypoint install -platform=nomad -accept-tos \
        -nomad-host=https://nomad.service.consul:4646 \
        -nomad-host-volume=waypoint-server-data \
        -nomad-runner-host-volume=waypoint-runner-data \
        -nomad-dc=skynet -nomad-consul-datacenter=skynet \
        -runner=false
```

Running the initial install with -v through -vvv does not appear to give any more detail on why it is unable to connect to the UI server.

While the server install process is in the middle of it's retries:

```
⠏ Connecting to: waypoint-ui.service.skynet.consul:9702    
⚠️ Retry connecting to server ... 4/12 retries: error connecting to server: context deadline exceeded
```

I am able to curl the ui service just fine from the same machine:

```
> curl -ks https://waypoint-ui.service.skynet.consul:9702/ |head
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Waypoint</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
```

**Expected behavior**
Success install in one step

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.10.5
* Waypoint Server Platform and Version: nomad 1.3.7
* Waypoint Plugin: N/A

**Additional context**

**Comment by evanphx** [comment]
Hi @jhillyerd,

Looks like you've found a bug! We'll get on fixing that. The only work around we have for now is what you've already done or writing your own nomad jobspec and not using `waypoint install`. We'll work on getting a fix for this in the next release.

(The bug is found here, https://github.com/hashicorp/waypoint/blob/6dfb969da7da89ded1228792e7d7942d95fa665e/internal/serverinstall/nomad.go#L287-L331, the branch for consul is returning the addresses for the endpoints in the wrong order)
