### ISSUE TITLE
Docs: Links from AWS ECS documentation to builders are broken

### ISSUE THREAD

**Issue by backspace** [hashicorp/waypoint#4405]
**Describe the bug**
The links to Docker and Cloud Native Buildpacks from the [AWS ECS plugin](https://developer.hashicorp.com/waypoint/plugins/aws-ecs) documentation are broken.

![waypoint-broken-links](https://user-images.githubusercontent.com/43280/212729664-745a5115-dbc1-43b5-ad46-4e2b99174fdd.gif)

**Comment by backspace** [comment]
Now that I try it, so is the [link](https://developer.hashicorp.com/waypoint/tutorials/docker-aws/aws-ecs) to the “step by step tutorial”.

**Comment by demophoon** [comment]
Hey @backspace,
Thanks for the report, we are actively looking at this issue!

**Comment by briancain** [comment]
Hey there @backspace ! Thanks for reporting this isuse. We got this fixed a while ago, but forgot to circle back and close the issue. Thanks again!
