### ISSUE TITLE
Optional parameters listed under Required parameters for aws-ecs (platform)

### ISSUE THREAD

**Issue by koesbong** [hashicorp/waypoint#4443]
**Describe the bug**
There is a list of optional parameters that show up under Required Parameters in [the docs for aws-ecs (platform)](https://developer.hashicorp.com/waypoint/plugins/aws-ecs#aws-ecs-platform)

**Steps to Reproduce**
Visit https://developer.hashicorp.com/waypoint/plugins/aws-ecs#aws-ecs-platform

**Expected behavior**
Optional parameters should be listed under Optional Parameters section

**Comment by catsby** [comment]
This looks like an issue with assuming `block` type fields are required even if all their subfields are optional here: 

https://github.com/hashicorp/waypoint-plugin-sdk/blob/cb3f0fdd21ecb5579c361d0e74d68ef5c6ca7224/docs/docs.go#L198-L209

**Comment by catsby** [comment]
Technically this isn't fixed by https://github.com/hashicorp/waypoint-plugin-sdk/pull/80 until another PR is opened here to update our version of the sdk to include that change, so I'm re-opening this for now
