### ISSUE TITLE
Trouble with Waypoint deploy jobs to Nomad cluster with ACL

### ISSUE THREAD

**Issue by DziubaMaksym** [hashicorp/waypoint#4454]
**Describe the bug**
If I set NOMAD_TOKEN as the environment variable for the waypoint static runner, it falls deployment with  
`! current user is not authenticated`  
 but if I unset NOMAD_TOKEN as the environment variable and set it with  
`waypoint config set -runner -workspace-scope=prod NOMAD_TOKEN=123abc`  
deployment falls with
`! Unexpected response code: 403 (Permission denied)`
And if I set `NOMAD_TOKEN=123abc` as an environment variable on my local machine, it will perfectly deploy the job to the Nomad cluster when I run 
`waypoint up -var "contour=dev" -var "namespace=dev" -var "datacenters=DC1" -var "region=global"  -local=true`

**Steps to Reproduce**
 - Nomad cluster with ACL enabled
 - Set `waypoint config set -runner -workspace-scope=prod NOMAD_TOKEN=123abc`
 - Run `waypoint up -var "contour=dev" -var "namespace=dev" -var "datacenters=DC1" -var "region=global"  -local=false`

I have a topic on [discuss.hashicorp.com](https://discuss.hashicorp.com/t/waypoint-deploy-jobs-to-nomad-cluster-with-acl/49263) with all hcl files and more info

**Expected behavior**
```
Deploying echo-app...
✓ Running deploy v102
✓ Job registration successful
The deploy was successful!
```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

waypoint -version
**CLI: v0.10.5**
**Server: v0.10.4**

Docker version **20.10.23, build 7155243**
Nomad **v1.4.3** (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

I hope someone had a similar problem and maybe can point me in the right direction 😄 

Thanks in advance, and have a nice day!

**Comment by cicoyle** [comment]
@DziubaMaksym Can you try `waypoint config set` without using workspaces. Or by chance did you also need to set the workspace scope on your `waypoint up`?

**Comment by DziubaMaksym** [comment]
Hi @cicoyle, thanks for your reply. I did `waypoint config set` without a workspace, I can confirm it with 
`waypoint config get`
```
   SCOPE  |    NAME     |                VALUE                 | WORKSPACE | LABELS  
----------+-------------+--------------------------------------+-----------+---------
  project | NOMAD_ADDR  | http://${IP_NOMAD_CLUSTER}                |           |         
  project | NOMAD_TOKEN | ${TOKEN}                                  |           |   
```      
I don't have a workspace defined in my waypoint hcl, so I did 
`waypoint deploy -local=false`
Just to test deployment. But unfortunately, I got the same error as previously:
`! current user is not authenticated`

**Comment by DziubaMaksym** [comment]
Additionally, I have found that if I unset the `NOMAD_TOKEN` variable for runner and add it only with `waypoint config set` I'm getting 
```
! Unexpected response code: 403 (Permission denied)
```
And when setting 
```
waypoint config set -scope=global -runner NOMAD_TOKEN=${TOKEN}
```
error after deployment is 
```
! current user is not authenticated
```
And have found by checking the values of variables with
`waypoint config get -runner -raw` values have the format
```
NOMAD_ADDR=&{http://0.0.0.0}
NOMAD_TOKEN=&{XXXX-XXXX-XXXX-XXXX-XXXX}
```
So additional `&{}` maybe it's nothing but I guess worth mentioning.

**Comment by DziubaMaksym** [comment]
@cicoyle Any suggestions? Because I tried different runners with some result 😢

**Comment by DziubaMaksym** [comment]
The last update of the waypoint server and client fixed everything. So I guess case is closed.
