### ISSUE TITLE
kubernetes-apply `prune_whitelist` improvements

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/waypoint#4516]
See https://github.com/hashicorp/waypoint-examples/pull/109 for a bit of background.

Whilst trying out the [kubernetes-apply example](https://github.com/hashicorp/waypoint-examples/tree/e12ae4dcae03469dc3e53860981c466160e90493/kubernetes/nodejs-apply) I noticed:

1. [The plugin docs](https://github.com/hashicorp/waypoint-examples/pull/109) don’t seem to cover the `prune_whitelist` param
2. It seems to me that `prune_whitelist` could be optional
3. Though the comments suggest `prune_whitelist = []` should be acceptable, it actually causes a panic
4. Kubernetes has renamed this flag to `prune-allowlist` — we should follow suit

**Comment by briancain** [comment]
@jgwhite - I agree, `prune_whitelist` should be optional rather than required. Sounds like a bug! Also 100% agree, let's rename it to allowlist. I'll go ahead and pick up this work today.
