### ISSUE TITLE
ui: health-check error expedited status report

### ISSUE THREAD

**Issue by Codelax** [hashicorp/waypoint#4538]
**Describe the bug**
When running  health-check from UI without setting a data-source I get a vague error (see additional context)

**Steps to Reproduce**
- Don't configure a data source
- Run a health check

**Expected behavior**
I expect the error to inform me that I miss this datasource. As it was before 0.11.0

**Waypoint Platform Versions**

* Waypoint CLI Version: HEAD (aa35b85e1044bf1b88b1704ac8c956ceac1ea474)
* Waypoint Server Platform and Version: 0.11 kubernetes
* Waypoint Plugin: scaleway-container

**Additional context**

![image](https://user-images.githubusercontent.com/12870834/219623214-4c5128a4-53ae-473a-b092-d775b600f6fb.png)

**Comment by jgwhite** [comment]
Thanks for reporting this. I think another simple thing we can do from the UI side is to hide this button if there is no data source present.

https://github.com/hashicorp/waypoint/blob/43966a7b01a3a1fe0f935cd81d9b3e1ce1c319e1/ui/app/components/status-report-meta-table/index.hbs#L28-L36

**Comment by jgwhite** [comment]
I think the underlying reason for the somewhat opaque error message is that we now wrap the error with our `hcerr.Externalize` helper:

https://github.com/hashicorp/waypoint/blob/43966a7b01a3a1fe0f935cd81d9b3e1ce1c319e1/pkg/server/singleprocess/service_status_report.go#L274-L278

**Comment by jgwhite** [comment]
We made the aforementioned tweak to the UI. This will go out in the next minor release. Thanks again for reporting the issue!
