### ISSUE TITLE
Error on waypoint install for Docker

### ISSUE THREAD

**Issue by arschles** [hashicorp/waypoint#471]
**Describe the bug**
Following the getting started guide, the `waypoint install --platform=docker -accept-tos` command fails with this output:

```shell
! Error installing server into docker: Error response from daemon: No such image: hashicorp/waypoint:latest
```

**Steps to Reproduce**

Follow the instructions on https://www.waypointproject.io/docs/getting-started (I am running ElementaryOS Hera, which is based on Ubuntu Bionic) up to and including the install command.

**Expected behavior**

I expected the install to complete successfully.

**Additional context**

A `docker pull hashicorp/waypoint:latest` completes successfully.

**Comment by gregmoy** [comment]
the image is up now

**Comment by abtris** [comment]
Works for me!

**Comment by evanphx** [comment]
You do have to pull the image right manually, We'll work on making it auto-pull shortly.

**Comment by arschles** [comment]
@evanphx sorry for the late reply, and thanks for your comment!

**Comment by mitchellh** [comment]
I'll note it autopulls in 0.1.4 so this was fully resolved.
