### ISSUE TITLE
Typo in CLI Output

### ISSUE THREAD

**Issue by cicoyle** [hashicorp/waypoint#4738]
**Describe the bug**
There is a typo in the CLI output. When running `$ waypoint release` , I see the output:
```
$ waypoint release -repeat

» Releasing example-nodejs1...

» Performing operation locally

» Variables used:
  VARIABLE | VALUE | TYPE | SOURCE  
-----------+-------+------+---------


Deployment 01H14Z681JQ6F59E2E1MKNZAXQ marked as released.

No release manager was configured and the configured platform doesn't
natively support releases. This means that releasing doesn't generate any
public URL. Waypoint marked the deployment aboved as "released" for server
history and to prevent commands such as "waypoint destroy" from deleting
the deployment by default.
```

There is a typo: `Waypoint marked the deployment aboved as`. It should be `above` not `aboved`.

**Steps to Reproduce**
Run:

[Installed a server in docker using these instructions here](https://github.com/hashicorp/waypoint/blob/main/.github/CONTRIBUTING.md#building-waypoint).
```
$ waypoint build
$ waypoint deploy
$ waypoint release -repeat
```

I used the [example nodejs app from the waypoint-examples repo](https://github.com/hashicorp/waypoint-examples/blob/main/docker/nodejs/waypoint.hcl).

**Expected behavior**
I would expect correct grammar in user facing output.

**Waypoint Platform Versions**
```
$ waypoint version
CLI: v0.11.0 (e92d6fbe0)
Server: v0.11.0-247-gac4ac5288
```
**Additional context**
Bonus, there is another typo here: https://github.com/hashicorp/waypoint/blob/8ad4ef67c18d8aaa4d19a0883251053ab0b0b211/internal/runner/accept_test.go#L387

See where it says `canceles` where it should say `cancels`.

**Comment by parikxxit** [comment]
@cicoyle I've fixed the typo as requested in PR #4739 pls check and assign this issue to me
