### ISSUE TITLE
ARM support for docker image

### ISSUE THREAD

**Issue by sstent** [hashicorp/waypoint#474]
Would be great to have official docker images for ARMHF etc

**Comment by rvbuelow** [comment]
ARM64 please!

**Comment by Shogan** [comment]
If you want to work around this for now, it's pretty easy to build an armhf image yourself. I blogged about this here: https://www.shogan.co.uk/devops/hashicorp-waypoint-server-on-raspberry-pi/

**Comment by mxplusb** [comment]
I would also like support for this. `waypoint server install` doesn't work because the binary format is wrong. Granted, you can just compile the docker image yourself, but still.

**Comment by briancain** [comment]
Hello everyone! Thanks for the request, as of Waypoint 0.4.0 we are offering a `linux/arm64` Waypoint Server. You can download it off of Docker Hub: https://hub.docker.com/r/hashicorp/waypoint/tags?page=1&ordering=last_updated
