### ISSUE TITLE
waypoint install supports only default network on Nomad

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/waypoint#4751]
**Describe the bug**

as per discussion here: https://discuss.hashicorp.com/t/waypoint-on-nomad-missing-host-network/33531
it's not possible to specify the network from the command line. 

**Expected behavior**

we should have an option like as: `-nomad-host-network`

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: `v0.11.1`
* Waypoint Server Platform and Version: `nomad`
* Waypoint Plugin: n/a

**Comment by cicoyle** [comment]
Hey @maxadamo, thanks for documenting this. We will look into it.
