### ISSUE TITLE
Add command to stop server

### ISSUE THREAD

**Issue by abtris** [hashicorp/waypoint#479]
Looks me as inconsistent CLI commands. I start server, no command to stop on localhost. You have to make `docker ps && docker stop` but will be nice to have command directly in `waypoint server`.

CLI for server command looks now: 

```
Usage: waypoint server SUBCOMMAND

  Server management.

  The CLI, UI, and entrypoints all communicate to a Waypoint server. A
  Waypoint server is required for logs, exec, config, and more to work.
  The recommended way to run a server is "waypoint install".

  This command contains further subcommands to work with servers.

Subcommands:
    bootstrap     Bootstrap the server and retrieve the initial auth token
    config-set    Set the server online configuration.
    install       Install the Waypoint server to Kubernetes, Nomad, or Docker
    run           Manually run the builtin server
```

I will suggest small change to:

```
Usage: waypoint server SUBCOMMAND

  Server management.

  The CLI, UI, and entrypoints all communicate to a Waypoint server. A
  Waypoint server is required for logs, exec, config, and more to work.
  The recommended way to run a server is "waypoint install".

  This command contains further subcommands to work with servers.

Subcommands:
    bootstrap     Bootstrap the server and retrieve the initial auth token
    config-set    Set the server online configuration.
    install       Install the Waypoint server to Kubernetes, Nomad, or Docker
    start           Manually run the builtin server
    stop           Manually stop the builtin server
```

**Describe alternatives you've considered**
- alternative just name can be `destroy` and stay with `run`.

**Explain any additional use-cases**
- I think cli will be clear and UX will be better

**Comment by evanphx** [comment]
One reason we didn't include such a command is that it's hard to know what it means in the context of, say, kubernetes. Additionally, the `waypoint server start` command runs the waypoint server locally as a foreground process, so it would be weird if `waypoint server stop` was manipulating a waypoint server setup via `install` probably.

Maybe `waypoint server docker stop` ?

**Comment by abtris** [comment]
That make sense. I think that server running outside deploying platform but that was wrong assumption.

**Comment by mitchellh** [comment]
I think we're not gonna do "stop" but we are going do uninstall and upgrades. See #612
