### ISSUE TITLE
Build failure: go-bindata: command not found

### ISSUE THREAD

**Issue by aj-jwair** [hashicorp/waypoint#487]
**Describe the bug**
I am getting the following error on a fresh build after cloning the repo:
```
$ make bin
GOOS=linux GOARCH=amd64 go build -o ./internal/assets/ceb/ceb ./cmd/waypoint-entrypoint
cd internal/assets && go-bindata -pkg assets -o prod.go -tags assetsembedded ./ceb
/bin/sh: go-bindata: command not found
make: *** [Makefile:15: bin] Error 127
```

**Steps to Reproduce**
Steps to reproduce the behavior. Please include any `waypoint.hcl` files
if applicable.

- Clone repo
```
$ git clone https://github.com/hashicorp/waypoint.git
Cloning into 'waypoint'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 19662 (delta 79), reused 95 (delta 47), pack-reused 19477
Receiving objects: 100% (19662/19662), 25.85 MiB | 14.79 MiB/s, done.
Resolving deltas: 100% (13314/13314), done.
```
- `cd` into repo dir
- Run `make bin`
```
$ make bin
GOOS=linux GOARCH=amd64 go build -o ./internal/assets/ceb/ceb ./cmd/waypoint-entrypoint
cd internal/assets && go-bindata -pkg assets -o prod.go -tags assetsembedded ./ceb
/bin/sh: go-bindata: command not found
make: *** [Makefile:15: bin] Error 127
```

**Expected behavior**

Successful build expected.

**Additional context**

None.

**Comment by evanphx** [comment]
Yes, sorry about that. You need to install the go-bindata tool manually for now.

**Comment by evanphx** [comment]
You can use our vendored one: https://github.com/hashicorp/go-bindata

**Comment by aj-jwair** [comment]
Do you think we can clarify that in the CONTRIBUTING doc?
Maybe as a prerequisite under: https://github.com/hashicorp/waypoint/blob/main/.github/CONTRIBUTING.md#making-changes-to-waypoint
