### ISSUE TITLE
Migrate away from deprecated `heroku/buildpacks:20` CNB builder image

### ISSUE THREAD

**Issue by edmorley** [hashicorp/waypoint#4911]
Hi 👋

This project uses Heroku's `heroku/buildpacks:20` CNB builder images:
https://github.com/search?q=repo%3Ahashicorp%2Fwaypoint+%22heroku%2Fbuildpacks%3A20%22&type=code

We have deprecated this builder image as of https://github.com/heroku/cnb-builder-images/pull/429.

Please migrate to `heroku/builder:22` or `heroku/builder:20`, to continue to receive security updates, and to avoid disruption when the build time deprecation warning is upgraded to an error in the future.

More information on the difference between the various builder images can be seen here:
https://github.com/heroku/cnb-builder-images#heroku-cnb-builder-images

I also see there are references to the even older (and EOL/insecure) `heroku/buildpacks:18` - these need to be migrated too:
https://github.com/search?q=repo%3Ahashicorp%2Fwaypoint+%22heroku%2Fbuildpacks%3A18%22&type=code

**Comment by edmorley** [comment]
Gentle nudge that builds using these images will start erroring in the future, plus the underlying images themselves will stop receiving security updates.

**Comment by edmorley** [comment]
@evanphx ^

**Comment by evanphx** [comment]
@edmorley I'm sorry but this version of Waypoint is no longer maintained. You're free to fork it and fix this. 

https://www.hashicorp.com/blog/a-new-vision-for-hcp-waypoint

**Comment by edmorley** [comment]
@evanphx I personally don't use Waypoint, this issue was just one of many filed against projects that consume our builder images to warn about future breakage.

**Comment by evanphx** [comment]
@edmorley Ah gotcha. So noted then!
