### ISSUE TITLE
Feature: CI/CD Documentation

### ISSUE THREAD

**Issue by Brian-McBride** [hashicorp/waypoint#498]
Waypoint seems like a great addition to the Hashicorp tool stack. 

In my organization, no one is allowed to deploy to any server from a CLI. All deployments to any infrastructure should be through a CI/CD pipeline. It is how we do Terraform as well. While I love my developer teams, deployments via CLI is just asking for conflicts and management issues. 

In that regard, I think it would be helpful for the Waypoint documentation to provide some CI/CD examples. 
It would also be great for Hashicorp to demonstrate a full-stack example with all the products. A K8S cluster described in Terraform, Waypoint for deploying a multi-service (microservice ideally) application with service discovery and a public endpoint path via an API gateway, and security via Vault. 

But, at minimum, tutorials for users to see a full CI/CD with testing, build, and deployment of an app. The NodeJS examples are great - I'd suggest adopting Typescript for NodeJS examples as that is the trend in enterprise development on that stack. And, of course, Python, Java, C#, and GoLang examples will help facilitate adoption. 

Very supportive of this tool. On the application level, there is a lack of solid tooling with the "Deploy Anywhere" methodology in mind.

**Comment by pearkes** [comment]
@Brian-McBride Did you find what you were looking for here? If you didn't yet, we do have documentation for CI/CD:

[Using Waypoint with CI/CD services](https://www.waypointproject.io/docs/automating-execution) 

Also wanted to write this not for future readers of this issue if they end up here looking for the same thing.
