### ISSUE TITLE
Support for docker config in docker-pull

### ISSUE THREAD

**Issue by orenmazor** [hashicorp/waypoint#501]
I realize that the docker client in golang is closer to the metal than not, so this may be out of context.

But basically, it doesnt support credentials that exist in `~/.docker/config.json`, which means that if I want to deploy artifacts that are built for me in a private repo, I now need to wrap waypoint with another tool (bash, make, whatever) that will get those credentials and let me feed them into the `encoded_auth` parameter in docker-pull.

Off the cuff brainstorming:
 - some sort of mechanism for pre-checking that config.json when building a docker client
 - a hook in docker-pull that lets me do a `docker login` using a helper

**Comment by evanphx** [comment]
Ah ha! This is a simple oversight. The docker registry plugin can read the docker config file in, we just need to port this code over to the docker pull builder: https://github.com/hashicorp/waypoint/blob/main/builtin/docker/registry.go#L79-L113
