### ISSUE TITLE
GCP: "waypoint build" fails, "Error parsing reference... invalid reference format"

### ISSUE THREAD

**Issue by johntellsall** [hashicorp/waypoint#503]
**Describe the bug**

`waypoint build` fails with error:

```
Generated new Docker image: example-nodejs:latest
❌ Tagging Docker image: example-nodejs:latest =>
gcr.io/<my-project-name>/example-nodejs:latest
! unable to tag image:Error parsing reference:
  "gcr.io/<my-project-name>/example-nodejs:latest" is not a valid repository/tag:
  invalid reference format
```

**Steps to Reproduce**
1. `cd waypoint-examples/google-cloud-run/nodejs`
2. `waypoint build`

**Expected behavior**

Expected app to build, and push a Docker image to GCR.

**Additional context**

From the error I'd have expected a manual tag to fail. However, tagging and pushing manually succeeds:

```
docker  tag example-nodejs:latest gcr.io/site-randocat/example-nodejs:latest
docker push gcr.io/site-randocat/example-nodejs:latest
```

The "push" correctly pushes an image to GCR.

Gcloud correctly knows my default project name, as verified by "gcloud config list --format 'value(core.project)'"

**Comment by evanphx** [comment]
This is expected, you have to update the waypoint.hcl file with your repo name.  The `<my-project-name>` is meant as a placeholder for you to fill in.
