### ISSUE TITLE
! Error initializing server: context deadline exceeded

### ISSUE THREAD

**Issue by sandeep540** [hashicorp/waypoint#504]
**Describe the bug**
Waypoint for docker is crashing with this error

**Steps to Reproduce**
Steps to reproduce the behavior. Please include any `waypoint.hcl` files
if applicable.

**Expected behavior**

**Additional context**

```
020-10-15T21:17:13.037Z [INFO] waypoint: waypoint version: full_string="Waypoint v0.1.1 (44e2d3d6+CHANGES)" version=v0.1.1 prerelease= metadata= revision=44e2d3d6+CHANGES

2020-10-15T21:17:13.037Z [TRACE] waypoint: starting interrupt listener for context cancellation

2020-10-15T21:17:13.038Z [TRACE] waypoint: interrupt listener goroutine started

2020-10-15T21:17:13.038Z [DEBUG] waypoint: home configuration directory: path=/home/waypoint/.config/waypoint

2020-10-15T21:17:13.038Z [INFO] waypoint.server: opening DB: path=/data/data.db

2020-10-15T21:17:23.009Z [INFO] waypoint.server: gracefully closing db: path=/data/data.db

2020-10-15T21:17:23.009Z [TRACE] waypoint: stopping signal listeners and cancelling the context

! Error initializing server: context deadline exceeded
```

**Comment by mitchellh** [comment]
Hello, can you please add any reproduction steps so we can try to debug this? That section is not filled out and without repro steps we cannot fix this. Thank you!

**Comment by httpsOmkar** [comment]
I am facing the same issue.

**Operating System**
- CentOS 8

**Describe the bug**
When trying to install the waypoint with the command `waypoint install --platform=docker -accept-tos`. It stuck at

<img width="645" alt="Screenshot 2020-10-16 at 7 31 51 AM" src="https://user-images.githubusercontent.com/29942725/96209854-ab0ebe00-0f81-11eb-9046-8380d00d071a.png">
And the docker container logs are

<img width="1549" alt="Screenshot 2020-10-16 at 7 32 40 AM" src="https://user-images.githubusercontent.com/29942725/96209901-c7aaf600-0f81-11eb-8b02-d590c5be51a0.png">

**Comment by httpsOmkar** [comment]
If I try to run this on macOS I was able to do that. But on cent, it does not work.

**Comment by gtirloni** [comment]
I **cannot** reproduce this on the following environment:

* CentOS 8.0.1905
* Docker CE 19.03.13 (nightly repo enabled for containerd.io package due to seccomp)
* Waypoint v0.1.1 (44e2d3d6)

**Comment by sandeep540** [comment]
Steps to reproduce

1. Installed Waypoint on Mac 10.15.7 Catalina
2. Started the Server - It was on VPN, when I tried to Open the URL with .run, firewall was blocking the same
3. Disconnected the VPN and tried again, Docker Server was not coming up and I was getting the above error and same error as @Omar-Khawaja

**Comment by gtirloni** [comment]
@sandeep540 are you able to run `docker run hello-world` from the command line?

**Comment by sandeep540** [comment]
<img width="694" alt="Screen Shot 2020-10-16 at 5 21 08 PM" src="https://user-images.githubusercontent.com/741952/96316149-1aad9900-0fd4-11eb-98c2-25916d789333.png">

**Comment by mitchellh** [comment]
@sandeep540 My only thought is that your VPN could be interfering with the local Docker networking? During the `waypoint install` process the Waypoint CLI on your Mac has to be able to communicate to the Waypoint server running in Docker. We had dozens of testers all on Mac prior to release and currently and we haven't seen any similar issues on our end.

**Comment by sandeep540** [comment]
No issues, will wait for next release, 

Then I will completely uninstall and reinstall on open internet without vpn and test it

**Comment by mitchellh** [comment]
Please give it a shot with 0.1.2. I don't think the version here will matter much. Please try without a VPN, I do think that's it. I think we would've heard more of this issue if it was more widespread.

**Comment by dcanadillas** [comment]
@sandeep540 I had similar issue with Docker platform because I was using a previous version of the CLI binary with the latest Docker image 0.1.2. The reason was that I installed the latest version with `brew install` but didn't realize that I had a previous manual version in `/usr/local/bin`. So I was using the first manual downloaded version instead of the latest one.

I would give it a try with 0.1.2, but checking that your CLI version and Docker image are aligned (I guess that if you did a `docker pull` before but having some connectivity restrictions later you may have been using a non updated Docker image)

In my case I just solved it by uninstalling all CLI and local Docker image versions and reinstalling (I am using MacOS 10.15.7 btw): 
* `brew uninstall waypoint` 
* `sudo rm /usr/local/bin/waypoint`
* `docker container stop waypoint-server && docker container rm waypoint-server`
* `brew install waypoint`

Then check that you have the latest version:
```
$ waypoint version                                                                                                                                                                             INT
Waypoint v0.1.2 (edf37a09)
```

Then I re-run the Docker server again:
```
$ waypoint install -platform=docker -accept-tos
 + Server container started
Waypoint server successfully installed and configured!

The CLI has been configured to connect to the server automatically. This
connection information is saved in the CLI context named "install-1602967846".
Use the "waypoint context" CLI to manage CLI contexts.

The server has been configured to advertise the following address for
entrypoint communications. This must be a reachable address for all your
deployments. If this is incorrect, manually set it using the CLI command
"waypoint server config-set".

Advertise Address: waypoint-server:9701
HTTP UI Address: https://localhost:9702
```

In my case was just a matter of versioning, but not sure if it is your same case.

I see that you are running 0.1.1 version of the Docker image, so check also the CLI version with `waypoint version`. 

You can also try to execute the server locally to see if it is a matter of the docker image:
```
$ waypoint server run -accept-tos
Warning! Default DB path will be used. This is at the path shown below.
The server stores persistent data here so this file should be saved and
consistent for every server run otherwise data loss will occur. It is
recommended that you explicitly set the "-db" flag as acknowledgement of
the importance of the DB file.


» Server configuration:

             DB Path: data.db
        gRPC Address: 127.0.0.1:9701
        HTTP Address: 127.0.0.1:9702
       Auth Required: yes
  Browser UI Enabled: yes
         URL Service: api.waypoint.run:443 (account: token)

» Server requires bootstrapping!

  New servers must be bootstrapped to retrieve the initial auth token for
  connections. To bootstrap this server, run the following command in your
  terminal once the server is up and running.

    waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify

  This command will bootstrap the server and setup a CLI context.

» Server logs:

2020-10-17T23:03:04.195+0200 [INFO]  waypoint.server: starting built-in server: addr=127.0.0.1:9701
2020-10-17T23:03:04.195+0200 [INFO]  waypoint.server.http: starting HTTP server: addr=127.0.0.1:9702
2020-10-17T23:03:04.195+0200 [INFO]  waypoint.server.grpc: starting gRPC server: addr=127.0.0.1:9701
```

So, if you can run locally it could be some Docker image related thing. Just a guess.

**Comment by sandeep540** [comment]
Hi @dcanadillas , Thanks for explaining in detail, I tried, but its failing, attached are docker logs 

<img width="1006" alt="Screen Shot 2020-10-17 at 6 42 06 PM" src="https://user-images.githubusercontent.com/741952/96355581-aa247c00-10a8-11eb-9739-4921049f7798.png">
<img width="1037" alt="Screen Shot 2020-10-17 at 6 41 50 PM" src="https://user-images.githubusercontent.com/741952/96355587-b577a780-10a8-11eb-8422-7fbd93ae8659.png">

**Comment by mitchellh** [comment]
Yes I'm sorry I'm not sure what's happening here, we haven't heard any other reports of this beyond the couple folks in this issue, and we've seen at least 5,000 successful installs at this point. 

Based on your logs @sandeep540 I am noticing something strange... we are exceeding a context deadline on server start. This is a clue. During server startup, we reach out to the Waypoint URL service to setup the account. I think this is the most likely culprit. Are your Docker containers able to contact the external network? And specifically `api.waypoint.run:443`? I think that is the issue.

**Comment by sandeep540** [comment]
Let me ssh into one of the containers and ping it

**Comment by sandeep540** [comment]
My Bad, the link it blocked by McAfee Enpoint Security for Mac, need to work with network team

<img width="1648" alt="Screen Shot 2020-10-17 at 8 04 36 PM" src="https://user-images.githubusercontent.com/741952/96356449-2ff9f480-10b4-11eb-8fc5-68cc777a4aa1.png">

**Comment by mitchellh** [comment]
Perfect, note you're seeing `http://api.waypoint.run:443` but you can simplify this to `https://api.waypoint.run` (TLS).

Thank you, I'm confident this is the issue. I'm going to make a note in the docs about this, please report back if you have further issues.

**Comment by vtomasr5** [comment]
Hi,

I hit the same issue by following the [kubernetes guide](https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes). I'm using kind and Waypoint v0.1.2 (edf37a09).
No VPN involved.

At this step:
```
$ waypoint install --platform=kubernetes -accept-tos
service/waypoint created
statefulset.apps/waypoint-server created
! Error waiting for service ready: timed out waiting for the condition
  
  The Waypoint server has been deployed, but due to this error we were
  unable to automatically configure the local CLI or the Waypoint server
  advertise address. You must do this manually using "waypoint context"
  and "waypoint server config-set".
```

These are the logs from the waypont-server-0 Pod:
```
$ kubectl logs waypoint-server-0 
2020-10-18T16:28:20.243Z [INFO]  waypoint: waypoint version: full_string="Waypoint v0.1.2 (edf37a09+CHANGES)" version=v0.1.2 prerelease= metadata= revision=edf37a09+CHANGES
2020-10-18T16:28:20.243Z [TRACE] waypoint: starting interrupt listener for context cancellation
2020-10-18T16:28:20.243Z [TRACE] waypoint: interrupt listener goroutine started
2020-10-18T16:28:20.243Z [DEBUG] waypoint: home configuration directory: path=/home/waypoint/.config/waypoint
2020-10-18T16:28:20.243Z [INFO]  waypoint.server: opening DB: path=/data/data.db
! Error initializing server: context deadline exceeded
2020-10-18T16:28:30.250Z [INFO]  waypoint.server: gracefully closing db: path=/data/data.db
2020-10-18T16:28:30.250Z [TRACE] waypoint: stopping signal listeners and cancelling the context
```

**Comment by mitchellh** [comment]
Hey @vtomasr5 there are a number of kind issues currently reported (search "kind") that you might be hitting as well. 

Given your logs though it sounds similar with networking.

**Comment by donovanmuller** [comment]
Just to add to this for posterity, I also experienced this issue and it was directly related to running VPN software (ZScaler). After shutting down the VPN, Waypoint started successfully.

Mac: `10.15.7`
Docker Desktop: `2.4.0.0 (48506)` 
Waypoint: `Waypoint v0.1.3 (cf5706e9)`
ZScaler Security: `2.1.2.44 (233861)`

**Comment by nadilas** [comment]
Can the URL service be disabled globally for the whole server?

> Yes I'm sorry I'm not sure what's happening here, we haven't heard any other reports of this beyond the couple folks in this issue, and we've seen at least 5,000 successful installs at this point.
> 
> Based on your logs @sandeep540 I am noticing something strange... we are exceeding a context deadline on server start. This is a clue. During server startup, we reach out to the Waypoint URL service to setup the account. I think this is the most likely culprit. Are your Docker containers able to contact the external network? And specifically `api.waypoint.run:443`? I think that is the issue.

**Comment by amitmawkin** [comment]
why does the waypoint server needs to connect back to api.waypoint.run:443 , its been blocked and flagged by corporate proxies

**Comment by gtirloni** [comment]
> why does the waypoint server needs to connect back to api.waypoint.run:443 , its been blocked and flagged by corporate proxies

For the [URL Service](https://www.waypointproject.io/docs/url), most likely.

**Comment by mitchellh** [comment]
You can disable the URL service globally at the server level but not via `waypoint install` currently, only via the manually run `waypoint server run`. We’ll expand install to support this option soon.

**Comment by amitmawkin** [comment]
I believe this is a good thing, is there  an option to turn this off for folks who are just exploring Waypoint specifically in corporate environments where each outbound connections are examined and they do not need a Let's Encrypt generated certificate for non prod scenarios

**Comment by mitchellh** [comment]
> I believe this is a good thing, is there an option to turn this off for folks who are just exploring Waypoint specifically in corporate environments where each outbound connections are examined and they do not need a Let's Encrypt generated certificate for non prod scenarios

Not unless you run the server manually: https://www.waypointproject.io/docs/server/run#manually-running-the-server

And like I said, we’ll introduce an option to `waypoint install` to disable the URL service in the future.

**Comment by amitmawkin** [comment]
@mitchellh  thanks for your response, -  we posted at the same time, you answered it in your previous post,  I will try to run this manually as previously I was using waypoint install option to deploy it on a local kubernetes env on my laptop.

**Comment by amitmawkin** [comment]
for anybody else facing this and landing at this page and facing issues to VPN or coprorate proxies blocking the URL Service 

**To start** 
 `waypoint server run  --accept-tos -url-enabled=false`

After successful running the above command , you still need to bootstrap it and run the command

**To BootStrap**
`waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify`

**To load the UI**
 `waypoint ui --authenticate`

**Comment by nadilas** [comment]
Thanks @mitchellh! I removed my post shortly, as I discovered the cli parameter you mentioned. However I can't seem to find the option to disable TLS on the listeners.
I deployed on an openshift cluster and my cluster inbound connection is already under TLS. I would like to disable TLS on the waypoint server internally within the cluster.

I found the appropriate `ServerConfig` part, but I can't set it for the `server run` command. Is not not yet possible?

**Comment by cmoulliard** [comment]
> **To BootStrap**
> `waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify`

Why do we have to bootstrap the server as it has been started with the previous command ?

**Comment by saidmasoud** [comment]
Hello, I am experiencing a similar issue when installing the waypoint server on GKE. The command I used to install is `waypoint install -server-image=<internal-docker-registry> -namespace=<some-ns> -accept-tos -advertise-internal`. Initially, the `waypoint-server-0` pad was successfully `Runing`, so I ran `waypoint up` in the `waypoint-examples/kubernetes/nodejs` subdir.  See below for logs:

```sh
said@ZZZ-M-CH7HDM nodejs % kubectl get po
NAME                                                         READY   STATUS             RESTARTS   AGE
example-nodejs-01ept38edw0k6xp4brty6afjk3-85595c95b4-5q9kx   0/1     CrashLoopBackOff   132        2d10h
waypoint-server-0                                            0/1     CrashLoopBackOff   17         2d10h
said@ZZZ-M-CH7HDM nodejs % kubectl logs waypoint-server-0
2020-11-16T17:01:01.492Z [INFO]  waypoint: waypoint version: full_string="Waypoint v0.1.4 (3810a3c7+CHANGES)" version=v0.1.4 prerelease= metadata= revision=3810a3c7+CHANGES
2020-11-16T17:01:01.492Z [TRACE] waypoint: starting interrupt listener for context cancellation
2020-11-16T17:01:01.493Z [TRACE] waypoint: interrupt listener goroutine started
2020-11-16T17:01:01.493Z [DEBUG] waypoint: home configuration directory: path=/home/waypoint/.config/waypoint
2020-11-16T17:01:01.493Z [INFO]  waypoint.server: opening DB: path=/data/data.db
2020-11-16T17:01:11.495Z [INFO]  waypoint.server: gracefully closing db: path=/data/data.db
2020-11-16T17:01:11.496Z [TRACE] waypoint: stopping signal listeners and cancelling the context
! Error initializing server: context deadline exceeded
said@ZZZ-M-CH7HDM nodejs % waypoint version
Waypoint v0.1.4 (3810a3c7)
said@ZZZ-M-CH7HDM nodejs % kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.10-gke.601
said@ZZZ-M-CH7HDM nodejs %
```

**Comment by riponbanik** [comment]
I am having the same issue with docker. Kubernetes(EKS) install also fail with Liveliness probe issue. I am using Waypoint version is 0.1.5. Manual install is not an option.

**Comment by warsameSkew** [comment]
If anyone is still facing the problem and the above mentioned didn't work. 

Doing `docker volume prune -f` solved my issue
