### ISSUE TITLE
how to integrate the following additional configs

### ISSUE THREAD

**Issue by aavileli** [hashicorp/waypoint#509]
My workflow is as follows thru CI

1. build image
2. push to registry
3. generate manifest for k8s + istio service
4. push to git 
5. git ops tool deploys to n clusters

how is the integration of the last 3 steps done in waypoint  

As there is a concept of plugin/providers is there a provider for the above 3,4,5 points

**Comment by mitchellh** [comment]
Yes Waypoint is completely pluggable: https://www.waypointproject.io/docs/extending-waypoint

Steps 1 and 2 you can call `waypoint build` (it pushes by default but you can split those up too)

For 3 and 4 and 5 you can either write a custom plugin or use our "exec" plugin: https://www.waypointproject.io/plugins/exec

Please continue to ask usage questions on our forum: discuss.hashicorp.com you'll be better served there and its easier to search for future users!
