### ISSUE TITLE
Could not create any of the following paths: /home/waypoint/.config/waypoint

### ISSUE THREAD

**Issue by clarkmcc** [hashicorp/waypoint#511]
**Describe the bug**
When running `waypoint install --platform=docker -accept-tos` I see the following output in the docker container before it dies.

```
2020-10-15T22:42:39.286Z [INFO] waypoint: waypoint version: full_string="Waypoint v0.1.1 (44e2d3d6+CHANGES)" version=v0.1.1 prerelease= metadata= revision=44e2d3d6+CHANGES

2020-10-15T22:42:39.287Z [TRACE] waypoint: starting interrupt listener for context cancellation

! could not create any of the following paths: /home/waypoint/.config/waypoint,

/etc/xdg/waypoint

2020-10-15T22:42:39.291Z [TRACE] waypoint: stopping signal listeners and cancelling the context
```

**Steps to Reproduce**
1. Run `waypoint install --platform=docker -accept-tos` in a terminal instance on MacOS 10.15.7

**Expected behavior**
The docs indicate that I should see

```
✓ Server container started
Waypoint server successfully installed and configured!

The CLI has been configured to connect to the server automatically. This
connection information is saved in the CLI context named "install-1601411904".
Use the "waypoint context" CLI to manage CLI contexts.

The server has been configured to advertise the following address for
entrypoint communications. This must be a reachable address for all your
deployments. If this is incorrect, manually set it using the CLI command
"waypoint server config-set".

Advertise Address: waypoint-server:9701
HTTP UI Address: localhost:9702
```

**Additional context**
I'm using MacOS 10.15.7

**Comment by mitchellh** [comment]
Waypoint uses the XDG base directory standard for configuration. It'll attempt to create some default locations if they aren't created. See: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html You may need to create an `XDG_CONFIG_HOME` directory.

Usually we have permission to create that home directory for you but it looks like your system may be a bit more locked down.
