### ISSUE TITLE
InvalidParameterException trying to use an existing ECS cluster via the `cluster` parameter

### ISSUE THREAD

**Issue by kylegalbraith** [hashicorp/waypoint#513]
**Describe the bug**
I have a static ECS cluster that was provisioned via Terraform along with the ECR repository for my container image. I then tried to use the `waypoint.hcl` file seen below and specify the name of the cluster via the `cluster` parameter. Based on [this documentation](https://www.waypointproject.io/plugins/aws-ecs#cluster), Waypoint should recognize the cluster already exists and skip trying to create it and just deploy to it.

**Steps to Reproduce**
1. Deploy the `waypoint.hcl` below with the ECS cluster, `waypoint-nextjs-cluster`, already created in your AWS account.
```hcl
project = "example-next-ecs"

app "next-ecs" {
  build {
    use "pack" {}
    registry {
      use "aws-ecr" {
        region     = "us-west-2"
        repository = "nextjs-image"
        tag        = "latest"
      }
    }

  }

  # Deploy to ECS
  deploy {
    use "aws-ecs" {
      region  = "us-west-2"
      cluster = "waypoint-nextjs-cluster"
      memory  = "512"
    }
  }
}

```

With the existing cluster already provisioned, Waypoint throws the following error when you run `up`.

```
» Building...
Creating new buildpack-based image using builder: heroku/buildpacks:18
✓ Creating pack client
✓ Building image
 │ [exporter] Reusing layer 'config'
 │ [exporter] Adding label 'io.buildpacks.lifecycle.metadata'
 │ [exporter] Adding label 'io.buildpacks.build.metadata'
 │ [exporter] Adding label 'io.buildpacks.project.metadata'
 │ [exporter] *** Images (b3e6e24ef072):
 │ [exporter]       index.docker.io/library/next-ecs:latest
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:nodejs'
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:toolbox'
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:yarn'
 │ [exporter] Reusing cache layer 'heroku/nodejs-yarn:node_modules'
✓ Injecting entrypoint binary to image

Generated new Docker image: next-ecs:latest
Creating new buildpack-based image using builder: heroku/buildpacks:18✓ Creating pack client
✓ Building image
 │ [exporter] Reusing layer 'config'
 │ [exporter] Adding label 'io.buildpacks.lifecycle.metadata'
 │ [exporter] Adding label 'io.buildpacks.build.metadata'
 │ [exporter] Adding label 'io.buildpacks.project.metadata'
 │ [exporter] *** Images (b3e6e24ef072):
 │ [exporter]       index.docker.io/library/next-ecs:latest
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:nodejs'
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:toolbox'
 │ [exporter] Reusing cache layer 'heroku/nodejs-engine:yarn'
 │ [exporter] Reusing cache layer 'heroku/nodejs-yarn:node_modules'
✓ Injecting entrypoint binary to image

Generated new Docker image: next-ecs:latest
Tagging Docker image: next-ecs:latest => <aws-account-id>.dkr.ecr.us-west-2.amazonaws.com/nextjs-image:latest
Docker image pushed: <aws-account-id>.dkr.ecr.us-west-2.amazonaws.com/nextjs-image:latest

» Deploying...
❌ Creating new ECS cluster: waypoint-nextjs-cluster
! InvalidParameterException: Arguments on this idempotent request are inconsistent
  with arguments used in previous request(s).
```

**Expected behavior**
Waypoint should **not** try to create the ECS cluster and instead use the one that is already there by name.

**Comment by evanphx** [comment]
That's strange, it should happily use your existing one. We'll look into that!

**Comment by evanphx** [comment]
The code in question is here: https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/platform.go#L284-L321 perhaps it's a permission issue of not being able to describe the existing clusters?

**Comment by kylegalbraith** [comment]
> The code in question is here: https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/platform.go#L284-L321 perhaps it's a permission issue of not being able to describe the existing clusters?

The AWS profile I am using has Admin level access to resources so I don't think it's a describe issue. For reference I am calling up using an AWS profile so, `AWS_PROFILE=foo waypoint up`. This works fine for the ECR repository as it gets pushed to without any issues.

**Comment by kylegalbraith** [comment]
It looks like this is the problem, https://github.com/hashicorp/waypoint/blob/327c83e84da174a905ec941fa28e7d6bde7069ee/builtin/aws/ecs/platform.go#L300.

If there is only one cluster in the AWS account, it won't get returned. I believe this should be `>=`.
