### ISSUE TITLE
Nomad Plugin - allow specification of an hcl file

### ISSUE THREAD

**Issue by akio-outori** [hashicorp/waypoint#516]
Waypoint looks really interesting but isn't quite flexible enough for us yet (definitely understand its a day 1 release).  Of particular note for us is being able to get deployment feedback from Nomad (e.g., whether allocations of a job actually enter a running state).

One of the big items that would block adoption for us is being able to use existing Nomad job files, and I wouldn't necessarily expect (or want to wait for) abstraction of all nomad options.  Instead, what about allowing users to specify a path to an hcl file to use?

That seems like it would lower overhead for feature requests while allowing lots of custom setups to work without too much modification.

Example of one of our local dev nomad jobs below:

```
job "edge-server" {

  datacenters = ["local"]
  type        = "service"
  
  group "edge-server" {

    count = 1

    update {
      max_parallel     = 1
      auto_revert      = "true"
      min_healthy_time = "30s"
      healthy_deadline = "2m"
    }

    # scratch space for all tasks in this group, must include space
    # for all the logs (100 MB by default)
    ephemeral_disk {
      size = 200 # MB
    }

    task "edge-server" {

      driver = "docker"

      config {
        image        = "density/edge-server:0"
        network_mode = "host"

        logging {
          type = "fluentd"
          config {
            fluentd-async-connect = true
            fluentd-address       = "${attr.unique.network.ip-address}:24224"
            tag                   = "edge-server"
          }
        }
      }

      # cgroup-limited resources for the container on the host
      resources {
        cpu    = 256
        memory = 512
        network {
          port "http" {
            static = 80
          }
          port "metrics" {
            static = 8888
          }
        }
      }

      service {
        name = "edge-server"
        port = "http"
        
        check {
          type     = "http"
          port     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
        }

        check {
          type     = "script"
          name     = "check_config"
          command  = "/bin/nginx"
          args     = ["-T"]
          interval = "60s"
          timeout  = "5s"
        }
      }

    }
  }
}
```

**Comment by attachmentgenie** [comment]
and as an elevated version of this, levant integration, so that we can pass variables to the nomad script

**Comment by orenmazor** [comment]
I can't help but assume somebody is out there at this very moment hacking a levant plugin, and I wish I could buy that person a beer

**Comment by kaykelins** [comment]
you can use exec plugin to deploy the job file

**Comment by orenmazor** [comment]
@kaykelins I'm having a hard time visualizing this but I'm super interested. can you post a small example? in my mind the exec plugin is for one-off tasks and not for CD

**Comment by kaykelins** [comment]
this is on example, but use exec plugin has issues, [documetation](https://www.waypointproject.io/plugins/exec)
```
### waypoint.hcl
project = "example-python"
app "example-python" {
  labels = {
    "service" = "example-python",
    "env" = "dev"
  }

  build {
    use "docker" {}
    registry {
      use "docker" {
        image = "python-example"
        tag = "1"
        local = true
      }
    }
  }

  deploy {
    use "exec" {
        command = ["nomad","run","job.hcl"]
    }
  }
}
### job.hcl
job "example" {
  datacenters = ["dc1"]

  group "demo" {
    network {
      port "web" {
        to = 8080
      }
    }

    task "python" {
      driver = "docker"
      config {
        image = "python-example:1"
        ports = ["web"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```
and you right, is not ideal, but works, I don't recommend for production envs, but for dev or demo is ok

**Comment by akio-outori** [comment]
That'd get us over the initial hurdle for testing, though I'm guessing that things like job deployment status aren't supported (the main use case for us).  Levant might be a better choice for us for now.

**Comment by orenmazor** [comment]
just a followup: this exec+levant approach has turned into the way I deploy 3 different stacks now. A++

**Comment by MarilynFranklin** [comment]
I ran into similar issues with the limitations of the nomad plugin and ended up creating a levant plugin. I'll link to it here in case anyone else would find it helpful: https://github.com/MarilynFranklin/waypoint-plugin-levant

**Comment by mitchellh** [comment]
Fixed by #1299, will be in 0.4

**Comment by Allan-Nava** [comment]
> @orenmazor exec plugin has issues, [documetation](https://www.waypointproject.io/plugins/exec), but here one example.
> 
> ```
> ### waypoint.hcl
> project = "example-python"
> app "example-python" {
>   labels = {
>     "service" = "example-python",
>     "env" = "dev"
>   }
> 
>   build {
>     use "docker" {}
>     registry {
>       use "docker" {
>         image = "python-example"
>         tag = "1"
>         local = true
>       }
>     }
>   }
> 
>   deploy {
>     use "exec" {
>         command = ["nomad","run","job.hcl"]
>     }
>   }
> }
> ### job.hcl
> job "example" {
>   datacenters = ["dc1"]
> 
>   group "demo" {
>     network {
>       port "web" {
>         to = 8080
>       }
>     }
> 
>     task "python" {
>       driver = "docker"
>       config {
>         image = "python-example:1"
>         ports = ["web"]
>       }
> 
>       resources {
>         cpu    = 500
>         memory = 256
>       }
>     }
>   }
> }
> ```
> 
> and you right, is not ideal, but works, I don't recommend for production envs, but for dev or demo is ok

But how can I pass the tag= gitrefpretty() to nomad.hcl?

**Comment by Allan-Nava** [comment]
I have problem to build ->
```
✓ Running build v11
✓ Building Docker image with kaniko...
❌ Testing registry and uploading entrypoint layer
! error setting up entrypoint layer to host
```
