### ISSUE TITLE
Add fargate support

### ISSUE THREAD

**Issue by pharindoko** [hashicorp/waypoint#523]
**Describe the solution you'd like**
I would like to have aws fargate support. Serverless containers make it even easier to deploy in a fast manner.

**Comment by flowirtz** [comment]
I had the same thought but then I saw this. Look at the screenshot right above the headline "destroy the instance". It says that launch type is Fargate.

https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/deploy-aws#destroy-the-instance

Didn't test it yet though, but that made me think maybe they already support fargate?

**Comment by evanphx** [comment]
The easiest way to use Fargate here is via the ECS plugin, which by default will launch on Fargate. Does that satisfy what you're looking for?

**Comment by pharindoko** [comment]
> The easiest way to use Fargate here is via the ECS plugin, which by default will launch on Fargate. Does that satisfy what you're looking for?

@evanphx 
Yes. 

Just a proposal:
Please mention this in the waypoint documentation. 

https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/deploy-aws
