### ISSUE TITLE
Waypoint not working on existing kubernetes cluster

### ISSUE THREAD

**Issue by saiyam1814** [hashicorp/waypoint#525]
following the documentation I installed waypoint and have kubeconfig in place 
Going through the nodejs repo I change docker section to push the image to my repo else it would be errimagepull

waypoint.hcl looks like this 
```
project = "example-nodejs"

app "example-nodejs" {
  labels = {
      "service" = "example-nodejs",
      "env" = "dev"
  }

  build {
    use "pack" {}
    registry {
        use "docker" {
          image = "saiyam911/example-nodejs"
          tag = "1"
          
        }
    }
 }

  deploy { 
    use "kubernetes" {
     
    }
  }

  release {
    use "kubernetes" {
      node_port = 31766
    }
  }
}
```
The pod goes into running but the liveliness and readiness probe fails 
If I manually go and remove the readiness and liveliness probe the pod runs but the service is not accessible

Is there something I am missing or doing wrong ?

**Comment by mitchellh** [comment]
I believe you need to set a probe path up: https://www.waypointproject.io/plugins/kubernetes#probe_path

Does that work?

**Comment by saiyam1814** [comment]
Nope Actually I had that as well but it gives readiness probe failed error so no luck

**Comment by saiyam1814** [comment]
@mitchellh  is my latest waypoint.hcl 
```
project = "example-nodejs"

app "example-nodejs" {
  labels = {
      "service" = "example-nodejs",
      "env" = "dev"
  }

  build {
    use "pack" {}
    registry {
        use "docker" {
          image = "saiyam911/example-nodejs"
          tag = "1"
          disable_entrypoint = true
  }
    }
 }

  deploy { 
    use "kubernetes" {
        probe_path = "/"
        service_port = 5000
}
  }

  release {
    use "kubernetes" {
      node_port = 31766 
      port = 5000
    }
  }
}
```

Now I get readiness probe failed for this. 
When I manually remove the readiness and. liveliness probes everything succeeds but the nodeip:nodeport does not display anything. 

Though the image pushed to docker hub when I try to run that manually it runs fine as docker run -p 5000:5000 image name

 I tried it on my personal repository as well the same issue first readiness/liveliness probe and then if I remove manually from the deployment it succeeds but service I am not able to access through no errors on deployment, service is there and endpoint also created.

**Comment by saiyam1814** [comment]
I am in a process of writing a blog which is stuck due to the above, if I am able to solve this it would at least solve other 4-5  opened issues as well :)

**Comment by nicholasjackson** [comment]
@saiyam1814 I am just giving this a check, when I have an application which is listening on port 5000 using the default `service_port=5000` creates the correct readiness probes for me.

```
    Liveness:       http-get http://:5000/ delay=5s timeout=5s period=10s #success=1 #failure=5
    Readiness:      http-get http://:5000/ delay=5s timeout=5s period=10s #success=1 #failure=3
```

My application then starts, there was an issue earlier on with the URL service which was stopping applications using the entrypoint from starting. This has been fixed now so I wonder if you were running into this issue?

Would you do two things for me please:

1. Could you send me your example app so I can run it here.
2. Could you send me the logs for the container `kubectl logs waypoint_app_name`.

Kind regards,

Nic

**Comment by saiyam1814** [comment]
just to confirm you have 
```
deploy {
    use "kubernetes" {
        probe_path = "/"
        service_port = 5000
}
```
in the waypoint.hcl file @nicholasjackson

**Comment by nicholasjackson** [comment]
Yes,

This is the config I am using

```javascript
project = "wpmini"

app "wpmini" {
  labels = {
    "service" = "wpmini",
    "env" = "dev"
  }

  build {
    // Use Build packs to auto detect applcation code and create
    // a Docker image
    use "pack" {}

    // Store the built image in a Docker registry
    registry {
      use "docker" {
        image = "docker-registry.container.shipyard.run:5000/wpmini7"
        tag = "latest"
        local = false
      }
    }
  }

  // Deploy the application from Kubernetes
  // image created in previous step is automatically used
  deploy {
    use "kubernetes" {
      probe_path = "/"
      service_port = 5000
    }
  }

  // Release the image, this creates a loadbalancer and
  // makes the application publically accessible
  release {
    use "kubernetes" {
      node_port = 31766
      port = 5000
    }
  }
}
```

**Comment by saiyam1814** [comment]
Yes it worked and as promised here is the complete blog for the same - https://www.civo.com/learn/waypoint-solving-the-build-deploy-and-release-problem
@nicholasjackson @mitchellh

**Comment by mitchellh** [comment]
Great thank you so much @saiyam1814 !
