### ISSUE TITLE
install/k8s: kind requires LoadBalancer 

### ISSUE THREAD

**Issue by akin-ozer** [hashicorp/waypoint#527]
This guide shows that if we have minimal kind cluster then we can install waypoint but we still need LoadBalancer requirement 
and we should use metallb or something like that: https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes

**Steps to Reproduce**
Following the guide doesn't end you up in a working state.

**Expected behavior**
Example should be complete with LoadBalancer installation or configuring waypoint to use NodePort.

**Comment by ronakbanka** [comment]
@mitchellh I've written this Blog to use Waypoint with K8s inbuilt from Docker Desktop, works like a charm as LoadBalancer Type is exposed on localhost 👍 

https://medium.com/@ronakbanka/getting-started-with-hashicorp-waypoint-and-kubernetes-c818607c9b05

**Comment by mitchellh** [comment]
We now detect kind and show a warning about requiring more. We're also updating the docs today.
