### ISSUE TITLE
Waypoint Helm Chart

### ISSUE THREAD

**Issue by SubatomicHero** [hashicorp/waypoint#529]
Being able to deploy the Waypoint Server in a K8s cluster that exposes everything needed in a simple manner is needed. Then, our Gitlab CI/CD process can communicate with Waypoint without running the server in that process.

**Comment by evanphx** [comment]
Could you link to how Gitlab allows Helm in this way? Just want to be sure we hit your use case, since it sounds it's not a simple "run something before hand" since then you could use `waypoint install` I presume?

**Comment by SubatomicHero** [comment]
Dont have any links. Just the use case where we dont want to install waypoint as part of the CI/CD process. It could/should be maintained externally. The pipeline then just has to connect to Waypoint and run the process. We could start adding metrics to waypoint to get an understanding of its usage (if it were external)

**Comment by curtbushko** [comment]
I don't think you would need to anything special with Gitlab CI/CD to get it working with waypoint if it was running on a kubernetes server. To get it running, the steps would include:

- Install waypoint server with exposed endpoint
- Install waypoint binary in a container that gitlab runner would use (it uses docker-in-docker)
- Call waypoint up directly as part of the gitlab pipeline.

Note: this is almost the same pattern that I follow for using gitlab runners, terraform and kubernetes.

**Comment by aditsachde** [comment]
I'd appreciate this for another reason. Everything in my cluster is deployed using fluxcd, ensuring that the state of my cluster matches the desired state in git, so I didn't want to just do `waypoint install`. I wrote a custom deployment for just the single waypoint pod, and its pretty straightforward, however, a helm chart be very useful for things like HA or deploying a custom URL service alongside waypoint.

**Comment by mitchellh** [comment]
For Waypoint 0.6 we'll have a helm chart and the `waypoint install` for Kubernetes will use this chart: https://github.com/hashicorp/waypoint-helm

(Note, it requires 0.6 which as of this post is unreleased)
