### ISSUE TITLE
Waypoint getting started on Docker doesn't work

### ISSUE THREAD

**Issue by girikuncoro** [hashicorp/waypoint#530]
**Describe the bug**
`waypoint up` deploys the example nodejs app, but the URL is not accessible.

**Steps to Reproduce**
Follow the steps in getting started section [here](https://www.waypointproject.io/docs/getting-started) to use waypoint with docker.

**Expected behavior**
The preview URL should display the static nodejs page.

**Comment by rvbuelow** [comment]
I've ran into the same problem:

I've used the following Dockerfile
```
FROM nginx
```

So i've tried to run the Docker image created by Waypoint using `docker run --rm -ti waypoint.local/web:latest` which resulted in the the following error message:
```
/waypoint-entrypoint: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /waypoint-entrypoint)
```

**Comment by Siyfion** [comment]
I too am getting issues with the Getting Started tutorial with the example `docker/nodejs` project:

![Screenshot 2020-10-16 at 11 35 47](https://user-images.githubusercontent.com/338488/96248682-d6a2a000-0fa3-11eb-9ff7-12bf8811e9b9.png)

![Screenshot 2020-10-16 at 11 36 00](https://user-images.githubusercontent.com/338488/96248689-d904fa00-0fa3-11eb-8dd4-a039208d4956.png)

I wonder if the Waypoint service at Hashicorp's end is having issues post-launch demand?

**Comment by jgarcia-starz** [comment]
Just ran into the same issue as @Siyfion ☝️

**Comment by conorseabrook** [comment]
I experienced the same issue. Destroyed and tried a few times, no luck. Also no response from the docker instance going directly to the published port.

**Comment by gtirloni** [comment]
So this is inside the container started by `waypoint up`:

```
$ docker exec -ti example-nodejs-01EMRQDJCSTASQJN826FS8JJEY /bin/sh
$ ps axf
    PID TTY      STAT   TIME COMMAND
     25 pts/0    Ss     0:00 /bin/sh
     30 pts/0    R+     0:00  \_ ps axf
      1 ?        Ssl    0:00 /waypoint-entrypoint /cnb/lifecycle/launcher
```

Tried to start the image myself and it seems to work fine:

```
$ docker run --rm -ti example-nodejs:latest
2020-10-16T13:22:02.391Z [TRACE] starting interrupt listener for context cancellation
2020-10-16T13:22:02.391Z [TRACE] interrupt listener goroutine started
2020-10-16T13:22:02.392Z [INFO]  entrypoint starting: deployment_id= instance_id=01EMRS63GR6MX83HDE984CTHK6 args=[/cnb/lifecycle/launcher]
2020-10-16T13:22:02.392Z [INFO]  entrypoint version: full_string="Waypoint v0.1.1" version=v0.1.1 prerelease= metadata= revision=
2020-10-16T13:22:02.392Z [INFO]  init: no waypoint server configured, disabled entrypoint
2020-10-16T13:22:02.392Z [INFO]  starting child process: args=[/cnb/lifecycle/launcher] cmd=/cnb/lifecycle/launcher
Listening on 5000
```

```
$ docker exec -ti loving_nobel /bin/sh
$ ps axf
    PID TTY      STAT   TIME COMMAND
     26 pts/1    Ss     0:00 /bin/sh
     31 pts/1    R+     0:00  \_ ps axf
      1 pts/0    Ssl+   0:00 /waypoint-entrypoint /cnb/lifecycle/launcher
     16 pts/0    Sl+    0:00 node index.js
```

I tried to `waypoint destroy/up` a few times and it's always the same thing. The Node.js process is not running inside the container started by waypoint.

**Comment by nymous** [comment]
FYI if I skip the waypoint entrypoint (https://www.waypointproject.io/docs/entrypoint/disable) I can access the published port on the container.

**Comment by hev** [comment]
It's DNS... 💯 

+1 to hitting this on both NPM and Java examples. Ruby didn't build for me. Still getting a feel for things but I wish it was easier/faster to figure out what's running locally in docker as it seems like things mostly worked.

**Comment by mitchellh** [comment]
Dupe #519  we're looking into it.
