### ISSUE TITLE
Waypoint getting started for GKE cluster doesn't work

### ISSUE THREAD

**Issue by girikuncoro** [hashicorp/waypoint#532]
**Describe the bug**
`waypoint up` is timing out because of unhealthy pods
```
$ waypoint up
...
» Deploying...
 + Kubernetes client connected to <redacted> with namespace default
 + Creating deployment...
⠹ Waiting on deployment to become available: 1/1/0
! Deployment was not able to start pods after 10m0s
```
The reason of timeout is because the pods keep restarting due to failing readiness/liveness probes.

**Steps to Reproduce**
Follow the steps to deploy Waypoint apps to Kubernetes (the GKE part) https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes

**Expected behavior**
`waypoint up` should deploy successfully.

**Additional context**

**Comment by evanphx** [comment]
Can you give us some info about your application? And also the waypoint.hcl file you're using? If it's failing the probes, it's a question of what you're app is up to mostly.

**Comment by mitchellh** [comment]
Its been about a week and we haven't heard additional reports of this (and we've seen thousands more seemingly run through the GKE example). If you determine more information please respond and let us know, otherwise I will close this for now.
