### ISSUE TITLE
Waypoint getting started: Kind cluster image registry side load not completed

### ISSUE THREAD

**Issue by AlexsJones** [hashicorp/waypoint#537]
**Describe the bug**
After completing the Waypoint installation on Kind, the nodejs deployment has an `ImagePullBackOff` error with warning

```
Warning  Failed     8m17s (x4 over 9m47s)   kubelet, kind-control-plane  Failed to pull image "example-nodejs:1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/ │
│ example-nodejs:1": failed to resolve reference "docker.io/library/example-nodejs:1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: aut │
│ horization failed
``` 

**Steps to Reproduce**
1.  Follow this guide https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes
2. `kind install cluster` 
3. ` waypoint install --platform=kubernetes -accept-tos` ( I manually had to exit this once deployment was complete due to another issue https://github.com/hashicorp/waypoint/issues/531 )
4. `waypoint init`
5. `waypoint up`

**Expected behavior**
Expected behaviour is `example-nodejs:1` would have been side loaded via the `kind load docker-image` mechanism into the internal registry or similar. Ultimately resulting in a successful in cluster pull.

**Additional information**
```
 kind version
kind v0.9.0 go1.15.2 darwin/amd64
```

```
waypoint version
Waypoint v0.1.1 (44e2d3d6)
```

```
docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
 OS: macOS Catalina 10.15.6 19G2021 x86_64
 Host: MacBookPro16,2
Kernel: 19.6.0
```

**Comment by saiyam1814** [comment]
So basically the Ideo here is that it should take a local image that gets build on the system, now it won't be there for k8s deployment and when kubernetes tries to pull form this it throws an error, so you have to have to push it you your docker hub and the image pull part will be resolved and you will get stuck on the next one :D

**Comment by AlexsJones** [comment]
> So basically the Ideo here is that it should take a local image that gets build on the system, now it won't be there for k8s deployment and when kubernetes tries to pull form this it throws an error, so you have to have to push it you your docker hub and the image pull part will be resolved and you will get stuck on the next one :D

My expectation is for AKS/Kind/GCP it leverages each of those providers registry strategies ( Pushing to ECR/Container registry etc.. )
```
 If the registry clause is not present, Waypoint will default to using the local Docker instance to store the application's artifacts.
```
It is not entirely clear to me whether this runs a local registry on the localhost or uses the Kind side loader.

**Comment by saiyam1814** [comment]
Yeah the docs are not clear I have one more issue raise already :D 

What I understood is locally it creates the image and will try to use for kind cluster but for other respective registries, for existing kubernetes I used my own registry

**Comment by nicholasjackson** [comment]
Hey all,

I am going to get the docs update on this, but as @saiyam1814 stated the issue is that the build is pushed to the local Docker registry which is not used by Kind.

Kind uses its own version of ContainerD inside the Kind container and does not share the Docker Engine on which it is running. There are a number of solutions to this, the easiest is to not use `local = true` and to use a remote registry for your Docker image.

```javascript
      use "docker" {
        image = "remote.registry/nodejs-example"
        tag   = "latest"
        local = false
      }
```

The other option is that you run your own docker registry locally which can be accessed by the Kind server.

Sorry for the confusion in the Docs, will get these updated ASAP.

Nic
