### ISSUE TITLE
CLI: enhance the config command experience

### ISSUE THREAD

**Issue by rugwirobaker** [hashicorp/waypoint#561]
**Describe the solution you'd like**
* Adding the -all flag to config command which would print all the variables set in that project.(ALREADY IMPLEMENTED by config get)
````sh
➜  ✗ waypoint config get -all
  SCOPE | NAME | VALUE  
--------+------+--------
        | PORT     |  8000  
        | PASSWORD | password
        | USERNAME | username
        | .....    | .....
````

* Also maybe a flag `-raw` to get the VALUES without the tabular format in case you want to pipe them to a file(.env)
```sh
➜ ✗  waypoint config get -all -raw | tee .env
PORT=8000  
PASSWORD=password
USERNAME=username
````

* Another welcome feature would be to be able to pipe KEY/VALUE pair in the form of `KEY=VALUE` to the `config set` command
```sh
➜  ✗cat .env |  waypoint config set 
````
**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by mitchellh** [comment]
These are all good suggestions.

For the first suggestion: what do you mean "all the variables set in that project" ? Is this not how `waypoint config get` behaves today? I'm sure I'm misunderstanding something here.

**Comment by rugwirobaker** [comment]
Ohhh my bad I think it works.
