### ISSUE TITLE
Support Multiple Docker Images for ECS Deployment

### ISSUE THREAD

**Issue by flowirtz** [hashicorp/waypoint#563]
I found [this tutorial](https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/deploy-aws) really helpful and love the idea of Waypoint!

I'd like to start using it for my ECS deployments. For my use case I have multiple docker images in the same ecs service however. I couldn't figure out a way to replicate that in Waypoint. It seems like it's always one registry and one image per ECS service.

That's why I'd like to request the option to support multiple tasks/images in one service.

**Comment by evanphx** [comment]
The reason we don't support that is it's hard to figure out the mapping between the build phase (which generates one docker image) and ECS, which can support multiple containers.

Can you give us some examples of what you're doing here? Would be enough to allow you the ability to hardcode the additional container information in the config, ie maybe you're using some sidecar containers?

**Comment by apaz037** [comment]
+1 I'm currently running the xray daemon as a sidecar in most of my tasks and would love to be able to leverage waypoint.

**Comment by sveniu** [comment]
Another use case: In all our ECS tasks, we have the main application container plus two side-cars: The Datadog Agent container, and the AWS FireLens (aka Fluent Bit) container. These enable forwarding of metrics and logs to Datadog, without having to take the slow detour via AWS CloudWatch.

**Comment by mitchellh** [comment]
This is available in WP 0.1.3
