### ISSUE TITLE
Put Changelog Details in GitHub Release

### ISSUE THREAD

**Issue by RichiCoder1** [hashicorp/waypoint#565]
In short, it'd be great to see Changelog details in the GitHub Release information. We use GitHub releases as a release tracker, and it's frustrating to get a release notification and then have to go to the changelog just to see what changed.

Idea spawned by #557

**Comment by mitchellh** [comment]
@krantzinator thoughts?

**Comment by krantzinator** [comment]
Yes this is the plan for handling the CHANGELOG and GitHub releases moving forward. I'll close this issue once it's part of our release pipeline.

**Comment by krantzinator** [comment]
These will be part of releases with 0.1.3 forward.
