### ISSUE TITLE
Add a flag to limit the amount old releases that 

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/waypoint#566]
**Is your feature request related to a problem? Please describe.**
At the moment there doesnt seem to be a way for waypoint to cleanup after itself, and your e.g nomad/k8s will quickly fill up with running releases that will never be shown to any users ever again.

**Describe the solution you'd like**
Adding some config flag to the release stanza that allows the operator to decided how many old releases to keep running after release version N+1. for e.g roll back purpose.

**Describe alternatives you've considered**
A date based expiration flag

**Comment by mitchellh** [comment]
We should only keeping the last two deployments. Is this not happening for you? `waypoint destroy` should then remove them all. I think there is a bug around Nomad destroy which we need to look into but the rest should be working. Can you verify this and if not provide some steps to repro?

**Comment by attachmentgenie** [comment]
for me it is not cleanup, i have made 5 changes to the app and redeployed using "waypoint up" and i still have 5 jobs running. but since i also reported #560 this might be related.

I followed https://learn.hashicorp.com/collections/waypoint/get-started-nomad with nomad (v0.12.5 (514b0d66..))
) and waypoint (v0.1.1 (44e2d3d6)) installed from the hashicorp apt repo

**Comment by mitchellh** [comment]
Yes I think its all related to that. I've reproduced #560 once I fix that you should be good to go.
