### ISSUE TITLE
aws-ecs (on EC2): no memory/cpu combinations valid?

### ISSUE THREAD

**Issue by nickatsegment** [hashicorp/waypoint#574]
**Describe the bug**
For aws-ecs deployments on EC2 (i.e., not Fargate), I cannot seem to find a valid memory+CPU combination. 

This includes not having set it at all. [According to the docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html), this is not a required field.

**Steps to Reproduce**

1. Create an ECS cluster using EC2 nodes.
2. Try to deploy an app using this:
```
    deploy {
        use "aws-ecs" {
          cluster = "blah"
          ec2_cluster = true
          memory = "512"
          region = "us-west-2"
        }
    }
```
3. I always get an error:

```
! ClientException: Invalid 'cpu' setting for task. For more information, see the
  Troubleshooting section of the Amazon ECS Developer Guide.
```

**Expected behavior**

**Additional context**
ECS cluster (EC2):
- 1 instance
- t3.large (CPU: 2048, RAM: 7874)

I'm going to attempt to repro and get a little more info with a custom build.

**Comment by mitchellh** [comment]
We document valid values here: https://www.waypointproject.io/plugins/aws-ecs

Sorry for the formatting is terrible there right now we're gonna try to improve that!

**Comment by nickatsegment** [comment]
@mitchellh those docs only talk about valid values for fargate?

**Comment by mitchellh** [comment]
Oh I misread! I think so yes. Let me reopen and ping @evanphx or @anubhavmishra for further info.

**Comment by nickatsegment** [comment]
Just a quick look at the code, I see no way that `Cpu` could be `nil`, which is a valid thing to do.

**Comment by nickatsegment** [comment]
This little hack lets me set `Cpu: nil`, and I'm making progress now. Not sure about other values yet.

**Comment by nickatsegment** [comment]
Hm, something's always setting `cpuShares` to `0` it would seem. And the AWS API doesn't like `Cpu: aws.String("0")`.
