### ISSUE TITLE
custom plugin not detected

### ISSUE THREAD

**Issue by nicolai86** [hashicorp/waypoint#578]
**Describe the bug**
When following the [waypoint creating plugins](https://www.waypointproject.io/docs/extending-waypoint/creating-plugins) guide, the created plugin is not detected by `waypoint init`:

```
❯ waypoint init
✓ Configuration file appears valid
✓ Local mode initialized successfully
✓ Project "example_app" and all apps are registered with the server.
❌ Failed to load and validate plugins!

! This validation check ensures that you have all the required plugins available
  and the configuration for each plugin (if it exists) is valid. The error message
  below should tell you which plugin(s) failed.

! 1 error occurred:
  	* plugin "bazel" not found


! Project had errors during initialization.
  Waypoint experienced some errors during project initialization. The output
  above should contain the failure messages. Please correct these errors and
  run 'waypoint init' again.
```

**Steps to Reproduce**
1. Follow the [guide](https://www.waypointproject.io/docs/extending-waypoint/creating-plugins) until you `make` - change your plugin name to `bazel`. 
2. Run `make install`
3. verify the plugin exists:

```
❯ stat $HOME/.config/waypoint/plugins/waypoint-plugin-bazel
16777220 238971436 -rwxr-xr-x 1 nicolai86 staff 0 19054204 "Oct 16 20:21:35 2020" "Oct 16 20:29:55 2020" "Oct 16 20:29:55 2020" "Oct 16 20:17:27 2020" 4096 38912 0 /Users/nicolai86/.config/waypoint/plugins/waypoint-plugin-bazel
```

4. run `waypoint init` on an example project

example waypoint.hcl:

```
project = "example_app"

app "web" {
    build {
        use "bazel" {
            target = "//cmd/server"
        }
    }

    deploy {
        use "docker" {}
    }
}

```

**Expected behavior**
As described in the guide, I expect waypoint init to succeed.

**Additional context**
modified [builder.go](https://gist.github.com/nicolai86/8cf415434c9661fad073e5ed2f643309) file.

**Comment by mitchellh** [comment]
The guide worked for me. Please run init with `-vv` and look for a line like the following to ensure that Waypoint is searching in the correct place. If you don't have an `$XDG_CONFIG_DIR` set then it may be searching somewhere else:

```
2020-10-17T11:32:12.743-0700 [DEBUG] waypoint.runner: plugin search path: job_id=01EMVXARPMVCPYWE4FPECZY30B path=[, .waypoint/plugins, /Users/mitchellh/.config/waypoint/plugins]
```

I'm going to add this troubleshooting to the docs now!
