### ISSUE TITLE
Broken GitHub actions demo URL

### ISSUE THREAD

**Issue by edtan** [hashicorp/waypoint#579]
**Describe the bug**
In the [GitHub actions documentation](https://github.com/hashicorp/waypoint/blob/main/website/content/docs/automating-execution/github-actions.mdx), there is a link to [hashicorp/action-waypoint-demo](https://github.com/hashicorp/action-waypoint-demo).  However, the link returns a 404.

**Steps to Reproduce**
Visit https://github.com/hashicorp/action-waypoint-demo when not signed into GitHub.

**Expected behavior**
Link to GitHub actions demo content.

**Comment by pearkes** [comment]
Thanks for the report! See #588, I think to minimize confusion between the two actions it's better to just remove the link to that (private) repo, as it might mislead people as time goes on.
