### ISSUE TITLE
Submission to DoD DCAR (Iron Bank)

### ISSUE THREAD

**Issue by anoncam** [hashicorp/waypoint#594]
**Describe the solution you'd like**
I would like to use waypoint for Department of Defense production projects, which will require submission and accreditation via the [DCAR Pipeline](https://repo1.dsop.io/dsop/dccscr).

**Describe alternatives you've considered**
Hashicorp currently provides vault containers to the DCAR, but the only way for me to begin using waypoint is to request the submission of the container to the Container Hardening Team (CHT).
**Explain any additional use-cases**
Once hardened, waypoint can be used by any DoD program, which will undoubtedly increase the userbase and feedback to the upstream source here.

**Comment by mitchellh** [comment]
Hello, at this stage of the project we’re not currently attempting any accreditation/compliance. We have a team dedicated to these sorts of activities and I’ll forward this to them. If someone in the community wants to do this then they’re welcome to in the mean time. Feel free to email us at hello@hashicorp.com as well and we can have some of our field team follow up with you directly.
