### ISSUE TITLE
Templating support for Docker builder plugin

### ISSUE THREAD

**Issue by psyhomb** [hashicorp/waypoint#595]
It would be nice to implement templating support for Docker builder plugin so we can use go template syntax in `Dockerfile`.

That way it would be possible to pass e.g. docker base image name and tag via environment variables (CI/CD) instead of hardcoding it.

Or to introduce `--build-arg` as variable (`map[string]string`).

Dockerfile
-------------

**w/o template support**:

```dockerfile
FROM ubuntu:20.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENV SERVICE_NAME="foo"

RUN apt-get update -y && apt-get install python3-pip -y

ADD requirements.txt /app/
WORKDIR /app
RUN /bin/bash -c "pip3 install --no-cache-dir -r requirements.txt"

ADD /app/ /app/

EXPOSE 8080

CMD ["gunicorn", "-b", "0.0.0.0:8080", "wsgi", "-k", "gevent"]
```

**w/ template support**:

```dockerfile
FROM {{ index .Env "DOCKER_BASE_IMAGE_NAME" }}:{{ index .Env "DOCKER_BASE_IMAGE_TAG" }}

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENV SERVICE_NAME={{ index .Env "SERVICE_NAME" }}

RUN apt-get update -y && apt-get install python3-pip -y

ADD requirements.txt /app/
WORKDIR /app
RUN /bin/bash -c "pip3 install --no-cache-dir -r requirements.txt"

ADD /app/ /app/

EXPOSE 8080

CMD ["gunicorn", "-b", "0.0.0.0:8080", "wsgi", "-k", "gevent"]
```

Build
------

```hcl
project = "foo"

app "foo" {
  build {
    use "docker" {}
  }

  deploy { 
    use "docker" {
        service_port = 8080
    }
  }
}
```

```bash
export DOCKER_BASE_IMAGE_NAME="ubuntu"
export DOCKER_BASE_IMAGE_TAG="20.04"
export SERVICE_NAME="foo"

waypoint build
```

**Comment by mitchellh** [comment]
Thanks! I’ve been thinking about a generic templating solution for Waypoint and will bring this up with the team this week. Then we can avoid this in all future plugins as well. I’ll keep this open for now until we have an issue tracking that.

**Comment by mitchellh** [comment]
Note this is in a PR and slated for 0.2 here: #757

**Comment by mitchellh** [comment]
This is done!
