### ISSUE TITLE
Pack Plugin support for non-default process types.

### ISSUE THREAD

**Issue by jbayer** [hashicorp/waypoint#598]
**Is your feature request related to a problem? Please describe.**
Buildpacks support multiple types of processes beyond the default, which is web. Today the Waypoint pack plugin does not support that.

**Describe the solution you'd like**
Be able to specify a different Buildpack image process type using the pack plugin for a Waypoint deployment.

**Additional context**
Here is [buildpacks documentation](https://buildpacks.io/docs/app-developer-guide/run-an-app/#non-default-process-type) on how to specify a launch process, including non-default ones.

**Comment by evanphx** [comment]
In this case, would it also mean supporting non-web workloads?

**Comment by mitchellh** [comment]
Yeah, the use case was from the discuss forum of someone trying to deploy a background worker as a separate app. I think this makes sense.

**Comment by mitchellh** [comment]
Note: there's obviously improvements we can make around not registering the URL service and so on, but I think in the mean time this will just work, just not optimally.

**Comment by evanphx** [comment]
Well, I ask partly because the "web" process label is just that, a label. I'm trying to see if @jbayer is thinking that if a user used, say, a "worker" label, we'd automatically detect that and deploy it as non-web.

We could also just mostly ignore the non-default process types and have the user configured the workload type in waypoint itself.

**Comment by mitchellh** [comment]
Ah I see. I don't think that matters today right? But thinking towards the future, I think we can do something similar to Heroku where `web` is a special case that means you get a PORT available. The rest are assumed to be non-web yeah but maybe we can expose future config to force them as web.

I'm not sure, but I know the immediate pain is just launching non-web workloads :)

**Comment by evanphx** [comment]
Righto, the pain is absolutely non-web workloads. I was trying to figure out if we could mostly ignore this issue so long as non-web workloads work fine (which I think we can).

**Comment by jbayer** [comment]
I should have linked to [the original discuss post](https://discuss.hashicorp.com/t/non-web-workloads/16147/7). Yes in this particular case it's non-web workloads.

E.g. Imagine you have this example from `pack inspect-image` (which is [from the buildpacks docs](https://buildpacks.io/docs/app-developer-guide/run-an-app/#non-default-process-type))

```
Processes:
  TYPE                 SHELL        COMMAND                                                     ARGS
  web (default)        bash         java -jar target/sample-0.0.1-SNAPSHOT.jar
  sys-info             bash         /layers/samples_hello-processes/sys-info/sys-info.sh
```
Then perhaps the pack plugin could be enhanced with a process_type variable:

```
build {
  use "pack" {
    process_type = "sys-info"
  }
}
```

**Comment by evanphx** [comment]
Ok, I thought perhaps it was that discussion. I don't think it has much to do with non-default process types with pack, especially since users might not even use pack for their non-web build process.
