### ISSUE TITLE
AWS EKS Fargate `waypoint install` Support

### ISSUE THREAD

**Issue by bassrock** [hashicorp/waypoint#599]
**Is your feature request related to a problem? Please describe.**

I tried to deploy Waypoint onto EKS using only a Fargate profile. However it won't deploy for a few reasons:
* Fargate requires the use of EFS as a persistent volume store. I tried setting this up manually as a pv and made it the default so Waypoint would select it automatially. Once I did this and made the volume have 777 permissions it would boot up.
* When using fargate you need to use an ALB which requires you to use Ingress with a ALB annotation https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html  Because the LoadBalancer is setup using a Service you can not edit it to use an ALB instead.

**Describe the solution you'd like**
When you run waypoint install I would expect to be able to pass --fargate and it would make all the necessary changes to make this possible.

**Describe alternatives you've considered**
I've tried manual edits after creation but it started to become to much.

**Comment by mitchellh** [comment]
With `waypoint install` we'd like to keep it fairly generic for the time being. For use cases like this we recommend manually deploying the waypoint server and we'll work on things such as #529 to make that easier. We don't want `waypoint install` to be an option that works for a variety of platform edge cases 😄 

In the mean time, I recommend looking into running the server manually: https://www.waypointproject.io/docs/server/run

**Comment by fagiani** [comment]
@bassrock would you mind sharing how did you get the waypoint service to boot up? Did you successfully had it working on EKS Fargate with EFS? It would be very helpful if you could share more details on how you did it both for EFS and ALB.

Thanks a bunch!
