### ISSUE TITLE
Using AWS profile with assumed role raises NoCredentialProviders

### ISSUE THREAD

**Issue by matthewlehner** [hashicorp/waypoint#604]
**Describe the bug**
I'm using an AWS profile that's an assumed cross-organization role. When running `waypoint build` with `AWS_PROFILE` set to the profile for the role, `waypoint build` fails when trying to push the image to the ECR repo with the following error:

```
! NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Steps to Reproduce**
With a second AWS organization, set up cross organization roles following this guide: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
Then [configure the role for use with the CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) and use the `AWS_PROFILE` env variable to specify that URL.

For example, `~/.aws/config` will contain the following:

```
[profile default]
region = us-east-1

[profile otherprofile]
role_arn = arn:aws:iam::123456789012:role/marketingadminrole
source_profile = default
```

When running `AWS_PROFILE=otherprofile waypoint build`, it's unable to find credentials, though running other `aws` commands from the CLI works.

FWIW, this setup is working with terraform.

**Expected behavior**
It works with the profile/credentials that are specified by `AWS_PROFILE`.

**Comment by jdub** [comment]
Waypoint is probably using version 1 of the AWS SDK for Go – have you tried setting `AWS_SDK_LOAD_CONFIG=1` in your environment? Because I use so much Go stuff with AWS, I've put it in my `.bash_profile`.

**Comment by matthewlehner** [comment]
@jdub Ah, thanks, that fixes it. I hadn't heard of that setting before now.

**Comment by mitchellh** [comment]
Good catch, I've got a PR up to fix this.
