### ISSUE TITLE
at new release creates some "intermediate" containers and not removes them once release is done

### ISSUE THREAD

**Issue by yevgeniyo** [hashicorp/waypoint#610]
**Describe the bug**
at new release creates some "intermediate" containers and not removes them once release is done
the same behaviour on "waypoint destroy", it removes containers itself with code, but not these intermediate ones

**Steps to reproduce**
Create python release
Change code
Create new python release

![Screen Shot 2020-10-18 at 17 20 22](https://user-images.githubusercontent.com/14246521/96370456-8e7fab00-1166-11eb-89ec-c3a229ee1fbb.png)
![Screen Shot 2020-10-18 at 17 21 13](https://user-images.githubusercontent.com/14246521/96370457-8fb0d800-1166-11eb-9559-f70c723bfbe0.png)

**Expected behavior**
no intermediate containers at new release and after the destroy command

**Comment by mitchellh** [comment]
I've seen this as well. I'm honestly not sure what is causing this and why they aren't getting cleaned up. A part of me has always felt this is Docker behaving poorly but I need to do more research if its our fault. 😄

**Comment by mitchellh** [comment]
@yevgeniyo Can you do a `docker inspect` on one of those and output that here?

**Comment by yevgeniyo** [comment]
Hi @mitchellh, sure thing

Please find files in attachments

[1.txt](https://github.com/hashicorp/waypoint/files/5406885/1.txt)
[2.txt](https://github.com/hashicorp/waypoint/files/5406887/2.txt)
[3.txt](https://github.com/hashicorp/waypoint/files/5406888/3.txt)
[4.txt](https://github.com/hashicorp/waypoint/files/5406889/4.txt)

**Comment by mitchellh** [comment]
@evanphx I think these are buildpack leftovers... I can't see an API on the Pack API to clean these up so perhaps this is a bug with pack. Could you take a quick look and share any thoughts?

**Comment by jbayer** [comment]
I played around a bit with this and it seems like I can consistently reproduce it with a start with a fresh Waypoint install using the docker python example app. I did not see it on subsequent `waypoint up` commands. I also did not see it by invoking `pack` with the Heroku builder directly.

```
$ docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED              STATUS                          PORTS                              NAMES
7139d532cf4c        waypoint.local/example-python:latest   "/waypoint-entrypoin…"   About a minute ago   Up About a minute               0.0.0.0:32792->8080/tcp            example-python-01EN3N8Z5ECSRX7E65Z0R8413G
45919c5e578e        c921d794ee63                           "/bin/sh -c '#(nop) …"   About a minute ago   Created                                                            funny_shamir
ed48dccb4310        9c4952624d60                           "/bin/sh -c '#(nop) …"   About a minute ago   Created                                                            strange_hertz
b3d2e4b32d6b        6cb9c94bbc2d                           "/bin/sh -c '/bin/ba…"   About a minute ago   Exited (0) About a minute ago                                      compassionate_almeida
a19c95ce3d3e        ed702536c38b                           "/bin/sh -c '#(nop) …"   About a minute ago   Created                                                            elated_cerf
ad64024b9a59        3ca26393e063                           "/bin/sh -c 'apt-get…"   About a minute ago   Exited (0) About a minute ago                                      dazzling_raman
ea3165495360        2964f1e3ca9f                           "/bin/sh -c '#(nop) …"   About a minute ago   Created                                                            brave_jepsen
c2c9f7079ec4        9140108b62dc                           "/bin/sh -c '#(nop) …"   About a minute ago   Created                                                            silly_feistel
0c5b372d7f53        hashicorp/waypoint:latest              "/usr/bin/waypoint s…"   2 minutes ago        Up 2 minutes                    0.0.0.0:9701-9702->9701-9702/tcp   waypoint-server
```

**Comment by doodlesbykumbi** [comment]
Dug into this a little bit. The Docker builder was not passing in the remove option to get rid of intermediate containers. Here's a PR https://github.com/hashicorp/waypoint/pull/667

**Comment by doodlesbykumbi** [comment]
@jbayer I think the reason you're able to consistently replicate this on the first run of the python example is because subsequent runs make use of the cached image and so have no build steps to generate intermediate containers.
