### ISSUE TITLE
waypoint install output should refer to HTTPS UI Address (not HTTP)

### ISSUE THREAD

**Issue by cpswan** [hashicorp/waypoint#611]
**Describe the bug**
Output of `waypoint install -platform=docker -accept-tos` ends with:

```
HTTP UI Address: localhost:9702
```

But the listener is HTTPS, and so if you browse to http://localhost:9702 you'll see:

```
Client sent an HTTP request to an HTTPS server.
```

**Steps to Reproduce**

Run `waypoint install -platform=docker -accept-tos` on a clean system

**Expected behavior**

Final line specifies that the UI is HTTPS, could even have a URL to make things easier e.g.

```
HTTPS UI Address: https://localhost:9702
```

**Comment by mitchellh** [comment]
I switched to just `web UI` since I think that makes more sense. The protocol in the URL is of course `https`
