### ISSUE TITLE
Unable to inject ceb into image with nix-based waypoint build

### ISSUE THREAD

**Issue by winpat** [hashicorp/waypoint#614]
I am trying to package waypoint 0.1.2 for the Nix package manager.
* https://github.com/NixOS/nixpkgs/pull/100994

**Describe the bug**
When using `waypoint up`, I get the following error:

```
...
 │ Successfully tagged waypoint.local/example-python:latest
⠸ Injecting Waypoint Entrypoint...
! unable to restore custom entry point binary: Asset ceb/ceb can't read by error:
  Read "ceb/ceb": gzip: invalid checksum
```
(The complete output is referenced in the context section below.)

I did spend a couple of hours learning about the go module system and go-bindata, but was not able to find the root cause. As you also use Nix, you might have a tip for me.

**Steps to Reproduce**

```
$ nix-env -f https://github.com/winpat/nixpkgs/archive/add_waypoint.tar.gz -iA waypoint
$ git clone https://github.com/hashicorp/waypoint-examples.git
$ cd waypoint-examples/docker/python
$ waypoint init
$ waypoint up
```
The `waypoint.hcl` that I've used can be found here:
* https://github.com/hashicorp/waypoint-examples/blob/c8f632147e10a5ec93e1f73a744ea986cfc364ec/docker/python/waypoint.hcl

**Expected behavior**
I would have expected that `ceb` would get successfully injected into the container.

**Additional context**

The full output with enabled verbose flags can be found here:
* https://gist.github.com/winpat/321145ab42bb5bddba7ea0adc66777b0

**Comment by mitchellh** [comment]
Hey @winpat, yeah, the way we build Waypoint with the CEB embedded is a bit strange. See our `make bin` task and you should have all the info you need. We build a Linux/amd64 version and embed that within the Waypoint binary. We choose Linux/amd64 since it is the most common deployment target but in the future we’ll probably have to do something else.

Hopefully that should be enough to get you going! Thanks for getting this in.

**Comment by winpat** [comment]
Thank you for your response @mitchellh. Unfortunately, I have already tried both the `bin` and `bin/linux` targets without any luck. I tried to keep the nix expression as close as possible to the instructions in CONTRIBUTING.md.

I slowly start to believe that nix breaks the binaries by patching them after the build. So this is probably a nix issue 😃 .

**Comment by mitchellh** [comment]
Indeed, note that `make bin` is how we make our _release builds_ too so it's definitely working. :)
