### ISSUE TITLE
Tutorial doesn't work out of the box

### ISSUE THREAD

**Issue by spuder** [hashicorp/waypoint#616]
Trying to follow along the waypoint tutorial gives inconsistent examples. (Understandably this is a 0.1 product). 

For example, the tutorial shows using a node.js application, however the user can not follow along because the tutorial doesn't provide the reference waypoint file

https://learn.hashicorp.com/tutorials/waypoint/get-started-intro

If a user tries to get started with waypoint using `waypoint init`, they will most likely get this error. 

```
» Building...
❌ Initializing Docker client...
! unable to create Docker context: unable to evaluate symlinks in Dockerfile path:
  lstat /Users/foobar/waypoint-fun/Dockerfile: no such file or
  directory
```

For a better user experience, either
A). Include the node-js example in the tutorial
B) Ship a working `waypoint init` example so users don't get the above error

<details><summary>waypoint.hcl</summary>
<p>

```python
# The name of your project. A project typically maps 1:1 to a VCS repository.
# This name must be unique for your Waypoint server. If you're running in
# local mode, this must be unique to your machine.
project = "my-project"

# Labels can be specified for organizational purposes.
# labels = { "foo" = "bar" }

# An application to deploy.
app "web" {
    # Build specifies how an application should be deployed. In this case,
    # we'll build using a Dockerfile and keeping it in a local registry.
    build {
        use "docker" {}

        # Uncomment below to use a remote docker registry to push your built images.
        #
        # registry {
        #   use "docker" {
        #     image = "registry.example.com/image"
        #     tag   = "latest"
        #   }
        # }

    }

    # Deploy to Docker
    deploy {
        use "docker" {}
    }
}```

</p>
</details>

**Comment by mitchellh** [comment]
Hello! I'll forward this feedback along to our learn team, I agree that it is a bit confusing here. Here is the link to the working example code: https://github.com/hashicorp/waypoint-examples/tree/main/docker/nodejs Which we eventually get to a couple steps later: https://learn.hashicorp.com/tutorials/waypoint/get-started-docker?in=waypoint/get-started-docker

I do agree the intro is misleading in thinking that'll work right away so I'm sending this to that team now and we'll get it cleaned up early this week. Thanks!

**Comment by spuder** [comment]
I did eventually find `git clone https://github.com/hashicorp/waypoint-examples.git` a few more pages in. A single sentence would have probably prevented any confusion.

> An example waypoint.hcl file will be provided later in this tutorial.

**Comment by mitchellh** [comment]
Yep totally, feedback already sent to that team and we should see this get resolved soon! Thank you.
