### ISSUE TITLE
Windows CLI can't make symlink

### ISSUE THREAD

**Issue by issacg** [hashicorp/waypoint#625]
When trying to execute the following:

`C:\Users\issac>waypoint.exe context create -server-addr=18.184.87.164:9701 -server-auth-token=bM152PWkXxfoy4vA5XXXDzNx3fPfAAdFpETSCpphtHR5tjyqr -server-require-auth=true  -set-default 18.184.87.164-ui` I get the following error:

```
! symlink C:\Users\issac\AppData\Local\waypoint\context\18.184.87.164-ui.hcl
  C:\Users\issac\AppData\Local\waypoint\context\_default.hcl: A required privilege
  is not held by the client.
```

**Comment by mitchellh** [comment]
I think on Windows we should just not use symlinks here since symlinks are full of challenges on Windows. Let's just copy the file cause its small...

**Comment by issacg** [comment]
FWIW, I'm not arguing to have the symlink (I don't know the system well enough yet to care either way), but [NVM](https://github.com/coreybutler/nvm-windows) managed to do symlinks on Win32 pretty well, if you decide that it's important...
