### ISSUE TITLE
Support deployment to remote Docker Hosts

### ISSUE THREAD

**Issue by tomwillfixit** [hashicorp/waypoint#627]
**Is your feature request related to a problem? Please describe.**

I would like to deploy my containerized app to a remote Docker Host or Docker Swarm cluster.

**Describe the solution you'd like**

Something like this in waypoint.hcl to allow the deploy to happen to a remote host : 
```
deploy { 
    use "docker" {
        remote_host=ssh://docker@your_server_ip
    }
  }
```

Support for Docker Swarm may be more complicated and out of scope of this request since Waypoint would need to support service creation, resource allocation etc.

**Describe alternatives you've considered**

Setting the DOCKER_HOST environment variable may work as is but I need to try it out.

**Explain any additional use-cases**

Docker Compose is very popular amongst developers for starting local and remote stacks, supporting remote docker hosts may make that easier using Waypoint.

**Additional context**

**Comment by nicholasjackson** [comment]
@tomwillfixit I have added this functionality in the following PR:

https://github.com/hashicorp/waypoint/pulls

I think for a more comprehensive Docker Swarm integration we should probably create a specific plugin.

**Comment by josephlim75** [comment]
For a workaround, can we execute the following ?,  Of course docker environment need to be set beforehand, `DOCKER_HOST`, `DOCKER_CERT_PATH`, and `DOCKER_TLS_VERIFY`

```
deploy {
  use "exec" {
    command = ["docker", "stack", "deploy", "-c", "<TPL>", "stackname"]

  template {
    path = "./template/docker-compose.yaml"
  }
 }
}
```
