### ISSUE TITLE
Unable to deploy waypoint-examples

### ISSUE THREAD

**Issue by chasetb** [hashicorp/waypoint#636]
I received an error when attempting to deploy the [Getting Started with Waypoint](https://www.waypointproject.io/docs/getting-started) NodeJS example to AWS ECS. The error simply says:
```
! transport is closing
```
I know this implies an error during deployment but I don't know what I've done wrong or what to do to fix it. 

Here's a full `-vv` gist of the command output: https://gist.github.com/chasetb/0131dd52e7522b1909d855918a4db6f9
Here's a gist of my `waypoint.hcl` file: https://gist.github.com/chasetb/14374826d1e69fa5e2daf1c09cb37bab

**Comment by mitchellh** [comment]
Thanks for the log, PR to fix this is up and we're releasing a new version (0.1.3) today that will include this.
