### ISSUE TITLE
Docs: the hashicorp go-bindata doesn't work

### ISSUE THREAD

**Issue by rugwirobaker** [hashicorp/waypoint#641]
Having tried to build this project so many times without success I decided instead of using the hashicorp go-bindata: https://github.com/go-bindata/go-bindata I was gonna use this: https://github.com/kevinburke/go-bindata/ since it's the one that is used in the CI pipeline. This time it worked.

The hashicorp copy should perhaps be removed from the [contribution docs](https://github.com/hashicorp/waypoint/blob/main/.github/CONTRIBUTING.md)

**Comment by mitchellh** [comment]
Thanks! Resolved.
