### ISSUE TITLE
Error when "server-addr" option is used on server bootstrap

### ISSUE THREAD

**Issue by jaypif** [hashicorp/waypoint#645]
**Describe the bug**
Client is not create during server bootstrap
I am trying to run manually a server on an Kubuntu desktop.
I am using the latest release (0.1.3) but I also faced the issue with the previous one.

**Steps to Reproduce**

The server starts when I run the basic command
```
jp@jp-XPS$ waypoint server run -accept-tos
Warning! Default DB path will be used. This is at the path shown below.
The server stores persistent data here so this file should be saved and
consistent for every server run otherwise data loss will occur. It is
recommended that you explicitly set the "-db" flag as acknowledgement of
the importance of the DB file.



» Server configuration:

             DB Path: data.db
        gRPC Address: 127.0.0.1:9701
        HTTP Address: 127.0.0.1:9702
       Auth Required: yes
  Browser UI Enabled: yes
         URL Service: api.waypoint.run:443 (account: token)

» Server requires bootstrapping!

  New servers must be bootstrapped to retrieve the initial auth token for
  connections. To bootstrap this server, run the following command in your
  terminal once the server is up and running.
  
    waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify
  
  This command will bootstrap the server and setup a CLI context.

» Server logs:

2020-10-20T10:27:58.432+0200 [INFO]  waypoint.server: starting built-in server: addr=127.0.0.1:9701
2020-10-20T10:27:58.432+0200 [INFO]  waypoint.server.http: starting HTTP server: addr=127.0.0.1:9702
2020-10-20T10:27:58.432+0200 [INFO]  waypoint.server.grpc: starting gRPC server: addr=127.0.0.1:9701

^C2020-10-20T10:28:03.516+0200 [INFO]  waypoint.server.grpc: shutting down gRPC server
2020-10-20T10:28:03.517+0200 [INFO]  waypoint.server.http: shutting down HTTP server
2020-10-20T10:28:04.017+0200 [INFO]  waypoint.server: gracefully closing db: path=data.db
```

However when I follow the message to bootstrap the server (with the same options), the client context is not created
```
jp@jp-XPS$ waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify
! failed to create client: context deadline exceeded
```

When I follow this tutorial for docker: https://learn.hashicorp.com/tutorials/waypoint/get-started-docker the server is not started too.

Please note that nothing is listening on the port 9701.

**Expected behavior**
The bootstrap command should work and the server should be bootstrap . I should be able to create a client context too.

**Additional context**
My laptop is using a Kubuntu 18.04 distribution
I use a Waypoint 0.1.3

Maybe this issue is related to another one, if it is the case feel free to close this one and redirect me the original one.

**Comment by jaypif** [comment]
To be more precise, the issue seems to be llinked to `-server-addr=127.0.0.1:9701` option.

When I don't use it, the bootstrap is OK.

**Comment by mitchellh** [comment]
It appears you may have shut down the server prior to running bootstrap. You must continue running the server for bootstrap to work properly.

**Comment by jaypif** [comment]
Ok That's the part I missed. 
I though `bootstrap` should be done before running the server and not after.

Thanks @mitchellh

**Comment by mitchellh** [comment]
No problem!
