### ISSUE TITLE
Support auth for pulling container image

### ISSUE THREAD

**Issue by rluisr** [hashicorp/waypoint#646]
**Is your feature request related to a problem? Please describe.**
There is no way to pull container image from private registry.

**Describe the solution you'd like**
Add `auth` property to nomad plugin.

**Describe alternatives you've considered**
```hcl
deploy {
    use "nomad" {
      auth = {
        "username": "rluisr",
        "password": ""
      }
    }
  }
```

**Additional context**
PR #647

**Comment by nickethier** [comment]
closed by #647
