### ISSUE TITLE
AWS Lambda Build/Deploy Support

### ISSUE THREAD

**Issue by jason-riddle** [hashicorp/waypoint#649]
**Is your feature request related to a problem? Please describe.**
Using AWS Sam to build, deploy, and monitor Lambda functions does not always provide a good developer experience.

**Describe the solution you'd like**
I’d like to build/deploy/monitor Lambda functions with Waypoint.

**Describe alternatives you've considered**
The main alternatives include AWS Sam and Serverless. Both are okay, but Sam tends to focus on the whole serverless ecosystem versus providing a really solid, well-documented workflow for Lambda functions. Serverless sometimes requires adding/using community developed plugins which vary in quality and may require further customization in a non-obvious or non-standard way. Both are YAML driven which has it’s own set of limitations, mainly injecting variables and values sometimes require guessing what is the precise syntax required. Also, debugging YAML syntax errors are painful.

**Explain any additional use-cases**
I would like the build/deploy/monitor portion of Lambda to be really smooth. I’m not as concerned about the other pieces such as ALBs, Api Gateway, etc because it feels like Terraform + CICD is a better fit for managing those longer-lived infrastructure components.

**Comment by pearkes** [comment]
This was added in #1052.
