### ISSUE TITLE
AWS-ECS Plugin: Add loadbalancer scheme

### ISSUE THREAD

**Issue by pharindoko** [hashicorp/waypoint#652]
**Is your feature request related to a problem? Please describe.**
I can`t use an internal loadbalancer with the aws-ecs plugin

**Describe the solution you'd like**
add scheme property for the alb to the waypoint aws-ecs plugin

**Explain any additional use-cases**
internal non-public deployments

**Comment by pharindoko** [comment]
Hey,

any update on this ?
do you need more information ?

br,

Florian

**Comment by krantzinator** [comment]
@pharindoko Thanks for bringing this up. Is this related to https://github.com/hashicorp/waypoint/issues/1070? It looks like we do support using an internal load balancer, but there are other issues with the implementation?

**Comment by pharindoko** [comment]
Hey @krantzinator,
thanks for your reply.

Yes you support existing internal load balancers. 
But as far as I understood waypoint should be capable to create new load balancers (AWS alb/nlb) as well and in this case the possibility to create such a new load balancer with type "internal" is missing.

br,

Flo
