### ISSUE TITLE
Support for custom port configuration in ECS

### ISSUE THREAD

**Issue by mbamber** [hashicorp/waypoint#653]
It appears that the ECS plugin currently has no configuration options for container ports. I would like to be able to set the container port to a custom value.

**Additional context**
https://discuss.hashicorp.com/t/changing-the-port-of-an-ecs-deployment/16241/2

**Comment by mitchellh** [comment]
This is fixed in main now, will be in WP 0.1.4 (no scheduled release but sometime this week)
