### ISSUE TITLE
Incorrect address link to documentation in the waypoint config command

### ISSUE THREAD

**Issue by chadsly** [hashicorp/waypoint#657]
I'm running waypoint 0.1.2 on Windows

I typed 'waypoint config' to see the options, it returned the 'set' and 'get' information but it also returned a hyperlink for more information (https://waypointproject.io/docs/config).  That link does exist. Perhaps the correct address should be: https://www.waypointproject.io/docs/app-config

**Comment by mitchellh** [comment]
I believe this is resolved in WP 0.1.3 already! Please let me know if we missed it but we did do a sweep on this for that release.
