### ISSUE TITLE
waypoint_0.1.3_windows_amd64 does not execute

### ISSUE THREAD

**Issue by chadsly** [hashicorp/waypoint#658]
I was using waypoint 0.1.2.  It was working well enough.  I just updated to waypoint 0.1.3 and it doesn't execute.  I really don't know how to describe error other than the binary doesn't seem "complete".

Steps to repeat.
1. close all terminals
2. download the latest version of waypoint from: https://releases.hashicorp.com/waypoint/0.1.3/ (in my case I was using https://releases.hashicorp.com/waypoint/0.1.3/waypoint_0.1.3_windows_amd64.zip)
3. Unzip and move the binary to the PATH
4. open a terminal window and type "waypoint"

I expected the same waypoint option results from previous versions.  Instead I received exceptions:
`$ waypoint
Exception 0xc0000005 0x0 0x7ff9f2692fff 0x1f5ed900000
PC=0x1f5ed900000

syscall.loadlibrary(0xc00004bb80, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:154 +0xe5
syscall.LoadDLL(0x3a1d169, 0xa, 0xc000262b70, 0xc0000bbd30, 0x957834)
        /usr/local/go/src/syscall/dll_windows.go:83 +0x3bb
syscall.MustLoadDLL(...)
        /usr/local/go/src/syscall/dll_windows.go:101
github.com/xanzy/ssh-agent.winAPI(0x3a1d169, 0xa, 0x3a1dd82, 0xb, 0x12)
        /go/pkg/mod/github.com/xanzy/ssh-agent@v0.2.1/pageant_windows.go:68 +0x45
github.com/xanzy/ssh-agent.init()
        /go/pkg/mod/github.com/xanzy/ssh-agent@v0.2.1/pageant_windows.go:62 +0x19b
rax     0x7ff9f1cd6390
rbx     0x7ff9f1cd638e
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x1f5ed6b6fd0
rsp     0x77057ff100
r8      0x94b
r9      0x94b
r10     0x0
r11     0x94b
r12     0x7ff9f24a0000
r13     0x0
r14     0x7ff9f1cd6390
r15     0xc000007a
rip     0x1f5ed900000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b`

I'll spend some more time trying to verify this another way.  Can someone else confirm that this version is working in their Windows environment?

**Comment by mitchellh** [comment]
That is extremely weird... we didn’t update dependencies or change any Windows behavior for 0.1.3 so I’m not sure why this would happen. Getting additional verification would help here.

**Comment by chadsly** [comment]
I verified that 0.1.3 works on a different Windows machine.  This is not an issue with Waypoint.

**Comment by mitchellh** [comment]
Roger thanks, please let us know if we can help in any way. Closing.
