### ISSUE TITLE
Waypoint fails to build when DOCKER_HOST has an ssh scheme

### ISSUE THREAD

**Issue by aditsachde** [hashicorp/waypoint#663]
**Describe the bug**
Waypoint fails to build when `$DOCKER_HOST` has an `ssh://` scheme.

**Steps to Reproduce**
Set `DOCKER_HOST` to `ssh://username@host` and do `waypoint up`.

**Expected behavior**
I'm not sure if this should be a feature request, but I filed as a bug report because the Docker command supports hosts using an ssh scheme, so I'd expect waypoint to support it in the same way.  

**Additional context**
```
» Building...
Creating new buildpack-based image using builder: heroku/buildpacks:18
✓ Creating pack client
❌ Building image
 │ 2020/10/20 22:44:24.097615 DEBUG:  Pulling image index.docker.io/heroku/buildpac
 │ ks:18
! failed to fetch builder image 'index.docker.io/heroku/buildpacks:18': error
  during connect: Post
  "http://docker%!d(MISSING)ocker.domain.tld/v1.38/images/create?fromImage=heroku%!F(MISSING)buildpacks&tag=18":
  dial tcp: lookup docker@docker.domain.tld: no such host
```

**Comment by doodlesbykumbi** [comment]
Below, `client` and `cli` will refer to `github.com/docker/docker/client` and `github.com/docker/cli/cli` respectively.

As far as I can tell, this is an issue that will be present in anything that consumes `client`. `client` does not have any smarts to connect to the Docker API via SSH. However, `cli` does, see [connhelper](https://github.com/docker/cli/blob/master/cli/connhelper/connhelper.go).
> // Package connhelper provides helpers for connecting to a remote daemon host with custom logic.

I've put together a quick draft PR for this repo with a solution that uses `connhelper`, see https://github.com/hashicorp/waypoint/pull/664. Tested locally and it does the job.
