### ISSUE TITLE
Waypoint server UI unresponsive during builds

### ISSUE THREAD

**Issue by almonk** [hashicorp/waypoint#666]
**Describe the bug**
When building a Waypoint project (`waypoint up`) the server UI appears to be completely unresponsive to requests and the UI hangs.

**Steps to Reproduce**
* Build a waypoint project
* Visit the server UI 

**Expected behavior**
The server UI should be responsive all the time including during builds

**System**
* Chrome for macOS (Version 86.0.4240.80 (Official Build) (x86_64))
* macOS 10.15.7
* Docker for Desktop (latest)

---

I've noticed that this seems to happen intermittently. If I close the tab and open a new one, the UI seems responsive again.

**Comment by chadsly** [comment]
@almonk , I noticed that during a build on waypoint using the docker platform.  Which platform are you using?

**Comment by almonk** [comment]
@chadsly Chrome latest, macOS and Docker Desktop.

**Comment by pearkes** [comment]
@almonk Do you mind sharing the url path you're on when this is occurring? 

Also, if you're to reproduce consistently, for example:

1. Run `waypoint up`
1. Go to the main application page 
1. Click Builds

Please share those steps. Just trying to figure out how to debug this further, it's definitely possible the streaming logic on the build page is causing the hang.

**Comment by almonk** [comment]
@pearkes I can reproduce successfully with the following steps:

* Run `waypoint up`
* Open the ui `waypoint ui -authenticate`
* Visit the project / Deployments URL (https://localhost:9702/default/project-name/app/app-name/deployments)
* The UI is responsive and working until the CLI hits `Building image...`
* From the Deployments page the UI is suddenly completely unresponsive and remains so even after the build is finished

If I close the tab and open it again it works again fine.

**Comment by koesbong** [comment]
Hi @almonk, would you mind trying to reproduce it again? I just tried it and I wasn't able to reproduce it. Thank you!

**Comment by almonk** [comment]
@koesbong good news! I can't seem to reproduce this bug anymore so I'm going to close this issue
