### ISSUE TITLE
failed to create client: context deadline exceeded

### ISSUE THREAD

**Issue by wahmedswl** [hashicorp/waypoint#669]
**Describe the bug**

Every operation with ```waypoint``` cli results in ```failed to create client: context deadline exceeded```.

**Steps to Reproduce**
Steps to reproduce the behavior. Please include any `waypoint.hcl` files
if applicable.

i have ```multipass``` based ```ubuntu 20.04``` vm, initially everything worked. ```k3s``` is installed and ```waypoint``` server components are installed. 

```
kubectl get all
NAME                       READY   STATUS    RESTARTS   AGE
pod/waypoint-server-0      1/1     Running   2          160m
pod/svclb-waypoint-tfzps   2/2     Running   2          160m

NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                         AGE
service/kubernetes   ClusterIP      10.43.0.1       <none>         443/TCP                         3h39m
service/waypoint     LoadBalancer   10.43.141.177   172.20.20.45   9701:31813/TCP,9702:32692/TCP   160m

NAME                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/svclb-waypoint   1         1         1       1            1           <none>          160m

NAME                               READY   AGE
statefulset.apps/waypoint-server   1/1     160m
```

After restart, vm ip has been changed and now every ```waypoint``` cli invoke results in ```failed to create client: context deadline exceeded```. ```waypoint``` web ui is also available but not able to interact with the server. Any option to reset client to regenerate token etc as even not able to regenerate token as well with ```waypoint token new```

Thanks

**Comment by mitchellh** [comment]
If your Waypoint server address is changing, you'll have to change two things:

(1) `waypoint context` must be recreated with the new settings: https://www.waypointproject.io/docs/server#connecting
(2) `waypoint server config-set` must be called to set new advertise address settings: https://www.waypointproject.io/commands/server-config-set

The Waypoint server expects to be on a stable IP. Note the pod itself doesn't have to be (and isn't expected to be) stable, but the LoadBalancer or final advertised IP is expected to be stable.

**Comment by wahmedswl** [comment]
Hi, thanks for quick prompt @mitchellh. i guess its better to just delete context and re-init.

- ```waypoint context list```
- ```waypoint context delete xxxxxxxxxx```
- ```waypoint init```

Thanks

**Comment by mitchellh** [comment]
This will not reconnect to your server. If no context is available its probably using one-shot mode (using a local server, not connecting to your remote server).

**Comment by wahmedswl** [comment]
Oh, then re-creating context is the only option then. i was able to re-init but still context was not generated.

Thanks

**Comment by wahmedswl** [comment]
Hi, i am getting following error after creating new context

```
failed to create client: grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)
```

i have created context using

```
waypoint context create \
>     -server-addr=c1.k8s.cluster:9701 \
>     -server-auth-token=bM152PWkXxfoy4vA51JFhR7LsZXT1ADc6MDndoJU1VA28wjPNRLZEkF6FZPwqphWjfDDfWUy5s7ghNdvTUd1r1tRHj6BeuWgW3jM2 \
>     -server-tls \
>     -set-default waypoint-c1-k8s-luster
```

**Comment by mitchellh** [comment]
You must set ` -server-require-auth` on the context, sorry that's a bit of a weird UX.

**Comment by wahmedswl** [comment]
```
waypoint context create \
    -server-addr=c1.k8s.cluster:9701 \
	-server-require-auth \
    -server-auth-token=bM152PWkXxfoy4vA51JFhR7LsZXT1ADc6MDndoJU1VA28wjPNRLZEkF6FZPwqphWjfDDfWUy5s7ghNdvTUd1r1tRHj6BeuWgW3jM2 \
    -server-tls \
    -set-default waypoint-c1-k8s-cluster
```

still getting 

```
waypoint context verify
❌ Connecting with context "waypoint-c1-k8s-cluster"...
! Error connecting with context "waypoint-c1-k8s-cluster": grpc: no transport security set (use grpc.WithInsecure() explicitly or set
  credentials)
```

Thanks

**Comment by wahmedswl** [comment]
Please re-open this issue as its still on-going.

Thanks

**Comment by Fuco1** [comment]
I also have this problem.  I'm trying to connect to waypoint running on nomad though.

**Comment by dylanrhysscott** [comment]
Hi,

I'm having this issue connecting to Waypoint running on a Digitalocean droplet in Docker too - I ran 

```
waypoint token new
```

on the server giving me a token and on my client passing that in to the context

```
waypoint context create -server-addr=XXX -server-auth-token=XXX -server-tls -server-require-auth -set-default waypoint
Context "waypoint" created.
```

and then running 

```
waypoint context verify
❌ Connecting with context "waypoint"...
! Error connecting with context "waypoint": grpc: no transport security set (use grpc.WithInsecure() explicitly or set
  credentials)
```

Any advice on this? Thanks

**Comment by azalio** [comment]
Just try to do this
```
kubectl create ns waypoint2
waypoint install --platform=kubernetes -accept-tos -k8s-pull-policy=Always -k8s-namespace=waypoint2
```

I faced this problem above and found out that I reinstalled waypoint with cli ver0.2 but in my k8s cluster was image for 0.14. So it just version incompatibility.

**Comment by 1mamute** [comment]
I'm also getting this error.
- All ports are open in my ec2 instance
- Runned `waypoint install -platform=docker -accept-tos` then `waypoint token new`
- Used the token to authenticate in the UI, all good.
- Copied the CLI snippet above to my terminal and got the error in the screenshot

```
waypoint context create \
    -server-addr=example-east-1.compute.amazonaws.com:9701 \
    -server-auth-token=bM152PWkXxfoy4vA51JFhR7LnPLmDMMxyYj4d8Z36eBThvfHcUpWNvieRdycQWq9MuC5mJyWzVnEmja5GhqPxvx2Xc1QG1NvHUo5z \
    -server-require-auth=true \
    -set-default example-east-1.compute.amazonaws.com-ui
```

![image](https://user-images.githubusercontent.com/22196761/124517364-2c310e00-ddba-11eb-8624-238caf499fd2.png)

As you can see, no other context is available.

**Comment by vladfr** [comment]
Adding `-server-tls-skip-verify` did it for me.

**Comment by thatsk** [comment]
not working for nomad platform
