### ISSUE TITLE
Waypoint intall for kubernetes is stuck on waiting for service with inlets

### ISSUE THREAD

**Issue by dirien** [hashicorp/waypoint#670]
**Describe the bug**
Waypoint intall for kubernetes is stuck on waiting for service

```
Installing Waypoint to a Kind cluster requires that the cluster has
LoadBalancer capabilities (such as metallb). If Kind isn't configured
in this way, then the install may hang. If this happens, please delete
all the Waypoint resources and try again.
 + Creating Kubernetes resources...
 │ service/waypoint created
 │ statefulset.apps/waypoint-server created
 + Kubernetes StatefulSet reporting ready
⠦ Waiting for Kubernetes service to become ready..
```

**Steps to Reproduce**
Follow the tutorial on https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes

But install inlets (https://github.com/inlets/inlets) for getting a public ip adress on the mac

**Expected behavior**
waypoint install terminates successfull.

**Additional context**
I am running waypoint and kind on a mac.

**Comment by dirien** [comment]
@alexellis maybe you have an idea, why the combination of inlets and waypoint is not working?

**Comment by alexellis** [comment]
Hi @dirien 

I'd need a lot more context than what you've provided. I also haven't used waypoint yet.

How do you know that it's not working? (logs, errors etc?) How are you installing and deploying inlets?

(importantly) what are you trying to do?

**Comment by dirien** [comment]
I install inlet on digitalocean via this tutorial https://docs.inlets.dev/#/get-started/quickstart-ingresscontroller-cert-manager?id=install-the-inlets-operator. 

These part work fine. No error mesages in the logs of the operator. The exit-server is installed and the service from waypoint gets an public ip (great!)

But the waypoint install command gets stuck in the waiting for service ready state (Tutorial under https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes)

I will try now to waypoint with GKE to see if it is a generel problem...

**Comment by dirien** [comment]
with GKE it works fine. The install is not stuck...

![image](https://user-images.githubusercontent.com/38325136/96778176-8edca800-13eb-11eb-9859-b2fba6a953dc.png)

**Comment by alexellis** [comment]
(If you're trying to access a gRPC service, you will need to use inlets PRO with the inlets-operator for the TCP support.)

**Comment by dirien** [comment]
@alexellis, many thanks! i will try the eval! I keep on talking about inlets at work!

**Comment by alexellis** [comment]
I also believe that @jsiebens got this working with inlets.. feel free to reach out to us in the #inlets channel in the [OpenFaaS community Slack](https://slack.openfaas.io/)
