### ISSUE TITLE
Uninstall/Remove Waypoint

### ISSUE THREAD

**Issue by wahmedswl** [hashicorp/waypoint#672]
**Is your feature request related to a problem? Please describe.**
There should be instructions to ```Uninstall/Remove Waypoint``` fully, ```K8S``` generated stuff etc

Thanks

**Comment by mitchellh** [comment]
Coming in Waypoint 0.2.

**Comment by wahmedswl** [comment]
Thanks, i have to re-create k3s cluster to get rid of #669. Was not able to re-create working context and it seems the faster way ...

Thanks
