### ISSUE TITLE
server bootstrap uses context server-addr and not provided cmd arg 

### ISSUE THREAD

**Issue by alikefia** [hashicorp/waypoint#673]
**Bug description**
When having a context to a remote server (waypoint.domain) and want to boostrap a local new server, the -server-addr cmdline argument is not considered by the command (waypoint try to connect to waypoint.domain)

**Steps to Reproduce**
- Create a context to a remote server : `waypoint context create -server-addr waypoint.domain`
- Start local waypoint server : `waypoint server run`
- Bootstrap local server : `waypoint server bootstrap -server-addr 127.0.0.1:9701`

**Expected behavior**
Bootstrap OK

**Comment by alikefia** [comment]
After analyzing, it look like this is due to  the connectOptions resolution priority @ https://github.com/hashicorp/waypoint/blob/main/internal/cli/base_init.go#L83
```
	connectOpts := []serverclient.ConnectOption{
		serverclient.FromContextConfig(flagConnection),
		serverclient.FromContext(c.contextStorage, ""),
		serverclient.FromEnv(),
	}
```
Should I interpret here that flagConnection (commandline args if I understand well) is the least dominant ?

Thx for help

**Comment by mitchellh** [comment]
Yes this ordering is probably incorrect. The precedence order we imagined was: context => env => flags. So this is just all wrong probably.
