### ISSUE TITLE
"By default, waypoint deploy automatically performs a release."

### ISSUE THREAD

**Issue by jdub** [hashicorp/waypoint#689]
This gave me [serious heebie-jeebies](https://www.waypointproject.io/docs/lifecycle/deploy#automatic-release) as soon as I read it, so while I'm glad you're going to let folks disable it, I reckon it'd be worth encouraging users towards best practice by default.

Plus, the potential for error is huge: "Can you take a look at this bug? I'll do a quick deploy so you can see it in action." 🚨🚨🚨 

Perhaps there's a worthwhile compromise: `waypoint up` automatically releases, but `waypoint deploy` does not.

**Comment by jack1902** [comment]
https://github.com/hashicorp/waypoint/issues/534
