### ISSUE TITLE
Waypoint not deploying in private nomad cluster

### ISSUE THREAD

**Issue by thatsk** [hashicorp/waypoint#690]
**Describe the bug**
waypoint not intializing in nomad cluster

**Steps to Reproduce**
https://learn.hashicorp.com/tutorials/waypoint/get-started-nomad?in=waypoint/get-started-nomad
waypoint init
root@nomad-master: ~/waypoint-examples/nomad/nodejs# waypoint install -platform=nomad --nomad-dc=nomad -accept-tos
❌ Nomad allocation created
! Error installing server into Nomad: allocation failed

**Expected behavior**
it should deploy in nomad cluster.

![image](https://user-images.githubusercontent.com/15324013/97080987-ff1e4000-161c-11eb-8fca-af4bd4ecb165.png)

**Comment by chuckyz** [comment]
@thatsk I think this was introduced in https://github.com/hashicorp/nomad/pull/8623.  You might need to upgrade to 0.12.  Looks like 0.12.7 fixes some regressions and a CVE so it might be a good idea to upgrade anyway.

**Comment by mitchellh** [comment]
CC @nickethier who may have some thoughts here too.

**Comment by nickethier** [comment]
Hey @thatsk currently the Nomad Waypoint installer requires a 0.12.2 or greater cluster. You are likely getting this because of an older cluster version. Can you confirm your Nomad version?

**Comment by mitchellh** [comment]
Closing due to lack of response, the Nomad version is likely the issue. We may want to verify the Nomad version on `install`.

**Comment by thatsk** [comment]
i am using nomad version 1.0.1 . Still its crashloopback nomad will try to allocate waypoint and just goes die as per screenshot

**Comment by thatsk** [comment]
This is allocation task status
{code}
ID                     = b3e9e4b7-eaa4-acfa-d0cc-ba8ce81273a1
Eval ID                = 78822703
Name                   = waypoint-server.waypoint-server[0]
Node ID                = b4ea0562
Node Name              = msapi02p1.re.smf1.mobitv
Job ID                 = waypoint-server
Job Version            = 8
Client Status          = failed
Client Description     = Failed tasks
Desired Status         = run
Desired Description    = <none>
Created                = 2m45s ago
Modified               = 1m19s ago
Reschedule Eligibility = 1m39s from now

Allocation Addresses (mode = "host")
Label    Dynamic  Address
*ui      yes      10.174.206.56:9702 -> 9702
*server  yes      10.174.206.56:21498 -> 9701

Task "server" is "dead"
Task Resources
CPU        Memory          Disk     Addresses
0/100 MHz  14 MiB/300 MiB  300 MiB

Task Events:
Started At     = 2021-01-04T11:46:47Z
Finished At    = 2021-01-04T11:46:57Z
Total Restarts = 2
Last Restart   = 2021-01-04T11:46:27Z

Recent Events:
Time                  Type            Description
2021-01-04T11:46:57Z  Not Restarting  Exceeded allowed attempts 2 in interval 30m0s and mode is "fail"
2021-01-04T11:46:57Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2021-01-04T11:46:47Z  Started         Task started by client
2021-01-04T11:46:46Z  Driver          Downloading image
2021-01-04T11:46:27Z  Restarting      Task restarting in 18.222469949s
2021-01-04T11:46:27Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
2021-01-04T11:46:17Z  Started         Task started by client
2021-01-04T11:46:15Z  Driver          Downloading image
2021-01-04T11:45:59Z  Restarting      Task restarting in 16.147022258s
2021-01-04T11:45:59Z  Terminated      Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"
{code}

**Comment by thatsk** [comment]
this seems some problem with deploying waypoint server jobs

**Comment by mitchellh** [comment]
Are you able to get the logs out of the allocation? We need to see why the container is exiting. Thank you!

**Comment by thatsk** [comment]
this is what i got.

**Comment by thatsk** [comment]
let me know if you need more info I will provide you.

**Comment by thatsk** [comment]
@mitchellh @chuckyz is there anything you want information are you seeing the same issue which I got in private nomad cluster

**Comment by jwthomp** [comment]
@thatsk Is your docker image being built locally? 

If so, the remote nomad cluster will not have access to it.
You need to build your image so that it goes to a registry that the cluster can access it from.

**Comment by thatsk** [comment]
But at least first waypoint need to come up that's my first point.

**Comment by thatsk** [comment]
Waypoint is not coming up and waypoint container crashed loopoff

**Comment by thatsk** [comment]
@mitchellh do you need any info to find out root cause

**Comment by briancain** [comment]
@thatsk - What do your logs say for waypoint-server container? It looks like Nomad is saying it exited 1, so seeing what that container logs says would be a good thing to see. Thanks!

**Comment by briancain** [comment]
@thatsk - Were you able to find the container logs for Waypoint server? Thanks.

**Comment by briancain** [comment]
Hey there @thatsk - since we haven't heard back in a while, I'm going to go ahead and close this issue since I was not able to reproduce it myself. If you are still facing this issue, let us know and provide any extra debug information like waypoint server logs, etc. Thanks again for reporting the issue to us! 😄

**Comment by marcgweg** [comment]
I have this same issue running nomad on Raspberry PI (arm64). So would like to proceed. How can I get these logging you mentioned!?
