### ISSUE TITLE
`waypoint server install`: support for `exec` driver on Nomad

### ISSUE THREAD

**Issue by spencergilbert** [hashicorp/waypoint#698]
**Is your feature request related to a problem? Please describe.**
I'm running Nomad on arm64 today, and while [Hashicorp releases](https://releases.hashicorp.com/waypoint/) provide `arm` binaries, the docker images only support amd64 today. 

**Describe the solution you'd like**
Additional CLI flags to install via Nomad's `exec` driver, this could also be useful to user's primary deploying binaries/jars and not using docker.

**Describe alternatives you've considered**
Installing using the CLI and editing the job that is submitted by waypoint to use the binary at release.hashicorp.com/Github releases.

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**
Related issue: #474

**Comment by chuckyz** [comment]
Have you tried building/pushing the arm binary into a docker repo and then passing `-server-image`?  `arm` is always a little funky with docker no matter what.  That should "just work" given that the job takes in ServerConfig from the install cli command:

https://github.com/hashicorp/waypoint/blob/045f490f1043fc802f3529eb4e15768d0e153c4f/internal/serverinstall/nomad.go#L211

**Comment by spencergilbert** [comment]
I'll give that a try when I've got my cluster stable again - I do try and run things as binaries when possible though, dockerless could still be nice - though I don't know how frequently used it might be

**Comment by mitchellh** [comment]
I think the plan here is to keep using Docker for the `waypoint server install` command. For more advanced cases we recommend manually running the Waypoint server: https://www.waypointproject.io/docs/server/run
