### ISSUE TITLE
Have a parameter to specify the hcl file to be used when we do waypoint init

### ISSUE THREAD

**Issue by cmoulliard** [hashicorp/waypoint#717]
## Feature request

It is not possible to specify when we execute the command `waypoint init` the hcl file to be used and by consequence waypoint will pickup the file : `waypoint.hcl`.

Having the possibility to specify the file to be used would help to use waypoint with the same project but different cloud providers: docker, kubernetes, ...

` waypoint init -f my-waypoint.hcl.kubernetes`

**Comment by mitchellh** [comment]
I thought we had a `--from` flag that could take a filepath already but i'll have to check. For now labeled as enhancement.

**Comment by dominikbraun** [comment]
@mitchellh: There's indeed a struct field of `InitCommand` called `from`, but it is used to store the `-from-project` option. An option like `-from` doesn't exist yet.
