### ISSUE TITLE
Plugins for hooks

### ISSUE THREAD

**Issue by surminus** [hashicorp/waypoint#733]
**Describe the solution you'd like**

I'd love to be able to develop custom hooks that people can use as part of the release process. I feel like hooks are going to be a really powerful part of the experience with this tool. At the moment hooks are limited to running commands with `os/exec` so they can obviously do whatever you want, but being able to use a community driven hook would be amazing.

### Example

A basic example could be:

```
app "frontend" {
  build {
    use "docker" {}
  }

  deploy {
    use "aws-ecs" {}
  }

  release {
    hook "slack" {
      channel = "#releases"
      when = "after"
    }

    ...
  }
}
```

Something that I would be pretty keen to have specifically in ECS land would be:

```
app "frontend" {
...

  release {
    hook "aws-ecs-run-task" {
      command = "rails db:migrate"
      when    = "before"
    }

    ...
  }
}
```

Where it runs the task in the container you've just built, waits for it to finish and then provides logs.

Traditionally this kind of stuff ends up being in CI/CD pipelines but I'd much rather be configuring a build-to-release deployment outside of these traditional mechanisms.

**Comment by simar7** [comment]
This is actually exactly what I had in mind as well but for a slightly different use case. I wanted to write a custom vulnerability scanning plugin for Waypoint that would look something like this:

```
app "frontend" {
  build {
    use "docker" {}
    hook "trivy" {
        severity = "foo"
        scantype = "bar"
  }
    ...
  }
}
```
Where [trivy](https://github.com/aquasecurity/trivy) is a vulnerability scanner of choice. 

We could also take it a step further and do something like the following:
```
app "frontend" {

  scan {
    use "trivy" {}
  }

  build {
    use "docker" {}
  }
    ...
  }
}
```

But I feel the latter is a more involved change as it will introduce a new top level type called `scan`. Either way it's an idea I had and wanted to share with the maintainers.

**Comment by mitchellh** [comment]
I'll note that the bigger picture functionality here is something we'd like to support: code scanning plugins, notification triggers, etc. I'm not sure if that will/should manifest itself via plugin hooks yet. But I'll mark this as an ehnancement issue and keep it open so we can discuss as we start thinking about this more.

**Comment by briancain** [comment]
We currently don't have plans for enhancing the hooks system that was introduced in the early stages of Waypoint. So from that standpoint, we don't plan on expanding them to support plugins. We do hope to support the flow that is running actions before or after certain lifecycle operations, so we hope to support this feature in some form going forward. Thank you for your consideration of Waypoint!
