### ISSUE TITLE
Waypoint failed to install on DigitalOcean Kubernetes

### ISSUE THREAD

**Issue by ianwalter** [hashicorp/waypoint#735]
**Describe the bug**

I tried to install Waypoint on a Kubernetes cluster created on DigitalOcean by following the instructions on HashiCorp Learn and was met with this error:

```
❯ waypoint install --platform=kubernetes -accept-tos
✓ Creating Kubernetes resources...
 │ service/waypoint created
 │ statefulset.apps/waypoint-server created
✓ Kubernetes StatefulSet reporting ready
✓ Waiting for Kubernetes service to become ready..
❌ Connecting to: 206.189.254.81:9701
! Error connecting to server: context deadline exceeded

  The Waypoint server has been deployed, but due to this error we were
  unable to automatically configure the local CLI or the Waypoint server
  advertise address. You must do this manually using "waypoint context"
  and "waypoint server config-set".
```

The Waypoint Server is in CrashLoopBackOff:

```
❯ kubectl get po waypoint-server-0
NAME                READY   STATUS             RESTARTS   AGE
waypoint-server-0   0/1     CrashLoopBackOff   6          7m39s
```

And the logs indicate a permission issue when opening the database:

```
❯ kubectl logs waypoint-server-0
2020-10-29T23:49:41.781Z [INFO]  waypoint: waypoint version: full_string="Waypoint v0.1.4 (3810a3c7+CHANGES)" version=v0.1.4 prerelease= metadata= revision=3810a3c7+CHANGES
2020-10-29T23:49:41.781Z [TRACE] waypoint: starting interrupt listener for context cancellation
2020-10-29T23:49:41.782Z [DEBUG] waypoint: home configuration directory: path=/home/waypoint/.config/waypoint
2020-10-29T23:49:41.782Z [INFO]  waypoint.server: opening DB: path=/data/data.db
2020-10-29T23:49:41.782Z [TRACE] waypoint: stopping signal listeners and cancelling the context
! Error opening database: open /data/data.db: permission denied
2020-10-29T23:49:41.782Z [TRACE] waypoint: interrupt listener goroutine started
```

**Steps to Reproduce**

1. Create a  Kubernetes cluster on DigitalOcean.
2.  Add the kubeconfig locally via doctl.
3. Run `waypoint install --platform=kubernetes -accept-tos`

**Expected behavior**

That the Waypoint Server runs.

**Additional context**

The Kubernetes version is `1.19.3-do.0`.

**Comment by evanphx** [comment]
Hm, can you run `kubectl describe pod waypoint-server-0` and paste the output here? Odd that the PVC mounted an /data would be the wrong perms...

**Comment by ianwalter** [comment]
```
❯ kubectl describe pod waypoint-server-0
Name:         waypoint-server-0
Namespace:    default
Priority:     0
Node:         nyc1-pool-2-4g-01-3sv7m/10.116.0.6
Start Time:   Thu, 29 Oct 2020 19:43:54 -0400
Labels:       app=waypoint-server
              controller-revision-hash=waypoint-server-8678c4f6cb
              statefulset.kubernetes.io/pod-name=waypoint-server-0
Annotations:  <none>
Status:       Running
IP:           10.244.0.229
IPs:
  IP:           10.244.0.229
Controlled By:  StatefulSet/waypoint-server
Containers:
  server:
    Container ID:  docker://cd7d8f8dcedbebd1401e0a3ce108a610651d6bad17dc908c0fbe9120f9e0d3f0
    Image:         hashicorp/waypoint:latest
    Image ID:      docker-pullable://hashicorp/waypoint@sha256:740159de064a87e32c044547ce26766ed1260cabeb882ea85ba464cd8c7db83c
    Ports:         9701/TCP, 9702/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      waypoint
    Args:
      server
      run
      -accept-tos
      -vvv
      -db=/data/data.db
      -listen-grpc=0.0.0.0:9701
      -listen-http=0.0.0.0:9702
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 29 Oct 2020 21:37:11 -0400
      Finished:     Thu, 29 Oct 2020 21:37:11 -0400
    Ready:          False
    Restart Count:  27
    Requests:
      cpu:        100m
      memory:     256Mi
    Liveness:     http-get https://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gglwv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-waypoint-server-0
    ReadOnly:   false
  default-token-gglwv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gglwv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                              Message
  ----     ------   ----                    ----                              -------
  Warning  BackOff  4m19s (x529 over 114m)  kubelet, nyc1-pool-2-4g-01-3sv7m  Back-off restarting failed container
```

**Comment by cmoulliard** [comment]
I think that you must check the permissions of the volume mounted by pv/pvc as certainly that the UID of the pod used dont has the permissions to create the DB and write.

**Comment by ianwalter** [comment]
Not sure what you mean but here is the information for the pvc:

```
❯ kubectl describe pvc data-waypoint-server-0
Name:          data-waypoint-server-0
Namespace:     default
StorageClass:  do-block-storage
Status:        Bound
Volume:        pvc-399efd93-af5d-4738-a2ac-8e640350698e
Labels:        app=waypoint-server
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    waypoint-server-0
Events:        <none>
```

**Comment by mitchellh** [comment]
This is interesting cause I'll add that I haven't had issues installing in K8S in DO, but I haven't done it in a couple releases so perhaps something changed...

**Comment by lfarnell** [comment]
So just to add some additional information to the ticket. I tried with  `1.19.3-do.0`, `1.18.10-do.0` and `1.17.13-do.0`. I only managed to get this to work with `1.17.13-do.0`. I started with waypoint `0.1.0` and once that worked I immediately tried `0.1.4` and it was successful again. After digging through the [changelog](https://www.digitalocean.com/docs/kubernetes/changelog/), its seems like this could be a CSI driver or CCM issue but leaning towards CSI.

**Comment by cmoulliard** [comment]
The problem is not the PVC or PV but instead the volume mounted on digital ocean where you dont have the permission RWO to create a file. Look at the permissions on the Filesystem for

**Comment by ianwalter** [comment]
Thanks @lfarnell, `1.17.13-do.0` worked for me as well.

**Comment by harshthakur9030** [comment]
I am facing the similar issue on docker. I am using a debian based OS : 
`2020-11-02T23:47:47.708Z [INFO]  waypoint.server: opening DB: path=/data/data.db
! Error initializing server: context deadline exceeded
2020-11-02T23:47:57.792Z [INFO]  waypoint.server: gracefully closing db: path=/data/data.db
2020-11-02T23:47:57.792Z [TRACE] waypoint: stopping signal listeners and cancelling the context
`

**Comment by jbayer** [comment]
The issue is described in the [Digital Ocean Kubernetes Volumes documentation](https://www.digitalocean.com/docs/kubernetes/how-to/add-volumes/#setting-permissions-on-volumes).

 [I wrote up a workaround](https://github.com/jbayer/waypoint-digital-ocean-docs/blob/main/README.md) that involves using `waypoint install` with the `-show-yaml` command and adding an InitContainer.

**Comment by mitchellh** [comment]
I just installed Waypoint 0.1.4 with K8S `1.19.3-do.1` with a clean `waypoint install` without issue...

I didn't have to use @jbayer's workaround or anything. Is there something I'm missing?

**Comment by jbayer** [comment]
Interesting, I certainly had to do the workaround because the /data directory was not writable from what I remember. I had created a 1.19 cluster in SF about a week ago. `doctl kubernetes cluster list` says it is 1.19.3-do.0. Not sure I have time to try it again in the short-term.

**Comment by lfarnell** [comment]
I can confirm this does work again on DO using 1.19.3-do.2. I believe this can be closed now

**Comment by ianwalter** [comment]
Thanks everyone
