### ISSUE TITLE
Different environments/config 

### ISSUE THREAD

**Issue by nihaals** [hashicorp/waypoint#741]
**Is your feature request related to a problem? Please describe.**
Having the same config file for dev and prod might not always make sense. For example, you may not want to inject an entrypoint into prod images but are fine with it on dev, or you may tag images differently with releases versus new commits (and only push on CI for a specific commit but not during development).

**Describe the solution you'd like**
A way to have multiple versions of your config that can be switched easily, for example `waypoint up -e prod`. These could be defined inside an `app`.

**Describe alternatives you've considered**
Having multiple `waypoint.hcl` seems to be against a key part of Waypoint so I’m not sure other than not using Waypoint

**Explain any additional use-cases**
- Different tags for releases and dev
- Different images for releases and dev
- Not wanting to inject the entrypoint in release images

**Comment by mitchellh** [comment]
Workspaces are designed for this: https://www.waypointproject.io/docs/workspaces

They are fairly limited for 0.1 but it is already on [our roadmap](https://www.waypointproject.io/docs/roadmap#app-promotion) to improve this.

As part of this we do want to enable some way to conditionally change some configs based on workspace or label set.

**Comment by pmalon** [comment]
I read documentation for Workspaces and I still don't know how they address the problem described here - how to define configuration specific for a given environment 'dev' vs 'staging' vs 'production' - let's say that I am using ECS plugin and I'd like to have different static environment variables, secrets and ALB configuration per environment, how can I achieve that with workspaces?

**Comment by citicruiser** [comment]
I think to be able to support multi env dev vs. staging vs. prod is absolute hard requirement for any enterprise.  Without that, I don't see how my company can use this. Please let's add this feature quickly....

**Comment by mitchellh** [comment]
Absolutely agree @citicruiser, we don't yet claim Waypoint is "enterprise ready" and they aren't our current target user (but 100% an eventual target user). We're focusing first on individuals and small teams with Waypoint to build up the initial featureset, and we'll continue to grow towards enterprise usage over time, following the same patterns as our other software.

We are planning on supporting more advanced promotion and other functionality over time, it won't come all at once, so watch out for incremental improvement.

**Comment by brettwilcox** [comment]
Hi Waypoint team! 👋

I have started playing with waypoint and so far everything is brilliant! My only want at the moment is better environment variables implementation. Below is an example pattern I use.

### .env

```env
IMAGE=myimage
TAG=1.2.3
```

### docker-compose.yml

```docker-compose
services:
  my-app:
    env_file:
      - ".env"
    labels:
      - "IMAGE=${IMAGE}"
      - "TAG=${TAG}"
    build:
      context: ./docker/my-app
      args:
        - "IMAGE=${IMAGE}"
        - "TAG=${TAG}"
    restart: always
```

### ./docker/my-app/Dockerfile

```dockerfile
ARG IMAGE =${IMAGE}
ARG TAG=${TAG}

# Image and version to pull
FROM ${IMAGE}:${TAG}

```

**Comment by sheb-gregor** [comment]
Hello!

I found Waypoint as a great opportunity to replace my own bash-hell for building and shipping Docker images.
Unfortunately, this is not yet possible. Waypoint doesn't support build arguments for docker and variables for config files like Terraform does.

A short example of my routine. I have a monorepo for microservices. Most of them have the same Docker files, the difference only in ARG values. When I build the image for production, I need to pass another set of arguments.


Here is a snippet from the bash script to handle this and Dockerfiles examples :

##### build.sh (part)

```shell
build_mono() {
  debug_log "build_mono"
  local GIT_VERSION=""
  GIT_VERSION=$(get_version)

  docker build -f "${TOOLS_WD}/mono.dockerfile" -t mono \
    --build-arg "CREDENTIALS=${CREDENTIALS}" \
    --build-arg "GIT_VERSION=${GIT_VERSION}" .
}

build_service() {
  debug_log "build_service: ${1}"

  docker build -f "${TOOLS_WD}/service.dockerfile" -t "ae-${1}" --build-arg "SERVICE=${1}" .
}

tag_service_image() {
  local SERVICE=${1}
  local IMAGE="${REGISTRY}/${PROJECT}/${SERVICE}"
  debug_log "tag_service_image: ${IMAGE}"

  echo "Tag the image: ${IMAGE}"
  docker tag "${SERVICE}" "${IMAGE}"

  if [ "${SKIP_PUBLISH}" = "no" ]; then
    docker push "${IMAGE}"
  fi
}

deploy_service() {
  local SERVICE=${1}
  local IMAGE="${REGISTRY}/${PROJECT}/${SERVICE}"

  debug_log "deploy_service: ${IMAGE}"

  gcloud run deploy "${SERVICE}" \
    --image "${IMAGE}" --region "${REGION}" \
    --platform managed --allow-unauthenticated
}

```

##### mono.dockerfile

```Dockerfile
FROM rust:alpine
RUN apk add --no-cache gcc musl-dev

ARG GIT_VERSION="n/a"
ARG CREDENTIALS="./env/firebase-service-account.json"

WORKDIR /opt/services

ADD . .

RUN echo $GIT_VERSION \
    && cargo build --release \
    && cp ./target/release/service_alice ./bin/ \
    && cp ./target/release/service_bob ./bin/ \
    && cp ./target/release/service_eva ./bin/ \
    && cp $CREDENTIALS ./bin/firebase-service-account.json \
    && cargo clean
```

##### service.dockerfile

```Dockerfile
ARG SOURCE_IMAGE="mono"
FROM ${SOURCE_IMAGE} as builder

FROM alpine:latest

ARG SERVICE

## Service must listen to $PORT environment variable.
## This default value facilitates local development.
ENV PORT 8080
ENV RUST_LOG info
ENV CREDENTIALS ./firebase-service-account.json

WORKDIR /opt/backend

COPY --from=builder /opt/services/bin/${SERVICE} /opt/backend/service
COPY --from=builder /opt/services/bin/firebase-service-account.json /opt/backend

CMD ["./service"]

```

##### waypoint

It will be very cool to have the possibility to write something like this to describe local build:

```hcl
app "service_alice" {
  build {
    use "docker" {
      image = "${var.repo}/${var.project}/service_alice"
      tag   = "smth"
      args {
       SERVICE = "service_alice"
       CREDENTIALS = "${var.credentials_path}"
      }
    }
  }
}
```

**Comment by briancain** [comment]
Thank you everyone for providing some extra information on this issue! We have opened a new issue here that captures the intention of this enhancement: https://github.com/hashicorp/waypoint/issues/1221

For now, I will go ahead and close this issue in favor of the new one. If you have any more additional information please feel free to include it on the new issue. Thank you! 😄
