### ISSUE TITLE
invalid reference format when pushing image to private harbor registry

### ISSUE THREAD

**Issue by thedewpoint** [hashicorp/waypoint#744]
I'm building my project with waypoint and deploying to harbor as my private registry. Image build is successful but deployment is not and I can't seem to figure out why. Repository located here:
https://github.com/thedewpoint/expense-api

```
» Building...
✓ Initializing Docker client...
✓ Building image...
 │  ---> f3f351e0f21d
 │ Step 6/7 : COPY --from=build /usr/local/cargo/bin/expense-api /usr/local/bin/exp
 │ ense-api
 │  ---> Using cache
 │  ---> d82d58128607
 │ Step 7/7 : CMD ["expense-api"]
 │  ---> Using cache
 │  ---> 61423ec6b516
 │ Successfully built 61423ec6b516
 │ Successfully tagged waypoint.local/expense-api:latest
✓ Injecting Waypoint Entrypoint...
❌ Tagging Docker image: waypoint.local/expense-api:latest => http://dewyserver.duckdns.org:80/expense/expense-api:latest
! unable to tag image:Error parsing reference:
  "http://dewyserver.duckdns.org:80/expense/expense-api:latest" is not a valid
  repository/tag: invalid reference format
```

**Comment by mitchellh** [comment]
This line is not a valid Docker image name: https://github.com/thedewpoint/expense-api/blob/55f5b7f6eb34919dcea1242e9ea4854c9684b04a/waypoint.hcl#L13

**Comment by thedewpoint** [comment]
@mitchellh  I'm confused, isn't this where i specify my private repo? If not, where do I configure that url?

**Comment by mitchellh** [comment]
I believe Docker uses the image name to determine the URL yes. Whatever format you use with `docker tag` or `docker push` is what you want to put here sans the tag (`:latest` and so on).

**Comment by thedewpoint** [comment]
@mitchellh  here are some examples of me deploying another image manually to my repo

docker tag e49a285ed975 dewyserver.duckdns.org:80/twitch/twitchlurk:latest
docker push dewyserver.duckdns.org:80/twitch/twitchlurk:latest

Which part of the stanza in my repo is invalid? It looks as though it matches up. Additionally this is the docker push command I copied right out of harbor for the expense repo

docker tag SOURCE_IMAGE[:TAG] dewyserver.duckdns.org/expense/IMAGE[:TAG]
docker push dewyserver.duckdns.org/expense/IMAGE[:TAG]

**Comment by mitchellh** [comment]
Got it, looking at that it looks like the value should be `dewyserver.duckdns.org:80/twitch/twitchlurk:latest`
