### ISSUE TITLE
aws-ecr support for AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by orenmazor** [hashicorp/waypoint#745]
**Is your feature request related to a problem? Please describe.**
I am currently deploying my stack to several AWS regions in several accounts.

Unfortunately, it's problematic for me that the registery settings for aws-ecr force me to hardcode the region, as such:

```
        registry {
            use "aws-ecr" {
                region = "us-east-1"
                repository = "foo"
                tag = "0xdeadbeef"
            }
        }
```

**Describe the solution you'd like**
my deploy environment is always fully defined and the AWS_DEFAULT_REGION is always set to point to the correct environment.

waypoint automatically uses the AWS environment session that is set. I'd love it if that plugin was able to use the region as well, and I wouldn't need to specify the region explicitly

this is basically a smaller subset of what #741 would help me with

**Describe alternatives you've considered**
I currently deploy via a makefile that assumes role to whatever account I need to be in. I thought about dynamically generating a waypoint.hcl per deploy but that's a smelly antipattern.

**Comment by mitchellh** [comment]
I'm surprised the AWS SDK doesn't do this for us! We'll have to take a look.

**Comment by orenmazor** [comment]
thanks @mitchellh! thats what I also expected, so I'm still 50/50 on whether this is just PEBKAC somehow

**Comment by orenmazor** [comment]
merged MR handles this issue. thanks all!
