### ISSUE TITLE
waypoint install fails on docker

### ISSUE THREAD

**Issue by harshthakur9030** [hashicorp/waypoint#748]
**Describe the bug**
`waypoint install -platform=docker -accept-tos` fails with an error: `! Error connecting to server: context deadline exceeded
` 
docker logs show:
`2020-11-02T23:47:47.708Z [INFO]  waypoint.server: opening DB: path=/data/data.db
! Error initializing server: context deadline exceeded
2020-11-02T23:47:57.792Z [INFO]  waypoint.server: gracefully closing db: path=/data/data.db
2020-11-02T23:47:57.792Z [TRACE] waypoint: stopping signal listeners and cancelling the context
`

**Steps to Reproduce**
I am on a debian based OS and ran the above command

**Expected behavior**
Waypoint server to run

**Additional context**
Similar to https://github.com/hashicorp/waypoint/issues/735 but on Docker

**Comment by mitchellh** [comment]
There are various other issues of folks having stuff like this happen and it has so far always been environmental. Try doing a full system prune and reinstall, and ensure that local networking to the Docker container works. I run in Docker every day and we have folks on the team running in Docker every day on Linux so it should be fine.

For further usage questions I recommend using discuss.hashicorp.com!
