### ISSUE TITLE
Allow components access to datadir

### ISSUE THREAD

**Issue by pearkes** [hashicorp/waypoint#762]
Related to #739 we need to re-enable access to the datadir for components.

**Comment by mitchellh** [comment]
Additional notes: we removed the `datadir` param for plugins on main, but there are legitimate reasons for it to exist: plugins may require local state such as Netlify storing tokens.

Let's bring it back but redocument it to be only for local, _never synced_ state.

**Comment by mitchellh** [comment]
Brought it back as is but we can limit it later.
