### ISSUE TITLE
aws-ecs: third `up` deletes ALB

### ISSUE THREAD

**Issue by talton-heb** [hashicorp/waypoint#765]
**Is your feature request related to a problem? Please describe.**
When running through the [AWS-ECS Tutorial](https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/docker-aws), after completing the tutorial steps I ran `waypoint up` near-simultaneously in two different terminals.  At the end when the commands finished running, the ALB had no listener (100% of traffic was being dropped).  Rerunning `waypoint up` did not restore the ALB Listener, and it required a manual fix in AWS before traffic would flow again.

**Describe the solution you'd like**
 ¯\\_(ツ)_/¯   Concurrency is a hard problem, and the solutions are varied.  Couple of ideas to get the brainstorm forming:
1. Force every releaser to handle concurrency correctly
2. Add a release queue per project, with the waypoint server blocking a client/runner until it becomes active in the queue (Optional: add ability to drop non-active items from the release queue when a new release is enqueued)
3. Mix of 1/2:  Allow releasers to declare if they handle concurrency correctly.  If they do, allow concurrent runs.  If not, use the waypoint server for linearization of the releases.

**Describe alternatives you've considered**
Use some mutex via CI/CD runner to prevent `waypoint up` from being called concurrently.

**Explain any additional use-cases**
This is likely to happen on teams with frequent commits that trigger deployments, or even as a rare scenario for small teams with relatively infrequent commits/deploys.

**Comment by mitchellh** [comment]
If you were in the same `(project, app, workspace)` tuple against the same server, concurrent operations are prevented so this probably shouldn't have happened. The server performs operation locking for the CLI. This is already implemented today.

This is at a per-operation level (build, deploy, release) so its possible that those got interwoven in some way... can you try to see if you can reproduce this running `waypoint release` simultaneously? I don't think its possible.

We can fix this for `up` by treating `up` as a holistic operation, I believe.

**Comment by talton-heb** [comment]
Would treating `up` as a holistic operation still prevent a deploy operation and a release operation from running concurrently? Eg:  One dev runs `waypoint up`, and the CI/CD runner concurrently runs `waypoint build/deploy/release`).

At first glance, it looks like the [`deploy`](https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/platform.go#L560) and [`release`](https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/releaser.go#L33) functionality for ECS both query and modify the same targeted LoadBalancer and Listener, and as long as that's the case the likelihood for race conditions is super high.

**Comment by mitchellh** [comment]
Yes it would prevent that.

Prior to executing any operation, the operation is queued with the Waypoint server (even for local CLI operations). So if a dev and a CI both simultaneously run `up`, one of those would get queued yes. That should be working today on a per-operation level.

**Comment by mitchellh** [comment]
And just for clarity: the plugins themselves (i.e. the ECS plugin) do _not_ have to worry about concurrency since the locking happens at a higher level with the Waypoint server preventing concurrent operations outright.

**Comment by talton-heb** [comment]
This may not actually be concurrency related.  I ran through the [AWS ECS tutorial](https://learn.hashicorp.com/tutorials/waypoint/aws-ecs?in=waypoint/docker-aws) from a blank slate, then afterwards kept making changes and re-running `waypoint up`.  It appears that on the 3rd `waypoint up` command invocation that the listener gets deleted.  (First creates the ALB, second introduces the second target group on the default listener, third should rotate target groups on the default listener, but somehow deletes it?)

**Comment by mitchellh** [comment]
Ah hah that is a good discovery. We may be accidentally deleting the ALB due to some broken deployment destroy logic? I have no idea I didn't look but just a hunch that's what stands out first.

**Comment by gnomeria** [comment]
I also had that listener deletion happened even with referencing the existing alb and listener arn. I think that would be captured in this issue.

**Comment by skottler** [comment]
👋 I'm also running into this issue with a build against HEAD.

In debugging this I found the listener does in fact exist, but is then destroyed during the `release` invocation. This explains why it takes running `release` several times before the listener gets deleted.

I wound up doing some tracing through verbosified logs and found that the issue lines in `aws.ecs.Destroy()`:

```go
if len(def) == 1 {
	log.Debug("only 1 target group, deleting listener")
	_, err = elbsrv.DeleteListener(&elbv2.DeleteListenerInput{
		ListenerArn: listener.ListenerArn,
	})
...
```

I haven't had time to dig in further, but I assume the `release` stage calls `Destroy()` to clean up old deployments. This function may be over-generalized for its purpose here and therefore is more destructive than it should be.

Here is relevant debug output from `waypoint deploy`:

```
2021-02-12T13:20:09.404-0500 [DEBUG] waypoint.runner.app.api.deploy: running local operation: id=01EYBPBWKHAQP0FC02YP1XYH1F job_id=01EYBQHEWM187Q34JW11DRN5AX
2021-02-12T13:20:09.417-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: removing deployment target group from load balancer: job_id=01EYBQHEWM187Q34JW11DRN5AX @module=waypoint.runner.app.api.deploy timestamp=2021-02-12T13:20:09.417-0500
2021-02-12T13:20:09.418-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: load balancer arn: job_id=01EYBQHEWM187Q34JW11DRN5AX @module=waypoint.runner.app.api.deploy arn=arn:aws:elasticloadbalancing:us-east-1:[removed]:loadbalancer/app/waypoint-ecs-api/[removed] timestamp=2021-02-12T13:20:09.418-0500
2021-02-12T13:20:09.721-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: listener arn: job_id=01EYBQHEWM187Q34JW11DRN5AX @module=waypoint.runner.app.api.deploy arn=arn:aws:elasticloadbalancing:us-east-1:[removed]:listener/app/waypoint-ecs-api/[removed]/[removed] timestamp=2021-02-12T13:20:09.721-0500
2021-02-12T13:20:09.721-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: only 1 target group, deleting listener: job_id=01EYBQHEWM187Q34JW11DRN5AX @module=waypoint.runner.app.api.deploy timestamp=2021-02-12T13:20:09.721-0500
2021-02-12T13:20:09.844-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: deleting target group: job_id=01EYBQHEWM187Q34JW11DRN5AX @module=waypoint.runner.app.api.deploy arn=arn:aws:elasticloadbalancing:us-east-1:[removed]:targetgroup/api-[removed]/[removed] timestamp=2021-02-12T13:20:09.844-0500
2021-02-12T13:20:09.922-0500 [DEBUG] waypoint.runner.app.api.platform.waypoint: deleting ecs service: job_id=01EYBQHEWM187Q34JW11DRN5AX arn=arn:aws:ecs:us-east-1:[removed]:service/waypoint/api-[removed] @module=waypoint.runner.app.api.deploy timestamp=2021-02-12T13:20:09.922-0500
2021-02-12T13:20:10.346-0500 [DEBUG] waypoint.runner.app.api.deploy: metadata marked as complete: id=01EYBPBWKHAQP0FC02YP1XYH1F job_id=01EYBQHEWM187Q34JW11DRN5AX
```

Therefore the determinant trigger for this issue is not being the third release, but rather old deployments getting pruned. I may be able to submit a PR for this soon, but wanted to get this posted since it's a show stopper for using ECS with waypoint.

**Comment by skottler** [comment]
One other thing of note for folks who might look into this in the future - the issue title of the ALB being deleted does not match the behavior I can reproduce. The _listener_ gets deleted, but the ALB itself remains provisioned, albeit it no listener.

**Comment by krantzinator** [comment]
@skottler yes that's exactly right; we're erroneously doing this as part of the pruning of previous deployments. I plan to fix this today, thanks for digging in here.

**Comment by skottler** [comment]
Awesome, thanks @krantzinator! I'm happy to try out the fix in our environment to validate too, I'll keep an eye out for it. 🙇
