### ISSUE TITLE
waypoint server config-set should be able to run in a non-project directory

### ISSUE THREAD

**Issue by jbayer** [hashicorp/waypoint#780]
**Describe the bug**
`waypoint server config-set` complains if it's not run from a directory with `waypoint.hcl` in it, but the command is not particular to an application.

**Steps to Reproduce**
Install a new waypoint server (confirmed these steps with 0.1.5) and run this command:

```
$ waypoint server config-set -advertise-addr=waypoint.iamjambay.com:9701 -advertise-tls-skip-verify
! failed to load config: A Waypoint configuration file is required but wasn't found.
```

**Expected behavior**
It completes successfully. 

**Additional context**
After running this command from a directory with an app that has `waypoint init` called, it works.

**Comment by dlundgren** [comment]
The `server config-set`, to the best of my knowledge, tells the deploy process to set environment variables so that the image can contact the waypoint server via the waypoint-entrypoint, which is why I think it needs the waypoint.hcl, as it's per app.

**Comment by jbayer** [comment]
@dlundgren I'm pretty sure that you're referring to `waypoint config set` [which is application specific according to the docs](https://www.waypointproject.io/commands/config-set).

The `waypoint server config-set` does not have a reason to be app specific to my knowledge. [Docs here](https://www.waypointproject.io/commands/server-config-set) show that `-app` can be set on this command, but it doesn't make sense to me why these options would vary by applications.

**Comment by dlundgren** [comment]
During our local testing we had to use `waypoint server config-set` either per context, or per app, otherwise our ECS task definitions were being deployed with `WAYPOINT_SERVER_DISABLE` set to 1.
