### ISSUE TITLE
Improve UI log styling

### ISSUE THREAD

**Issue by pearkes** [hashicorp/waypoint#784]
The current styling of application and operation logs provides no ability to:

* Start and stop auto-scrolling
* Syntax highlight
* Jump to the bottom

**Comment by dizzyup** [comment]
@pearkes Addressed the `auto-scrolling` and `jump to` pieces of this task here: https://github.com/hashicorp/waypoint/pull/803, but there's no syntax highlighting introduced.

**Comment by jgwhite** [comment]
@gregone the current implementation of `<OperationLogs>` uses [triple-curlies](https://github.com/hashicorp/waypoint/blob/v0.4.0/ui/app/components/operation-logs/index.hbs#L48) and [self-described “simple escaping”](https://github.com/hashicorp/waypoint/blob/v0.4.0/ui/app/helpers/ansi-to-html.ts#L8-L9). This is a potential XSS vulnerability and an extra incentive for us to upgrade our log-rendering mechanism.

**Comment by gregone** [comment]
@jgwhite Yeah, it's been a long-standing task to rewrite this. Fortunately I just got started on it
