### ISSUE TITLE
ecs deploy fails

### ISSUE THREAD

**Issue by aruntomar** [hashicorp/waypoint#790]
**Describe the bug**
Deploying to ECS fails with the following error. 
```
» Deploying...
✓ Created new ECS cluster: waypoint
✓ Created IAM role: ecr-example-nodejs
❌ IAM role not found:
! InvalidParameter: 1 validation error(s) found.
  - minimum field size of 1, GetRoleInput.RoleName.
```

**Steps to Reproduce**
I'm using the waypoint-example app
https://github.com/hashicorp/waypoint-examples/blob/main/aws-ecs/nodejs/waypoint.hcl

**Expected behavior**
Application gets deployed on ECS

**Additional context**
If i add a specific role_name as the [doc](https://www.waypointproject.io/plugins/aws-ecs) then i get the following error 

```
waypoint-examples/aws-ecs/nodejs/waypoint.hcl:24,7-16:
  Unsupported argument; An argument named "role_name" is not expected here.
```

```
deploy {
    use "aws-ecs" {
      region = "ca-central-1"
      memory = "512"
      role_name = "ecr-example-nodejs"
    }
  }
```

```
waypoint version
Waypoint v0.1.5 (084d8603)
```

**Comment by krantzinator** [comment]
The variable name should be `execution_role_name`, which I'll update our documentation to reflect. You can also use `task_role_name` to assign a task IAM role; I'll add that to the documentation as well.
Thanks for bringing this up!

**Comment by philippelegaldeloitte** [comment]
Hello @krantzinator ,
I am experiencing the same issue as @aruntomar.

  deploy {
    use "aws-ecs" {
      region = "eu-central-1"
      memory = "512"
    }
  }
}

yields :

» Deploying...
✓ Found existing ECS cluster: waypoint
⠙ Found existing IAM role to use: ecr-example-nodejs
! InvalidParameter: 1 validation error(s) found.
  - minimum field size of 1, GetRoleInput.RoleName.

same using :

execution_role_name = "ecr-example-nodejs" in

deploy {
    use "aws-ecs" {
      region = "eu-central-1"
      memory = "512"
      execution_role_name = "ecr-example-nodejs"
    }
  }

Is there a fix or a work around ?

Thanks

**Comment by aruntomar** [comment]
@philippelegaldeloitte @krantzinator 
I think `task_role_name` is a required variable 🤔 

I tried these in sequence. 
1. Add `execution_role_name` - FAILS ❌ 
2. Use both `execution_role_name` & `task_role_name` - SUCCESS ✅ 
3. Only use `task_role_name` - SUCCESS ✅

**Comment by krantzinator** [comment]
Thanks for sharing your workaround! We likely need to update the handling of `task_role_name` to also auto-create a role if one is not specified, which is how `execution_role_name` is handled. We can include this in the next release.

**Comment by philippelegaldeloitte** [comment]
Hi @aruntomar and @krantzinator,

`deploy {
    use "aws-ecs" {
      region = "eu-central-1"
      memory = "512"
      execution_role_name = "ecr-example-nodejs"
      task_role_name = "ecr-example-nodejs"
    }
  }`

deployed successfully to aws-ecs. 

Note that, at the moment, the 2 variables _execution_role_name_ and _task_role_name_ are indicated as [optional](https://www.waypointproject.io/plugins/aws-ecs)

**Comment by surminus** [comment]
I added the [PR](https://github.com/hashicorp/waypoint/pull/692) that introduced this behaviour, and both should definitely be optional (with the execution role created automatically if not provided). Probably needs a conditional [here](https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/platform.go#L245-L248) and [when defining the task definition](https://github.com/hashicorp/waypoint/blob/main/builtin/aws/ecs/platform.go#L744-L762).

Given I introduced this bug I feel compelled to fix it so will look at whipping up a PR :)

**Comment by krmayankk** [comment]
just ran into the same issue, specifying `task_role_name = "ecr-example-nodejs"` resolved it
