### ISSUE TITLE
Dynamically reference terraform resources via terraform remote_state

### ISSUE THREAD

**Issue by aruntomar** [hashicorp/waypoint#806]
I'm sad that I've to copy AWS resource id's to be used in my waypoint.hcl files. 
1. It leaves the scope to make mistakes. 
2. I'll have to track and update resources in waypoint.hcl file if the corresponding AWS resource id's changes. 

I understand that waypoint & terraform are two different projects and trying to solve different problems. But if i understand correctly, in a production environment waypoint expects the required resources are created by eg: terraform. 

**Describe the solution you'd like**
I wish that I should be able to dynamically refer the resources created by terraform in my waypoint config file.

**Comment by mitchellh** [comment]
Thanks! This is something we'd like to do in some way.

**Comment by briancain** [comment]
This has been fixed via #1191. Thanks for reporting this enhancement! 😄
