### ISSUE TITLE
Deploying to an inaccessible nomad cluster

### ISSUE THREAD

**Issue by orenmazor** [hashicorp/waypoint#812]
**Is your feature request related to a problem? Please describe.**
This isn't fully fleshed out yet in my mind, so I'm just describing my problem here. Maybe I'm not seeing the proper solution forest due to all the trees :) 

I currently use waypoint to deploy 3 different stacks to nomad. In all of those cases, nomad is inaccessible, so I'm actually using the deploy exec plugin to run a script which spins up a double ssh tunnel to expose NOMAD_ADDR on a local port, then shut it down when the deploy is done. 

I know eventually you'll support nomad hcls and maybe even levant itself, which will be awesome. 

In my case tho, nomad lives in an inaccessible environment, so I need a way to expose it to waypoint somehow. 

Maybe support boundary somehow? or a custom deployment driver that also takes a bastion IP as a hop?

Or maybe I could use hooks somehow for this?

**Comment by mitchellh** [comment]
This is potentially better suited for remote runners? (roadmap): https://www.waypointproject.io/docs/roadmap#remote-runners  Just one option.

I think otherwise natively supporting tunnels could work in core but seems like a fairly complicated feature when a remote runner may be a better option. Thoughts?

**Comment by orenmazor** [comment]
Ahhh yup. that'd almost certainly work for me, depending on how its done!

**Comment by mitchellh** [comment]
It'd be great to validate our runner design with you to ensure that it does work for this use case cause "accessing private resources" is a general design goal. 

Can I just verify: what you're generally doing is setting up NOMAD_ADDR to point to the proper tunnel and everything _just works_ right? Its just you don't want to keep that tunnel open all the time on your local machine. This totally makes sense just verifying.

**Comment by orenmazor** [comment]
Yup!

the gist is I run one tunnel to the bastion, and then a second tunnel over that tunnel to my nomad cluster. 

locally I end up with NOMAD_ADDR=localhost:4646, but that actually points to a faraway cluster. waypoint execs levant which just runs as usual.

I could probably make it simpler using hooks, but I gotta track the PIDs so I can kill the tunnel after I'm done.

**Comment by briancain** [comment]
This use case is specifically covered in the upcoming 0.3 release using the new runner feature! Thanks again for reporting this enhancement 😄
