### ISSUE TITLE
waypoint config get -raw doesn't print any values

### ISSUE THREAD

**Issue by dominikbraun** [hashicorp/waypoint#813]
**Describe the bug**
Using the `-raw` flag on `waypoint config get` doesn't print any configuration values for me. However, a plain `waypoint config get` shows that there are configuration values present in the project.

**Steps to Reproduce**
```
$ waypoint config set USERNAME=alice
$ waypoint config set PASSWORD=test
$ waypoint config get -raw
```

Removing the `-raw` indicates that the values have been set:

```
  SCOPE |   NAME   | VALUE
--------+----------+--------
        | PASSWORD | test
        | USERNAME | alice
```

**Expected behavior**
I expected a raw output like this:

```
USERNAME=alice
PASSWORD=test
```

**Additional context**
Waypoint version: `Waypoint v0.1.5 (084d8603)`

**Comment by briancain** [comment]
Hey there @dominikbraun ! This is because the `-raw` flag is expecting an argument to be passed in to match against:

```
 -raw
      Output the value for the named variable only (disables prefix matching)
      The default is false.
```

So for example....

```
brian@localghost:go % waypoint config set TESTING="123"                                                                                                                                                                               ±[main]

brian@localghost:go % waypoint config get                                                                                                                                                                                             ±[main]
  SCOPE |   NAME    | VALUE
--------+-----------+--------
        | TESTING  |   123
        | USERNAME | test

brian@localghost:go % waypoint config get -raw TESTING                                                                                                                                                                                ±[main]
123

```

That being said, we can give some better help here to let users know an argument was missing. Thanks for bringing this issue to our attention!

**Comment by dominikbraun** [comment]
Thanks, so this was my bad. To explain this a bit: #561 proposed a `-raw` flag for `config get`, and the proposed usage was like this:

```
➜ ✗  waypoint config get -all -raw | tee .env
PORT=8000  
PASSWORD=password
USERNAME=username
```

While I fixed #561, I noticed that the `-raw` flag already existed but didn't print any values with the suggested usage. Additionally, the command usage implied for me that `prefix` - or in this case, the config variable - is _always_ optional:

```
$ waypoint config get -help
  Usage: waypoint config-get [prefix]
```

I didn't quite realize that the command syntax basically changes when passing `-raw`.

**Comment by briancain** [comment]
@dominikbraun I see, thanks for the extra context there. It is a bit surprising to me too that the flag `-raw` is only per named variable, but `-json` is everything or a single named variable against the same command. We could potentially add an `-all` flag to go along with `-raw`, but maybe it makes more sense to have `-raw` and `-json` work the same? @mitchellh

**Comment by briancain** [comment]
Hey @dominikbraun - I'm about to merge my fix which will close this, but I think if my proposed changed makes sense we should open an "enhancement request" issue so we don't lose track of this in the future! Thanks :)
