### ISSUE TITLE
waypoint exec hangs when not executed on terminal

### ISSUE THREAD

**Issue by tjaartvdwalt** [hashicorp/waypoint#826]
**Describe the bug**
`waypoint exec` commands that are run outside of a terminal environment does not exit, but instead hangs until you manually terminate it.

**Steps to Reproduce**

- `git clone git@github.com:hashicorp/waypoint-examples.git`
- `cd waypoint-examples/docker/ruby`
- `waypoint init`
- `waypoint up`
- `nohup waypoint exec ls`

Notes:
- The waypoint server needs to be configured so that the entrypoint works correctly. 

**Expected behavior**
`waypoint exec` should exit, after the underlying command that gets executed exits

**Additional context**

I found the issue while trying to run `waypoint exec` as a step in Github Actions

**Comment by mitchellh** [comment]
Thanks, we've got a fix for this staged and plan to backport it to 0.1.x.

**Comment by mitchellh** [comment]
Fixed and backported. I'm sure we'll cut a 0.1.6 release sometime soon, perhaps next week.
