### ISSUE TITLE
`init` panics when using an AMI filter

### ISSUE THREAD

**Issue by topfunky** [hashicorp/waypoint#879]
**Describe the bug**
According to the [documentation](https://www.waypointproject.io/plugins/aws-ec2#filters), it should be possible to specify an AMI to use when building with the AWS-AMI and deploying with the AWS-EC2 plugins.

However, when using the code snippet below, Waypoint panics when running `init` (and `up`).

**Steps to Reproduce**
Here is a `waypoint.hcl` that recreates the issue.

The commented lines show a valid use of `name` which works (but doesn't allow me to specific a particular AMI ID). The use of `filter` panics.

```hcl
project = "example-ami"

app "example-ami" {
  labels = {
    "service" = "example-ami",
    "env"     = "dev"
  }

  build {
    use "aws-ami" {
      # This throws a panic
      filters = { 
        "image-id" = "ami-04e229bcb91f0f16b" # Nginx
      }
      
      # This works but not with a specific AMI ID
      # name = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"

      region = "us-west-2"
    }
  }

  deploy {
    use "aws-ec2" {
      region        = "us-west-2"
      instance_type = "t2.medium"
      service_port  = 80
    }
  }

  release {
    use "aws-alb" {
      port = 80
    }
  }
}
```

Output of `waypoint init`

```
$ waypoint init

✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "example-ami" and all apps are registered with the server.
⠙ Validating required plugins...panic: unsuitable DecodeExpression target: no cty.Type for interface {}

goroutine 39 [running]:
github.com/hashicorp/hcl/v2/gohcl.DecodeExpression(0xfc58e80, 0xc00088adc0, 0xc000d04660, 0x37deee0, 0xc000d365b8, 0xc000d365b8, 0x195, 0x3a40280)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:295 +0x978
github.com/hashicorp/hcl/v2/gohcl.decodeBodyToStruct(0x44fcd60, 0xc000644e70, 0xc000d04660, 0xc0000a0e40, 0xc000d36580, 0x199, 0x0, 0xc0006db740, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:111 +0x6ae
github.com/hashicorp/hcl/v2/gohcl.decodeBodyToValue(0x44fcd60, 0xc000644e70, 0xc000d04660, 0xc0000a0e40, 0xc000d36580, 0x199, 0xc000d9f438, 0x1a922bd, 0xc0001e1480)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.6.0/gohcl/decode.go:43 +0xd9
```

**Expected behavior**
Waypoint should successfully use a specific AMI.

**Additional context**
I have tried this and other AMIs with Terraform to verify that they work correctly. However, the same AMI ID doesn't work with Waypoint.

- Waypoint 0.1.5
- macOS 10.15.7
- Example was run with valid AWS credentials set as environment variables

**Comment by mitchellh** [comment]
I see the problem with this. Filters is defined as a `map[string]interface{}` and we can't have `interface{}` types. 

In the implementation, I see that it can be a string or a `[]string`. The easy thing to do here might just be to force `[]string` always.
