### ISSUE TITLE
generated ui tokens cut off by terminal width

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#884]
**Describe the bug**
The output token from `waypoint token new` will be cut off if the terminal window width is smaller than the length of the full token.

**Steps to Reproduce**
Run `waypoint token new` with a small-width terminal.

**Expected behavior**
The full token is output and wraps to the second line if the terminal width is shorter.

**Additional context**
full-width terminal
```
$ waypoint token new
bM152PWkXxfoy4vA51JFhR7LooY36cJnka7CKHXoyeEZXPs4Z94ENSYaQHqEktBEtKm7kQ9uWA5Bj6YDYijiCQCFaKDVrt4jSWkjA
```
short-width terminal
```
$ waypoint token new
bM152PWkXxfoy4vA51JFhR7LmZNBUbmubJ1ybj5JMLeXG4pYDhDMPaPvE9YCfnbep11arxWoyb13AaLXsLiGExo6ts
```

**Comment by mitchellh** [comment]
Ahhhhh yes. There are no spaces in this text so we can't wrap it so it has to be cut off by our UI framework.

The solution here is we probably shouldn't use the UI framework for this and just output direct to stdout.
