### ISSUE TITLE
support ingress resource in kubernetes plugin

### ISSUE THREAD

**Issue by daroga0002** [hashicorp/waypoint#889]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Currently kubernetes plugin is using Loadbalancer or Node port. In case where we have multiple developers working on different projects Node port opening over network is not feasible, from second side creating multiple Loadbalancers  on Kubernetes is creating quite big cost for infrastructure (for example each AWS ELB is ~$15 per month).

Better and desired feature will be usage of ingress resource which is become now stable in Kubernetes (https://kubernetes.io/docs/concepts/services-networking/ingress/).

I am imagine that there will be additional variable in kubernetes releasemanager: ingress (boolean) which will be activating this. Probably this will be require some additional variable to setup a ingress main FQDN 🤔 under which will be dynamically generated ingress route. 

Some unknown here is how to address dynamic URL  generated by waypoint, as this will be not working in this setup as there will be no IP hosting service directly and generating this to ingress IP will be rejected by missing virtual host in ingress controller.

Above are just ideas and doesn't reflect any desired design as I am new beginner in Waypoint, so feel free to adjust this to most suitable implementation way.

**Describe alternatives you've considered**
We can still use Loadbalancer or Node port approach but this doesnt fit to secure or economically reasonable Development environment design.

**Explain any additional use-cases**
This will open whole bunch of use cases in multiple companies where exists shared development clusters which have some basic security control or are used as a dev consolidated environments

**Comment by dirathea** [comment]
I think the dynamic URL has nothing to do with Ingress because I still could access the dynamic URL even I set `load_balancer = false` on the `release` stanza. Maybe the issue is around user expectation because a user could set an FQDN on the configuration file, but it can't really work immediately because another step is missing: registering the public ingress IP to the DNS record.

But personally, I think this feature might be a deal-breaker for those who want to try waypoint but had tight cost constraints so they can't really do the `LoadBalancer` service type.

**Comment by daroga0002** [comment]
You can access dynamic URL but only when you have public NodePort. In case when I have setup that only my ingress is public endpoint then it is some `shared` loadbalancer. What is more ingress is relying on `virtual_host` passed with request. So even if ingress is single loadbalancer then: https://example.com pointing to IP 32.0.12.21 is something other than https://admin.example.com pointing to same IP
