### ISSUE TITLE
homebrew installation is not working on macOS Big Sur

### ISSUE THREAD

**Issue by daroga0002** [hashicorp/waypoint#890]
**Describe the bug**
I cannot install waypoint using brew on MacOS Big Sur.

**Steps to Reproduce**
I have Homebrew:
```
$ brew config
HOMEBREW_VERSION: 2.6.0-157-g3fc8c70
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3fc8c703f2dfccc09ca32537e20fcdb0411534ea
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 764a95e49fd2a4e54ecfc4476287bd159febbbfc
Core tap last commit: 73 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.271.09, 1.8.0_221
macOS: 11.0.1-x86_64
CLT: 1103.0.32.62
Xcode: 12.2
```

and then following instruction for Mac OS https://www.waypointproject.io/downloads using Homebrew:

```
$ brew tap hashicorp/tap
$ brew install hashicorp/tap/waypoint
==> Installing waypoint from hashicorp/tap
==> Downloading https://releases.hashicorp.com/waypoint/0.1.5/waypoint_0.1.5_darwin_amd64.zip
Already downloaded: /Users/*******/Library/Caches/Homebrew/downloads/4e9e132832179b96513a8aef1c33d6cdcc408ad995cbc5d05105fdead566594b--waypoint_0.1.5_darwin_amd64.zip
Error: Your CLT does not support macOS 11.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Error: An exception occurred within a child process:
  SystemExit: exit
```

macOS version 11.0.1
![image](https://user-images.githubusercontent.com/20227477/101461447-2dd94700-393b-11eb-80ea-52e462de04bf.png)

**Expected behavior**
Waypoint will install correctly

**Additional context**
I have arleady reinstalled totally Xcode, tried suggested `softwareupdate --all --install --force` and `  sudo rm -rf /Library/Developer/CommandLineTools; sudo xcode-select --install` but this doesn't helped.

**Comment by mitchellh** [comment]
I just ran the install on Big Sur with `brew` and everything worked fine for me. I believe this may be environmental. 

I tested on two separate computers. If you find out anything Waypoint specific please do let us know!

**Comment by briancain** [comment]
@daroga0002 - You might need to download and install Command Line Tools for XCode 12.2 directly after deleting the old version. It seems like some users had luck trying that: https://apple.stackexchange.com/a/402377. They also mentioned that afterwords you need to open the app for the "install command line tools" dialog to open.

**Comment by daroga0002** [comment]
you were right, for me helped following procedure:
1. uninstall xcode from app store
2. install xcode from app store
3. make:
```
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
```

then this started working. Thx for suggestions
