### ISSUE TITLE
Very unstable connection to the Waypoint UI

### ISSUE THREAD

**Issue by kfh** [hashicorp/waypoint#905]
Just upgraded from WP 0.1.5 to 0.2.0 and it works great except for when connecting to the WP UI. The logs are full of:

```
 2020-12-11T14:41:03+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:40:55+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:41:54+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:42:04+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:42:55+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:43:03+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:43:54+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-11T14:44:03+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF 
```

and we are loosing the connection all the time. This was not an issue at all in 0.1.5.

For the record, we are running on _AWS Fargate_ using the _aws-ecs_ plugin.

Also, i did a full reinstall server side, the WP Server is fresh on EKS.

EDIT: Just checked the version running on the server:

```
/ $ waypoint version
Waypoint v0.1.5 (084d8603+CHANGES)
```

Is that right?

**Comment by krantzinator** [comment]
You'll want to upgrade your server version as well. You can follow our [upgrade guide here](https://www.waypointproject.io/docs/upgrading). Let us know how that goes!

**Comment by kfh** [comment]
> You'll want to upgrade your server version as well. You can follow our [upgrade guide here](https://www.waypointproject.io/docs/upgrading). Let us know how that goes!

Yeah, as mentioned, i did a full reinstall server side also. Removed everything from EKS by follwing the WP server uninstall guide and then a fresh install wIth the 0.2.0 version of the Waypoint client:
`waypoint install --platform=kubernetes -accept-tos`

That gave me the v0.1.5 (084d8603+CHANGES)

**Comment by krantzinator** [comment]
You may need to manually remove the `hashicorp/waypoint:latest` image from your local docker. We have some [troubleshooting advice here as well](https://www.waypointproject.io/docs/troubleshooting).

**Comment by mitchellh** [comment]
If this is AWS Fargate, this might be expected as AWS aggressively shuts down the containers. Do you think that is what is happening? You'd get an EOF anytime the workload shuts down.

I'm making some assumptions cause it isn't clear to me what "logs" you're talking about so are these: UI logs, CLI logs, server logs, or entrypoint logs?

**Comment by mitchellh** [comment]
(And note, if there is any more context you could give us, i.e. both sides of the logs that'd be helpful.)

**Comment by kfh** [comment]
> You may need to manually remove the `hashicorp/waypoint:latest` image from your local docker. We have some [troubleshooting advice here as well](https://www.waypointproject.io/docs/troubleshooting).

The most straightforward solution was to add `-k8s-server-image=hashicorp/waypoint:0.2.0` as part of the install command. The server is now properly installed based on the latest image:
```
/ $ waypoint version
Waypoint v0.2.0 (360b2b3a+CHANGES)
```

And i can confirm that everything works really nice now. The UI is contrary to the first attempt very stable now. I think we can conclude that this bug is manifested only when running with 0.1.5 on the server and WP client 0.2.0. Feel free to close this if the versions are incompatible.

**Comment by kfh** [comment]
> If this is AWS Fargate, this might be expected as AWS aggressively shuts down the containers. Do you think that is what is happening? You'd get an EOF anytime the workload shuts down.
> 
> I'm making some assumptions cause it isn't clear to me what "logs" you're talking about so are these: UI logs, CLI logs, server logs, or entrypoint logs?

I was talking about the _application log_ streamed out directly in the WP UI. Unfortunately i don't have access to that older installation anymore for further debugging since it's erased. But as shown in my first post the _entrypoint.log_ is referenced when the error logging is happening. Anyways, this is probably caused by incompatible versions of WP server and client used as mentioned in my previous post.

Short status after playing around with the 0.2.0 version is that it seems very stable. But i noticed that after application startup when following  the _application.log_ in the UI, if i switch to another tab in the ui, ie _Builds_ or_Deployments_ and then go back to the _Logs_ tab the log history is lost. I no longer see the logs fra mye application startup. But instead i see the following two lines:
```
2020-12-13T20:56:51+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
2020-12-13T20:57:51+01:00: [ERROR] entrypoint.log: log stream disconnected from server, attempting reconnect: err=EOF
```

The connections to the UI is kept alive at all times so no disconnect issues at all but i would suspect this is a bug? Should it be reported in another issue?

**Comment by mitchellh** [comment]
It should've worked with the old version but lets ignore that and move forward (given the early state of the project).

The UI issue does look like a bug and would appreciate if you opened a new issue for it! We'll tag and look at it accordingly.

Thanks!

**Comment by andrea-defraia** [comment]
> 



> It should've worked with the old version but lets ignore that and move forward (given the early state of the project).
> 
> The UI issue does look like a bug and would appreciate if you opened a new issue for it! We'll tag and look at it accordingly.
> 
> Thanks!

So, today I was trying Waypoint with ECS, this bug still exists, I could sometime deploy, sometimes it would fail with EOF error...

Best wishes! Tomorrow is the 1 year anniversary of this bug being closed without solution.

**Comment by catsby** [comment]
Hello @andrea-defraia ! Could you clarify some information for us? The issue reported above is regarding an `EOF` message in the Waypoint UI's display of a deployed application's logs. Are you experiencing the same error when viewing logs for a deployed application in the Waypoint UI? Your comment mentioned occasionally failing with an `EOF` error when deploying, and I wonder if they are possibly different issues. Thanks!
