### ISSUE TITLE
[Install][k8s] Allow to specify or create an ingress/nodeport for waypoint

### ISSUE THREAD

**Issue by Moep90** [hashicorp/waypoint#935]
**Versions**

Waypoint
```bash
$ waypoint --version
Welcome to Waypoint
Docs: https://waypointproject.io
Version: v0.2.0
```
Kubernetes:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-16T12:12:57Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
As I use a custom cluster I dont have a AWS or GCP ELB in place. Therfore I need to have the ability to specify an ingress or NodePort. 

```bash
waypoint install --platform=kubernetes -k8s-namespace=waypoint -k8s-servicetype=(ingress/) -accept-tos
```

**Describe alternatives you've considered**
Updating the service which does not resolv the problem.

**Explain any additional use-cases**
More flexible installations on different clusters with different components.

**Additional context**
https://github.com/hashicorp/waypoint/issues/933

**Comment by briancain** [comment]
Hey there @Moep90 - I _think_ this might be a duplicate, or similar issue to https://github.com/hashicorp/waypoint/issues/889. I'm going to close this one, but only for the sake of consolidating the issue into a single source. The other issue should still reference this one, so it shouldn't get lost. Thanks again for bringing this issue to our attention!
