### ISSUE TITLE
Error occurred during a database lookup

### ISSUE THREAD

**Issue by Hokutosei** [hashicorp/waypoint#937]
**Describe the bug**
sorry, if I have posted to a wrong location, I would also like to report a problem, and continue discussion from [here](https://discuss.hashicorp.com/t/error-occurred-during-a-database-lookup/19017?u=hokutosei). from a clean installation, windows localhost, then docker on a VM. I did waypoint.exe install --platform=docker -accept-tos, but it gave an error…
```
$ waypoint.exe install --platform=docker -accept-tos
-> Initializing Docker client...
-> Checking for existing installation...
! Error installing server into docker: error during connect: Get
  "http://jeanepaul%40192.168.217.128/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22waypoint-type%3Dserver%22%3Atrue%7D%7D&limit=0":
  dial tcp: lookup jeanepaul@192.168.217.128: getaddrinfow: A non-recoverable
  error occurred during a database lookup.
```

**Steps to Reproduce**
1. windows machine + docker toolbox
2. follow instructions here
3. and execute waypoint.exe install --platform=docker -accept-tos

**Expected behavior**
from the installation instructions, I should get some message like this
```
✓ Server container started
Waypoint server successfully installed and configured!
```

is there any steps I missed? thank you!

**Comment by Hokutosei** [comment]
following up the gist with `-vvv`

```
$ waypoint.exe install --platform=docker -accept-tos -vvv
2020-12-21T13:54:59.950+0900 [INFO]  waypoint.exe: waypoint version: full_string="Waypoint v0.2.0 (360b2b3a)" version=v0.2.0 prerelease= metadata= revision=360b2b3a
2020-12-21T13:54:59.951+0900 [TRACE] waypoint.exe: starting interrupt listener for context cancellation
2020-12-21T13:54:59.951+0900 [TRACE] waypoint.exe: interrupt listener goroutine started
2020-12-21T13:54:59.951+0900 [DEBUG] waypoint.exe: home configuration directory: path=C:\Users\jeanepaul\AppData\Local\waypoint
-> Initializing Docker client...
-> Checking for existing installation...
! Error installing server into docker: error during connect: Get
  "http://jeanepaul%40192.168.217.128/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22waypoint-type%3Dserver%22%3Atrue%7D%7D&limit=0":
  dial tcp: lookup jeanepaul@192.168.217.128: getaddrinfow: A non-recoverable
  error occurred during a database lookup.
2020-12-21T13:54:59.956+0900 [TRACE] waypoint.exe: stopping signal listeners and cancelling the context
```

**Comment by briancain** [comment]
Hey @Hokutosei ! I noticed you mentioned that you're using docker toolbox. If I remember right, that project has been deprecated in favor of [Docker Desktop](https://www.docker.com/products/docker-desktop). Can you install that after removing docker toolbox and see if that makes any difference? Thanks!

**Comment by briancain** [comment]
Hey there @Hokutosei - we haven't heard from you in a while, and given that you might be using a deprecated way to use docker, I'm going to go ahead and close this issue. If that's not the case and you are using something like Docker Desktop, please feel free to open a new issue and we'll be happy to take a look. Thanks!
