### ISSUE TITLE
Passing environment variables to the WP build step

### ISSUE THREAD

**Issue by kfh** [hashicorp/waypoint#938]
We have a case now where we would like to pass _Github secrets_ as environments variables to Docker when building our applications. For the record, we are using _Gradle_ from within _Docker_ to build our _Kotlin_ applications. I can not see an obvious way of doing this as of now and it is limiting us from using ie _Github packages_ from Gradle as we for obvious reasons don't want to have plain passwords checked into version control. Or is there a way of working around this?

**Comment by mitchellh** [comment]
Someone else brought this up recently so this _might_ be a dupe but until we find that issue I'll tag it.

We knew this would come up eventually but we haven't yet planned or figured out how to exactly expose this.

The only workaround I can think of currently would be to set environment variables that are read via the `file()` function or something so that they don't have to be embedded in your Waypoint file.

**Comment by kfh** [comment]
> Someone else brought this up recently so this _might_ be a dupe but until we find that issue I'll tag it.
> 
> We knew this would come up eventually but we haven't yet planned or figured out how to exactly expose this.
> 
> The only workaround I can think of currently would be to set environment variables that are read via the `file()` function or something so that they don't have to be embedded in your Waypoint file.

Just to clearify, do you mean that i need to write the variables to a file and read that file in with the _file function_? Because i had a quick look and that function expects an _absolute path_ as argument.

**Comment by mitchellh** [comment]
Yes. Yes, all the file paths should be absolute, you're expected to use [path variables](https://www.waypointproject.io/docs/waypoint-hcl/variables/path) to make it so easily. I'll note that for updating the documentation. Example:

```hcl
file("${path.app}/env.d/FOO")
```

The env var thing is an ugly hack right now I know but I was just trying to note some temporary way to make it work.

**Comment by kfh** [comment]
> Yes. Yes, all the file paths should be absolute, you're expected to use [path variables](https://www.waypointproject.io/docs/waypoint-hcl/variables/path) to make it so easily. I'll note that for updating the documentation. Example:
> 
> ```terraform
> file("${path.app}/env.d/FOO")
> ```
> 
> The env var thing is an ugly hack right now I know but I was just trying to note some temporary way to make it work.

Right. Thanks, now i'll happily take _anything_ that works :) Would it make sense though to offer an _env function_ as part of the _core library_ so we could read env variables exposed in _Github actions_ directly? Just to avoid the _intermediary step_ of writing to files.

**Comment by kfh** [comment]
@mitchellh Just want to give you a quick feedback of how this went. I had a look at this yesterday and maybe i wasn't too clear about what we actually need. We have a fully automated build pipeline using Github Actions and also utilizing the [Waypoint GHA](https://github.com/hashicorp/action-waypoint) so we can continously deploy all our branches to different workspaces(releases are only done when merging to _main)_.  It works really well albeit i had to fork the WP GHA since nobody seems to bother make sure it runs out of the box. 

As mentioned above we are using docker for all our container needs but the image building process is twofolded. We first build our Kotlin applications using Gradle in an intermediary Gradle image before passing on the finished artifact to the main image to avoid filling up our base image with build related stuff. Gradle is merely a use and throw tool. But the gist of it is that we need to pass env variables _during the image building process_ to Gradle. Do correct me if i'm wrong, but if i understand how WP works all WP related stuff is _injected after image building_ but before _deployment of the actual application_ as part of the _Entrypoint_. 

I did verify that your suggested solution worked in the sense that env variables written to filles could be read back by _waypoint.hcl_ but of course they where never available when needed. Maybe i've just been overthinking this but i quickly realized that since i already have written said variables to disk i can just copy them into the Gradle image where they are needed and the benefit is that thew will never be transported into the main image. 

Also just want to mention that i _think_ i stumbled upon a bug when playing with reading variables back in to WP from the files. Variables defined as _project variables_ where never updated when i changed them, ie wrote new values into the files on disk. I did manage to overwrite them when moving the _config block_ into the _application block_ though.

**Comment by evanphx** [comment]
Because of the various limitations of the build plugins, there is no easy way to pass environment variables to them each generically. Instead, each one supports their own mechanism. For instance, in 0.3.2, we've added support for docker's `build_args`. And the pack builder supports a `static_environment` map that is environment variables that will be exposed to the build.

We're going to do a write-up about this particular pattern and how to utilize for our primary builder plugins.

**Comment by evanphx** [comment]
Closing this issue in favor of #1467 where we'll document the pattern.
