### ISSUE TITLE
Support specifying multiple buildpacks with the pack plugin

### ISSUE THREAD

**Issue by MarilynFranklin** [hashicorp/waypoint#942]
**Is your feature request related to a problem? Please describe.**

I have an application on heroku that uses multiple buildpacks and I'm unable to
build it with the current pack plugin because it does not support setting
multiple buildpacks.

**Describe the solution you'd like**

I would like the ability to specify buildpacks for the pack plugin to use when
building an application:

```
app "example-app" {
  build {
    use "pack" {
      buildpacks = [
        "./path/to/buildpack",
        "heroku/nodejs",
        "heroku/ruby",
      ]
    }
  }
```

**Describe alternatives you've considered**

As an alternative, I could use the `docker` plugin or I could write my own plugin.

**Explain any additional use-cases**

Heroku describes a few use-cases for supporting multiple buildpacks in [their documentation](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app):

* Run a buildpack for each language your app uses. For example, run a JavaScript buildpack for assets and a Ruby buildpack for your application.
* Run a daemon process such as pgbouncer with your application.
* Pull in system dependencies with apt.

**Additional context**

Here is the [buildpack documentation](https://buildpacks.io/docs/app-developer-guide/specific-buildpacks/) for specifying buildpacks

**Comment by briancain** [comment]
This was resolved via https://github.com/hashicorp/waypoint/pull/943. Thanks for reporting and fixing the issue! :smile: :tada:
