### ISSUE TITLE
Allow a different image URL to be used for build and deploy

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/waypoint#949]
**Is your feature request related to a problem? Please describe.**

When deploying container driven applications, it is often helpful to carry out a promotion process between images. For example, an image is built to the `latest` tag once, then pushed to a number of different tags based on the environment that is being targeted. I understand that workspaces are intended to solve this problem, but a workspace still requires a re-build of the image.

In this use case, I take one built image and deploy it to multiple different kube contexts with a different URL.

**Describe the solution you'd like**

I'd like to be able to overwrite the image URL with a variable to target different environments with different image tags via external promotion processes.

**Describe alternatives you've considered**

* Rebuild the container for every environment 😢 
* Only use waypoint deploy for dev and then replicate the configs other ways for higher environments

**Explain any additional use-cases**

Another possibility here is an internal/external container registry, especially in cloud use cases. I originally want to deploy to my company internal registry which is not available off network for scanning, testing, and validation. Then, I want to push that image to the target cloud environment registry for deployment.

**Additional context**

Thanks for an interesting project! I've enjoyed digging into the source here and look forward to further discussions.

**Comment by mitchellh** [comment]
Thanks, I've tagged this with enhancement/core. We have promotion workflows planned for 0.4.0. Would you mind sharing the workflow you currently use and what you're trying to achieve with Waypoint? THat'll help us as we work on desigining this feature.

**Comment by jmcshane** [comment]
OK, a little more context.

Generally, in containerized workflows you build your container a single time, then push that constructed image around to lots of different places. I understand the general flow of waypoint and have used it to deploy some toy apps, but I'm trying to design workflows that will use waypoint to push to multiple environments as I release code.

Start with build, lets' call it image:1. I test that and it looks good. I tag the repo with a release tag and the CI system tags image:1 with a new tag, let's call it image:alpha. Now, we push this alpha image version to stage for validation. Then, it passes and i tag that same manifest with a new version, :preprod. The process continues to production and I want to deploy based on those tags to every environment. I understand the idea that I could use workspaces to segregate the different environment workflows, but I want my "non-dev" environments to have no build associated to them in any way. Non-dev builds should in fact link back to a build in the dev workspace.

Here's a second workflow. Working within an environment with strong segregation between onprem and public cloud. They have internal and public facing container registries. Security enforces that all containers pushed to public facing registries must be scanned for vulnerabilities in the internal Artifactory registry. I want to do a waypoint build to the internal registry, complete the scanning (via a build hook), push the image to the public registry, then deploy based on the public registry image URL. This would be within a single `waypoint up` flow and I would know the internal & external URLs and pass those in to the build.

**Comment by krantzinator** [comment]
Would making use of [`docker-pull` in the docker plugin](https://www.waypointproject.io/plugins/docker#docker-pull-builder) help to satisfy your use case? If not, can you help us understand why?

**Comment by evanphx** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
