### ISSUE TITLE
Kubernetes plugin: Support injecting data from waypoint deploy into K8s labels

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/waypoint#966]
**Is your feature request related to a problem? Please describe.**
I would like to be able to talk meta information about the waypoint deploy and inject it into labels of the Kubernetes deployment. For clusters running istio expecting `app` and `version` labels, it will be helpful to have the waypoint app name as the `app` label (this can be done hard-coded for now) and the waypoint release version hash as the `version`. Right now, by default, we get a label like:

```
labels:
  name: example-app-01evrnw04bkevhzsfzk1x29n5t
  waypoint.hashicorp.com/id: 01EVRNW04BKEVHZSFZK1X29N5T
```

That label name is set here: https://github.com/hashicorp/waypoint/blob/main/builtin/k8s/platform.go#L169

**Describe the solution you'd like**

I would like to be able to customize the labels on the resulting k8s deployment.

**Describe alternatives you've considered**

Istio can create `DestinationRule` objects using labels other than `version`, so I can use `waypoint.hashicorp.com/id` label as the target of the destination rule.

**Explain any additional use-cases**

Another use case is that waypoint build information can be passed to the kubernetes deployment as well using these meta-labels. For example, the docker build could set labels on the container image that get exposed on the deployment as labels or annotations...such as buildTime, commit hash, etc.

**Comment by briancain** [comment]
Hey there @jmcshane ! I was able to address this issue in #1146. I didn't end up addressing the additional use-casess for injecting in the containers build tags. I'm curious if you wouldn't already get this meta-data directly on the container image itself, and why you'd look for it in the pod label? Is there another integration (maybe Istio) that would ingest this information? If you've got a good idea for this please feel free to open another enhancement issue. Thanks! :smile:
