### ISSUE TITLE
App-level waypoint.hcl labels are not applied to Kubernetes deployment resources

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/waypoint#968]
**Describe the bug**
In the [documentation for `waypoint.hcl`](https://www.waypointproject.io/docs/waypoint-hcl/app), the project describes:

> A set of labels to apply to all operations for this application. All builds, deploys, etc. will have these labels applied

Unfortunately, adding labels to this top level stanza is not passing down to the k8s plugin (which I am using) or any other deployment plugin I have found.

**Steps to Reproduce**

Deploy example waypoint with kubernetes deployment: https://github.com/hashicorp/waypoint-examples/blob/main/kubernetes/nodejs/waypoint.hcl

**Expected behavior**
The `env` and `service` labels should show up on the Kubernetes deployment, pod, and service objects that are generated.

**Additional context**
There is some conflict here with the label called `name`. Would have to figure out appropriate behavior, for the time may fail open and just ignore the label.

**Comment by mitchellh** [comment]
This is currently working "as intended" though that doesn't mean some changes can be made here.

The labels are applied to the Waypoint operations, not to the underlying system in use. 

Your use case seems totally reasonable to me, I just wonder if this should be automatic, an opt-in thing, or something like exposing an HCL var so you can access the labels and assign them to the K8S deployment...

**Comment by jmcshane** [comment]
Ok, so the labels apply to the operation, but how do those labels play any role in the operation? I can't seem to get that label set passed in to a custom plugin (as documented here: https://github.com/hashicorp/waypoint-plugin-sdk/issues/9) and i don't see any place that these labels are actually _used_.

I guess I assumed that since the k8s deployment object didnt have labels, the labels from the top level block would provide the source for additional labels to apply here.

**Comment by jmcshane** [comment]
I also don't see a place where those labels modify any specific operation inside the waypoint core. Are those there for future extensibility of the base operations or are they intended to pass down to the plugins/platforms?

**Comment by briancain** [comment]
Hey there @jmcshane - I think I've addressed this use case already via https://github.com/hashicorp/waypoint/pull/1146

From the description, it seems like you are wishing to have a way to label your k8s deployment pods?

```
Steps to Reproduce

Deploy example waypoint with kubernetes deployment: https://github.com/hashicorp/waypoint-examples/blob/main/kubernetes/nodejs/waypoint.hcl

Expected behavior
The env and service labels should show up on the Kubernetes deployment, pod, and service objects that are generated.
```

This should be possible now by including a `labels` array in the deploy stanza for kubernetes. It sounds like the App level Labels are used for something else, as @mitchellh mentioned. If that's the case, it would be good to clarify that in the documentation for the intended use of [app labels](https://www.waypointproject.io/docs/waypoint-hcl/app#labels).

**Comment by briancain** [comment]
Hey @jmcshane - I believe this was address from the previous comment. Thanks again for opening the issue and providing some additional context! Since we haven't heard back from you in a while, I'm going to go ahead and close this issue. However if you feel like there's something missing from the resolution please feel free to comment on here or open a new issue or enhancement request! Thank you! 😄
