### ISSUE TITLE
gitreftag returns an empty string 

### ISSUE THREAD

**Issue by miran248** [hashicorp/waypoint#978]
**Describe the bug**
`gitreftag` returns an empty string in both build and release steps.

**Steps to Reproduce**

```hcl
app "app-test" {
  build {
    use "pack" {
      builder            = "heroku/buildpacks:18"
      disable_entrypoint = true
    }

    registry {
      use "aws-ecr" {
        region     = "eu-west-1"
        repository = "app-test"
        tag        = substr(gitreftag(), 1, -1)
      }
    }
  }

  deploy {
    use "exec" {
      command = [ "echo", gitreftag() ]
    }
  }
}
```

**Expected behavior**
It should return the actual tag.

**Additional context**
`git log --pretty=oneline` returns `hash (HEAD -> branch, tag: v0.1.5, origin/branch) chore(release): 0.1.5` - `gitreftag()` should thus return `"v0.1.5"` instead of `""`. `substr` would then remove the `v` from the tag.

Both `gitrefhash` and `gitrefpretty` are working!

`macos 10.15.7`
`Waypoint v0.2.0 (360b2b3a)`

**Comment by catsby** [comment]
I attempted to fix this in #1047, and while it works for me I wasn't able to figure out why the tests were passing to truly understand what the source of the bug is 🤔
