### ISSUE TITLE
Default buildpack improvements

### ISSUE THREAD

**Issue by zdunecki** [hashicorp/waypoint#985]
**Is your feature request related to a problem? Please describe.**
I faced that default Heroku builder is probably less productive for Go language than from Google. 
Image size is much less (around 100MB instead of 500MB) also downloading an image is much faster. 

Additionally, Heroku needs a special directive to detect the Go version in `go.mod`. Let's take an example:
```
// +heroku goVersion go1.15
```
Above line is required to pull the correct Go version.

**Describe the solution you'd like**
Detect Go language before passing through buildpack and if necessary, change default builder.

**Describe alternatives you've considered**
That PR(https://github.com/hashicorp/waypoint/pull/943) can partially solve this but it would be nice if Waypoint could detect the best buildpack as a default behaviour.

**Explain any additional use-cases**
I think it would be nice to use the best builder for specific language. Heroku's buildpack is nice because it supports many languages but for Go language it seems worse than Google. Perhaps in another language other buildpack could work better too.

**Additional context**
Here's [Google buildpack](https://github.com/GoogleCloudPlatform/buildpacks) and [Heroku's Go buildpack](https://github.com/heroku/heroku-buildpack-go#go-module-specifics).

If you like this idea, I can take it.

**Comment by krantzinator** [comment]
Waypoint allows you to specify your own [pack builder here](https://www.waypointproject.io/plugins/pack#builder) and a [specific buildpack](https://www.waypointproject.io/plugins/pack#buildpacks). Additionally, you can specify a specific buildpack by URI.
These sources may be helpful to you:
https://buildpacks.io/docs/app-developer-guide/specific-buildpacks/
https://registry.buildpacks.io/
