### ISSUE TITLE
Customize pruning count for platform

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/waypoint#988]
**Is your feature request related to a problem? Please describe.**

Currently, the platform will prune all deployments that exist if there are more than 2 currently out there. I want to customize this behavior in a couple ways:

* Allow for configurability of this number - say keep three previous releases out there
* Allow for configurability of the behavior based on a releaser func

In the k8s plugin, this always leaves an old version of the deployment out there unless the deployment is explicitly destroyed. I want to be able to opt into the destroy capabilities automatically based on some criteria.

**Describe the solution you'd like**
* Waypoint Releaser can define a bool function that will determine if old deployments should be pruned

**Describe alternatives you've considered**
* Manually destroy the previous deployment using `waypoint deployment destroy <id>`

**Explain any additional use-cases**
* `waypoint release -repeat` could be used to determine if the previous deployments should be marked for pruning.
* Could put more complex behavior in the destroy functions if the pruning happens based off conditions.

**Comment by jmcshane** [comment]
See https://github.com/hashicorp/waypoint/blob/main/internal/runner/operation_release.go#L51 for hardcoded value of 2

**Comment by kfh** [comment]
> See https://github.com/hashicorp/waypoint/blob/main/internal/runner/operation_release.go#L51 for hardcoded value of 2

This is also something we would much appreciate if was exposed and tunable. As of now it gives us concurrency issues if we are not killing the old deployments immediately. But the actual pruning is now limited to when _releases_ are performed. I think it would make sense to offer this for _plain deployments_ as well. For instance, we are running a fully automated pipeline deploying branches continously without releasing them which gives us _unlimited deployments_ if they are not killed.

**Comment by kfh** [comment]
@mitchellh As mentioned here: https://discuss.hashicorp.com/t/limit-running-deployments-in-k8s/19530 you have the internal machinery to expose this functionality. We are on the verge of using Waypoint in production after testing it for months already but this is a major issue for us and makes it harder to sell company wide since we are facing concurrency issues as mentioned above. Any chance of seeing this functionality exposed in the near future? If so that would be fantastic news for us.

**Comment by mitchellh** [comment]
Hey @kfh yes let me take a look at this next week and we'll get something in for you. I've applied this to the 0.3.0 milestone.

**Comment by kfh** [comment]
@mitchellh Just curious if anything is happening in the background here ? Is it a bigger task to expose this feature?

**Comment by mitchellh** [comment]
Sorry for the late update, we're still planning on getting this into 0.3.0 (coming out hopefully this month), just got distracted by some other issues.

**Comment by mitchellh** [comment]
I have a PR open at #1230. Could you let me know if that would solve your issues?

I think we can do a much more holistic and better experience to set this (for example a serverside default, waypoint.hcl, etc.) but I wanted to make sure we got _something_ in for you in 0.3.

**Comment by kfh** [comment]
> I have a PR open at #1230. Could you let me know if that would solve your issues?
> 
> I think we can do a much more holistic and better experience to set this (for example a serverside default, waypoint.hcl, etc.) but I wanted to make sure we got _something_ in for you in 0.3.

Great stuff, thanx for the effort! My only question is about _plain deployments_ as mentioned above(https://github.com/hashicorp/waypoint/issues/988#issuecomment-765263408). Should't also this scenario be covered? It would also make all deploy related commands(_up, deploy, release_) consistent.

**Comment by mitchellh** [comment]
> Great stuff, thanx for the effort! My only question is about _plain deployments_ as mentioned above([#988 (comment)](https://github.com/hashicorp/waypoint/issues/988#issuecomment-765263408)). Shouldn't also this scenario be covered? It would also make all deploy related commands(_up, deploy, release_) consistent.

The `deploy` command having the same flags makes sense. I’ll add that.

Note that `release` if no release plugin is used is a no-op so pruning logic I think only makes sense as long as you release as well.

**Comment by kfh** [comment]
> > Great stuff, thanx for the effort! My only question is about _plain deployments_ as mentioned above([#988 (comment)](https://github.com/hashicorp/waypoint/issues/988#issuecomment-765263408)). Shouldn't also this scenario be covered? It would also make all deploy related commands(_up, deploy, release_) consistent.
> 
> The `deploy` command having the same flags makes sense. I’ll add that.
> 
> Note that `release` if no release plugin is used is a no-op so pruning logic I think only makes sense as long as you release as well.

So, just to be clear, the _exact_ case i'm talking about is when we are running `deploy -release=false`. Doesn't it make sense to cover this as well? Or else, as it is now, we end up with _unlimited deploys_ of our _topic branches_. Are we forced to _release_ for pruning to work correctly?

**Comment by mitchellh** [comment]
> So, just to be clear, the _exact_ case i'm talking about is when we are running `deploy -release=false`. Doesn't it make sense to cover this as well? Or else, as it is now, we end up with _unlimited deploys_ of our _topic branches_. Are we forced to _release_ for pruning to work correctly?

At the moment yes, you must release.

I'll have to think on this further. What you're saying makes sense, having a way to prune unreleased deployments. The pruning logic at the moment is fully tied to release so its less trivial to make the deployment change.

**Comment by kfh** [comment]
> > So, just to be clear, the _exact_ case i'm talking about is when we are running `deploy -release=false`. Doesn't it make sense to cover this as well? Or else, as it is now, we end up with _unlimited deploys_ of our _topic branches_. Are we forced to _release_ for pruning to work correctly?
> 
> At the moment yes, you must release.
> 
> I'll have to think on this further. What you're saying makes sense, having a way to prune unreleased deployments. The pruning logic at the moment is fully tied to release so its less trivial to make the deployment change.

@mitchellh Let me know if you want me to create an issue for this case or maybe this is something you want to describe in more detail yourself?
